- examples/colour-uniform/main.rs
- examples/quad/main.rs
- src/hal/src/window.rs
Fixes #2421 by adding a default parameter to SwapchainConfig::from_caps. In Vulkan on Wayland, the surface capabilities don't give us a current extent because `vkGetPhysicalDeviceSurfaceCapabilitiesKHR` sets current_extent to `0xFFFFFFFF`. Which means that the surface size is determined by the swapchain, not the surface capabilities.
PR checklist:
- Vulkan (on Wayland and X11)
- OpenGL (on Wayland and X11)
- A very noisy diff so I left it as a separate commit
> Add a default size parameter to SwapchainConfig::from_caps

- src/backend/dx12/src/window.rs
Fixes #issue
PR checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/2490)
> Allow to use swapchain image as trasnfer destination

- examples/quad/main.rs
Both vs_module and fs_module are concrete ShaderModules.
Fixes #issue
PR checklist:
> Ignore when using concrete ShaderModule

- src/backend/vulkan/src/info.rs
- src/backend/vulkan/src/lib.rs
This is a follow up on #1931 and fixes #1930.
cc @kvark 
PR checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/2488)
> [vk] extend dual-source blending disable on Intel/windows

- src/hal/src/command/mod.rs
> Field init shorthand RFC 1682

- src/backend/gl/Cargo.toml
- src/backend/gl/src/lib.rs
- src/backend/vulkan/src/factory.rs
Fixes a heavy memory leak per frame when using host-mapped resources.
What was happening is the fence being created on a temporary manger, which never cleans up the resources properly (just clears instead, since it assumes it's never the last one).
Ideally, we'd want to design the internal handle manager in such a way that it's not possible at the API level, but this isn't a priority right now.
> [0.17/gl] don't use temporary manager for resource creation

- examples/colour-uniform/main.rs
- examples/quad/main.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/window.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/window/glutin.rs
- src/backend/metal/src/window.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/window.rs
- src/hal/src/lib.rs
- src/hal/src/queue/capability.rs
- src/hal/src/window.rs
Fixes #2507
PR checklist:
- [] `make` succeeds (on *nix)
> Expose alpha composition mode

- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/resource.rs
- src/backend/dx12/src/root_constants.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/command.rs
- src/backend/gl/src/native.rs
- src/backend/gl/src/queue.rs
- src/backend/metal/src/command.rs
- src/backend/metal/src/native.rs
- src/backend/metal/src/soft.rs
- src/backend/vulkan/src/command.rs
Follow-up to #2514 that actually tries to lift the `Clone` bounds in the backends. This is going to be a long CI fight, I feel, but it's good that there is a ton of places where it was used.
PR checklist:
> Actually stop deriving Clone for backend's command buffers

- examples/colour-uniform/main.rs
- examples/compute/main.rs
- examples/quad/main.rs
- src/backend/dx11/src/conv.rs
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/internal.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/lib.rs
- src/backend/dx12/src/resource.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/native.rs
- src/backend/metal/src/command.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/lib.rs
- src/backend/metal/src/native.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/hal/src/device.rs
- src/hal/src/lib.rs
- src/warden/src/gpu.rs
Remove unbound resources from backend and adjust creation and binding api
Fixes #2517
> Remove Unbound resource variants

- src/backend/empty/src/lib.rs
> Consistent Instance::create in empty backend

- src/backend/dx11/src/device.rs
Fixes #issue
PR checklist:
The DEVICE_LOCAL branch was incorrectly using the size of the buffer for the BindFlags value. Changed it to actually use the BindFlags value that was created in create_buffer.
> Fix dx11's bind_buffer_memory for DEVICE_LOCAL memory

- src/warden/src/gpu.rs
just something I screwed up when porting the `Unbound` changes earlier
> Fix warden memory

- examples/Cargo.toml
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
Code was currently unused iin the project and was specific to the Vulkan backend. Compilation from GLSL->SpirV should be done outside of gfx-hal
PR checklist:
> removing create_shader_module_from_glsl from vulkan backend

- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/command.rs
- src/backend/vulkan/src/conv.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/backend/vulkan/src/native.rs
- src/backend/vulkan/src/pool.rs
- src/backend/vulkan/src/result.rs
- src/backend/vulkan/src/window.rs
Fixes #2510. A lot of the changes were just renaming various constants that were moved around with no major changes. I went through the diff and checked to make sure everything was updated correctly, but it's possible there could have been a typo somewhere in the 500 or so changes. 
I tested the changes with warden and the examples and nothing appears to be wrong, but I can't be sure since it looks like warden is broken with 7 failing tests on the Vulkan backend. But this appears to be a separate issue from updating Ash since warden is also broken on at least the 0.1 release and maybe earlier.
PR checklist:
- vulkan
> Updated Ash dependency from 0.24 to 0.26

- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/command.rs
- src/backend/gl/src/command.rs
- src/backend/metal/src/command.rs
- src/backend/vulkan/src/command.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/native.rs
- src/hal/src/command/raw.rs
- src/hal/src/pass.rs
Fixes #2248
PR checklist:
Interestingly, DX11/12 backends were already treating the clear color iterator as specified for cleared attachments only (presumably because I implemented that and I was confused in the first place).
@msiglreith comments are welcome! I don't feel super strong either way, just want to make the semantics stronger.
> Attachment clear order API changes

- src/backend/vulkan/src/conv.rs
Now that conversion methods abound in `ash` and `hal`, `mem::transmute` may be a thing of the past? 
PR checklist:
> [vulkan] Remove `mem::transmute` usages in `conv.rs` 

- src/hal/src/lib.rs
As suggested in PR 2539, this fixes the Features struct to have the correct names. Going by https://www.khronos.org/registry/vulkan/specs/1.1-khr-extensions/html/vkspec.html#features-features the `SHADER_RESIDENCY_IMAGE_2D` and `SHADER_RECIDENSY_IMAGE_3D` should be changed to     `SPARSE_RESIDENCY_IMAGE_2D` and `SPARSE_RESIDENCY_IMAGE_3D`.
PR checklist:
> Fix typo in physical device Features struct

- src/backend/vulkan/src/command.rs
Fixes #2552
PR checklist:
cc @kvark
> [vk] fix push constants offset

- src/backend/vulkan/src/lib.rs
`VK_EXT_debug_report` will be going stale, and `VK_EXT_debug_utils` is the new thing. 
Fixes #issue
PR checklist:
> [vulkan] Use `VK_EXT_debug_utils` instead of `VK_EXT_debug_report`

- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/lib.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/lib.rs
- src/backend/metal/src/device.rs
- src/backend/vulkan/src/conv.rs
- src/backend/vulkan/src/lib.rs
- src/hal/src/adapter.rs
Fixes #1928 by adding an optional parameter containing device features to enable. Currently only actually does anything on the Vulkan back-end since both Metal and DirectX use feature sets rather than fine grained features. If a device does not support all the requested features, than `DeviceCreationError::MissingFeature` is returned. I wasn't too sure what to do with `open_with`, but since it's just a convenience method, I thought it was alright to just not request any additional features. But I'm not sure if we want to expose it or not. Otherwise people can just use `PhysicalDevice::open` instead of `Adapter::open_with`
PR checklist:
- Vulkan on Linux
- Vulkan, DX12, DX11, OpenGL on Windows
> Support device specific feature requests

- src/backend/metal/src/lib.rs
Crash log: -[MTLDebugRenderCommandEncoder setDepthClipMode:]:2621: failed assertion `-[MTLDebugRenderCommandEncoder setDepthClipMode:] is only supported on MTLFeatureSet_iOS_GPUFamily2_v1 and later'
Fixes #issue
PR checklist:
> Fix crash on iPhone5s iOS 12.1

- src/hal/src/command/mod.rs
- src/hal/src/command/raw.rs
- src/hal/src/command/render_pass.rs
- src/hal/src/pool.rs
This PR:
- implements `Submittable` for `SubpassCommandBuffer`, thus allowing it to be recorded into primary command buffers. 
- Modifies `CommandPool::free` to allow freeing also secondary and subpass command buffers.
PR checklist:
> Improve secondary and subpass command buffers

- src/backend/metal/src/command.rs
PR checklist:
Without setting the viewport/scissor, metal will use a default 0x0 rect and clear nothing.
Also there is an Y flip for the clear. (Note: the blit code also uses the same Y flip)
> [MTL] Set viewport and scissor for clear

- src/backend/dx11/src/device.rs
- src/backend/dx12/src/device.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/device.rs
- src/backend/metal/src/device.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/backend/vulkan/src/window.rs
- src/hal/src/adapter.rs
- src/hal/src/device.rs
Depends on https://github.com/gfx-rs/gfx/pull/2565
Added the `get_pipeline_cache_data` function to query pipeline cache data from Device. Added the optional `data` member to `create_pipeline_cache` where we can supply the bytes of a loaded cache.
PR checklist:
- Vulkan (Windows, Linux)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/2566)
> [vk] Extend pipeline cache functionalities

- README.md
- src/backend/dx12/src/command.rs
Add note about switching `cwd` to examples to further clarify the comment in the code block.
#2567 accidentally used the wrong fork – not sure if that was causing issues with bors. Also fixed a typo in dx12, which should run AppVeyor just in case.
> Add note about `examples` directory

- src/backend/empty/Cargo.toml
- src/backend/empty/src/lib.rs
Makes it more straightforward to use the empty backend in place of other ones in a complex project.
r? @grovesNL
> Dummy surface creation for the empty backend

- src/backend/vulkan/src/command.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/backend/vulkan/src/native.rs
- src/backend/vulkan/src/pool.rs
- src/backend/vulkan/src/window.rs
Fixes #2585 
PR checklist:
cc @msiglreith
> [vk] remove unnecessary unsafe blocks

- src/backend/gl/src/lib.rs
A first pass at inferring the device type.  If we see "intel" in the device string we can be confident that it is an integratedgpu.  If we see "nvidia", "ati", or "amd" it is either going to be discrete or have performance much better than the intel integrated gpu. Otherwise we set device_type to Other since we really have no idea.
Fixes #2593 
PR checklist:
> add device_type inference to gl backend

- src/backend/gl/src/command.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/queue.rs
While researching how to support vendor id's I came across: http://vulkan.gpuinfo.org/
Which lists hardware and whether it is discrete or integrated.  By cross referencing with the opengl database I was able to expand on the logic for detecting integrated gpus.
Also it will set the vendor id based on the vendor string.
Supporting device id is not practical unless you want to pull in a huge database of strings and ids!
The last commit removes unnecessary unsafe blocks which cleans up the warning spam a lot.
PR checklist:
> [gl] Device type inference enhanced

- examples/colour-uniform/main.rs
- examples/quad/main.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/window.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/window/glutin.rs
- src/backend/metal/src/window.rs
- src/backend/vulkan/src/conv.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/window.rs
- src/hal/src/window.rs
> Fix default `CompositeAlpha` mode

- src/backend/metal/src/window.rs
On macOS with a Retina display, the surface `compatibility()` function was returning a non-DPI scaled value for `current_extent` (e.g. 640x360 when we were expecting 1280x720), which is not consistent with the behaviour on Windows, where a DPI-scaled value is returned.
My understanding is that the cause of this is that `NSView` `bounds` returns a value in "points" and you're meant to use `convertRectToBacking` to convert the value to pixels. Someone familiar with this backend, please review.
PR checklist:
> [mtl] fix DPI handling in surface extents

- src/backend/dx12/src/command.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/lib.rs
- src/backend/dx12/src/pool.rs
- src/backend/dx12/src/window.rs
> [dx12] remove unnecessary unsafe blocks

- src/backend/metal/src/command.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/soft.rs
Fixes #2564 
PR checklist:
This is basic support for SCBs, which allows us to pass those few tests in CTS that don't use events.
> [mtl] secondary command buffers

- .travis.yml
- bors.toml
- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/device.rs
- src/backend/empty/Cargo.toml
- src/backend/empty/src/lib.rs
- src/warden/src/gpu.rs
Backports a few essential changes in dx12 and empty backends.
PR checklist:
> [hal-0.1] back-port fixes in dx12 and empty

- src/backend/gl/src/device.rs
Fixes #2376 by letting them know they are misusing the API.
PR checklist:
> Added panic for attempting to render an image descriptor set to a surface

- src/backend/metal/src/device.rs
Allows the portability library to query image view support.
Also exposes the `SEPARATE_STENCIL_REF_VALUES` feature.
PR checklist:
> [mtl] expose a swizzle query

- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/lib.rs
Adds a method for enumerating the GPUs ordered by preference on Windows 10 v1803+ with the Direct3D 12 backend. Simply returns None on lower versions of the platform.
PR checklist:
> Add enumerate_adapters_by_gpu_preference

- .travis.yml
- bors.toml
- src/render/src/encoder.rs
- src/render/src/macros/mod.rs
- src/render/src/macros/pso.rs
- src/render/src/macros/structure.rs
See #2193 for details.
kvark you monster you made me figure out how to use `git squash` again.  :-P
Which apparently got git confused enough to require a new branch.
> Added `clear_raw()` methods to Encoder (squashed version of #2193).

- examples/colour-uniform/main.rs
- examples/quad/main.rs
- src/backend/dx11/src/device.rs
- src/backend/dx12/src/device.rs
- src/backend/gl/src/command.rs
- src/backend/metal/src/device.rs
- src/backend/vulkan/src/device.rs
- src/hal/src/pso/input_assembler.rs
Vulkan doesn't support input rates > 1 (instance rate). This PR changes the `VertexBufferDesc` rate to be an enum between `Vertex` and `Instance` to match Vulkan spec. Previously it was allowed to use a number > 1 and it would be properly passed through to the metal/dx12/dx11 backends, but there is no emulation for the Vulkan backend so it would create inconsistent behavior. 
PR checklist:
> Use enum for vertex input rate

- src/backend/metal/src/device.rs
> [mtl] improve pipeline_desc debug readability

- src/hal/src/command/mod.rs
> Expose `RawCommandBuffer::reset()` in `CommandBuffer`

- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/lib.rs
The `DXGI_CREATE_FACTORY_DEBUG` flag is only allowed to be passed to `CreateDXGIFactory2` if the debug interface is actually available. So this commit adds a check for whether it exists first.
Fixes #2630
> [D3D12] Conditionally pass the dxgi debug flag

- src/backend/metal/src/command.rs
- src/backend/metal/src/device.rs
> [mtl] improve literal readability

- src/backend/metal/src/command.rs
> [mtl] remove lifetime based on clippy's extra_unused_lifetimes warning

- reftests/scenes/vertex-offset.ron
> Fix reftest issue introduced in #2611

- examples/colour-uniform/main.rs
- examples/compute/main.rs
- examples/quad/main.rs
- src/backend/dx11/src/device.rs
- src/backend/dx12/src/device.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/device.rs
- src/backend/metal/src/device.rs
- src/backend/vulkan/src/conv.rs
- src/backend/vulkan/src/device.rs
- src/hal/src/device.rs
- src/hal/src/pso/descriptor.rs
- src/warden/src/gpu.rs
Allows specifying `DescriptorPoolCreateFlags::FREE_DESCRIPTOR_SET` on descriptor pool creation to allow individual descriptor sets to be freed with `DescriptorPool::free_sets` without triggering a validation error on the Vulkan backend.
PR checklist:
> Add `DescriptorPoolCreateFlags`

- src/backend/vulkan/src/lib.rs
Fixes a null pointer dereference in `debug_utils_messenger_callback` when `callback_data.p_message_id_name` is null. This occurs for example when injecting RenderDoc into the application. RenderDoc will output a debug message without specifying `p_message_id_name` for the message.
Fixes #issue
PR checklist:
> [vk] fix crash in `debug_utils_messenger_callback`

- src/hal/src/pool.rs
> [hal] remove unused lifetimes

- src/hal/src/adapter.rs
> [hal] more succinctly expressed by calling .find(p) instead.

- examples/quad/main.rs
Fixes TODOs in quad example and demonstrates a more proper method of frame synchronization
PR checklist:
> Improve frame synchronization in quad example

- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/lib.rs
Device `context` field (`ID3D11DeviceContext`) have to call `.Release()` in `Drop` impl.
> Implement Drop for Device

- src/backend/dx12/src/conv.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/resource.rs
Fixes the simple case of creating a depth texture and trying to view it as R32Float
PR checklist:
Edit: Closes https://github.com/gfx-rs/gfx/issues/2083 -msiglreith
> [dx12] create image with typeless format

- src/backend/dx12/src/command.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/pool.rs
Adjust reset behavior for associated allocator for individual command lists.
`quad` example runs fine (as expected).
wgpu examples will crash due to resetting the allocator while concurrent recording.
> dx12: Stricter allocator reset

- src/backend/vulkan/src/lib.rs
Mirror of #2669 for master instead of 0.1
PR checklist:
> Replace unimplemented! debug implementation with placeholder

- src/backend/dx12/src/command.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/resource.rs
Fixes #2614
Also contains a small but necessary follow-up to #2664
With these fixes, we only fail the fill_buffer tests, and that is easily explained by a giant TODO that now takes place inside :)
PR checklist:
> [dx12] relaxed vertex buffer binding

- src/backend/dx12/src/device.rs
Fixes the ability to create 2D views out of 2DArray images.
PR checklist:
> [dx12] coerse image views to arrays

- src/backend/dx12/src/command.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/resource.rs
Back-ports #2590, #2672, and #2674  to hal-0.1
makes the wgpu-rs shadow example work
PR checklist:
> [0.1/dx12] back-port vertex buffer fixes

- src/hal/src/queue/family.rs
Adds serde traits for trivially serializable `QueueFamilyId`.
PR checklist:
> Add serde derives to QueueFamilyId

- CHANGELOG.md
- examples/Cargo.toml
- examples/colour-uniform/main.rs
- examples/compute/main.rs
- examples/quad/main.rs
- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/conv.rs
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/internal.rs
- src/backend/dx11/src/lib.rs
Fixes dx11 to the point of being usable from wgpu-rs, enables it in the examples
PR checklist:
> [0.1/dx11] buffer creation and synchronization fixes

- src/backend/vulkan/src/device.rs
…ell as there being no pixel shader)
Fixes #issue
PR checklist:
> Only discard rasterization if no fragment shader and the Depth/Stencil tests are both disabled (Vulkan backend)

- Cargo.toml
- src/lib.rs
- src/shade.rs
(Note: this is for `pre-ll`)
I understand that `gfx_app` is meant to be a framework for the `gfx` examples, but I've found it to be very useful in prototype or toy renderers. My original intention was to generalize it a little such that more kinds of projects could use it, but I figured I'd start by documenting the existing code (and potentially creating a new project that just does the cross platform window/backend initialization that `gfx_app` does).
Please let me know if this PR is useful and what improvements I can make on it, if so!
Cheers!
> Add documentation to `gfx_app`

- src/backend/metal/src/command.rs
- src/backend/metal/src/conversions.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/lib.rs
- src/backend/metal/src/native.rs
Fixes vkQuake2 running on gfx-portability.
Changes are relatively harmless.
PR checklist:
> [mtl] expose line fill, fix MSAA views

- Cargo.toml
- examples/performance/main.rs
- src/window/dxgi/Cargo.toml
- src/window/glutin/Cargo.toml
- src/window/glutin/README.md
- src/window/glutin/src/headless.rs
- src/window/glutin/src/lib.rs
- src/window/metal/Cargo.toml
- src/window/vulkan/Cargo.toml
Bumped for release _(reflecting the v0.18 branch)_
* gfx_window_dxgi -> `0.19`
* gfx_window_glutin -> `0.30`
Also updated gfx_app `env_logger` and some dev-dependencies because why not?
PR checklist:
> [pre-ll] Update winit/glutin -> 0.19/0.20

- Cargo.toml
- examples/performance/main.rs
- src/window/dxgi/Cargo.toml
- src/window/glutin/Cargo.toml
- src/window/glutin/README.md
- src/window/glutin/src/headless.rs
- src/window/glutin/src/lib.rs
- src/window/metal/Cargo.toml
- src/window/vulkan/Cargo.toml
Bumped for release
* gfx_window_dxgi -> `0.19`
* gfx_window_glutin -> `0.30`
Also updated gfx_app `env_logger` and some dev-dependencies because why not?
PR checklist:
> [v0.18] Update winit/glutin -> 0.19/0.20

- src/backend/dx12/src/device.rs
Follow up for #2664. Without this I get an error, when calling `clear_attachments`, because the [format](https://github.com/gfx-rs/gfx/blob/master/src/backend/dx12/src/command.rs#L1345) is typeless:  
```
D3D12 ERROR: ID3D12Device::CreateRenderTargetView: The Format (0x3c, R8_TYPELESS) is invalid,
when creating a View; it is not a fully qualified Format castable from the Format of the 
Resource (0x3c, R8_TYPELESS). [ STATE_CREATION ERROR #38: CREATERENDERTARGETVIEW_INVALIDFORMAT]	
```
PR checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/2692)
> [dx12] fix image view format

- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/command.rs
- src/backend/vulkan/src/lib.rs
The related conversation is here: https://github.com/MaikKlein/ash/pull/191
Also updates ash version
PR checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/2693)
> [vk] Pass blend constant value by reference

- examples/quad/main.rs
Fixes a small error in the quad example that would cause problems for when `frames_in_flight` < `frame_images.len()`. Aligns the code with what the comments say.
> Fix acquire semaphore initialization in quad example

- Cargo.toml
- examples/colour-uniform/main.rs
- examples/quad/main.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/lib.rs
- src/backend/gl/src/command.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/info.rs
- src/backend/metal/src/command.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/lib.rs
- src/backend/vulkan/src/command.rs
- src/backend/vulkan/src/lib.rs
- src/hal/src/command/graphics.rs
- src/hal/src/command/raw.rs
- src/hal/src/command/render_pass.rs
- src/hal/src/lib.rs
- src/warden/src/bin/reftest.rs
- src/warden/src/gpu.rs
Closes #2201 
Fixes #2041
Allows WebRender to avoid hard-coding the texture limits. cc @zakorgy 
PR checklist:
> More detailed limits

- src/backend/dx12/src/command.rs
- src/backend/dx12/src/conv.rs
- src/backend/dx12/src/device.rs
Fixes WebRender issue with clear rectangles on DX12. cc @zakorgy 
Note: the swizzles are only implemented for SRV. I don't know how to get them for other views.
PR checklist:
> [dx12] clear attachments and SRV component swizzles

- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/conv.rs
- src/backend/dx12/src/device.rs
Sibling of #2696
PR checklist:
> [0.1/dx12] array attachment clear fix and SRV component mapping

- src/backend/metal/src/lib.rs
Fixes the crash on exit in Dolphin
PR checklist:
> [mtl] retain NSView when used with existing layer

- src/backend/dx11/src/internal.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/lib.rs
- src/backend/metal/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/hal/src/lib.rs
We can't remove the hard-coded defaults from gfx-portability until the backends start actually exposing sensible values....
PR checklist:
> Fill out some viewport/framebuffer limits

- src/backend/metal/Cargo.toml
- src/backend/metal/src/command.rs
- src/backend/metal/src/conversions.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/internal.rs
- src/backend/metal/src/lib.rs
- src/backend/metal/src/native.rs
- src/backend/metal/src/soft.rs
- src/backend/metal/src/window.rs
Allows us to get a better idea of the swapchain performance when looking at a system trace. Disabled by default.
PR checklist:
> Metal presentation signposts

- src/backend/metal/Cargo.toml
- src/backend/metal/src/command.rs
- src/backend/metal/src/device.rs
Metal piece of #2702
This is just an optimization. Main idea is to bring structure construction closer to the placement spot. I.e. instead of doing 1) construct 2) try extending the vector 3) write into it, we now do 2-1-3, which allows the compiler to construct the data in place (without any `box` magic).
PR checklist:
> [mtl] use copyless vec helper

- examples/colour-uniform/main.rs
- examples/quad/main.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/window.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/window/glutin.rs
- src/backend/metal/src/command.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/native.rs
- src/backend/metal/src/window.rs
- src/backend/vulkan/src/window.rs
- src/hal/src/lib.rs
- src/hal/src/window.rs
Fixes #2711
It makes us compatible with the updated Diligent Engine.
Also improves Metal limits and logging of fences.
PR checklist:
> Remove FrameSync, add support for Metal acquiring fences

- src/backend/metal/src/command.rs
Fixes the case when an incompatible pipeline is bound to a pass, but then used in the next pass.
PR checklist:
> [mtl] handle incompatible pipelines better

- src/backend/dx12/src/lib.rs
Fixes #issue
PR checklist:
I might be misunderstanding how closely gfx-hal and the backends follow the Vulkan Spec but, according to the [Vulkan Spec](https://vulkan.lunarg.com/doc/view/1.0.30.0/linux/vkspec.chunked/ch10s02.html), MemoryTypes can not be `COHERENT` or `CPU_CACHED` without also being `CPU_VISIBLE`. Before this change, removing just the `CPU_VISIBLE` flag would cause some MemoryTypes to have a flag of `COHERENT` or `COHERENT | CPU_CACHED`. This change removes the extra flags as they shouldn't be on there with MemoryTypes that are not `CPU_VISIBLE`.
> [dx12] Remove extra flags on certain MemoryTypes

- src/backend/metal/src/device.rs
I haven't fully verified that this is correct, but SPIRV-Cross seems to handle it in some way, and vkQuake3 doesn't complain any more :)
PR checklist:
> [mtl] expose clip distance feature

- src/backend/vulkan/src/window.rs
This PR exposes the `create_surface_from_vk_surface_khr` function, which should make it easier to use the Vulkan backend with libraries like GLFW and SDL.
Fixes #issue
PR checklist:
> [vulkan] make create_surface_from_vk_surface_khr public

- src/backend/vulkan/src/lib.rs
- src/hal/src/memory.rs
This commit updates the `COHERENT`, `CPU_VISIBLE` and `LAZILY_ALLOCATED` flags to match the order and values defined by Vulkan.
See https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkMemoryPropertyFlagBits.html
PR checklist:
> Fix `gfx_hal::memory::Properties` to match `VkMemoryPropertyFlagBits`

- src/backend/vulkan/src/lib.rs
Silences warnings on Windows about being unable to find the VK_KHR_xlib_surface, VK_KHR_xcb_surface, VK_KHR_wayland_surface and VK_KHR_android_surface extensions.
PR checklist:
> [vk] request surface extensions based on platform

- src/backend/gl/src/info.rs
> Remove `!is_emscripten` override for constant buffer support in GL backend

- src/hal/src/window.rs
> Change `surface.capabilities_and_formats(device)` to `surface.compatibility(device)` in the docs

- src/backend/vulkan/src/lib.rs
This is a follow up to #2698
Fixes https://github.com/szeged/webrender/issues/277
PR checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/2732)
> [vk] add max_image_array_layers limit

- src/backend/vulkan/src/device.rs
We were taking pointers to `attachment_refs`, but pushing to a `Vec` causes reallocation when the capacity is exceeded (`attachment_refs` has an initial capacity of 0), which invalidates existing pointers. Hence, if we have more than a single subpass, the first subpasses would contain invalid pointers.
Solves the issue by allocating `attachment_refs` in one go before iterating over the subpasses. I also noticed that we are able to use `Box<[_]>` here instead of `Vec<_>` because we don't need to be able to grow these containers, but this is not crucial in terms of function.
PR checklist:
> [vk] fix sporadic failures in `create_render_pass`

- src/backend/vulkan/src/device.rs
> Support attachment multisampling in vulkan backend

- src/backend/dx12/src/lib.rs
16x anisotropic filtering is supported across all feature levels, but the dx12 backend does not expose the `SAMPLER_ANISOTROPY` feature flag for the `PhysicalDevice`
PR checklist:
> [dx12] add missing SAMPLER_ANISOTROPY feature flag

- src/backend/metal/src/conversions.rs
- src/backend/metal/src/device.rs
Sets multisampling state for `MTLRenderPipelineDescriptor` and maps the `Image::Usage::INPUT_ATTACHMENT` flag to `MtlTextureUsage::ShaderRead`. This is enough to implement multisampling if you resolve the samples yourself using a fragment shader on a fullscreen quad in a separate subpass. Doesn't implement resolve attachments, but it looks like that could be added relatively easily in the future.
PR checklist:
> [mtl] add multisampling basics

- src/backend/metal/src/device.rs
- src/backend/metal/src/lib.rs
I also found out that the queried feature set was off by one version.
PR checklist:
> [mtl] Use private_caps data for reported texture sizes

- src/backend/gl/src/factory.rs
> [pre-ll] Add emscripten build failure workaround

- .travis.yml
- Cargo.toml
- src/backend/dx11/src/data.rs
- src/backend/gl/Cargo.toml
- src/backend/gl/src/tex.rs
- src/backend/metal/src/map.rs
- src/backend/vulkan/src/data.rs
- src/core/src/format.rs
- src/window/sdl/src/lib.rs
Adds compressed BC1 & BC3 image formats for gfx_device_gl/opengl. Image data is expected to be already compressed.
New formats:
* `SurfaceType::BC1_R8_G8_B8` (DXT1)
* `SurfaceType::BC3_R8_G8_B8_A8` (DXT5)
Each supports rgb & srgb.
Resolves #2688
I've been investigating texture compression to reduce VRAM usage in my game Robo Instructus. For this end I wanted more efficient 8-bit channel rgb & rgba storage with good opengl driver & hardware support.
S3TC is old and the best supported compression available (see https://opengl.gpuinfo.org/listcompressedformats.php). Patent issues are now history (see https://en.wikipedia.org/wiki/S3_Texture_Compression). For testing I used [GPUOpen-Tools/Compressonator](https://github.com/GPUOpen-Tools/Compressonator) for encoding, which is quite fast and …
> [pre-ll] Add BC1 (DXT1), BC3 (DXT5) S3TC texture formats

- .travis.yml
Checking if this fixes Travis CI on macOS/iOS (xcode9.4 is the default now)
> Bump Travis osx_image to xcode9.4

- examples/Cargo.toml
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/lib.rs
- src/warden/Cargo.toml
PR checklist:
vulkan
I updated everything I could test on my system, except the opengl dependencies where the glutin changes looked fairly involved and should be done by someone who better understands the backend.
The ash changes are because the Display output has been moved to Debug, as per the changelog: https://github.com/MaikKlein/ash/blob/master/Changelog.md
> Update env_logger, image, ron and ash versions

- src/backend/vulkan/src/lib.rs
> [vk] expose NON_FILL_POLYGON_MODE feature flag

- src/backend/dx12/src/command.rs
PR checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/2768)
> [dx12] Fix blit_image post barriers

- examples/colour-uniform/main.rs
- examples/quad/main.rs
- src/backend/gl/src/device.rs
- src/backend/metal/src/device.rs
- src/hal/src/pso/mod.rs
Attempt to bring type safety into specialization constants API.
No backend/examples change is required except types renaming.
Fixes #2382
Fixes #issue
PR checklist:
> Strongly typed specialization constants API

- examples/colour-uniform/main.rs
- examples/quad/main.rs
- src/backend/dx11/src/device.rs
- src/backend/dx12/src/device.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/command.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/info.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/native.rs
- src/backend/gl/src/queue.rs
- src/backend/gl/src/state.rs
- src/backend/gl/src/window/glutin.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/window.rs
- src/backend/vulkan/src/device.rs
- src/hal/src/adapter.rs
- src/hal/src/command/raw.rs
- src/hal/src/device.rs
- src/hal/src/lib.rs
- src/hal/src/mapping.rs
- src/hal/src/memory.rs
- src/hal/src/pass.rs
- src/hal/src/pso/graphics.rs
- src/hal/src/window.rs
WIP for fixing some of the shortcomings of the GL backend. 
Currently the fixes would allow Lokathor's gfx-hal tutorials to be ran on OpenGL as well.
Fixes: 
PR checklist:
> Implementing missing gl backend functions

- src/backend/vulkan/src/lib.rs
> [vulkan] Query VK_EXT_debug_utils support before creating messenger

- examples/colour-uniform/main.rs
- examples/quad/main.rs
- src/hal/src/device.rs
Fixes #2777:
- Add documentation to `create_framebuffer` indicating minimum dimensions
- Set minimum window dimensions of (1, 1) in examples
PR checklist:
- [*] tested examples with the following backends: gl, vulkan
- [*] `rustfmt` run on changed code
> Handle & document behavior re: framebuffers with any dimension == 0

- src/backend/vulkan/src/lib.rs
- src/hal/Cargo.toml
Backports #2778 to hal-0.2
cc @kvark 
Fixes #issue
PR checklist:
> [hal-0.2] Query VK_EXT_debug_utils support before creating messenger

- src/backend/vulkan/src/lib.rs
Fixes https://github.com/gfx-rs/gfx/issues/1805 I think.
The android ndk only ships with five validation layers and does not support `VK_LAYER_LUNARG_standard_validation`. This PR only enables the validation layers android supports.
```
VK_LAYER_LUNARG_core_validation
VK_LAYER_LUNARG_object_tracker
VK_LAYER_LUNARG_parameter_validation
VK_LAYER_GOOGLE_threading
VK_LAYER_GOOGLE_unique_objects
```
Additionally, the vulkan validation layers repo is only setup to build those 5 validation layers on android [source](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/build-android/jni/Android.mk).
> android only supports a subset of the standard validation layers

- src/hal/src/adapter.rs
- src/hal/src/lib.rs
- src/hal/src/queue/mod.rs
- src/hal/src/window.rs
> [hal] Add debug printing to `Adapter`

- src/hal/src/backend.rs
- src/hal/src/buffer.rs
- src/hal/src/command/mod.rs
- src/hal/src/command/raw.rs
- src/hal/src/command/render_pass.rs
- src/hal/src/lib.rs
- src/hal/src/mapping.rs
- src/hal/src/pass.rs
- src/hal/src/pso/descriptor.rs
- src/hal/src/pso/mod.rs
- src/hal/src/queue/capability.rs
- src/hal/src/queue/family.rs
- src/hal/src/queue/mod.rs
- src/hal/src/window.rs
> [hal] Add deny(missing_debug_implementations) to enforce debug printers

- src/backend/vulkan/src/window.rs
- src/hal/src/window.rs
> Add missing `Timeout` variant for `AcquireError`

- src/hal/src/window.rs
> [hal] fix typo

- src/hal/src/window.rs
> [hal] fix typos of Surface.

- examples/colour-uniform/main.rs
- examples/quad/main.rs
- reftests/scenes/basic.ron
- reftests/scenes/transfer.ron
- reftests/scenes/vertex-offset.ron
- src/backend/dx11/src/internal.rs
- src/backend/dx11/src/lib.rs
- src/backend/metal/src/command.rs
- src/backend/vulkan/src/conv.rs
- src/hal/src/command/graphics.rs
> [hal] Rename ClearColor::Type to ClearColor::Stype for consistency

- src/backend/metal/src/window.rs
> [mtl] keep the same order with hal::Surface

- src/hal/src/pso/output_merger.rs
> [hal] Fix typo in documentation

- src/backend/dx11/src/device.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/lib.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/command.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/lib.rs
- src/backend/metal/src/command.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/lib.rs
- src/backend/vulkan/src/command.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/backend/vulkan/src/native.rs
- src/hal/src/command/raw.rs
- src/hal/src/device.rs
- src/hal/src/lib.rs
Also adds placeholder implementations for all other backends.
Fixes #2804 
PR checklist:
> Add Events API and implement for Vulkan backend

- src/backend/metal/src/device.rs
- src/hal/src/lib.rs
Fixes a few invalid validation layer messages when running with `VK_LAYER_LUNARG_standard_validation`
PR checklist:
> Specify limits for portability validation layers

- CHANGELOG.md
- src/hal/Cargo.toml
- src/hal/src/adapter.rs
- src/hal/src/backend.rs
- src/hal/src/buffer.rs
- src/hal/src/command/mod.rs
- src/hal/src/command/raw.rs
- src/hal/src/command/render_pass.rs
- src/hal/src/lib.rs
- src/hal/src/mapping.rs
- src/hal/src/pass.rs
- src/hal/src/pso/descriptor.rs
- src/hal/src/pso/mod.rs
- src/hal/src/queue/capability.rs
- src/hal/src/queue/family.rs
- src/hal/src/queue/mod.rs
- src/hal/src/window.rs
Sibling of #2787 
cc @BourgondAries 
PR checklist:
> [hal-0.2] Back-port Debug implementations

- src/hal/src/memory.rs
> [hal] Merge use statements in memory module

- src/hal/src/image.rs
> hal: Merge use statements in image module

- src/hal/src/pass.rs
> hal: Merge use statements in pass module

- examples/colour-uniform/main.rs
- examples/quad/main.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/pool.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/pool.rs
- src/backend/metal/src/command.rs
- src/backend/metal/src/device.rs
- src/backend/vulkan/src/pool.rs
- src/hal/src/pool.rs
Fixes #2407.
The behavior of this parameter on various backends:
- dx11: no effect (RawCommandPool::reset is a no-op)
- dx12: no effect (ID3D12CommandAllocator::Reset always releases
resources)
- gl: no effect (OwnedBuffer implementation always clears all data)
- vulkan: if true, pass RELEASE_RESOURCES flag to reset_command_pool
- metal: pass value to CommandBufferInner::reset
Fixes #issue
PR checklist:
> Add release_resources to CommandPool::reset

- src/backend/metal/Cargo.toml
- src/backend/metal/src/command.rs
> [mtl] fix leaked render pass descriptor data

- src/backend/metal/Cargo.toml
- src/backend/metal/src/command.rs
Sibling of #2829
PR checklist:
> [mtl] wrap render pass configuration into an AR pool

- src/backend/metal/Cargo.toml
- src/backend/metal/src/device.rs
Fixes the string leaking.
PR checklist:
> [0.2/mtl] metal-rs update

- CHANGELOG.md
- Makefile
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/lib.rs
- src/backend/vulkan/src/window.rs
Fixes #2796 
PR checklist:
Users need to ensure that Vulkan loader is available and ICD paths are set up. I launched the example with the following command line:
```bash
LD_LIBRARY_PATH=<vulkan_sdk>/macOS/lib/ VK_ICD_FILENAMES=<gfx-portability>/libportability-icd/portability-macos-debug.json cargo run --bin quad --features vulkan
```
> MacOS vulkan portability support

- examples/colour-uniform/main.rs
- examples/compute/main.rs
- examples/quad/main.rs
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx11/src/shader.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/resource.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/native.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/native.rs
- src/backend/vulkan/src/device.rs
- src/hal/src/device.rs
- src/hal/src/lib.rs
- src/hal/src/pso/mod.rs
- src/warden/src/gpu.rs
The Vulkan spec [mandates](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkShaderModuleCreateInfo.html):
> pCode must be a valid pointer to an array of codeSize / 4 uint32_t values
The address of some random `&[u8]` does not satisfy this for the obvious alignment reasons. Additionally, most other backends used unsafe code to transmute `&[u8]` to `&[u32]`, which is similarly UB. This is a breaking change.
It'd be nice to have somewhere to factor the `read_spv` helper out to.
PR checklist:
- vulkan
> Fix incorrect alignment assumptions in create_shader_module

- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/lib.rs
- src/backend/vulkan/src/window.rs
Reduces gratuitous foreign dependencies for some applications.
PR checklist:
- vulkan
> vulkan: don't unconditionally link xlib or xcb

- examples/colour-uniform/main.rs
#2833 seems to have inadvertently broken this example
PR checklist:
> Fix colour-uniform example

- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/command.rs
- src/backend/vulkan/src/conv.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/backend/vulkan/src/native.rs
- src/backend/vulkan/src/pool.rs
- src/backend/vulkan/src/result.rs
- src/backend/vulkan/src/window.rs
Fixes #2827 
Ran `cargo fix --edition`
Ran `cargo fix --edition-idioms`
PR checklist:
+ there were more changes than what I committed but they weren't relevant to anything in this commit so i didn't include them.
> upgrade vulkan backend to 2018 edition

- src/backend/gl/Cargo.toml
- src/backend/gl/src/command.rs
- src/backend/gl/src/conv.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/native.rs
- src/backend/gl/src/queue.rs
- src/backend/gl/src/window/glutin.rs
- src/backend/gl/src/window/web.rs
Allocates native buffers to back memory as soon as allocate_memory is called,
hal buffers become logical sub-ranges of native buffers.
This is still WIP, there is a lot of room for improvement here.  Separate INDEX
memory could be reserved only for webgl, there could be separate upload /
download memory, and the end of buffer sub-ranges could be checked with asserts
in debug mode.
Fixes #2812
PR checklist:
> Rework of gl memory / buffer handling

- src/backend/vulkan/src/lib.rs
> [vk] fix warnings wrt missing WSI extensions on macOS

- src/backend/dx11/src/factory.rs
- src/backend/dx11/src/mirror.rs
- src/render/src/pso/buffer.rs
Fixes #2748
PR checklist:
This changeset adds support for HLSL semantic indices.
Users should now be able to specify a semantic with an index (such as `"TEXCOORD1"`) in their pipeline. If one does not include the index, an index of `0` is assumed (as HLSL assumes).
Introduces a struct that can be converted to and from a packed String.
Here are some sample mappings:
- `"TEXCOORD"` -> `VertexSemantic { name: "TEXCOORD", index: 0 }` -> `"TEXCOORD0"`
- `"TEXCOORD0"` <-> `VertexSemantic { name: "TEXCOORD", index: 0 }`
- `"TEXCOORD10"` <-> `VertexSemantic { name: "TEXCOORD", index: 10 }`
On link_input, we will try linking against the semantic name and index together (e.g. `"TEXCOORD0"`) and also just the semantic name (e.g. `"TEXCOORD"`) if the semantic index is 0, in the case that the user did …
> [pre-ll] Support HLSL semantic indexes

- src/backend/gl/src/device.rs
- src/backend/gl/src/info.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/native.rs
- src/backend/gl/src/queue.rs
`buffer_role_change` is replaced by `index_buffer_role_change` which is limited
solely to buffers used as GL_ELEMENT_ARRAY_BUFFER target.  This is simpler, as
only a single buffer role is ever isolated.
This commit also:
* contains some minor corrections for buffer binding to more appropriate targets
* removes an old, improper assert that made it impossible to map memory on
`buffer_role_change` targets anyway.
Fixes #2844
PR checklist:
- [*] `make` succeeds (on *nix)
- [*] `make reftests` succeeds
- [*] tested examples with the following backends: gl
> Remove `buffer_role_change` flag and correct some buffer target logic

- src/backend/metal/src/command.rs
I think that there's `resize()` already so we don't need to clear/truncate it first which brings some impact performance to iOS devices.
Fixes #issue
PR checklist:
> mtl: Remove unnecessary `Vec::clear()`

- src/backend/gl/src/device.rs
- src/backend/gl/src/lib.rs
Also disables coherent memory types when glBufferStorage is not available
Fixes #issue
PR checklist:
> Only set persistent | coherent map flags when we have glBufferStorage

- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/device.rs
Backport of https://github.com/gfx-rs/gfx/pull/2813/files
I am able to get MSAA working on wgpu only with these changes.
Includes a new minor release, is there a process I should be aware of here?
The new release is needed because it is impractical to get wgpu to use these changes without a new release because of rendy's dependency on gfx-hal.
Simply using a specific git commit fails because rendy and wgpu both need to refer to the same trait from gfx-hal.
Fixes #issue
PR checklist:
- ~~[ ] `rustfmt` run on changed code~~
> [0.2] Backport renderpass resolve attachments fix

- src/backend/gl/Cargo.toml
- src/backend/gl/src/device.rs
- src/backend/gl/src/native.rs
- src/backend/gl/src/queue.rs
~~gl fences can now be in three states, raw (meaning they are backed by a raw
fence which is signaled or unsignaled), fake-signaled, and fake-unsignaled.
When creating a new fence, fences will start in the fake-unsignaled or
fake-signaled fence depending on how they are created.  waiting on a
fake-unsignaled fence will turn it into an unsignaled real raw fence and then
that and any further wait will wait on the real fence.~~
~~Before, fences created in the 'signaled' state would be created with a
raw *unsignaled* fence which was wrong, and reset fences would be set to None,
causing incorrect panics on future fence operations.  This change should fix
both these issues.~~
I wasn't thinking clearly about how fences were supposed to work, the gl fence implementation now mimics the metal …
> Quite a few gl backend fence fixes

- src/backend/gl/src/queue.rs
> Fall back to f32 depth range on gl backend

- examples/colour-uniform/main.rs
- examples/quad/main.rs
- src/backend/gl/Cargo.toml
- src/backend/gl/src/lib.rs
- src/backend/gl/src/queue.rs
- src/backend/gl/src/window/glutin.rs
- src/warden/src/bin/reftest.rs
Fixes #2757
Note that this represents a significant change to the public API of the OpenGL backend. In addition to the various type changes needed due to changes in Glutin 0.21:
1) In Glutin 0.21, `make_current()` consumes the `Context` struct. So it is not possible for the types in `gfx-backend-gl::window::glutin` to make themselves the current context anymore. After this PR, the calling code must make the context current before instantiating any gfx windowing types.
1) `gfx-backend-gl::window::glutin::Headless` must now carry a Starc because only _non_-current contexts implement `Send` and `Sync` in Glutin 0.21, but only _current_ contexts can be used to implement `hal::Instance`. To help with constructing a `Headless`, I have added `Headless::from_context()`.
1) `get_window()` has been …
> Update Glutin to 0.21.0

- src/backend/gl/src/command.rs
- src/backend/gl/src/info.rs
- src/backend/gl/src/queue.rs
- src/backend/gl/src/state.rs
This should enable the gl backend to support multiple draw buffers with all the
same blend settings even if glColorMaski / glBlendEquationi / glBlendFunci are
not available.
(Edit: also it should fix several problems, blend settings do not appear to work at all without this even with a single output target if glColorMaski / glBlendEquationi / glBlendFunci are not available)
Fixes #issue
PR checklist:
> More carefully set blend settings in the gl backend

- src/backend/gl/Cargo.toml
- src/backend/gl/src/command.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/native.rs
- src/backend/gl/src/queue.rs
- src/backend/gl/src/window/glutin.rs
- src/backend/gl/src/window/web.rs
> Support copying buffer to 2d texture array in gl backend, copy with proper texture format

- src/backend/metal/src/command.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/lib.rs
- src/backend/metal/src/native.rs
- src/warden/src/gpu.rs
Fixes #2848
Basic approach is described in the comments. We put push constants first, descriptors later, and vertex buffers at the end.
Based on #2840
Actually, it makes it impossible to use argument buffers together with push constants. We need a way to set argument buffer overrides in spirv-cross to fix that.
PR checklist:
> [mtl] better pipeline layout

- rustfmt.toml
> blank_lines_upper_bound = 2
This allows us to put more than a single blank line between important sections. I was really confused when rustfmt started erasing my empty lines separating `use` sections from the other items, for example. No more!
> spaces_around_ranges = true
Ranges are often used with non-trivial values on both sides, so spaces look much better.
> imports_layout = "HorizontalVertical"
A compromise...
> Some long-needed rustfmt changes

- src/backend/gl/src/info.rs
It is supposed to be a mask of acceptable sample counts (which must be a power
of 2).  We assume here that GL_MAX_SAMPLES is a power of 2, all powers of 2 less
than it are acceptable sample counts.
Fixes #issue
PR checklist:
> fix the `Limits::framebuffer_color_samples_count` field on the gl backend

- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/lib.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/window/glutin.rs
- src/backend/metal/src/lib.rs
Fixing https://github.com/gfx-rs/wgpu/issues/76 is blocked on the `Instance` types for all the backends not implementing `Debug`. This patch adds `#[derive(Debug)]` to all the instances.
PR checklist:
> Derive Debug for All Backend Instances

- src/backend/metal/Cargo.toml
- src/backend/metal/build.rs
This adds support for the iOS simulator. Xcode11 (in beta) supports metal in the simulator with pretty decent performance.
I had some trouble with spirv-cross as well (`-std=c++14` doesn't appear to be set), but I hackily worked around that to test this.
> [ios][metal] xcode11 supports metal on ios simulators

- src/backend/gl/Cargo.toml
- src/backend/gl/src/lib.rs
Will fix #2826 when grovesNL/glow#20 lands.
PR checklist:
> [gl] Enable debug output for native GL

- .travis.yml
- src/backend/metal/Cargo.toml
- src/backend/metal/src/command.rs
- src/backend/metal/src/native.rs
> Fixes #issue
Doesn't fix, but found during https://github.com/gfx-rs/gfx/issues/2563
> PR checklist:
> - [ ] `make` succeeds (on *nix)
Yes.
> - [ ] `make reftests` succeeds
No, as it seems to be trying to compile with the feature this patch adds ('signpost') turned on?
> - [ ] tested examples with the following backends:
metal
> - [ ] `rustfmt` run on changed code
I don't know how, but I tried to copy the existing style.
> kdebug_signpost* fns don't exist on macOS 10.11

- src/backend/metal/src/command.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/lib.rs
- src/backend/metal/src/native.rs
Fixes #2809
Passes the relevant Vulkan CTS test! Although, might still have logic flows due to complexity of the synchronization here.
Based on #2840 and #2857
PR checklist:
> [mtl] Events

- Makefile
- examples/Cargo.toml
- examples/quad/main.rs
- src/backend/gl/Cargo.toml
- src/backend/gl/build.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/queue.rs
- src/backend/gl/src/window/glutin.rs
- src/backend/gl/src/window/mod.rs
- src/backend/gl/src/window/web.rs
- src/backend/gl/src/window/wgl.rs
Add a wgl based window interface backend for the gl backend. This allows to get closer to the Vulkan API and a step towards multithreaded OpenGL.
It's based around context sharing where we seperate two different context types: PresentContext and DeviceContext. Each swapchain will have a present context which only does blitting towards the default framebuffer of the underlying surface and presentation. The device context is backed by no real surface/window and does the usual command submission etc. All contexts are shared. Present and device contexts only share the swapchain images.
Future work would include adding glx, egl and web support. Wayland + EGL turned out to be really tricky, need to look a layer deeper I guess (below EGL?). This PR should be an initial test for this approach and …
> gl: Add wgl WSI backend

- src/backend/dx11/src/device.rs
- src/backend/dx12/src/device.rs
- src/backend/gl/src/device.rs
- src/backend/metal/Cargo.toml
- src/backend/metal/src/device.rs
- src/backend/metal/src/lib.rs
- src/backend/metal/src/native.rs
- src/backend/vulkan/src/device.rs
- src/hal/src/image.rs
- src/hal/src/lib.rs
Also adds unnormalized sampling to HAL.
Blocked on spirv_cross 0.15.0 release.
Fixes #2837
Partially fulfills #2883 
PR checklist:
> Hardcoded immutable samplers in Metal

- src/backend/gl/src/queue.rs
This fixes `vertex_attrib_divisor` not being reset to `0` properly after using instanced drawing.
PR checklist:
> Reset `vertex_attrib_divisor` to `0` when needed on GL backend

- src/backend/gl/src/device.rs
I needed to support this format for the glyph cache in [`wgpu_glyph`].
[`wgpu_glyph`]: https://github.com/hecrj/wgpu_glyph
PR checklist:
> Support `R8Unorm` format in GL backend

- src/backend/gl/src/queue.rs
Currently, when there are no sync capabilites, the GL backend returns an unsignaled fence on `submit` which only changes to signaled if `wait_for_fence` is called. This behavior causes memory to _never_ be freed when using WebGL2 on `wgpu`.
The changes here flush immediately on `submit` in this case, and return an already signaled fence. I am not sure if this is the correct way to fix this. Let me know how to proceed.
PR checklist:
> Flush on `submit` in GL when there are no sync capabilities

- src/backend/gl/src/device.rs
- src/backend/gl/src/queue.rs
- src/backend/gl/src/window/web.rs
When working on #2892, I noticed that when using WebGL with the GL backend, the latest bound FBO was being blitted to the default framebuffer, instead of the correct swapchain FBO.
The changes in this PR fix this issue while:
- Unifying swapchain creation and presentation
- Removing related unused code
- Removing a related unnecessary unsafe block
PR checklist:
> Fix WebGL always presenting latest bound FBO

- src/backend/metal/src/lib.rs
Before this PR I was getting metal validation errors on iOS sim.
According to the apple [docs](https://developer.apple.com/documentation/metal/mtlrendercommandencoder/1516267-setdepthclipmode?language=objc), setDepthClipMode requires atleast ios gpu family 4 or later. FWIW it appears that iOS simulators do not support that gpu family.
This PR also bumps the metal backend version.
Also, it looks like apple is moving away from [FeatureSets](https://developer.apple.com/documentation/metal/mtlfeatureset?language=objc) to just Metal version and GPU Families. Probly due to metal on iOS sim.
> If your app is running on Metal 3.0 or later, don't use MTLFeatureSet. Instead, search for Metal software versions (supportsVersion:) and Metal GPU families (supportsFamily:).
> [mtl] Fixes the FeatureSet requirement for calling setDepthClipMode

- src/backend/gl/src/command.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/info.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/native.rs
- src/backend/gl/src/pool.rs
- src/backend/gl/src/queue.rs
- src/backend/gl/src/window/glutin.rs
- src/backend/gl/src/window/web.rs
- src/backend/gl/src/window/wgl.rs
This changes attachments references confusion that led to `draw_buffers` to contain shifted indices.
Also this opens route to support multiple subpasses in one render pass by having fbo per subpass.
> Fix attachments confusion

- src/backend/vulkan/src/lib.rs
Fixes #2783
PR checklist:
I looked through all other backends and could not find any other obvious unrecoverable aborts.
> Fix recovery of failed enumeration of physical devices

- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/lib.rs
- src/backend/gl/src/info.rs
- src/backend/metal/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/hal/src/lib.rs
closes https://github.com/gfx-rs/gfx/issues/2859
PR checklist:
- vulkan
- gl
~~- [ ] `rustfmt` run on changed code~~
> Make Limits sample_counts field naming consistent with vulkan

- examples/colour-uniform/main.rs
- examples/quad/main.rs
Fixes Validation error
> [2019-07-27T02:28:11Z ERROR gfx_backend_vulkan]
> VALIDATION [VUID-VkWriteDescriptorSet-descriptorType-01403 (0)] : vkUpdateDescriptorSets() failed write update validation for Descriptor Set 0x6 with error: Write update to VkDescriptorSet 0x6 allocated with VkDescriptorSetLayout 0x4 binding #0 failed with error message: Attempted write update to image descriptor failed due to: Descriptor update with descriptorType VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE is being updated with invalid imageLayout VK_IMAGE_LAYOUT_UNDEFINED. Allowed layouts are: VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL, VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL, VK_IMAGE_LAYOUT_GENERAL. The Vulkan spec states: If descriptorType is VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE or …
> Fix: Vulkan validation for examples using ShaderReadOnlyOptimal

- src/backend/gl/src/command.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/native.rs
- src/backend/gl/src/queue.rs
This is probably incomplete (and wrong). Now, it just always copies the color attachment. I imagine we should check the subresource layers in `data`. I would appreciate some guidance, is that easily implementable from here?
PR checklist:
> Implement surface-to-surface copy in GL backend

- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/device.rs
> [dx12] allow view creation to fail

- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/lib.rs
Fixes wgpu-rs "msaa-line" example to work properly.
PR checklist:
> [0.2/dx12] query supported multisample counts

- src/hal/src/pass.rs
Fixes https://github.com/gfx-rs/gfx/issues/2861
PR checklist:
- vulkan linux
~~- [] `rustfmt` run on changed code~~
> Add ATTACHMENT_UNUSED constant

- src/backend/vulkan/src/lib.rs
> Use all device features provided by vulkan

- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/window.rs
- src/backend/gl/src/window/glutin.rs
- src/backend/gl/src/window/web.rs
- src/backend/gl/src/window/wgl.rs
- src/backend/metal/src/window.rs
- src/backend/vulkan/src/window.rs
- src/hal/src/window.rs
Fixes https://github.com/gfx-rs/gfx/issues/2571
PR checklist:
vulkan - linux
gl - linux
~~`rustfmt` run on changed code~~
> Change SurfaceCapabilities fields to use RangeInclusive instead of Range

- src/backend/metal/Cargo.toml
Depends on kvark/storage-map#2 and needs a new version published of storage-map
PR checklist:
> [mtl] update parking_lot dependency to 0.9.0

- src/backend/metal/src/conversions.rs
> [mtl] fix missing depth formats on iOS

- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/conv.rs
- src/backend/dx12/src/device.rs
Just improves the root signature a bit...
PR checklist:
> [0.2/dx12] refactored root signature creation, improved shader visibility

- src/backend/dx12/src/command.rs
- src/backend/dx12/src/conv.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/lib.rs
- src/backend/dx12/src/resource.rs
Addresses the DX12 side of #2933 
PR checklist:
@msiglreith please take a careful look at it. I still need to run it over CTS to see if anything regressed, but the code should be ready for the review now.
> [dx12] read-only storage descriptors

- src/backend/metal/src/lib.rs
- src/backend/metal/src/window.rs
Fixes #issue
PR checklist:
r? @mtak-
> [mtl] fix `CAMetalLayer` creation and resize on iOS

- src/backend/metal/src/command.rs
- src/backend/metal/src/lib.rs
- src/backend/metal/src/window.rs
> [mtl] add explicit return types for `msg_send!` calls

- examples/colour-uniform/main.rs
- examples/quad/main.rs
- reftests/scenes/basic.ron
- reftests/scenes/vertex-offset.ron
- src/backend/dx11/src/conv.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx11/src/shader.rs
- src/backend/dx12/src/conv.rs
- src/backend/gl/src/command.rs
- src/backend/gl/src/native.rs
- src/backend/gl/src/queue.rs
- src/backend/gl/src/state.rs
- src/backend/metal/src/command.rs
- src/backend/metal/src/conversions.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/internal.rs
- src/backend/metal/src/native.rs
- src/backend/metal/src/soft.rs
- src/backend/vulkan/src/conv.rs
- src/backend/vulkan/src/device.rs
- src/hal/src/pso/graphics.rs
- src/hal/src/pso/output_merger.rs
- src/warden/Cargo.toml
- src/warden/src/bin/reftest.rs
- src/warden/src/gpu.rs
- src/warden/src/lib.rs
- src/warden/src/raw.rs
> Dynamic PSO states refactor

- examples/Cargo.toml
- examples/colour-uniform/main.rs
- examples/quad/main.rs
- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/lib.rs
- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/window.rs
- src/backend/empty/Cargo.toml
- src/backend/empty/src/lib.rs
- src/backend/gl/Cargo.toml
- src/backend/gl/src/lib.rs
- src/backend/gl/src/window/glutin.rs
- src/backend/gl/src/window/wgl.rs
- src/backend/metal/Cargo.toml
- src/backend/metal/src/lib.rs
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/window.rs
- src/warden/src/bin/reftest.rs
Fixes https://github.com/gfx-rs/gfx/issues/2874
PR checklist:
*   Backends: vulkan and opengl
*   OS: Arch Linux
*   GPU: GTX 960
*   Driver: Nvidia proprietary driver
- [] `rustfmt` run on changed code - its panicking and changing things outside of my commit :/ I'll look into this later
Concerns:
*   I had to comment out some opengl specific resize handling code, I dont seem to be able to call the needed functions on a `B::Surface` and I dont understand the rules behind how the `back::surface` becomes a `B::Surface` But it seems to still handle resize without this code?
*   The other backends I haven't tested can be assumed to not work.
*    I have copied the code from the unstabilized ManuallyDrop::take implementation in order to cleanup the resources.
*   For now the colour-uniform …
> Upgrade to winit 0.20.0

- src/backend/vulkan/src/device.rs
Related to #1510
PR checklist:
Hello!
The fix is obvious, the: `primitiveRestartEnable` property of the [VkPipelineInputAssemblyStateCreateInfo](https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VkPipelineInputAssemblyStateCreateInfo) should be `VK_TRUE` for `primitive_restart` == `pso::PrimitiveRestart::U16` or `pso::PrimitiveRestart::U32`. It doesn't matter which `IndexType` you later bind the index buffer with.
> Vulkan: fix setting up primitive restart enable flag while creating graphics pipeline

- src/backend/gl/Cargo.toml
- src/backend/gl/src/lib.rs
- src/backend/vulkan/src/lib.rs
This fixes the quad example on native GL.
We were unwrapping an invalid enum error when getting the `VENDOR` string, but the invalid enum was actually caused by trying to unconditionally use a constant from the KHR_debug extension.
PR checklist:
> gl: Check for debug extension support

- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/descriptors_cpu.rs
- src/backend/dx12/src/lib.rs
- src/backend/dx12/src/pool.rs
- src/backend/dx12/src/resource.rs
- src/backend/dx12/src/window.rs
- src/backend/gl/Cargo.toml
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/lib.rs
- src/backend/vulkan/src/window.rs
- src/hal/Cargo.toml
- src/hal/src/buffer.rs
- src/hal/src/command/clear.rs
- src/hal/src/device.rs
- src/hal/src/error.rs
- src/hal/src/image.rs
- src/hal/src/lib.rs
- src/hal/src/mapping.rs
- src/hal/src/pso/descriptor.rs
- src/hal/src/pso/mod.rs
- src/hal/src/query.rs
- src/hal/src/window.rs
- src/warden/Cargo.toml
- src/warden/src/gpu.rs
This cleans up our dependencies slightly through version matching or dependency removal.
Fixes #2436
- Removes `failure`
- `failure`'s README describes that it's in a bit of flux as improvements are being made to Rust's stdlib upstream, so we might want to avoid relying on it too greatly in its current state
- we aren't really using `failure` consistently throughout, and many of the messages are just taken directly from doc comments anyway. While we could make usage more consistent, it's not clear that this effort will be very useful if it's incompatible with upstream changes in Rust itself.
- Matches spirv_cross version across all backends
- Removes `derivative`
- most existing usages seem like they could be treated as opaque types because they don't provide much debug information, so we …
> Cleanup dependencies

- src/backend/metal/Cargo.toml
- src/backend/metal/src/command.rs
Fixes the leak of render command encoders
PR checklist:
> Metal: update metal-rs and wrap RP switch into an ARP

- CHANGELOG.md
- src/backend/metal/Cargo.toml
- src/backend/metal/src/command.rs
Sibling of #2972 for hal-0.3 with a version bump
> [0.3/mtl] update metal-rs and wrap RP switch into an ARP

- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/lib.rs
- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/window.rs
- src/backend/empty/Cargo.toml
- src/backend/empty/src/lib.rs
- src/backend/gl/Cargo.toml
- src/backend/gl/src/window/wgl.rs
- src/backend/metal/Cargo.toml
- src/backend/metal/src/lib.rs
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/window.rs
- src/hal/Cargo.toml
- src/hal/src/window.rs
Closes #2956.
PR checklist:
Non-breaking change version of #2967.
Currently Android is not supported in raw-window-handle and therefore unimplemented in gfx-backend-vulkan - waiting on https://github.com/rust-windowing/raw-window-handle/issues/12 to be resolved.
> [hal-0.3] Add support for `raw-window-handle`

- .travis.yml
- src/backend/gl/src/command.rs
- src/backend/gl/src/factory.rs
- src/backend/gl/src/info.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/shade.rs
- src/backend/gl/src/state.rs
- src/backend/gl/src/tex.rs
Fixes gfx_device_gl to compile on recent nightlies, fixes #2964. Cherry picked from #2979 into `v0.18`.
PR checklist:
> [v0.18] Remove `core` alias in gfx_device_gl

- .travis.yml
- src/backend/gl/src/command.rs
- src/backend/gl/src/factory.rs
- src/backend/gl/src/info.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/shade.rs
- src/backend/gl/src/state.rs
- src/backend/gl/src/tex.rs
Fixes `gfx_device_gl` to compile on recent nightlies, see #2964. I only removed the alias usage in this crate as it was the one that seems to cause issues.
PR checklist:
> [pre-ll] Remove `core` alias in gfx_device_gl

- examples/colour-uniform/main.rs
- examples/compute/main.rs
- examples/quad/main.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/lib.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/window/wgl.rs
- src/backend/metal/src/lib.rs
- src/backend/vulkan/src/lib.rs
- src/hal/src/lib.rs
- src/warden/src/bin/bench.rs
- src/warden/src/bin/reftest.rs
This is required for https://github.com/gfx-rs/wgpu/pull/311 and similar things that try to do more work at run-time instead of relying on the user-selected features. (Note: still needs to be back-ported to hal-0.3 before we can use it in wgpu).
PR checklist:
> Allow instance creation to fail

- CHANGELOG.md
- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/lib.rs
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/lib.rs
Bears the essence of #2981 from `master`: only for Vulkan and DX12, so that wgpu can use them properly.
> [0.3] Add Instance::try_create methods

- src/backend/metal/Cargo.toml
- src/backend/metal/src/window.rs
> [0.3-mtl] make resize fill configurable

- src/backend/metal/Cargo.toml
- src/backend/metal/src/window.rs
Sibling of #2986 for `master`
PR checklist:
> [mtl] make resize fill configurable

- src/backend/empty/src/lib.rs
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/device.rs
- src/hal/src/device.rs
- src/warden/src/gpu.rs
Fixes #2987
PR checklist:
`make` succeeds on Windows, and `make reftests` fails even on master, didn't try building on Linux.
This greatly reduces the amount of Vecs used on the Vulkan create_*_pipeline(s) by combining vectors.
> Reduces allocations on Vulkan create_*_pipeline(s), and fixes #2987

- src/backend/vulkan/src/lib.rs
- src/backend/vulkan/src/window.rs
> Fix compilation to iOS failed

- src/backend/gl/src/lib.rs
Fixes #2962
I'm not %100 sure this is the correct solution. Since the checks are only for string containment, I'm fairly sure SwiftShader would apply for any string that contains "swiftshader".
PR checklist:
> [gl] add SwiftShader to list of CPU renderers

- src/backend/vulkan/src/device.rs
PR checklist:
`make` succeeds on Windows excluded DX11, did not test on *nix.
> Makes create_*_pipeline allocate 1 less Vec on Vulkan

- src/backend/gl/Cargo.toml
- src/backend/gl/src/command.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/native.rs
- src/backend/gl/src/pool.rs
PR checklist:
`make` succeeds on Windows with DX11 disabled.
Please note that `parking_lot` types do not become poisoned, so a program behaviour may be different if a locking thread panics.
> Makes gl backend use parking_lot

- src/backend/dx11/src/device.rs
- src/backend/dx12/src/device.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/device.rs
- src/backend/metal/Cargo.toml
- src/backend/metal/src/command.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/native.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/hal/src/device.rs
Resolves a part of #1508
PR checklist:
> [mtl][vk] add object debug labels

- src/backend/dx11/src/device.rs
- src/backend/dx11/src/lib.rs
> [dx11] remove unnecessary unsafe blocks

- Cargo.toml
- src/auxil/auxil/Cargo.toml
- src/auxil/auxil/src/lib.rs
- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/lib.rs
- src/backend/dx11/src/shader.rs
- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/lib.rs
- src/backend/gl/Cargo.toml
- src/backend/gl/src/device.rs
- src/backend/metal/Cargo.toml
- src/backend/metal/src/device.rs
> Deduplicate spec const code shared between backends

- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
Fixes #issue
PR checklist:
Allows debug output again on platforms without the `VK_EXT_debug_utils` extension, such as android.
Minor fix for platforms where `c_char = u8` (also android :smile:)
> [vk] fall back to debug report when debug utils is not available

- examples/colour-uniform/main.rs
Fixes #3015
PR checklist:
@Herschel I wasn't able to repro the validation error about Present layout, and the code looks like it should be correct, so not sure what to make of that. Is you Vulkan SDK fresh? Do you still see this error?
> End render pass in colour-uniform

- src/backend/dx11/src/device.rs
- src/backend/dx12/src/device.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/device.rs
- src/backend/metal/src/device.rs
- src/backend/vulkan/src/device.rs
- src/hal/src/device.rs
> [vk] add debug labels for descriptor sets

- CHANGELOG.md
- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/conv.rs
- src/backend/dx12/src/device.rs
Follow-up to #3010 that tries to address #3009 better. Replaces #3013
Edit: this combines parts 2 and 3 of the big dx12 barrier refactor :)
PR checklist:
Contains 2 ideas:
1. we try to extract more information out of the image layouts, which is more robust
2. we are very selective in the external access dependencies, only taking ones that are related to where the attachment is used first or last.
> [0.3/dx12] rework resource state conversion, better external barriers

- src/backend/dx12/src/root_constants.rs
- src/backend/metal/src/device.rs
- src/backend/vulkan/src/device.rs
- src/hal/src/command/mod.rs
- src/hal/src/device.rs
> Take the push constant range as bytes in `create_pipeline_layout`

- src/backend/vulkan/src/window.rs
Currently wayland support is behind "x11" feature gate. This change separates those two.
PR checklist:
> Support wayland without x11 feature

- src/backend/dx12/src/conv.rs
- src/hal/src/buffer.rs
> Issue #3003: Rename constant CONSTANT_BUFFER_READ to UNIFORM_READ

- src/backend/metal/Cargo.toml
- src/backend/metal/src/lib.rs
When a `CAMetalLayer` is created by the Metal backend, the contents scale factor is set to match the window scale factor. However, we weren't updating this scale factor if the window scale factor changed later on (such as when moved to a screen with a different scale factor, or when entering exclusive fullscreen mode)!
AppKit updates the contents scale factor automatically for layers that it manages, but for layers created and managed by us, we must implement [`NSViewLayerContentScaleDelegate`](https://developer.apple.com/documentation/appkit/nsviewlayercontentscaledelegate?language=objc) and explicitly opt-in to this behaviour.
PR checklist:
> [mtl] update `CAMetalLayer` contents scale automatically on macOS

- src/core/Cargo.toml
- src/core/src/factory.rs
- src/core/src/handle.rs
- src/core/src/lib.rs
- src/render/Cargo.toml
- src/render/src/factory.rs
- src/render/src/lib.rs
- src/render/src/pso/buffer.rs
- src/render/src/pso/mod.rs
- src/render/src/pso/resource.rs
- src/render/src/pso/target.rs
- src/render/src/shade.rs
* Remove crate derivative.
* Fix some warnings: `&Error` -> `&dyn Error`.
After reading about master branch speeding up compile times by removing _derivative_ I wondered if it would help the pre-ll code too. Tbf I can see derivative is quite helpful for the `PhantomData` types where regular `#[derive(...)]` falls down. But it isn't _that_ hard to write out the impls.
It impacts clean builds more than I would expect _(linux, rust 1.38, ryzen 2700x)_.
```sh
$ hyperfine --max-runs 3 'cargo clean; cargo build --example cube' 
Benchmark #1: cargo clean; cargo build --example cube
Time (mean ± σ):     34.765 s ±  0.126 s    [User: 248.966 s, System: 12.062 s]
Range (min … max):   34.666 s … 34.906 s    3 runs
```
```sh
$ hyperfine --max-runs 3 'cargo clean; cargo build --example cube'
Benchmark …
```
> [pre-ll] Remove derivative

- src/core/Cargo.toml
- src/core/src/factory.rs
- src/core/src/handle.rs
- src/core/src/lib.rs
- src/render/Cargo.toml
- src/render/src/factory.rs
- src/render/src/lib.rs
- src/render/src/pso/buffer.rs
- src/render/src/pso/mod.rs
- src/render/src/pso/resource.rs
- src/render/src/pso/target.rs
- src/render/src/shade.rs
Cherry-pick #3029 into `v0.18` as a non-breaking improvement to compile speed.
Bumped versions:
* gfx_core -> `0.9.2`
* gfx -> `0.18.2`
> [v0.18] Remove derivative usage & release

- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/resource.rs
Part of #1949
Implement dynamic uniform buffers via root descriptors (2 slots in the root signature per descriptor).
This approach is suitable for uniform buffers as these are translated to typed constant buffers on the shader side.
Storage buffers need to be implemented another way as we would oversubscribe the root signature and we need to deal with read-only descriptors in a way, which is not feasible with the root descriptor approach.
Tested with an modified quad example, executing two draw calls with a different offset.
TODO: d3d12-rs changes pending
> dx12: Implement dynamic uniform buffers

- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/lib.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/lib.rs
- src/backend/metal/src/lib.rs
- src/backend/vulkan/src/lib.rs
- src/hal/src/lib.rs
Fixes #2963 
Much simpler than #3034, but still had to add the cfgs to the gl backend.
PR checklist:
- macOS: metal ✅ , vulkan (moltenvk) ✅ , gl 🔴 (panics)
- windows: vulkan ✅ , dx12 ✅ , dx11 ✅ , gl ✅
> Add type Instance to trait Backend

- src/backend/empty/src/lib.rs
> Added panic messages to using empty backend

- examples/Cargo.toml
- examples/quad/main.rs
- src/backend/gl/Cargo.toml
- src/backend/gl/src/command.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/info.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/native.rs
- src/backend/gl/src/queue.rs
- src/backend/gl/src/state.rs
- src/backend/gl/src/window/glutin.rs
- src/backend/gl/src/window/web.rs
- src/backend/gl/src/window/wgl.rs
Fixes #3023
Fixes #3036 
PR checklist:
Summary:
- Remove the coherent requirement and instead flush mapped memory ranges for the quad example.
- Currently [we purposely do not provide `COHERENT` when buffer storage isn't available](https://github.com/gfx-rs/gfx/blob/da078cd6e4cc49f542310ce7a0ff12ba0a07b13a/src/backend/gl/src/lib.rs#L452) on native OpenGL (I guess we can decide later whether that's necessary or if this can be emulated). Regardless I think we need the flush for WebGL to work here.
- Another option for the quad example is to fallback when coherent memory isn't available. I didn't do that for now because I thought it would complicate the quad example more.
- Avoid checking `MAX_TEXTURE_BUFFER_SIZE` and `SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT` on WebGL because they're not …
> gl: Fix quad example on native and web

- examples/quad/main.rs
PR checklist:
Fix validation errors in quad example
This commit fixes the Vulkan validation errors for the `quad` example:
- The framebuffer is destroyed without waiting for the command buffer to be executed.
- The swapchain is not destroyed.
This commit also adds a small comment explaining why `main` extends the lifetime of `window` beyond its initial scope.
> Fix validation errors in quad example

- examples/Cargo.toml
- src/backend/dx11/Cargo.toml
- src/backend/dx12/Cargo.toml
- src/backend/empty/Cargo.toml
- src/backend/gl/Cargo.toml
- src/backend/metal/Cargo.toml
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/window.rs
Reopening #3037 against `master`, for merge whenever ready.
Note that compiling examples currently doesn't work because `winit` still imports the old version of `raw-window-handle`; the two versions of the traits are incompatible.
PR checklist:
> Upgrade to raw-window-handle v0.3

- examples/colour-uniform/main.rs
- examples/quad/main.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/lib.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/window/glutin.rs
- src/backend/gl/src/window/web.rs
- src/backend/gl/src/window/wgl.rs
- src/backend/metal/src/lib.rs
- src/backend/vulkan/src/lib.rs
- src/backend/vulkan/src/window.rs
- src/hal/src/lib.rs
- src/warden/src/bin/bench.rs
- src/warden/src/bin/reftest.rs
Fixes #2950 
PR checklist:
- metal on macOS ✅ 
- vulkan on macOS ✅ 
- gl on macOS (quad ✅ , colour-uniform 🔴 - but master doesn't work either) 
This adds `hal::Instance::destroy_surface(&self, surface: B::Surface)` trait method, and its implementation in the vulkan backend. All other backend implementations are currently no-ops.
Apart from that, there are 2 notable changes:
- The `Drop` impl for `window::RawSurface` in the vulkan backend was removed to prevent double destroy for users of the new `destroy_surface`.
- Trait `hal::Instance` is now generic over `B: Backend` similarly to how other hal traits are, instead of having the `B: Backend` associated type. It might have been just my general rust inexperience, but I was unable to have `destroy_surface` compile without adding a fully …
> Add Instance::destroy_surface and implement it for the backends

- CHANGELOG.md
- examples/colour-uniform/main.rs
- examples/quad/main.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/window.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/window/dummy.rs
- src/backend/gl/src/window/glutin.rs
- src/backend/gl/src/window/web.rs
- src/backend/gl/src/window/wgl.rs
- src/backend/metal/src/window.rs
- src/backend/vulkan/src/conv.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/window.rs
- src/hal/src/window.rs
Fixes #3019
PR checklist:
I tried to make present mode consistent with composite alpha modes, both in names and types.
> Refactor surface capabilities

- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/conv.rs
- src/backend/dx11/src/debug.rs
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/dxgi.rs
- src/backend/dx11/src/internal.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx11/src/shader.rs
- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/conv.rs
- src/backend/dx12/src/descriptors_cpu.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/internal.rs
- src/backend/dx12/src/lib.rs
- src/backend/dx12/src/pool.rs
- src/backend/dx12/src/resource.rs
- src/backend/dx12/src/root_constants.rs
- src/backend/dx12/src/window.rs
Fixes #3052 
I also ran `rustfmt` over the files(by accident cause my setup runs it on file save) but figured this would be alright to do for this change anyways, if that's not the case I wouldn't mind reverting that.
PR checklist:
> Update DirectX backends to Rust2018

- src/hal/src/window.rs
> docs: Fix outdated doc links on window

- src/auxil/auxil/Cargo.toml
- src/auxil/auxil/src/lib.rs
- src/backend/dx11/Cargo.toml
- src/backend/dx12/Cargo.toml
- src/backend/gl/Cargo.toml
- src/backend/metal/Cargo.toml
Fixes #3063
This is a breaking revision for gfx-auxil, but we can release patched backends for 0.4 if/when we want.
PR checklist:
> Make spirv_cross an optional dependency of gfx-auxil

- src/backend/gl/src/lib.rs
Use `slice::iter` instead of `into_iter` to avoid future breakage
`an_array.into_iter()` currently just works because of the autoref
feature, which then calls `<[T] as IntoIterator>::into_iter`. But
in the future, arrays will implement `IntoIterator`, too. In order
to avoid problems in the future, the call is replaced by `iter()`
which is shorter and more explicit.
A crater run showed that your crate is affected by a potential future 
change. See https://github.com/rust-lang/rust/pull/65819 for more information.
> Use `slice::iter` instead of `into_iter` to avoid future breakage

- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/conv.rs
- src/backend/dx12/src/descriptors_cpu.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/internal.rs
- src/backend/dx12/src/lib.rs
- src/backend/dx12/src/pool.rs
- src/backend/dx12/src/resource.rs
Fixes #3067 (not exactly matching the wording but addresses the real blocker)
Depends on https://github.com/gfx-rs/d3d12-rs/pull/20 merged and published, doesn't need to be updated when that happens
PR checklist:
Verified on a Windows 7 machine that we are gracefully failing to init DX12 now.
> [dx12] update d3d12 to 0.3 and use explicit linking

- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/conv.rs
- src/backend/dx12/src/descriptors_cpu.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/internal.rs
- src/backend/dx12/src/lib.rs
- src/backend/dx12/src/pool.rs
- src/backend/dx12/src/resource.rs
Sibling of #3068
Also depends on https://github.com/gfx-rs/d3d12-rs/pull/20
> [0.4/dx12] update d3d12 to 0.3 and use explicit linking

- src/hal/src/buffer.rs
- src/hal/src/device.rs
- src/hal/src/image.rs
- src/hal/src/pso/descriptor.rs
- src/hal/src/pso/mod.rs
- src/hal/src/query.rs
- src/hal/src/window.rs
Fixes https://github.com/gfx-rs/gfx/issues/3073
Fixes #issue
PR checklist:
> Implement Error trait for error types

- CHANGELOG.md
- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/dxgi.rs
- src/backend/dx11/src/lib.rs
Sibling of #3076 but for `master`.
PR checklist:
> [dx11] explicit library loading

- CHANGELOG.md
- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/dxgi.rs
- src/backend/dx11/src/lib.rs
Supposedly fixes 32bit windows mingw CI: https://treeherder.mozilla.org/logviewer.html#/jobs?job_id=274334639&repo=try&lineNumber=88036
Similar to #3068 but for dx11
PR checklist:
> [0.4/dx11] explicit library loading

- CHANGELOG.md
- src/hal/Cargo.toml
- src/hal/src/buffer.rs
- src/hal/src/device.rs
- src/hal/src/image.rs
- src/hal/src/pso/descriptor.rs
- src/hal/src/pso/mod.rs
- src/hal/src/query.rs
- src/hal/src/window.rs
Has #3078 for 0.4, also has a fix for #3079 (still need to follow-up on `master`).
PR checklist:
Reviewers - how do you feel about the flag change? Can we actually publish it as a patch?
> [0.4/hal] Error derives and ShaderStageFlags

- CHANGELOG.md
- src/hal/Cargo.toml
- src/hal/src/buffer.rs
- src/hal/src/device.rs
- src/hal/src/image.rs
- src/hal/src/pso/mod.rs
Follow-up to #3078 with pieces from #3080
Fixes #3079
PR checklist:
> ShaderStageFlags fix

- src/hal/src/device.rs
- src/hal/src/pso/mod.rs
> Implement Error for pso::CreationError

- src/backend/dx11/src/dxgi.rs
- src/backend/dx11/src/lib.rs
Fixes #3092
PR checklist:
- [Yes (on Windows)] `make` succeeds (on *nix)
- [No (Win 7 does not support dx12, and those tests fail; I don't have access to other OS)] `make reftests` succeeds
- [Yes] tested examples with the following backends: dx11
- [Yes] `rustfmt` run on changed code
This PR keeps dxgi.dll around for the lifetime of `Instance`, in order to ensure that dxgi factories keep working.
This (I assumed) happened  to work before `d3d11.dll` was switched to libloading model, since linking in d3d11 statically pulled in dxdi transitively, so the lifetime issue never manifested.
Incidentally, this PR also marks the two libloaded `extern` functions as unsafe, as rust segfaulting in nominally `safe` code felt plain wrong to me.
Big thanks to @kvark for rubberducking me through this in …
> Ensure dxgi.dll is not unloaded while it's still needed (dx11)

- CHANGELOG.md
- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/dxgi.rs
- src/backend/dx11/src/lib.rs
Fixes #3092
PR checklist:
- [Yes] `make` succeeds (on ~~*nix~~ Win)
- [No; don't have access to dx12 ] `make reftests` succeeds
- [Yes] tested examples with the following backends: dx11
- [Yes] `rustfmt` run on changed code
This is a backport of #3096. 
Technically, this is a cherry-pick of c43d2b4b1cad00ca1f2ccecf7766e365b06aa9e5 + rustfmt + patch version bump
> Backport of #3096 to hal-0.4 branch; bump gfx-backend-dx11 to 0.4.3

- examples/colour-uniform/main.rs
- examples/compute/main.rs
- examples/quad/main.rs
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/resource.rs
- src/backend/gl/src/device.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/native.rs
- src/backend/vulkan/src/conv.rs
- src/hal/src/pso/descriptor.rs
- work/scenes/compute.ron
Fixes #3055 
PR checklist:
This PR refactors `DescriptorType`:
```rust
pub enum DescriptorType {
/// A descriptor associated with sampler.
Sampler,
/// A single descriptor associated with both a sampler and an image to be
/// used together.
CombinedImageSampler,
/// A descriptor associated with an image.
Image {
/// The specific type of this image descriptor.
ty: ImageDescriptorType,
},
/// A descriptor associated with a buffer.
Buffer {
/// The access type of this buffer descriptor.
access: BufferDescriptorAccess,
/// The format of this buffer descriptor.
format: BufferDescriptorFormat,
},
/// A descriptor associated with an input attachment.
InputAttachment,
}
```
The number of top-level variants is reduced from 11 to 5 by turning `Image` and `Buffer` into struct variants, which allows …
> Refactor DescriptorType

- src/backend/metal/src/command.rs
> [mtl] restore the viewport after clear_attachments

- src/backend/metal/src/device.rs
Found this while looking into gfx-rs/wgpu#103. Looks like this was a copy-paste mistake, this partially fixes the wgpu shadow example on mac.
PR checklist:
> [mtl] Properly set store operation for depth attachment

- examples/Cargo.toml
- examples/colour-uniform/main.rs
- examples/quad/main.rs
- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/lib.rs
The coherency isn't working properly yet. It needs to be improved before we can turn it on again (see #3119).
There was also an error in buffer ranges, possibly related to #3114 
PR checklist:
> [0.4/dx11] disable coherent memory, remove MemoryHeapFlags

- CHANGELOG.md
- examples/Cargo.toml
- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx11/src/shader.rs
- src/backend/gl/Cargo.toml
Does most of the work for #3121 . Unfortunately, it *still* doesn't fix it, because SPIRV-Cross on HLSL lacks resource mapping overrides. So we are blocked on https://github.com/KhronosGroup/SPIRV-Cross/issues/1252 , but we can follow-up with a fix here once it's available, the fix is going to be small.
Status:
Tested on wgpu-rs examples :tada: .
Compromises:
- descriptor binding code responsible for coherent memory is removed, since it's tricky and we disabled coherent memory in #3120
- copying descriptor sets is not implemented for now
> [0.4/dx11] New binding model

- CHANGELOG.md
- Makefile
- examples/Cargo.toml
- examples/colour-uniform/main.rs
- examples/quad/main.rs
- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx11/src/shader.rs
- src/backend/gl/Cargo.toml
- src/backend/gl/src/device.rs
- src/warden/Cargo.toml
- src/warden/src/bin/bench.rs
- src/warden/src/bin/reftest.rs
- src/warden/src/lib.rs
Sibling of #3122 on master
This change *really* shines on master, because the `DescriptorType` enum is now more complex, and all the matching is concentrated in one single place instead of being spread thin over the code.
> [dx11] new binding model

- src/backend/dx12/src/lib.rs
Fixes the crash in `enumerate_adapters`. Thanks @jrmuizel for discovering it!
Note: a similar fix for DX11 went in #3096
> [dx12] hold DXGI library alive

- src/backend/vulkan/src/lib.rs
Android support was added to `raw-window-handle` a while ago, so with this, gfx works on Android again!
PR checklist:
> Fix Android surface creation

- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/lib.rs
#3132 backported to 0.4
Would it be possible to get this released?
PR checklist:
> [0.4] Fix Android surface creation

- src/backend/dx11/src/conv.rs
- src/backend/dx12/src/conv.rs
- src/backend/gl/src/queue.rs
- src/backend/metal/src/conversions.rs
- src/backend/metal/src/device.rs
- src/backend/vulkan/src/device.rs
- src/hal/src/pso/graphics.rs
- work/scenes/basic.ron
- work/scenes/large.ron
- work/scenes/vertex-offset.ron
Line width state is not tied only to line polygon mode and storing it
there has correctness implications on Vulkan back-end. This is
problematic for gfx-portability when targeting Vulkan back-end, since it
can cause correct Vulkan application to trigger validation errors.
Prepares for fixing https://github.com/gfx-rs/portability/issues/206
PR checklist:
> Move line width out of line polygon mode

- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/backend/vulkan/src/window.rs
Fixes #3141 (works around)
PR checklist:
> [vk] expect -1 returned by acquire_next_image

- src/backend/vulkan/src/lib.rs
Currently, the following warning is emitted during building:
```
warning: this method call currently resolves to `<&[T; N] as IntoIterator>::into_iter` (due to autoref coercions), but that might change in the future when `IntoIterator` impls for arrays are added.
--> src/backend/vulkan/src/lib.rs:296:51
|
296 |         for (info_label, info) in additional_info.into_iter() {
|                                                   ^^^^^^^^^ help: use `.iter()` instead of `.into_iter()` to avoid ambiguity: `iter`
|
= note: `#[warn(array_into_iter)]` on by default
= warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
= note: for more information, see issue #66145 <https://github.com/rust-lang/rust/issues/66145>
```
This …
> [vk] supress into_iter autoref coercion warning

- examples/Cargo.toml
- src/backend/gl/Cargo.toml
Fixes `STATUS_ENTRYPOINT_NOT_FOUND` error on Windows (all backends).
`glutin` needed to be updated for `winit` to work correctly.
PR checklist:
> Update winit (0.21.0) and glutin (0.23.0)

- src/backend/metal/src/device.rs
- src/backend/metal/src/lib.rs
Fixes #3098 fixes gfx-rs/wgpu-rs/issues/138
PR checklist:
it complains about `Testing Metal` "metal-0.17.1/src/capturemanager.rs:50:25": `Scene 'transfer': thread 'main' panicked at 'Class with name MTLCaptureManager could not be found'` because [that object doesn't exist on my macOS 10.11 machine](https://developer.apple.com/documentation/metal/mtlcapturemanager)
Metal
> check if addDebugMarker from Metal is supported

- src/hal/src/pso/specialization.rs
Fixes #issue
PR checklist:
Fix syntax error in the recursive cases of the spec_const_list macro that cause compilation to fail when there is more than one argument passed in.
> fix incorrect syntax in spec_const_list macro

- src/auxil/auxil/Cargo.toml
- src/backend/dx11/Cargo.toml
- src/backend/dx12/Cargo.toml
- src/backend/gl/Cargo.toml
- src/backend/metal/Cargo.toml
> Update spirv_cross to 0.18

- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/command.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/command.rs
- src/backend/metal/src/command.rs
- src/backend/vulkan/src/command.rs
- src/backend/vulkan/src/lib.rs
- src/hal/src/command/mod.rs
- src/warden/src/gpu.rs
Addresses the "Section/call marking" API portion of #1508 (only Vulkan implementation so far)
PR checklist:
> Basic debug markers API

- src/backend/dx11/src/device.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx11/src/shader.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/lib.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/info.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/queue.rs
- src/backend/gl/src/state.rs
- src/backend/metal/src/device.rs
- src/backend/vulkan/src/command.rs
- src/backend/vulkan/src/conv.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/hal/src/lib.rs
Paves the way to https://github.com/gfx-rs/wgpu/issues/519
PR checklist:
If I undetstand correctly, the only thing missing here is a proper check for supported device extensions in Vulkan backend.
> Support for NDC_Y_UP feature

- README.md
- src/backend/dx11/src/conv.rs
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/internal.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/conv.rs
- src/backend/dx12/src/device.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/command.rs
- src/backend/gl/src/device.rs
- src/backend/metal/src/command.rs
- src/backend/metal/src/device.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/native.rs
- src/backend/vulkan/src/pool.rs
- src/hal/Cargo.toml
- src/hal/src/buffer.rs
- src/hal/src/command/mod.rs
- src/hal/src/device.rs
- src/hal/src/format.rs
- src/hal/src/image.rs
- src/hal/src/lib.rs
- src/hal/src/memory.rs
- src/hal/src/pass.rs
- src/hal/src/pool.rs
- src/hal/src/pso/descriptor.rs
- src/hal/src/window.rs
- src/warden/src/gpu.rs
- src/warden/src/raw.rs
Generally simplifies the API by using more standard types and cleaner field names. This is preferred since we are no longer trying to be too much user-friendly. Simplicity is more important.
(last commit)
Fixes #2561
PR checklist:
> Hal cleanup for 0.5 release

- src/backend/dx11/src/conv.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/conv.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/lib.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/info.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/state.rs
- src/backend/metal/src/device.rs
- src/backend/vulkan/src/command.rs
- src/backend/vulkan/src/conv.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/backend/vulkan/src/native.rs
- src/backend/vulkan/src/pool.rs
- src/hal/src/buffer.rs
- src/hal/src/lib.rs
- src/hal/src/pool.rs
- src/hal/src/pso/descriptor.rs
- src/warden/src/bin/bench.rs
- src/warden/src/bin/reftest.rs
- src/warden/src/gpu.rs
- src/warden/src/lib.rs
Fixes the use of Extend. The last version was wrong because we can't pass Extend by reference if a value was expected.
Also has a commit for formatting pass: having the code formatted will help aligning the hal-0.5 with master in the future.
PR checklist:
> Pass Extend by mutable reference

- src/auxil/auxil/src/lib.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/resource.rs
Fixes the read-only bindings now in dx12. What we used to get is the shader disagreeing with the pipeline layout as to which bindings are UAV and which are SRV. Now we are setting the `NonWritable` decorations where appropriate.
PR checklist:
> [dx12] patch the pipeline layout with read-only decorations

- src/backend/gl/src/conv.rs
Hi gfx team!
In my project I'm using `gfx_hal::format::Rg16Unorm`, passing it to `device.create_image(...)` as a format at some point, however as I discovered there is not yet any conversion for that format defined in the gl backend in `conv.rs` (which later leads to a crash at runtime):
https://github.com/gfx-rs/gfx/blob/fdfe887f5afab7ca057e3e824817d0bcdcf794ba/src/backend/gl/src/conv.rs#L95-L101
I made a naive attempt to add a mapping myself, based on deductions from the other entries in the mapping table and eventually experimenting with different combinations, the last one I arrived at being the one in this draft PR:
```rust
Rg16Unorm => FormatDescription::new(glow::RG16, glow::RG_INTEGER, glow::UNSIGNED_SHORT, 2, Float),
```
However every variant I tried leads to an `Unsupported …
> [gl] add missing R/Rg/Rgba16Unorm format conversions

- src/backend/vulkan/src/command.rs
Fixes #3183
That was a silly mistake, but now we might need to publish a patch version with this fix...
PR checklist:
> [vk] fix debug color for markers

- src/backend/metal/src/command.rs
Another silly thing that wasn't covered by release testing.
PR checklist:
> [mtl] fix index buffer range check

- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/resource.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/native.rs
- src/backend/metal/src/native.rs
- src/backend/vulkan/src/native.rs
- src/hal/src/pso/descriptor.rs
> Rename DescriptorPool::free_sets to free

- src/backend/metal/src/device.rs
I missed the fact we have 2 spots where the options could be generated.
PR checklist:
> [mtl] fix NDC_Y_FLIP feature

- src/backend/vulkan/src/lib.rs
> [vk] fix mirror clamp extension name

- src/auxil/range-alloc/src/lib.rs
- src/hal/src/lib.rs
- src/hal/src/pass.rs
- src/hal/src/pso/specialization.rs
> Stricten the warnings on hal and range-alloc

- src/backend/vulkan/src/native.rs
- src/hal/src/pso/descriptor.rs
> Refactor AllocationError to use OutOfMemory

- src/hal/src/device.rs
> Add Access type to MapError

- CHANGELOG.md
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/command.rs
- src/backend/vulkan/src/conv.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/backend/vulkan/src/native.rs
- src/backend/vulkan/src/pool.rs
- src/backend/vulkan/src/window.rs
Addresses https://github.com/gfx-rs/wgpu-rs/issues/227
We are now taking MAINTENANCE1 whenever it's supported. This code path is supposed to be unaffected. However, if it's not supported, and NDC_Y_FLIP is requested, and we end up using AMD_NEGATIVE_VIEWPORT_HEIGHT, then we don't shift the Y of the viewport.
PR checklist:
> [0.5/vk] fix handling of AMD viewport negation

- src/backend/metal/src/device.rs
- src/backend/metal/src/lib.rs
Has 3 Metal fixes for portability:
- feature set is adjusted
- one can pass CA Layer as NSView (d'oh)
- limit for sampled images is fixed
> [mtl] update feature set, hack CAL support into NSView

- src/backend/metal/src/command.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/internal.rs
Gets us the Atmosphere demo working from Diligent Engine on macOS:
> Metal multiple attachment clears

- CHANGELOG.md
- src/backend/dx11/Cargo.toml
- src/backend/metal/Cargo.toml
Also required for a smooth update in gecko...
When dependencies change, Gecko engineering wants it to happen across all crates, preferably without functional changes
> [0.4] parking lot update for Metal and DX11

- src/backend/gl/src/command.rs
- src/backend/gl/src/pool.rs
- src/backend/gl/src/queue.rs
- src/backend/gl/src/state.rs
Fixes #3202 
It seems that the same issue could apply to the stencil and color buffers too (they have their own `stencil_mask` and `color_mask` functions which are not reset), but it would take some time for me to test that.
PR checklist:
> Fix clearing of GL depth buffer

- Makefile
- examples/Cargo.toml
- examples/colour-uniform/main.rs
- examples/quad/main.rs
- src/backend/gl/Cargo.toml
- src/backend/gl/build.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/info.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/native.rs
- src/backend/gl/src/queue.rs
- src/backend/gl/src/window/glutin.rs
- src/backend/gl/src/window/mod.rs
- src/backend/gl/src/window/surfman.rs
- src/backend/gl/src/window/web.rs
- src/warden/Cargo.toml
- src/warden/src/bin/bench.rs
- src/warden/src/bin/reftest.rs
- src/warden/src/lib.rs
Fixes/Discussion: https://github.com/gfx-rs/wgpu/issues/450
PR checklist:
- GL ( excluding compute because it isn't supported )
> OpenGL surface via surfman

- src/backend/gl/src/lib.rs
Fixes #issue
PR checklist:
Review the latest commit alone if you don't want to see all the rustfmt clutter. :wink:
This adds an extra export to the `glutin` backend for GL which was accidentally removed with the surfman update. This will keep code that is still using the `glutin` backend working.
> Add Missing glutin export

- src/backend/gl/src/conv.rs
Fixes #3222
PR checklist:
cc: @chemicstry (PR-ing some loose ends)
> Add Rgb8Srgb format for GL

- src/backend/gl/src/lib.rs
> WASM: set canvas width/height only if unset.

- src/hal/src/window.rs
Fixes rustdoc "Rust code block is empty" warnings.
> Remove empty example doc comments.

- src/backend/vulkan/src/lib.rs
Fixes:
error[E0599]: no variant or associated item named `Wayland` found for enum `raw_window_handle::RawWindowHandle` in the current scope
--> src/backend/vulkan/src/lib.rs:547:30
PR checklist:
- [y] `make` succeeds (on *nix)
- [n] `make reftests` succeeds
- [n] tested examples with the following backends:
- [n] `rustfmt` run on changed code
rustfmt doesn't build on Solaris
> Fix Solaris build.

- src/backend/vulkan/src/lib.rs
Fixes #3218
Also see: https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/LAYER_CONFIGURATION.md#validation-layer-overview
PR checklist:
> Switch to `VK_LAYER_KHRONOS_validation`

- CHANGELOG.md
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/lib.rs
> Backport to hal-0.5: Switch to `VK_LAYER_KHRONOS_validation`

- src/hal/src/command/mod.rs
Fixes a `TODO` I've found in the code. `const fn CommandBufferFlags::empty()` can be used instead.
PR checklist:
> Remove `CommandBufferFlags::EMPTY`

- src/hal/src/adapter.rs
- src/hal/src/buffer.rs
- src/hal/src/command/clear.rs
- src/hal/src/command/mod.rs
- src/hal/src/device.rs
- src/hal/src/lib.rs
- src/hal/src/memory.rs
- src/hal/src/pass.rs
- src/hal/src/pool.rs
- src/hal/src/pso/descriptor.rs
- src/hal/src/pso/mod.rs
- src/hal/src/pso/specialization.rs
- src/hal/src/query.rs
- src/hal/src/queue/family.rs
- src/hal/src/queue/mod.rs
- src/hal/src/window.rs
This PR improves the docs for various components of the public API. I also improved the crate-level documentation to give an overview of the device initialization flow.
The objective for me was to document everything on the "critical path". This means every item someone with no prior `gfx-hal` or Vulkan experience would require in order to do something simple, such as [rendering a triangle on screen](https://www.falseidolfactory.com/2020/04/01/intro-to-gfx-hal-part-1-drawing-a-triangle.html).
> Improve documentation

- .monocodus
- CHANGELOG.md
- src/backend/vulkan/src/lib.rs
Includes #3233
It's spammy right now. We should re-enable rustfmt spam after we format the code base and clear up the config.
> Monocodus config

- src/backend/dx12/src/command.rs
- src/backend/dx12/src/device.rs
Fixes #3243
Root descriptors were always given offset 0, regardless of any other descriptors that were present. This caused whatever user data that was at offset 0 and 1 to get overwritten (in my case, it was a SRV descriptor with an image, then a sampler descriptor, resulting in no image being rendered). 
`bind_descriptor_sets` expects a certain ordering for the descriptors within each set: 
SRV/CBV/UAV descriptors, in one table
Sampler descriptors, in one table
Root descriptors
`create_pipeline_layout` didn't follow this contract (looks like it was meant to, though), resulting in the offset mixup. I just re-arranged it a bit to ensure that tables are added first, so that the `root_offset` was correct by the end of the method and the `RootDescriptor` could be created with it.
I also …
> d3d12: Fix offset calculation for root descriptors that was causing root signature data to be overwritten

- CHANGELOG.md
- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/device.rs
From PR 3244 (https://github.com/gfx-rs/gfx/pull/3244)
>  d3d12: Fix offset calculation for root descriptors that was causing root signature data to be overwritten 

- src/backend/metal/src/command.rs
> [mtl] fix panic with fill_buffer when using offset and size

- CHANGELOG.md
- src/auxil/auxil/Cargo.toml
- src/backend/dx11/Cargo.toml
- src/backend/dx12/Cargo.toml
- src/backend/gl/Cargo.toml
- src/backend/metal/Cargo.toml
Backport #3249 to 0.5
PR checklist:
> [0.5] Update spirv-cross to version 0.20

- examples/colour-uniform/main.rs
- examples/quad/main.rs
- src/backend/dx11/src/conv.rs
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/conv.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/window.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/command.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/queue.rs
- src/backend/gl/src/window/web.rs
- src/backend/gl/src/window/wgl.rs
- src/backend/metal/src/command.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/lib.rs
- src/backend/metal/src/window.rs
- src/backend/vulkan/src/command.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/backend/vulkan/src/native.rs
- src/backend/vulkan/src/window.rs
- src/hal/src/command/mod.rs
- src/hal/src/lib.rs
- src/hal/src/pso/graphics.rs
- src/hal/src/pso/mod.rs
- src/warden/src/gpu.rs
This is my attempt at adding support for mesh shaders. 
This (first) PR only stubs the API. From my investigation, the extension is relatively simple(it effectively only adds new shaders and 3 draw commands mirroring the original ones) and seems to be the same across Direct3D and Vulkan. 
Even though the Vulkan only has NV extension so far, based on announcements of RDNA2 and DirectX Ultimate we can expect KHR version and I don't see how it could diverge in any way. Thus, both Vulkan and DX12 implementations should be trivial.
I know nothing about Metal and I am not aware of information about support for mesh shaders. At worst, they could be emulated using compute shaders but It would probably be so slow that It would be practically worthless.
Tasks:
PR checklist:
Resources:
[Vulkan …
> WIP: Initial stub for mesh shaders

- Cargo.toml
- src/backend/webgpu/Cargo.toml
- src/backend/webgpu/README.md
- src/backend/webgpu/src/command.rs
- src/backend/webgpu/src/device.rs
- src/backend/webgpu/src/lib.rs
- src/backend/webgpu/src/window.rs
This PR adds a WebGPU backend for `gfx-hal`, making some progress towards #3027.
I've currently gotten the backend to compile. Further additions will come in future PRs.
> Add WebGPU backend

- .travis.yml
- Makefile
Temporarily fixes broken CI by not building the tests, which would cause a `glsl-to-spirv` failure.
> Fix CI on iOS

- .travis.yml
- Makefile
- src/backend/webgpu/src/lib.rs
Add basic instance creation to the WebGPU backend. Also allows enumerating physical devices.
I've currently excluded the `WebGPU` backend from the `test` target, and added it manually to `check`.
PR checklist:
> [webgpu] Instance creation and device enumeration

- src/backend/dx12/src/lib.rs
This slightly modifies the DX12 backend to allow for better detection of integrated gpus. 
Upstream wgpu issue with more info: https://github.com/gfx-rs/wgpu/issues/683
I decided against using `DedicatedVideoMemory` as an indicator, as my intel chip reports 130MB or so of memory that is "dedicated", despite being `CacheCoherentUMA`. I suspect this is memory that the system allocator can't get to, so is always reserved for graphics, but this is but a hunch.
I tested this on my system with 4 DX12 gpus (1080ti, 960, Intel, Virtual), and they all report back the proper values: Dedicated, Dedicated, Integrated, and Virtual respectively.
> Update DX12 backend to interpret CacheCoherentUMA devices as IntegratedGpu

- src/backend/dx12/src/device.rs
Fixes UB in dx12's compile_shader: the formatted string was dropped before the pointer was used.
> [dx12] fix shader stage string UB

- CHANGELOG.md
- src/auxil/range-alloc/Cargo.toml
- src/auxil/range-alloc/src/lib.rs
- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/lib.rs
- src/backend/dx12/src/resource.rs
This PR adds logic to free the ranges of our global heaps of views and samplers upon destruction of descriptor pools. Without this, a `wgpu` application going through `gfx-descriptor` and constantly creating and freeing a single descriptor set would quickly run out of global samplers, since `gfx-descriptor` would correspondingly create and destroy the pool.
> [0.5/dx12] implement descriptor pool destruction, bump version

- CHANGELOG.md
- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/lib.rs
- src/backend/metal/Cargo.toml
- src/backend/metal/src/device.rs
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/conv.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/backend/vulkan/src/window.rs
- src/hal/Cargo.toml
- src/hal/src/lib.rs
This implements the gfx-hal component of supporting descriptor indexing.
Main actions:
- Add features to hal
- Enable appropriate features on metal
- Enable features on DX12 with additional compiler flag if needed
- Wire up enabling extensions to Vulkan.
Remaining Questions:
- This PR isn't finished, but my main concern is how to get the struct of function pointers from `Instance::create`, through `PhysicalDevice` so it can get to `PhysicalDevice::features` where it needs to be. I sorta just stuck it in the structs, but if you have a better idea, please do suggest.
- Any other vulkan advice/tips appreciated. 
- I need to properly detect when optional instance extensions aren't supported.
- Remove the horrible duplication of the extension name... somehow.
> [0.5] Implement Descriptor Indexing

- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/lib.rs
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/command.rs
- src/backend/vulkan/src/lib.rs
- src/hal/Cargo.toml
- src/hal/src/command/mod.rs
- src/hal/src/lib.rs
gfx-hal work for https://github.com/gfx-rs/wgpu/issues/742. I would not merge this until I've finished the wgpu work and prove that it works on both dx12 and vulkan, but it can be reviewed now :)
This adds two methods to a gfx-hal trait, so I added them with a default `unimplemented!()` implementation so it is a non-breaking change. When this is ported forward to master, the functions will just exist as is.
This adds support for this feature on DX12 and Vulkan (through `VK_KHR_draw_indirect_count`). Metal is possible as discussed in the wgpu issue, but I don't have access to a development mac, so I couldn't do the work on it, at least right now. GL 4.6 also seems to support this though `glMultiDrawIndexedIndirectCount`, but that's a problem to solve once the GL backend is sorted.
> [0.5] Add draw_indirect_count feature

- examples/quad/main.rs
- src/backend/empty/Cargo.toml
- src/backend/empty/src/lib.rs
Starts work on #3278 
I've stubbed enough functions to be able to get the `quad` example to compile, run, and do nothing in a loop.
Supersedes PR #2764 (which seems to not be progressing)
PR checklist:
> Start mocking the empty backend

- src/backend/dx12/src/command.rs
So this fixes the problem https://github.com/gfx-rs/wgpu/pull/754 was working around, but found a much more interesting problem:
- DX12 _must_ have a stride of 16/20, the value of the stride is ignored other than the assert. This isn't a problem from the wgpu perspective (we assume tightly packed), but would have issues for gfx-portability.
> Allow DX12 Backend to work with strides of 0

- src/backend/empty/src/buffer.rs
- src/backend/empty/src/image.rs
- src/backend/empty/src/lib.rs
- src/backend/empty/src/memory.rs
Mock even more functions in the empty backend.
Should be enough to start fuzzing `gfx-memory`.
- The first commit only replaces the `panic`s with `unimplemented`s.
- Second commit adds the `Memory`, `Buffer` and `Image` types.
PR checklist:
> Mock memory-related functions in the empty backend

- CHANGELOG.md
- src/backend/empty/Cargo.toml
- src/backend/empty/src/buffer.rs
- src/backend/empty/src/descriptor.rs
- src/backend/empty/src/lib.rs
More work on #3278, with the intent to follow up with fuzz testing for the `gfx-descriptor` crate.
> [0.5] Mock empty backend descriptor set functions

- CHANGELOG.md
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
Fixes #3296
Sibling of #3297 for master
PR checklist:
> [vk] filter out known memory types

- src/backend/dx11/src/device.rs
- src/backend/dx12/src/device.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/device.rs
- src/backend/metal/src/device.rs
- src/backend/vulkan/src/device.rs
- src/backend/webgpu/src/device.rs
- src/hal/src/device.rs
> added name setters for PipelineLayout, Graphics and Compute pipelines

- src/backend/dx11/src/device.rs
- src/backend/dx12/src/device.rs
- src/backend/gl/src/lib.rs
- src/backend/metal/src/device.rs
- src/backend/vulkan/src/device.rs
- src/hal/src/memory.rs
> changed mask type in Requirements to u32

- examples/colour-uniform/main.rs
- examples/quad/main.rs
- src/backend/dx11/src/device.rs
- src/backend/dx12/src/device.rs
- src/backend/gl/src/device.rs
- src/backend/metal/src/device.rs
- src/hal/src/pso/graphics.rs
- src/warden/src/gpu.rs
> replaced PrimitiveAssembler vecs with slices

- src/backend/metal/Cargo.toml
This fixes build issues on macOS caused by multiple versions of cocoa
dependencies. core-graphics is also updated to be consistent with cocoa v0.22,
which removes a duplication.
The build passes and test_send_sync passes with this PR on my macOS 10.15.5 machine.
> Bump cocoa and core-graphics deps for metal backend

- CHANGELOG.md
- src/backend/metal/Cargo.toml
- src/backend/metal/src/lib.rs
- src/backend/metal/src/window.rs
https://github.com/gfx-rs/gfx/pull/3312 hal 0.5 version
PR checklist:
> [0.5/metal] Remove core-graphics deps

- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/window.rs
This reduces the likelihood of dependency churn.
> Switch to core-graphics-types instead of core-graphics

- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/window.rs
This reduces the likelihood of churn.
Edit: sibling of #3317 for hal-0.5
> [0.5/vk] Switch to core-graphics-types instead of core-graphics

- CHANGELOG.md
- src/backend/dx11/Cargo.toml
This bumps libloading in dx11 to 0.6, this isn't a breaking change as it is all internal.
We now directly depend on both libloading 0.6 (dx11) and 0.5 (d3d12-rs), however we have indirectly depended on both (ash uses 0.6) for a while, so this is no worse. Once d3d12 gets a new release, this issue will go away.
> [0.5/dx11] Bump libloading to 0.6

- src/backend/gl/src/device.rs
- src/hal/src/pso/descriptor.rs
Implements #1725 for the OpenGL backend.
PR checklist:
> Implement descriptor copy for opengl

- CHANGELOG.md
- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/conv.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/window.rs
Fixes #2656
Tested on vange-rs and wgpu-rs examples
With these fixes, we run wgpu-rs stuff without validation errors, and terminate successfully :tada:
> [0.5/dx12] essential fixes to depth views and command allocation

- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/lib.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/command.rs
- src/backend/metal/src/command.rs
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/command.rs
- src/backend/vulkan/src/lib.rs
- src/backend/webgpu/src/command.rs
- src/hal/src/command/mod.rs
- src/hal/src/lib.rs
Forward-ports #3279 to master. The default impl in the hal was removed in favor of stub impls in all the backends. Addtionally the mesh shader function machinery was combined with the machinery #3279 adds to get extension pointers.
> Implement DRAW_INDIRECT_COUNT features

- examples/colour-uniform/main.rs
- examples/quad/main.rs
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/resource.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/native.rs
- src/backend/metal/src/command.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/native.rs
- src/backend/vulkan/src/conv.rs
- src/backend/vulkan/src/window.rs
- src/hal/src/format.rs
- src/hal/src/image.rs
- src/warden/src/gpu.rs
- work/scenes/basic.ron
- work/scenes/transfer.ron
- work/scenes/vertex-offset.ron
> Support unbound subresource ranges

- src/backend/metal/src/command.rs
- src/backend/metal/src/internal.rs
Fixes part of problem for running the Diligent Engine MSAA example on gfx-portability.
PR checklist:
> [mtl] support clear_attachments in MSAA-enabled passes

- CHANGELOG.md
- src/auxil/auxil/Cargo.toml
- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/shader.rs
- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/device.rs
- src/backend/gl/Cargo.toml
- src/backend/gl/src/device.rs
- src/backend/metal/Cargo.toml
- src/backend/metal/src/device.rs
spirv_cross 0.21 exposes `force_zero_initialized_variables` for GLSL/HLSL/MSL and `force_native_arrays` for MSL. I think we can probably enable both of these options unconditionally in gfx and wgpu.
(I'll backport this into 0.6 once we accept these changes)
PR checklist:
> Update spirv_cross to 0.21

- src/backend/dx12/src/command.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/resource.rs
- src/backend/gl/src/queue.rs
- src/backend/gl/src/window/surfman.rs
Fixes a critical problem reported in https://github.com/gfx-rs/wgpu/issues/849#issuecomment-685151553
It appears to be a regression from #3342, where I accidentally started using the root offsets where the root indices are expected. We might need to change their types to not hit this any more times (maybe in d3d12-rs even? cc @msiglreith ).
PR checklist:
> [dx12] fix root signature indexing

- CHANGELOG.md
- examples/Cargo.toml
- src/auxil/auxil/Cargo.toml
- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/shader.rs
- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/device.rs
- src/backend/gl/Cargo.toml
- src/backend/gl/src/device.rs
- src/backend/metal/Cargo.toml
- src/backend/metal/src/device.rs
- src/warden/Cargo.toml
Backport #3356 to update spirv_cross:
- spirv_cross 0.21 enables us to use zero initialization for shader variables and use of native arrays in MSL
- increase crate versions for the dx12/dx11/metal backends and auxil
> [0.6] Backport spirv_cross update

- src/backend/dx11/shaders/copy.hlsl
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/internal.rs
- src/backend/dx11/src/lib.rs
Makes the internal code better scale-able (shifting from fields to maps).
Fixes the race condition on the internal constant buffer (yikes!)
Enables uploading R8,RG8, and RGBA8 texture copies from buffers.
PR checklist:
Note: this is missing a commit that bumps the patch version and adds a changelog entry
> [0.6/dx11] dx11 internal copy refactor

- CHANGELOG.md
- src/backend/dx11/Cargo.toml
- src/backend/dx11/shaders/copy.hlsl
- src/backend/dx11/src/device.rs
Follow-up to #3362
Also fixes the read-only buffer SRVs.
Gets DX11 the the point of running vange-rs :tada:
> [0.6/dx11] fix read-only buffer SRV

- src/backend/dx11/shaders/copy.hlsl
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/internal.rs
- src/backend/dx11/src/lib.rs
Includes #3362 and #3363 but for master
> Dx11 correctness fixes for bindings, and buffer-image copies

- CHANGELOG.md
- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/internal.rs
- src/backend/dx11/src/lib.rs
Fixes running anything in release.
Tested on vange-rs 🎉 
One problem was that every memory was allocated as if it was cpu-visible, even if it wasn't supposed to be. And we used memory that was uninitialized...
Another, we had a few occasions of this evil pattern:
```rust
let some_ptr = if let Some(something) { &something } else {ptr::null()};
```
fun thing happens here because the `something` is dead right after that expression, and the pointer gets used still...
> [0.6/dx11] fix cpu-visible memory

- info/getting_started.md
Without the additional steps, an error like `error: failed to run custom build command for `gfx-backend-metal v0.3.3`` may occur. Tested on a fresh install of macOS 10.15.6
Additional steps copied from comment:
https://github.com/gfx-rs/gfx/issues/2309#issuecomment-506130902
> Made instructions for macOS more clear

- src/backend/dx12/src/device.rs
- src/backend/dx12/src/lib.rs
Fixes a case where we request `TRANSFER_DST` without `COLOR_ATTACHMENT` on an image that has a non-renderable format, when running on Resource Tier-1 hardware.
> [dx12] fix resource tier-1 handling of render targets

- src/backend/metal/Cargo.toml
- src/backend/metal/src/command.rs
- src/backend/metal/src/conversions.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/native.rs
Fixes #3378 , fixes #3377, fixes #3267
We keep the RP-desc to visibility buffer association permanent.
For fences, we are using `Mutex` instead of `RefCell`.
PR checklist:
Tested on Dota2 with gfx-portability.
> Bunch of Metal optimizations

- CHANGELOG.md
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/lib.rs
Fixes https://github.com/gfx-rs/wgpu/issues/946. DI requires maintence3, so we shouldn't need to check if it exists.
> [vk/0.6] Properly enable VK_KHR_maintenance3 when VK_EXT_descriptor_indexing is enabled

- examples/Cargo.toml
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/lib.rs
- src/backend/vulkan/src/window.rs
- src/warden/Cargo.toml
Even when built with x11 and xcb features enabled on Linux,
Vulkan backend does not use anything from x11 or xcb crates.
Fixes #issue
PR checklist:
> Remove unused dependencies

- examples/colour-uniform/main.rs
- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/lib.rs
- src/backend/dx12/src/resource.rs
- src/backend/vulkan/src/lib.rs
- src/backend/vulkan/src/window.rs
Fixes DX12 part of #3395
PR checklist:
> [dx12] command buffer markers, names for renderpasses and descriptorsets

- CHANGELOG.md
- src/backend/dx11/src/lib.rs
- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/conv.rs
Fixes https://github.com/gfx-rs/wgpu/issues/953
This is a part of Vulkan semantics that needs mapping. In D3D12 it's not legal to use the COLOR factors on alpha, but in Vulkan 
it's fine.
> [0.6/dx12] fix alpha blend factors

- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/internal.rs
- src/backend/dx12/src/lib.rs
- src/backend/dx12/src/pool.rs
- src/backend/dx12/src/resource.rs
Fixes #2661
Fixes #2668
Fixes #2140
Fixes the sampler part of #2652
Fixes #1949 (I think? it enables dynamic storage buffers)
PR checklist:
> [dx12] Dota-related fixes and improvements

- src/backend/dx12/src/descriptors_cpu.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/lib.rs
- src/backend/dx12/src/resource.rs
This PR follows #3393. It combines a few closely related things around samplers:
1. It turns out we can't copy GPU-visible descriptors into each other. We used to create samplers in the GPU-visible heap, and track the origin indices. Now we create them in a separate CPU-only pool, and only copy from there into the GPU heap.
2. The previous PR was missing a piece of logic that would update the sampler data on a descriptor inside `copy_descriptor_sets`.
3. From the early days, we had code duplication between descriptor copies and writes. This PR introduces a structure that manages those copy ranges and flushes them.
4. Using copy ranges more aggressively, and non-symmetrically between the source and destination.
> [dx12] fix and refactor the samplers

- examples/quad/main.rs
- src/backend/vulkan/src/device.rs
Fixes #3408
PR checklist:
The quad example now uses this semantics to update all the descriptors in a single write.
> [vk] allow different descriptors in a single write

- CHANGELOG.md
- examples/quad/main.rs
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/device.rs
Sibling of #3410 for `hal-0.6` branch, to be used by wgpu
> [0.6/vk] allow different descriptors in a single write

- src/hal/src/lib.rs
```rust
let instance = gfx_backend::Instance::create("cs535", 1)?;
```
gives compiling error
```
error[E0277]: the trait bound `UnsupportedBackend: std::error::Error` is not satisfied
--> src/hardware.rs:18:65
|
18 |         let instance = gfx_backend::Instance::create("cs535", 1)?;
|                                                                 ^ the trait `std::error::Error` is not implemented for `UnsupportedBackend`
|
= note: required because of the requirements on the impl of `From<UnsupportedBackend>` for `Box<dyn std::error::Error>`
= note: required by `from`
```
PR checklist:
> Implement std::error::Error for UnsupportedBackend

- CHANGELOG.md
- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/lib.rs
Helps progress #3308 towards completion. This improves the limits to better reflect reality. There are still some corner cases not covered by this, but it is much more accurate.
To derive these limits I used:
- https://docs.microsoft.com/en-us/windows/win32/direct3d12/hardware-support
- Various d3d constants.
- Poking people on the directx discord to understand what should go where :)
Not ready to merge as I didn't do a version bump in case we wanted to roll this and any possible bug fixes to my bug into a single release.
> [0.6/dx12] Improve D3D12 limits

- src/backend/vulkan/src/command.rs
- src/backend/vulkan/src/conv.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/backend/vulkan/src/native.rs
- src/backend/vulkan/src/pool.rs
- src/backend/vulkan/src/window.rs
I didn't call builder methods for values that were clearly being set to their defaults in the struct. I did leave e.g. calls to `*Flags::empty()` and other non-obvious defaults, as well as any values that were default but marked as `TODO`.
PR checklist:
- WSL doesn't have graphics drivers.
- I don't have `make` on Windows, so I manually ran `cd src/warden && cargo run --bin reftest --features vulkan -- local`
- Except `mesh-shading` (I didn't have that feature).
> [vk] Migrate ash structs to builders

- CHANGELOG.md
- src/backend/dx11/src/conv.rs
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/lib.rs
Depends on #3416. Commits will be rebased away once this is merged.
Fixes the water example under DX11.
> [0.6/dx11] Fix Read-Only Depth Stencil

- CHANGELOG.md
- src/backend/dx11/src/conv.rs
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/lib.rs
Fixes the `msaa-line` wgpu example.
Now only remains the texture-array example, and we're golden :)
> [0.6/dx11] Fix multisampling

- CHANGELOG.md
- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/lib.rs
Depends on #3423.
Fixes the `texture-array` wgpu example. Once this is merged, all examples should at least run on DX11, and as such I have bumped versions.
This is a surprisingly small change for how long it took me to understand the code :)
I have added some comments to help explain a bit more how the binding situation works, especially now with arrays involved.
> [0.6/dx11] Fix writes of descriptor arrays

- CHANGELOG.md
- src/backend/dx11/src/conv.rs
- src/backend/dx11/src/debug.rs
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/lib.rs
Does some general cleanup, supports alpha-to-coverage, and adds debug names to various resoures.
Debug spans don't work right for an unknown reason, for investigation later.
> [0.6/dx11] Add Debug Names and More

- CHANGELOG.md
- src/backend/dx11/src/internal.rs
- src/backend/dx11/src/lib.rs
This fixes a bug the shadow example had on non-nvidia platforms.
> [0.6/dx11] Fix Dynamic Offsets with Command List Emulation

- CHANGELOG.md
- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/lib.rs
This fixes memory leaks in various wgpu examples, as well as leaks on swapchain resize.
I have used `thunderdome` as my arena which is a simple, limited-unsafe, no-deps, implementation of a generational arena. It's on the newer end, but I've been seeing people use it successfully in the community, combined to the lack of unsafe, I think it should be perfectly stable for use here. 
Will rollup master after this passes review.
> [0.6/dx11] Fix two memory leaks

- CHANGELOG.md
- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/lib.rs
- src/backend/dx12/src/resource.rs
Can be reviewed commit-by-commit. Actually gets us to release the descriptors.
It also fixes a mistake I made in one of the previous PRs that would panic in view creation, unnecessarily.
Also works around https://github.com/gfx-rs/wgpu/issues/1002 in the following way:
- we rotate the temporary descriptor heaps instead of resetting them every time
- once we reach the head during rotation, we insert a new heap in
That is not a guarantee that we'll never hit this WARP issue again, but there is a high chance most apps will not notice. If there is a better workaround, I'll be happy to scrap this one.
I think the old logic was plain wrong, too: the `update_pool_index ` wasn't actually being used...
> [0.6/dx12] Improve descriptor handling

- src/backend/dx12/src/command.rs
- src/backend/dx12/src/lib.rs
Fixes #3439
We used to instantly return a command list into the pool upon submit() if we knew it's a one-time submit.
However, it could happen that the user would get that command list, record it, and submit before the last one has finished.
As indicated in the issue, this can't be allowed.
So this PR makes it so we keep a hold of the command list until the reset() time.
> [dx12] fix command list reuse

- CHANGELOG.md
- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx11/src/shader.rs
Fixes https://github.com/gfx-rs/wgpu/issues/997 and assorted issues discovered when fixing that.
This PR should be reviewed commit by commit and each commit is freestanding.
A note about the general arch of the UAV changes. This moves us more towards a "lazy state changes" model. ~~While vulkan discorages this, the DX11 driver is likely doing this anyway. We currently do a lot of redundant state changes (and the calculations to figure them out) due to the differences in binding model, so moving lazy should help eliminate this. More major changes are out of scope of this PR.~~ Discussed on matrix pros/cons of this approach, and this part is no longer relevant.
I will actually PR master after this PR this time ;)
> [0.6/dx11] Fix UAV bindings 

- src/backend/metal/Cargo.toml
- src/backend/metal/src/device.rs
- src/backend/metal/src/native.rs
First humble steps towards #71 ...
Naga is an optional github dependency (obviously will need to be switched to crates upon release).
If it fails, we fall back to spirv-cross. Extra steps are taking to ensure that shader modules compiled by Naga and SPIRV-Cross can still link together.
PR checklist:
> [mtl] experimental Naga support

- CHANGELOG.md
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/shader.rs
- src/backend/dx12/src/device.rs
If a shader has a matrix as a vertex input (for things like per-instance data), spirv-cross will generate different semantics than we expect (see https://github.com/KhronosGroup/SPIRV-Cross/issues/1512). This works around the problem on both DX11 and DX12 backends. It is not implemented as efficiently as it possibly could be, but this was the easiest way to do this without really changing some functions around. Hopefully this will be resolved soon enough and this change can be removed.
I didn't bump versions as I have more fixes for both backends coming shortly.
> [0.6/dx] Workaround spirv-cross Limitation

- CHANGELOG.md
- src/backend/dx12/src/device.rs
SPIRV-Cross translates the selected entrypoint to `main` always.
`.find(|entry_point| entry_point.name == real_name)` will fail for non-`main` entrypoints of the source spirv module. Actually we don't need to query for all the entry points as we already selected the one we want.
Tested it by modfiying one of the spirv modules in the quad examples.
PR checklist:
> dx12: fix entry point selection

- CHANGELOG.md
- src/backend/dx12/src/device.rs
This fixes the issues with BC7 images being created on the wrong heap. This only moves to the target heap if the DX12 image flags actually demand it be there.
> [0.6/dx12] Fix Heap Selection for Non-Renderable Textures

- CHANGELOG.md
- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/internal.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx11/src/shader.rs
- src/backend/dx12/src/device.rs
Fixes https://github.com/gfx-rs/wgpu/issues/1005
PR is commit by commit etc.
Notes:
- I have disabled `MAILBOX` right now as it was acting like FIFO. Until we can figure out a way to make it work without limiting frame rate, we can re-enable.
- An extension of the swapchain changes will be enabling the FLIP modes on windows 8 or newer. This will also allow us to bring back ALLOW_TEARING.
- The spirv-cross workaround had a bug where there is a panic while there were more vertex attributes than inputs to the shader.
- I have included changes that reduce the amount of clones we make to `ImageView`s where we didn't actually need them.
- I have chosen this method of doing borrowed image views (forgetting smart pointers) as removing the smart pointers will make a lot of code more complicated …
> [0.6/dx] Assorted Fixes to Make BVE-Reborn Work Under DX11

- CHANGELOG.md
- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/internal.rs
This fixes depth-stencil copies on DX11. It also adds some asserts so unsupported copies properly blows up instead of silently dropping calls. This will also tell us when we may need to add some extra compute copies for things that can be copied between in vk but not DX11.
> [0.6/dx11] Fix depth to depth copies

- src/backend/dx12/src/command.rs
- src/backend/dx12/src/conv.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/lib.rs
- src/backend/dx12/src/resource.rs
Functionally, the biggest change here is excluding swapchain images from the explicit pipeline barriers.
Plus, a whole bag of small refactor.
Note: this is related to #2503 but doesn't actually solve it.
> [dx12] refactor resource transitions, exclude swapchain images

- CHANGELOG.md
- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/lib.rs
- src/backend/dx11/src/shader.rs
These are fixes exposed by a user's project.
Fixes:
- Treat push constant offset as bytes not words
- Properly find register numbers for UAVs in non-fragment shaders.
> [0.6/dx11] Assorted Fixes

- CHANGELOG.md
- src/backend/dx11/Cargo.toml
- src/backend/dx11/shaders/copy.hlsl
- src/backend/dx11/src/lib.rs
We had some nasty corruption as a result of alignment throwing some calculations off. This fixes the copies for all copies to textures that have less than 4 bytes per pixel.
As a future extension, a lot of the copies in that file aren't using full warps, so adjusting them to use full warps likely will be useful.
> [0.6/dx11] Fix buffer to image copies of textures of <4 bytes/pixel.

- CHANGELOG.md
- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/device.rs
Fixes https://github.com/gfx-rs/wgpu/issues/1013
It could be a regression from spirv-cross update, although the decoration fixes imply that it shouldn't have ever worked 🤔 
PR checklist:
> [0.6/dx12] fix respecting the read-only storage flags

- .github/workflows/CI.yml
- deny.toml
Fixes #issue
PR checklist:
---
@kvark I'll add this to CI in a second, but it won't actually deny duplicate dependencies it will just display them in the log and deny crates with unallowed licenses. Is how we'd want it?
> Add Cargo Deny Configuration

- CHANGELOG.md
- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/device.rs
Fixes last issue preventing bve-reborn from running on DX12.
I'll forward port my pending changes after this merges.
> [0.6/dx12] Fix Panic When Creating Texture View

- CHANGELOG.md
- src/backend/gl/Cargo.toml
- src/backend/gl/src/command.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/info.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/native.rs
- src/backend/gl/src/window/surfman.rs
Makes us run the `cube` and `mipmap` examples somewhat...
cc @zicklag
> [0.6/GL] descriptor write fixes with version bump

- src/backend/dx11/shaders/copy.hlsl
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/internal.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx11/src/shader.rs
- src/backend/dx12/src/device.rs
Got a little behind here; rolls up #3444 #3446 #3448 #3452 #3456 #3458 and #3465. 
#3449 seems to have been obsoleted by a previous change in master: https://github.com/gfx-rs/gfx/blame/fa323527758d35a3913815e62bcb0e08511f7384/src/backend/dx12/src/device.rs#L2443-L2449. Could you just validate that this change does indeed serve the same purpose?
> [dx/master] Rollup of DX Fixes

- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/window.rs
Fixes #3477.
Uses [IDXGIFactory::MakeWindowAssociation](https://docs.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-idxgifactory-makewindowassociation) to disable Alt+Enter behavior on dx11/dx12 backends.
* winapi-rs does not have the `DXGI_MWA` constants (opened PR https://github.com/retep998/winapi-rs/pull/960). Not sure where to cram these -- for now, I put them right beside the function call.
* Using both `DXGI_MWA_NO_WINDOW_CHANGES | DXGI_MWA_NO_ALT_ENTER`. Either of these seems to disable the Alt+Enter behavior; according to the docs, `DXGI_MWA_NO_WINDOW_CHANGES` seems more general, but I guess this is desired (DXGI shouldn't fiddle with anything automatically for consistent behavior among backends?).
PR checklist:
- dx11, dx12, vulkan
> [dx] Disable automatic Alt+Enter handling in DXGI

- .github/workflows/CI.yml
- examples/Cargo.toml
- examples/quad/data/index.html
- examples/quad/main.rs
- src/backend/gl/Cargo.toml
- src/backend/gl/src/window/web.rs
Mentionned in https://github.com/gfx-rs/gfx/pull/3470
Maybe help issue #2749
PR checklist:
> re-enable WebGL support

- src/backend/dx11/src/conv.rs
- src/backend/dx11/src/debug.rs
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/internal.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx11/src/shader.rs
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/window.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/command.rs
- src/backend/gl/src/device.rs
- src/backend/metal/src/command.rs
- src/backend/metal/src/device.rs
- src/backend/vulkan/src/command.rs
- src/backend/webgpu/src/command.rs
- src/hal/src/buffer.rs
- src/hal/src/command/mod.rs
- src/warden/src/gpu.rs
Makes it more consistent with `bind_vertex_buffers`, and also removes one more type from gfx-hal.
Also fixes #3483 
PR checklist:
> Refactor bind_index_buffer API

- CHANGELOG.md
- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/lib.rs
Allows the latest rend3 version to run on DX11. As the DX11 backend has no actual limit to how many descriptor sets can be bound, I just set it to the max value.
> [0.6/dx11] Increase max bound descriptor set count

- CHANGELOG.md
- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/dxgi.rs
- src/backend/dx11/src/lib.rs
Partially addresses #3489
From what I can tell there's no way to discover this via the DX11 APIs, so guess based on the vendor and device IDs. This can be expanded on later, but initially I've just set it to guess "integrated" for Intel GPUs and "discrete" for everything else, which probably covers >90% of the cases where this applies...
> Determine GPU type on DX11 when possible

- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/window.rs
Add support for `PresentMode::IMMEDIATE` in the DX12 backend by using the "allow tearing" swap chain feature of DXGI.
Tested on a modified `quad` example on all three vendors, both in windowed and winit's `ExclusiveFullscreen` mode.
PR checklist:
> [dx12] Add support for PresentMode::IMMEDIATE

- src/backend/dx11/src/lib.rs
Rolls up #3487 now that wgpu is targeting master! Should be the last major rollup I need to do! Woooo!
I looked at #3449 again but I don't think master needs that change, it looks correct.
> [master/dx11] Increase max bound descriptor set count

- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
Fixes this VU reported in https://github.com/gfx-rs/wgpu/issues/1059 :
> [0.375320 ERROR]()(no module):
VALIDATION [VUID-VkPipelineViewportStateCreateInfo-viewportCount-01216 (-376016417)] : Validation Error: [ VUID-VkPipelineViewportStateCreateInfo-viewportCount-01216 ] Object 0: handle = 0x2d93dbcf100, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xe99671df | vkCreateGraphicsPipelines: The VkPhysicalDeviceFeatures::multiViewport feature is disabled, but pCreateInfos[0].pViewportState->viewportCount (=0) is not 1. The Vulkan spec states: If the multiple viewports feature is not enabled, viewportCount must be 1 (https://vulkan.lunarg.com/doc/view/1.2.141.0/windows/1.2-extensions/vkspec.html#VUID-VkPipelineViewportStateCreateInfo-viewportCount-01216)
object info: (type: DEVICE, hndl: …
> [vk] fix viewport/scissor count validation error

- src/backend/vulkan/src/lib.rs
Fixes #3501
PR checklist:
<details><summary>`make reftests` failed (should be unrelated)</summary>
```
friz64@arch /m/h/D/g/gfx (submit_info_fix)> make reftests
cd src/warden && cargo run --bin reftest --features "gl vulkan " -- local
Compiling instant v0.1.9
Compiling getrandom v0.1.15
Compiling raw-window-handle v0.3.3
Compiling log v0.4.11
Compiling khronos-egl v2.1.1
Compiling x11 v2.18.2
Compiling serde v1.0.117
Compiling thiserror v1.0.22
Compiling spirv_cross v0.22.1
Compiling parking_lot_core v0.8.0
Compiling rand_core v0.5.1
Compiling parking_lot v0.11.1
Compiling rand_chacha v0.2.2
Compiling rand v0.7.3
Compiling tempfile v3.1.0
Compiling glsl-to-spirv v0.1.7
Compiling gfx-hal v0.6.0 (/mnt/hdd1/Documents/git-clones/gfx/src/hal)
Compiling ron v0.6.2
Compiling gfx-auxil v0.5.0 …
```
> Remove invalid `SubmitInfo` builder call

- .github/workflows/CI.yml
- Makefile
- src/backend/metal/Cargo.toml
- src/backend/metal/src/device.rs
- src/hal/Cargo.toml
- src/hal/src/device.rs
- src/hal/src/lib.rs
By exposing Naga in gfx-hal we'll be able to have wgpu and gfx communicate the shaders without going through SPIR-V.
PR checklist:
The controversial part here is that Naga is not optional. I tried to think of pros and cons.
Cons:
- Naga needs more work anyway, it's not ready yet
- Naga in gfx-hal isn't needed for any libraries that only depend on the gfx-hal, and do not care about Naga
Pros:
- Naga *will* need to be ready at some point, replacing SPIRV-Cross. And it will need to be available for wgpu interop, so we might as well skip the stage where it's optional in the gfx-hal.
- Naga by itself without features is super lightweight, it shouldn't affect the libraries too much. All the frontends and backends are gated by features.
- The end user app will need to depend on gfx-hal backends, …
> Add Naga dependency

- src/backend/dx12/src/command.rs
- src/backend/dx12/src/device.rs
`CommandBuffer.raw` is null when the command buffer is not recording, so
we have to store the name and set it later in `CommandBuffer::begin`.
Fixes water and texture-arrays `wgpu-rs` examples: https://github.com/gfx-rs/wgpu/issues/1059
PR checklist:
> [dx12] Fix `set_command_buffer_name`

- examples/quad/main.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/window/web.rs
> [gl] Add Instance struct in web version to align API with other backends.

- src/backend/gl/src/info.rs
> [gl] Remove WebGL hardcoded min_storage_buffer_offset_alignment value.

- examples/quad/main.rs
- src/backend/metal/src/command.rs
Fixes #3509
This was a regression from #3486
PR checklist:
> [mtl] adjust render pass compatibility check at the start of a pass

- bors.toml
The Rust issue resulted in rolling back the originally causing change. We are green again.
> Unblock nightly builds

- src/backend/metal/src/device.rs
Solves https://github.com/gfx-rs/wgpu/issues/1075
PR checklist:
> [metal] disable MANAGED_DOWNLOAD memory type

- src/backend/metal/Cargo.toml
- src/backend/vulkan/Cargo.toml
- src/hal/Cargo.toml
Improves SPIR-V generation, allows wgpu to use the latest Naga.
> Update naga to gfx-3

- Makefile
- src/backend/gl/Cargo.toml
- src/backend/gl/src/device.rs
- src/backend/gl/src/native.rs
Closes #3519
The meat of the issue here is to get the proper resource mapping plumbed between gfx and Naga glsl backend, and this isn't done in the PR. However, very primitive shaders that use no resources (e.g. hello-triangle) should already work.
> OpenGL Naga integration

- src/backend/gl/src/device.rs
Running the quad sample the gfx-backend-gl backend works, but running the hello-triangle from the wgpu-rs project by creating the wgpu::Instance with wgpu::BackendBit::GL panics with:
```
Running `target/debug/examples/hello-triangle`
thread 'main' panicked at 'assertion failed: `(left == right)`
left: `"vs_main"`,
right: `"main"`', /path/to/home/.cargo/git/checkouts/gfx-e86e7f3ebdbc4218/f1398d2/src/backend/gl/src/device.rs:399:9
```
Current PR fixes this, by removing outdated assertions as per comment here:
https://github.com/gfx-rs/gfx/pull/3520#discussion_r537818829
> Remove outdated entry point assertions

- src/backend/gl/src/lib.rs
Fixes image_format_properties method for gfx-backend-gl to return None for unsupported/unmapped image formats.
Up until now clients where tricked into believing that all formats where available and subsequent calls to image_create failed.
> Return None for unsupported formats in image_format_properties

- src/backend/gl/src/device.rs
Fixes crash when client asks for unsupported texture type
> Replaced unwrap with proper error handling on create_image

- src/backend/gl/src/conv.rs
When using latest gfx-backend-gl as a backend for gfx-rs/portability vulkaninfo util fails on image creation because it asks some non mapped texture formats.
> GL: Add formats asked by vulkaninfo utility

- src/backend/gl/src/command.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/native.rs
- src/backend/gl/src/queue.rs
This will allow us to store a kind: hal::image::Kind field in the near future
> Renamed ImageKind to ImageType in opengl backend

- src/backend/gl/src/device.rs
- src/backend/gl/src/native.rs
- src/backend/gl/src/window/egl.rs
Implementation similar to metal backend
> Implement get_image_subresource_footprint in opengl backend

- examples/Cargo.toml
- src/backend/gl/Cargo.toml
- src/backend/gl/src/info.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/window/egl.rs
- src/warden/Cargo.toml
Fixes #3519 for real this time
Fixes #3534
Drops X11 dependency :tada: 
PR checklist:
> Better GL context initialization

- src/hal/Cargo.toml
It seems that `mint` is no longer used anywhere in `gfx`. This change removes the listing from the manifest file.
> Remove optional dependency on mint

- .github/workflows/CI.yml
- Makefile
- bors.toml
- src/backend/gl/Cargo.toml
- src/backend/gl/src/lib.rs
- src/backend/gl/src/window/egl.rs
- src/backend/gl/src/window/web.rs
- src/backend/webgpu/Cargo.toml
I believe the target was broken for a while, possibly since we moved to Github actions.
PR checklist:
> [gl] fix the WASM target and enable on CI

- Cargo.toml
- src/backend/gl/Cargo.toml
- src/backend/gl/src/command.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/native.rs
- src/backend/gl/src/queue.rs
- src/backend/metal/Cargo.toml
- src/backend/metal/src/device.rs
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/device.rs
- src/hal/Cargo.toml
Closes #2858
Closes #2784
Depends on https://github.com/gfx-rs/naga/pull/333
I was having a hard time trying to map our Naga semantics to the old binding model of gfx-backend-gl. I also couldn't stand the fact that the pipeline layouts were internally mutable, and mapping could grow as more pipelines are created. That seemed very out of line with regards to how other backends are written, and I didn't fully understand that code...
So the binding model is totally rewritten here. It becomes somewhat similar to Metal or D3D11, but with special logic to update the texture binding state instead of having true sampler objects.
The new code likely hosts bugs, I wasn't able to test it a lot, especially given the overall state of the backend. I think this rewrite is still a good investment into …
> Rewrite the GL binding model

- .github/workflows/CI.yml
- src/backend/gl/Cargo.toml
Fixes the fact that our wasm-bindgen was locked to 0.2.60 by #3537
> [gl] unlock wasm-bindgen version

- src/backend/gl/src/command.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/native.rs
- src/hal/src/window.rs
Fixes the stack overflow in tests
PR checklist:
> [gl] Fix the number of texture units

- examples/compute/main.rs
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/device.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/command.rs
- src/backend/gl/src/device.rs
- src/backend/metal/src/command.rs
- src/backend/metal/src/device.rs
- src/backend/vulkan/src/command.rs
- src/backend/vulkan/src/device.rs
- src/backend/webgpu/src/command.rs
- src/hal/src/buffer.rs
- src/hal/src/command/mod.rs
- src/hal/src/device.rs
Adds the following:
```rust
/// An stride between elements inside a buffer, in bytes.
pub type Stride = u32;
```
Note that `CommandBuffer::copy_query_pool_results`'s and `Device::get_query_pool_results`'s `stride` parameters have changed from `u64` to `u32`. I'm unsure of the implications of this, but I don't imagine nobody has a buffer with a stride > `u32::max_value()` (can backends even support buffers that large?). Please let me know if I should change this back!
PR checklist:
> Add typedef for buffer stride

- src/backend/dx11/src/lib.rs
This PR plus the gpu-alloc fixes all the DX11 specific issues in https://github.com/gfx-rs/wgpu/issues/1059.
These are all refcount issues, one was a double free of images, the other was some resources not being freed on the swapchain.
> [dx11] Fixes regressions from 0.6 to Master

- src/backend/gl/src/window/egl.rs
*~~This PR isn't meant to be merged in the current state, but to illustrate what changes were need to get it working.~~*
I've been trying to get the OpenGL backend working with wayland. The current device I'm targeting doesn't currently support Vulkan so I'm trying to get the wayland renderer working. During my tests I'm hitting some blockers with the `hal::Instance` API and I'm wondering if I'm doing something wrong, or if the API just wasn't developed with this in mind.
I'm hitting the following roadblocks:
1. I need a pointer to this display to pass to `get_platform_display`. Both creating a new connection and using `egl::DEFAULT_DISPLAY` results in the window not working or rendering in the `quad` example. To get around this I'm passing a pointer to the create function via the …
> Wayland Support for the OpenGL Backend

- src/backend/webgpu/src/command.rs
- src/backend/webgpu/src/device.rs
Fixing the parts of the WebGPU build I broke in #3546, since it's not included in the `make` build.
> Fix WebGPU build to use buffer::Stride

- src/backend/gl/src/device.rs
Fixes an issue where there is a panic because the program failed to link, but no actual error reported.
> Check for GL program linking before using it

- examples/colour-uniform/main.rs
- examples/compute/main.rs
- examples/mesh-shading/main.rs
- examples/quad/main.rs
- src/backend/dx11/src/device.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/lib.rs
- src/backend/dx12/src/resource.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/command.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/native.rs
- src/backend/gl/src/queue.rs
- src/backend/metal/src/command.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/native.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/backend/webgpu/src/command.rs
- src/backend/webgpu/src/device.rs
- src/hal/src/device.rs
- src/hal/src/pso/descriptor.rs
- src/hal/src/queue/mod.rs
- src/hal/src/window.rs
- src/warden/src/gpu.rs
~~The external sync in these objects *almost* allows us to simplify the implementations, but not really. So it's sort of a waste, but there is no reason to diverge from Vulkan here.~~
This allows our backends to do less locking! 🎉 
Fixes #3551 
PR checklist:
> Update API object mutability according to external synchronization requirements in Vulkan

- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/lib.rs
- src/backend/metal/src/conversions.rs
- src/backend/metal/src/lib.rs
- src/backend/vulkan/src/conv.rs
- src/hal/src/format.rs
Implemented for Vulkan/DX12/DX11.
In Vulkan, storage image implies simultaneous read/write access.
Other APIs in contrast may allow STORAGE writeonly while disallowing reading.
Related to https://github.com/gfx-rs/wgpu/pull/1109 - native extension for for read+write storage textures in wgpu native; following comments on the PR I'm redoing it and would need to add this to the hal api.
PR checklist:
- Vulkan/DX12/DX11
- did a dump of storage/storage-atomic/storage-rw flags each and eyeballed it as a sanity check
> Distinguish STORAGE from STORAGE_READ_WRITE image feature

- src/backend/empty/src/lib.rs
- src/backend/metal/src/lib.rs
- src/backend/metal/src/window.rs
- src/hal/src/device.rs
Just a maintenance PR to clean up some code.
PR checklist:
> Cleanup Empty backend, remove AcquireMode from Metal

- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/lib.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/info.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/queue.rs
- src/backend/metal/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/backend/webgpu/src/lib.rs
- src/hal/src/adapter.rs
- src/hal/src/lib.rs
Fixes  #3441
Reverses the semantic of "hints", also renaming them to "performance_caveats", and placing inside a new struct called `Capabilities`. Unlike features, this struct represent properties of the adapter that do not need to be enabled.
PR checklist:
> Expose dynamic state capabilities in the backends

- CHANGELOG.md
- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/lib.rs
- src/backend/gl/src/lib.rs
- src/backend/metal/src/conversions.rs
- src/backend/vulkan/src/conv.rs
- src/backend/vulkan/src/lib.rs
- src/hal/src/format.rs
Fixes #3575 
Having distinct `TRANSFER_SRC` and `TRANSFER_DST` flags follows Vulkan's maintenance-1 extension and allows for better separation between "blit" and "transfer" capabilities.
PR checklist:
> Add image features for transfers and min/max sampling

- src/backend/metal/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/hal/src/lib.rs
This is a limitation of D3D, which we want to expose one way or the other.
> Add a feature for non-normalized samplers

- src/backend/gl/Cargo.toml
- src/backend/gl/src/device.rs
Fixes #3580
Possible fixes #3562
PR checklist:
> [GL] Add empty fragment shader when only vertex shader present

- examples/Cargo.toml
- src/backend/gl/src/device.rs
- src/backend/gl/src/window/egl.rs
- src/backend/vulkan/src/lib.rs
Apparently, enabling maintenance-2 doesn't auto-enable maintenance-1. Who'd new? That manifests in our NDC inversion going broke:
> [1.285790 ERROR]()(no module): 
VALIDATION [VUID-VkViewport-height-01772 (-1596201395)] : Validation Error: [ VUID-VkViewport-height-01772 ] Object 0: handle = 0x559394238118, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID = 0xa0dbe64d | vkCmdSetViewport: pViewports[0].height (=-600.000000) is not greater 0.0. The Vulkan spec states: height must be greater than 0.0 (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkViewport-height-01772)
object info: (type: COMMAND_BUFFER, hndl: 94092333908248)
> [vk] don't forget to enable maintenance-1

- src/backend/gl/src/info.rs
- src/backend/gl/src/queue.rs
Fixes #3593
This works around the issue. To avoid redundant state changes in the future, as mentioned in the comment, we should coalesce on the command-generator side to a single global call.
> [GL] Workaround WebGL's Lack of Per-Target Color Masks

- src/backend/gl/src/window/egl.rs
PR checklist:
Android emulator doesn't support EGL_KHR_surfaceless_context.
> [GL] Android emulator support

- src/backend/gl/Cargo.toml
- src/backend/gl/src/window/egl.rs
Fixes https://github.com/timothee-haudebourg/khronos-egl/issues/11 (is there an according issue in this repo?)
PR checklist:
> Dynamic version detection for EGL

- src/backend/gl/src/info.rs
- src/backend/gl/src/queue.rs
- src/backend/gl/src/window/egl.rs
Fixes #3588
The problem was that the RWH handle was of a different XLib display from the one used for `Instance` creation. Now we detect this and react accordingly. Running the example is still not possible on those Intel+NV machines, but that should be resolved separately. There was already `supports_native_window = false` in the instance.
PR checklist:
> [gl] Detect XLib display mismatch

- src/backend/gl/src/command.rs
- src/backend/gl/src/info.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/native.rs
- src/backend/gl/src/queue.rs
- src/backend/gl/src/window/egl.rs
- src/warden/Cargo.toml
- work/scenes/transfer.ron
Fixes the GL backend presentation on all platforms (yikes!).
Refactors the fbconfig request to check for tiers in a loop.
Finally, implements `fill_buffer`. We can now go through `make reftests` without crashes, albeit some unimplemented methods remain.
r? @Gordon-F 
PR checklist:
> [gl] fix x11 RWH handling, tiered configs, and fill_buffer

- src/auxil/range-alloc/src/lib.rs
Noticed when trying to use range-alloc for purpose of buffer zero init tracking in wgpu.
(I don't know if this led to other issues down the line)
> Fix RangeAllocator.allocated_ranges returning empty iterator for fully allocated RangeAllocator

- src/backend/gl/src/queue.rs
Fixes a misfiring assert I added recently...
PR checklist:
> [gl] remove bogus assertions about viewports

- src/backend/gl/src/info.rs
Fixes #3601 (in one of the parallel universes)
PR checklist:
> [gl] Enable explicit shader layout in GLES

- src/backend/dx12/src/device.rs
Fixes a panic on device lost in DX12
PR checklist:
> [dx12] catch device lost during fence wait

- src/backend/gl/src/command.rs
- src/backend/gl/src/info.rs
- src/backend/gl/src/queue.rs
Fixes
> [2021-01-19T16:50:33Z WARN  gfx_backend_gl::queue] GLES and WebGL do not support per-target color masks. Falling back on global mask.
> [gl] Color mask warning fix

- src/auxil/auxil/Cargo.toml
- src/backend/dx11/Cargo.toml
- src/backend/dx12/Cargo.toml
- src/backend/gl/Cargo.toml
- src/backend/metal/Cargo.toml
- src/backend/metal/src/device.rs
Fix the comment in https://github.com/gfx-rs/gfx/issues/3389#issuecomment-763983048
> Update spirv-cross to version 0.23

- src/backend/gl/Cargo.toml
- src/backend/metal/Cargo.toml
- src/backend/metal/src/device.rs
- src/backend/vulkan/Cargo.toml
- src/hal/Cargo.toml
Gets gfx-7 tag for naga, also picks up https://github.com/timothee-haudebourg/khronos-egl/issues/11
PR checklist:
> Update naga, egl, and metal

- src/backend/gl/Cargo.toml
- src/backend/metal/Cargo.toml
- src/backend/metal/src/device.rs
- src/backend/vulkan/Cargo.toml
- src/hal/Cargo.toml
Gets us lots of new good things, including https://github.com/gfx-rs/naga/pull/366
PR checklist:
> Update naga to gfx-8, fix metal naga-parse feature

- src/backend/metal/src/device.rs
- src/backend/metal/src/native.rs
Fixes the new WGSL shaders in wgpu-rs.
Instead of treating the entry point name as unique within a module, we are treating the pair of `(Stage, Name)` as unique.
PR checklist:
> [mtl] separate entry points by stage

- CHANGELOG.md
- examples/Cargo.toml
- examples/bench/main.rs
- examples/compute/main.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/lib.rs
- src/backend/dx12/src/resource.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/Cargo.toml
- src/backend/gl/src/lib.rs
- src/backend/gl/src/queue.rs
- src/backend/metal/Cargo.toml
- src/backend/metal/src/command.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/lib.rs
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/command.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/backend/webgpu/src/command.rs
- src/backend/webgpu/src/lib.rs
- src/hal/Cargo.toml
- src/hal/src/adapter.rs
- src/hal/src/device.rs
- src/hal/src/lib.rs
- src/hal/src/queue/family.rs
- src/hal/src/queue/mod.rs
- src/hal/src/window.rs
Introduces a new example for benchmarking small transfers!
Fixes a small case where Linearly tiled image is created on the known memory. This is still a hack, but more useful than the old code.
Interestingly, the AMD machine on windows totally craps out when the total number of copy regions exceeds 4M per submission. So I had to keep the size down.
Results for 1K by 1K:
| API         | OS             | Hardware | image->image | buffer->image |
| -------  | ----------- | ---------  | -------------- | --------------- |
| Vulkan | Win7 | AMD Rx470 | 320ms | 18 ms|
| Vulkan | Win10 | Gtx1080 | 19ms | 19ms |
| Vulkan | Win10 | Iris 530 | 620ms | 620ms |
Results for 512 by 512:
| API         | OS             | Hardware | image->image | buffer->image |
| -------  | ----------- | ---------  | …
> Transfer benchmarking example, dx12 query resolve

- src/backend/dx12/src/lib.rs
Unblocks https://github.com/gfx-rs/portability/issues/242
PR checklist:
> [dx12] fill out the vs/fs input/output limits

- src/backend/metal/src/command.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/native.rs
- src/backend/metal/src/window.rs
Let's us run Dota2 again!
PR checklist:
> [mtl] fix sample count check for secondary command buffers

- src/backend/vulkan/src/extensions_resolver.rs
- src/backend/vulkan/src/lib.rs
This PR includes the following changes:
- Use `vkEnumerateInstanceVersion` to query for the Vulkan driver version and use `min(driver_version, 1.2)` to create the instance.
- This does not expose any additional 1.1+ functionality in `gfx-hal`, but should allow for later adding features like descriptor indexing and ray tracing.
- Refactor the device extension code to include an extension resolver that correctly includes and excludes requested extensions based on extension promotion status.
- `PhysicalDevice::open` on Vulkan can now fail with `DeviceCreationError::MissingExtension` if a required extension is missing.
Note that while this change can create 1.1 and 1.2 instances, we must opt into 1.3+ whenever that is released.
Some things to consider moving forward:
- API version minor …
> [vk] Support Vulkan 1.1 and 1.2 and refactor extension loading

- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/lib.rs
`RTLD_NEXT` is a GNU-specific flag which isn't supported currently by libloading, so we can't replace shared_library with it. However, we can simply use `dlsym` directly, and since libc is already present in the dependency chain, in practice it still means building one less dependency.
Closes #3540
PR checklist:
> Use libc for the use-rtld-next Vulkan backend feature

- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/dxgi.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx12/Cargo.toml
- src/backend/gl/Cargo.toml
- src/backend/gl/src/window/egl.rs
Just a (hopefully) harmless update. Updated in `d2d12-rs` too: https://github.com/gfx-rs/d3d12-rs/pull/28
PR checklist:
> Update libloading to 0.7

- src/backend/vulkan/src/lib.rs
The Vulkan validation layer outputs messages that reference object handles and message IDs in a hexadecimal format and this change makes `gfx`'s custom `DebugUtil` output consistent with that.
> [vk] Print IDs as hex in DebugUtil output

- src/backend/dx11/src/conv.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx11/src/shader.rs
- src/backend/dx12/src/device.rs
PR checklist:
fixes:
`error X4502: invalid vs_5_0 output semantic 'SV_Target0'`
`Unable to find binding 1`
note: on my machine win10 rx580, wgpu-rs shadow example and texture-arrays are still broken. gfx example compute not working but wgpu-rs hello-compute works. also gfx example colour-uniform is broken. this pr does not impact those issues.
on a win7 machine with nvidia 930m or intel 5500, almost everything does not work except use renderdoc.
> [dx11] Fix some panics with multiple entries spirv

- examples/Cargo.toml
- src/backend/dx11/src/lib.rs
- src/backend/gl/Cargo.toml
- src/backend/gl/src/conv.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/native.rs
- src/backend/gl/src/pool.rs
- src/backend/gl/src/window/egl.rs
- src/backend/metal/Cargo.toml
- src/backend/metal/src/command.rs
- src/backend/metal/src/conversions.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/internal.rs
- src/backend/metal/src/lib.rs
- src/backend/metal/src/native.rs
- src/backend/metal/src/soft.rs
- src/hal/src/pso/mod.rs
SPIRV-Cross is a big foreign dependency, which often cause issues, such as https://github.com/denoland/rusty_v8/issues/465 and #3389, #3117, #2520, and many others.
Previously in #3445 and #3520 we implemented Naga code path as an alternative, but hidden behind an optional feature. Now it's time to flip the table and say that Naga is permanent, but SPIRV-Cross is optional until completely phased out.
Most of the changes here are from re-routing the main shader creation logic from using SPIRV-Cross types to using Naga types. The "cross" stuff is just getting derived from Naga types if necessary.
The change only applies to Metal and OpenGL backends so far. D3D will come on board once https://github.com/gfx-rs/naga/pull/408 is operational.
Note: it's going to be a long while for Naga to …
> Make spirv-cross optional

- examples/bench/main.rs
- examples/colour-uniform/main.rs
- examples/mesh-shading/main.rs
- examples/quad/main.rs
- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/lib.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/info.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/queue.rs
- src/backend/metal/src/device.rs
- src/backend/vulkan/src/conv.rs
- src/backend/vulkan/src/lib.rs
- src/backend/webgpu/src/lib.rs
- src/hal/src/adapter.rs
- src/hal/src/lib.rs
- src/warden/src/bin/bench.rs
- src/warden/src/bin/reftest.rs
- src/warden/src/gpu.rs
This PR:
- Merges `hal::Limits` and `hal::Capabilities` as `PhysicalDeviceProperties`.
- The name was chosen to be more similar to Vulkan.
- Adds properties structs for mesh shaders and descriptor indexing.
- Adds a `DescriptorLimits` struct to hold descriptor limits and makes the values `u32`.
PR checklist:
> [hal] Merge `Limits` and `Capabilities` as `PhysicalDeviceProperties`

- src/backend/gl/src/info.rs
> [GL] Fix WebGL version checking

- src/backend/vulkan/src/lib.rs
- src/hal/src/device.rs
Fixes #3648 
What happened is an internal miscommunication between which extensions are required, and which aren't.
I also removed the `MissingExtension` error from the API because the API has no extensions.
> Fix Vulkan extension checks

- CHANGELOG.md
- src/backend/gl/Cargo.toml
- src/backend/gl/src/info.rs
0.7 version https://github.com/gfx-rs/gfx/pull/3646
Fixes #3644
PR checklist:
> [GL] Fix WebGL version checking (0.7)

- src/backend/gl/Cargo.toml
This pulls in a fix for timothee-haudebourg/khronos-egl#14,
which prevents segfaults when using this crate from another thread
(e.g. gfx-rs/wgpu#246)
PR checklist:
- GL
> Bump `khronos-egl` dependency to version 4

- examples/colour-uniform/main.rs
- examples/quad/main.rs
> Add fences between command pool resets. Fix for #3625

- src/backend/vulkan/src/command.rs
- src/backend/vulkan/src/lib.rs
- src/backend/vulkan/src/physical_device.rs
Fixes a couple issues caused by #3654
- `Features::NDC_Y_UP` was not advertised correctly for 1.1
- `Features::SAMPLER_MIRROR_CLAMP_EDGE` could be missed in 1.2 if the driver does not explicitly support `VK_KHR_sampler_mirror_clamp_edge`.
- `Features::DRAW_INDIRECT_COUNT` could be missed in 1.2 if the driver does not explicitly support `VK_KHR_draw_indirect_count`.
- `VK_KHR_draw_indirect_count` was not correctly excluded in 1.2
- `cmd_draw_indirect_count` and `cmd_draw_indexed_indirect_count` were not correctly being loaded in 1.2
- I'm unsure if there's a way in `ash` to load both the extension function pointer and the core promoted function pointer into the same Rust function, but that would certainly make this code simpler.
> [vk] Fix some issues caused by #3654

- examples/bench/main.rs
- examples/colour-uniform/main.rs
- examples/compute/main.rs
- examples/mesh-shading/main.rs
- examples/quad/main.rs
- src/backend/dx11/src/device.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/lib.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/device.rs
- src/backend/metal/src/device.rs
- src/backend/vulkan/src/conv.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/backend/webgpu/src/command.rs
- src/backend/webgpu/src/device.rs
- src/hal/src/buffer.rs
- src/hal/src/device.rs
- src/hal/src/image.rs
- src/hal/src/memory.rs
- src/hal/src/queue/mod.rs
- src/warden/src/gpu.rs
Progress in implementing sparse resources, listed on issue #1610
This PR adds the following:
- A `bind_sparse` method in CommandQueue based on `submit`.
- A Vulkan implementation for `bind_sparse`, making a [vkQueueBindSparse](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkQueueBindSparse.html) call.
- A DirectX12 implementation for `bind_sparse` for images, creating a virtual resource with [CreateReservedResource](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12device-createreservedresource) if unbound and mapping it to memory with [UpdateTileMappings](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12commandqueue-updatetilemappings).
- `SPARSE_BINDING`, `SPARSE_RESIDENCY` and `SPARSE_ALIASED` view capabilities when …
> Sparse (tiled) resources for Vulkan and DirectX 12

- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/lib.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/lib.rs
- src/backend/metal/src/lib.rs
- src/backend/vulkan/src/lib.rs
- src/backend/webgpu/src/lib.rs
- src/hal/src/queue/family.rs
Followup #3521 and alternative implementation for #3665.
PR checklist:
> Adding supports_sparse_binding to QueueFamily

- src/backend/gl/Cargo.toml
- src/backend/gl/src/device.rs
- src/backend/metal/Cargo.toml
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/physical_device.rs
- src/hal/Cargo.toml
Picks up https://github.com/gfx-rs/naga/pull/552 and https://github.com/gfx-rs/naga/pull/564, which doesn't affect gfx-rs in any way.
> Update naga to gfx-14

- src/backend/dx12/src/conv.rs
- src/backend/dx12/src/lib.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/physical_device.rs
- src/hal/src/lib.rs
Sorta fixes #3637 
Only provides the very basic option of enabling/disabling overestimation rasterization. This is almost everything DX12 has to offer anyways except the optional `SV_InnerCoverage` support, but leaves out even more Vulkan goodies (e.g. underestimation, various device properties, configurable extra-over-estimation, conservative raster of lines...).
Availability of the coverage variable is the most important missing thing but could later be exposed as an additional feature flag (debatable, since this is not how Vulkan does it, so more of a device property?)
Probably more controversial about this PR: `validate_creation_desc_support`
I didn't want to repeat feature check code over all devices so I created a function on the desc that validates against features (and made …
> basic conservative rasterization support for Vulkan & DX12

- src/backend/dx12/src/lib.rs
- src/backend/vulkan/src/physical_device.rs
- src/hal/src/lib.rs
Exposes storage buffer and uniform buffer arrays features in the same way as textures.
- Doesn't expose new features on gl or metal
PR checklist:
> Add uniform and storage buffer descriptor indexing

- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/conv.rs
- src/backend/dx12/src/pool.rs
- src/backend/gl/src/window/egl.rs
> [dx12] reset command allocators periodically

- src/backend/vulkan/src/physical_device.rs
Clients with a device that is running Vulkan 1.2 but does not support `sampler_filter_minmax` would crash on physical device creation. This can happen as well with `imageless_framebuffer` on e.g. Android devices.
This change makes it so the features are only enabled if they are available.
Fixes #3677
Note I can't effectively test this outside of the device simulator because I don't have real hardware in this configuration.
> [vk] Only enable sampler_filter_minmax and imageless_framebuffer on 1.2 when device supports it

- src/backend/dx11/src/device.rs
- src/backend/dx11/src/shader.rs
- src/backend/dx12/src/device.rs
- src/backend/gl/src/device.rs
- src/backend/metal/src/device.rs
- src/hal/src/pso/mod.rs
As discussed in the matrix. Add new pso creation error - ShaderCreationError.
PR checklist:
> Add pso ShaderCreationError

- src/backend/gl/src/info.rs
- src/backend/gl/src/lib.rs
This commit adds a structure called `info::TextureFormatFilter` and changes the
code in `info::query_all` so that, when detecting OpenGL ES it can select a
set of valid texture property combinations.
This provides `PhysicalDevice::image_format_properties` with a way of more
accurately filtering out formats that aren't valid for textures and whose
use would lead to a crash.
Fixes #3683
PR checklist:
1. OpenGL
2. Vulkan
One thing to keep in mind about this PR is that the current filter implementation overblocks formats. This is due to a limitation with the definition of `PhysicalDevice::image_format_properties`. Since the image creation function picks the underlying OpenGL function based on not just the format and usage, as `image_format_properties` assumes, but also based on the mipmap …
> Add a texture format filter.

- src/backend/metal/src/command.rs
push_graphics_constants can fail if the stages don't match the pipeline layout
i changed some `unwrap`s to `expect`s to make it a bit easier to see what's going wrong
> descriptive assertions in push_graphics_constants

- src/backend/gl/src/conv.rs
Fixes some incorrect internal texture format. [glTexImage2D](https://www.khronos.org/registry/OpenGL-Refpages/es3.0/html/glTexImage2D.xhtml) [Ext BGRA888](https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_texture_format_BGRA8888.txt)
PR checklist:
> Fix incorrect gl texture internal formats

- src/backend/vulkan/src/lib.rs
The vulkan implementation of Queue::present mixed up the return value of ash's queue_present.
queue_present "returns whether the swapchain is suboptimal for the surface". Therefore when it is true, we should return Some(Suboptimal) and when it's false we return None.
> [Vulkan] Fixed vulkan present optimality

- src/backend/vulkan/src/conv.rs
- src/backend/vulkan/src/physical_device.rs
Follow-up to #3677
PR checklist:
> [vk] Don't advertise `format::ImageFeature::SAMPLED_MINMAX` if the device does not support it.

- src/backend/gl/src/command.rs
- src/backend/gl/src/device.rs
- src/backend/gl/src/info.rs
- src/backend/gl/src/lib.rs
- src/backend/gl/src/native.rs
- src/backend/gl/src/queue.rs
- src/backend/gl/src/state.rs
- src/backend/gl/src/window/egl.rs
Fixes #3669
PR checklist:
Currently, the problem is not fully resolved:
> [WebGL] Fix index buffer usage

- src/backend/metal/src/command.rs
Fixes the current visual issues with running Dota2 on gfx-portability
> [mtl] fix depth/stencil state in secondary command buffers

- src/backend/gl/src/window/web.rs
WebGL doesn't supports BGRA texture formats
PR checklist:
> [WebGL] Return only RGBA swapchain formats

- src/backend/gl/Cargo.toml
- src/backend/gl/src/device.rs
- src/backend/metal/Cargo.toml
- src/backend/metal/src/device.rs
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/device.rs
- src/hal/Cargo.toml
- src/hal/src/device.rs
When trying to update my dev environment to the latest `naga`, I saw that api changes a little bit. This PR update to latest available naga (a0b5717fed0bd1c8536fb2204f308d6db39d295f)
Hope this will be helpful 😄 
PR checklist:
> Update naga to gfx-18

- src/backend/vulkan/src/lib.rs
> [vk] Enable VK_KHR_storage_buffer_storage_class on Vulkan 1.0

- src/backend/vulkan/src/physical_device.rs
Fixes descriptor indexing not being enabled on vulkan1.2
PR checklist:
> Fix buffer descriptor indexing on vulkan1.2

- examples/colour-uniform/main.rs
Ran into this when I forgot to add `--features dx12` to the colour-uniform example
PR checklist:
> List all features in colour-uniform error message

- src/auxil/auxil/src/lib.rs
- src/backend/dx12/src/device.rs
- src/hal/src/pso/specialization.rs
https://doc.rust-lang.org/std/primitive.u16.html#method.max_value
PR checklist:
> max_value() is being deprecated, use ::MAX instead

- CHANGELOG.md
- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/pool.rs
Backport #3680 to hal-0.7 to avoid excess memory usage in DX12.
Some Bevy users were hitting this through wgpu, so it might be nice to backport this fix this in 0.7 too (instead of waiting for the next wgpu release).
I tried hal-0.7 with and without the fix on quad by repeatedly resizing the window, and the memory grows without the fix but seems stable with it (as expected).
PR checklist:
> [0.7/dx12] Reset command allocators periodically

- src/backend/dx11/src/lib.rs
- src/backend/dx12/src/command.rs
- src/backend/dx12/src/lib.rs
- src/backend/gl/src/command.rs
- src/backend/metal/src/command.rs
- src/backend/vulkan/src/device.rs
- src/hal/src/lib.rs
- src/hal/src/pso/graphics.rs
"color" is an overloaded term. Constants is what Vulkan calls it, and it matches our blend factor variants.
PR checklist:
> Rename blend color to blend constants

- Cargo.toml
- examples/quad/main.rs
- src/backend/gl/Cargo.toml
- src/backend/metal/Cargo.toml
- src/backend/metal/src/device.rs
- src/backend/metal/src/lib.rs
- src/backend/metal/src/native.rs
- src/backend/metal/src/pipeline_cache.rs
- src/backend/vulkan/Cargo.toml
- src/hal/Cargo.toml
See #3716. This PR builds on-top of https://github.com/gfx-rs/metal-rs/pull/207 to add an implementation of `get_pipeline_cache_data` for the metal backend. This PR is not ready for reviews.
Todo:
PR checklist:
> Use Binary Archives as a pipeline cache on the metal backend

- src/backend/vulkan/src/conv.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/physical_device.rs
- src/hal/src/image.rs
- src/hal/src/lib.rs
> Sampler reduction modes exposed

- examples/colour-uniform/main.rs
- examples/quad/main.rs
- src/backend/dx11/src/device.rs
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/resource.rs
- src/backend/dx12/src/window.rs
- src/backend/empty/src/lib.rs
- src/backend/gl/src/device.rs
- src/backend/metal/src/device.rs
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/backend/vulkan/src/physical_device.rs
- src/backend/vulkan/src/window.rs
- src/hal/src/device.rs
- src/warden/src/gpu.rs
- src/warden/src/raw.rs
- work/scenes/basic.ron
- work/scenes/large.ron
- work/scenes/vertex-offset.ron
> Add image usage parameter to the view creation

- src/backend/metal/src/command.rs
- src/backend/metal/src/window.rs
Add a presentation path that forces CoreAnimation transaction.
> [mtl] present with transaction, optionally

- src/backend/metal/src/lib.rs
> [mtl] hack around supports_family check

- src/backend/metal/src/lib.rs
Fixes linking issues when QuartzCore is not linked by some other means
Fixes #issue
PR checklist:
> metal: Link to QuartzCore

- src/hal/src/device.rs
- src/hal/src/memory.rs
Running `cargo doc` on the vulkan backend will generate the following error:
```
error: unresolved link to `Device::reset_fences`
--> src/hal/src/device.rs:558:26
|
558 |     /// [`reset_fences`][Device::reset_fences].
|                          ^^^^^^^^^^^^^^^^^^^^ the trait `Device` has no associated item named `reset_fences`
|
note: the lint level is defined here
--> src/hal/src/lib.rs:9:5
|
9   |     broken_intra_doc_links,
|     ^^^^^^^^^^^^^^^^^^^^^^
error: unresolved link to `CommandQueue::bind_sparse`
--> src/hal/src/memory.rs:134:41
|
134 | /// This is used in the [`bind_sparse`][CommandQueue::bind_sparse] method to define a physical
|                                         ^^^^^^^^^^^^^^^^^^^^^^^^^ no item named `CommandQueue` in scope
error: unresolved link to …
```
> Fixed missing or wrong name links on documentation.

- examples/compute/main.rs
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
TODOs:
This is a follow up on #3708
Fixes #issue
PR checklist:
> [vk]: implement Device::start_capture() and Device::stop_capture() on Vulkan using renderdoc (as optional feature/dependency)

- src/backend/gl/src/device.rs
- src/backend/gl/src/native.rs
- src/backend/metal/src/device.rs
- src/backend/metal/src/lib.rs
- src/backend/metal/src/native.rs
Follow-up to #3641
Our code paths are more complex that they should be. Duplicating the Naga path both before and after the Cross, depending on the preference, is not needed by anybody. Now that Naga has matured quite a bit, we need to be more aggressive.
I believe this PR preserves the old behavior (minus fallback from Cross to Naga), but cleans up the code. It also avoids unnecessary work (naga parsing of SPIR-V) if Cross is enabled.
PR checklist:
> Remove Naga preference setting from GL and Metal

- src/backend/metal/src/window.rs
- src/hal/src/window.rs
Fixes #3704
PR checklist:
Tested it with the following patch: 
```diff
diff --git a/examples/quad/main.rs b/examples/quad/main.rs
index 8989a75ef..676e5a198 100644
--- a/examples/quad/main.rs
+++ b/examples/quad/main.rs
@@ -114,13 +114,18 @@ fn main() {
.append_child(&winit::platform::web::WindowExtWebSys::canvas(&window))
.unwrap();
-    let instance = back::Instance::create("gfx-rs quad", 1).expect("Failed to create an instance!");
-    let surface = unsafe {
-        instance
-            .create_surface(&window)
-            .expect("Failed to create a surface!")
-    };
+    let other_thread = std::thread::spawn(move || {
+            let instance = back::Instance::create("gfx-rs quad", 1).expect("Failed to create an instance!");
+            let surface = unsafe {
+ …
```
> Prevent accessing NSView from other threads

- src/backend/vulkan/src/window.rs
Fixes https://github.com/gfx-rs/gfx/issues/3420
I still have to test this on Android. Also I wasn't sure that changing `capabilities` to return with a `Result` thus adding an API change would be the proper way to do this, so I just put some `default`s there.
PR checklist:
> Fix panic on Android app reopen

- Cargo.toml
- examples/quad/main.rs
- src/auxil/renderdoc/Cargo.toml
- src/auxil/renderdoc/src/lib.rs
- src/backend/dx11/Cargo.toml
- src/backend/dx11/src/device.rs
- src/backend/dx12/Cargo.toml
- src/backend/dx12/src/device.rs
- src/backend/dx12/src/lib.rs
- src/backend/vulkan/Cargo.toml
- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/backend/vulkan/src/physical_device.rs
This is a follow up to #3737 to bring RenderDoc frame capture functionality to more backends
This is a first implementation sketch to bring RenderDoc frame capture to more backends. My first goal was to get the internal API right, and figure out if gfx-hal is the right location for this code (maybe auxil would be better suited?)
Fixes #issue
PR checklist:
> renderdoc: backend-agnostic RenderDoc frame capture functionality

- src/backend/vulkan/src/device.rs
- src/backend/vulkan/src/lib.rs
- src/backend/vulkan/src/physical_device.rs
Related issues: #3698 #3761 https://github.com/blaind/xrbevy/issues/1
This PR exposes some Vulkan-backend-specific details needed for interop with other low level APIs. In particular this PR aims to implement a minimum viable API to allow OpenXR integration as a separate crate.
This PR is nowhere complete. I opened it to get some feedback; this is my first PR on a project the size of gfx-hal.
This is the first of multiple PRs needed for OpenXR support in wgpu.
PR checklist:
EDIT: To make things clear, this is another take on #3761. Me and @blaind are working together on this route.
> Low level interop with Vulkan backend

- src/backend/dx12/src/lib.rs
Adds `INDEPENDENT_BLENDING`, `SAMPLE_RATE_SHADING`, and
`FRAGMENT_STORES_ATOMICS` to DX12 backend features
Fixes https://github.com/gfx-rs/wgpu/issues/1405
PR checklist:
> Add features needed for wgpu to dx12 backend

- src/backend/vulkan/src/physical_device.rs
This is required for OpenXR support, when creating a custom device gfx-hal needs to be queried for what raw vulkan extensions to enable for the given gfx-hal features.
PR checklist:
- gfx_backend_vulkan
> Make `enabled_extensions` public in Vulkan backend

- src/backend/gl/src/device.rs
Fixes "cube" example in wgpu-rs for webgl backend on Windows. Will also fix MacOS once https://github.com/gfx-rs/naga/pull/936 gets included.
`delete_shader` is delayed after linking the program. Not doing that seems to be randomly triggering linking issues. I'm not exactly sure under what circumstances it tends to happen, but the fix made it reliable.
The most important fix is about texture filtering for intager textures. ANGLE decides to ignore integer textures if their filtering is kept as default. Instead, it silently substitutes an empty 1px placeholder texture into the shader binding. Forcing the integer textures to NEAREST filtering makes that problem go away.
> Fix WebGL backend for wgpu-rs cube example

- examples/quad/README.md
Hi,
during the development of the direct display path i had removed the input acquisition so that no newer depencencies was needed. Unfortunately i have forgotten to update the example description accordingly, so this will fix it. The code works as intendend, just the description was not updated. Sorry for the incovenience.
Have a good day
> Correction on the description of the direct display behaviour for the quad example

- src/backend/metal/src/device.rs
This facilitates the ability to lock and utilize the underlying Metal device directly.
My need is very similar to the one described in https://github.com/gfx-rs/gfx/issues/3698, in which it was mentioned that functionality like this could be added to the individual backends and that PRs were appreciated.
PR checklist:
> expose the underlying metal device

- src/backend/metal/src/lib.rs
Fixes a crash when GfxManagedMetalLayerDelegate objective-c class is already registered.
I'm sure there's a better solution, let me describe the issue:
* I'm writing an application which hosts audio plugins & uses `iced`, internally it's using `gfx`
* I've an audio plugin I've written which also uses `iced` & uses `gfx` internally too
* When the plugin is loaded into the host, this class name has already been registered and thus registration fails
* Unwrap on registration bits causes a crash
I really don't know what this code is trying to do, but as far as registering the objective-c class decl, I suppose there're a couple of options:
* Declare an unique name every time
* Don't declare the class if it's present
- Issue: plugins may not have the same version of `gfx-backend-metal`, so the …
> Fix crash when GfxManagedMetalLayerDelegate's backing Objective-C class has already been registered

- info/getting_started.md
- wgpu-rs was linking to the archived version;
- rust-tutorials/learn-gfx-hal doesn't exist anymore;
As there is only 1 tutorial link for gfx, I've changed plurals to singular as well.
This is a minor change, does it need an issue?
> Fix broken links.

- src/backend/metal/src/lib.rs
> (macOS/iOS) readWriteTextureSupport is support on macOS 10.13+ / iOS 11.0
