gfx-rs/gfx

examples/deferred/main.rs
examples/terrain/main.rs

to conform with 
https://github.com/rust-lang/rust/commit/1e89bbcb67020892bc0af5af218c35f0fd453fa4

examples rename task_rng to thread_rng

---

examples/cube/main.rs
examples/deferred/main.rs
examples/glutin/main.rs
examples/performance/main.rs
examples/terrain/main.rs
examples/triangle/main.rs
src/device/lib.rs
src/gfx/lib.rs
src/gfx_macros/lib.rs
src/gfx_macros/shader_param.rs
src/gfx_macros/vertex_format.rs
src/gl_device/info.rs
src/gl_device/lib.rs
src/gl_device/shade.rs
src/render/lib.rs
tests/shader_param.rs
tests/shaders_macro.rs
tests/vertex_format.rs

Fixes a lot of breakages to do with changes to C string handling and the switch to unboxed closures. It's WIP because it compiles on the changed files but it doesn't completely fix the repo. 
The problem I'm stuck on is the `extern crate` hack in `gfx_macros`. I can't figure out how to fix it. It looks like the macro parsing rules changed and now you can't use `self`: 
```
<gfx_macros macros>:4:38: 4:42 error: expected identifier, found keyword `self`
<gfx_macros macros>:4 extern crate "gfx" as gfx_ ; pub use self :: gfx_ as gfx ; }
// Repeat ad-nauseum
```

Update to latest Rust nightly (WIP)

---

Cargo.toml
src/device/draw.rs
src/device/lib.rs
src/device/shade.rs
src/device/state.rs
src/device/target.rs
src/device/tex.rs
src/gfx/lib.rs
src/gfx_macros/lib.rs
src/gfx_macros/shader_param.rs
src/gfx_macros/vertex_format.rs
src/gl_device/draw.rs
src/gl_device/info.rs
src/gl_device/lib.rs
src/gl_device/shade.rs
src/gl_device/state.rs
src/gl_device/tex.rs
src/render/batch.rs
src/render/lib.rs
src/render/mesh.rs
src/render/shade.rs

This includes mainly slice notation and renaming to usize/isize. The vertex format macro no longer advises against the use of usize/isize specifically, as the new name alone should deter people from using it for numerical purposes.
To suppress the instability warnings, the "unstable" lint is allowed in all crates.
Oh, and I also restructured `Cargo.toml` to get an overview of the dependencies. I could send a separate pull request for this if that is desired.

Clean-up warnings from alpha changes

---

src/device/Cargo.toml
src/device/lib.rs

Fix to use bitflags crate as described in this commit: https://github.com/rust-lang/rust/commit/34fa70fba5425cbbb96bce783e9fd5c23dd9b471. As a bonus, this let older rust versions to compile gfx-rs.

Use bitflags from crates.io

---

src/device/lib.rs
src/gfx/lib.rs
src/gl_device/lib.rs
src/render/lib.rs

This compiles, but is broken by servo/rust-core-foundation#51

Make CommandBuffer and associated type on Device

---

src/device/gl_device/tex.rs
src/device/tex.rs

Closes #523 
I decided to make BGRA an exception because it has a very limited use case - interoperation with BMP, which is unlikely anything but 8 bit unsigned normalized data.

BGRA8 texture support

---

src/gfx_macros/shader_param.rs
src/gfx_macros/vertex_format.rs

Latest nighties changed closure syntax, so here's a patch!
NOTE: It just covers `gfx_macros` and should pass `build` and `test`.

Fix closure syntax errors.

---

src/gfx_macros/lib.rs
src/gfx_macros/vertex_format.rs

Syntax crate changes: deleted `get` method in InternedString
See PR rust-lang/rust#21505

Fix gfx_macros

---

examples/performance/main.rs
examples/triangle/main.rs
src/gfx/lib.rs
src/render/batch.rs
src/render/lib.rs
src/render/mesh.rs

Fixes #556 
Note: this PR does not change the API.
Please have a good look at it before submission: `Batch` interface is changed. I feel that it is more sound now, since the program and its parameters are handled by the `fill_params` method, while `get_data` is mostly taking care of the mesh.
The batch errors appeared to be useful for the `RefBatch` as well as the new component-based implementation, because `RefBatch` can technically be used with the wrong context.
Also, the `AttributeIndex` type seems to improve read-ability of the code.

Batch implementation for the components

---

examples/deferred/main.rs
src/device/draw.rs
src/device/gl_device/draw.rs
src/device/gl_device/lib.rs
src/device/gl_device/shade.rs
src/device/lib.rs
src/gfx/lib.rs
src/gfx_macros/vertex_format.rs
src/render/batch.rs
src/render/device_ext.rs
src/render/lib.rs
src/render/mesh.rs
src/render/shade.rs
src/render/target.rs
tests/shader_param.rs

This should get us closer to implementing #416. 
Currently referring to the `Resources` type via `Device` is quite ugly, eg. `<<D as Device>::Resources as Resources>::Buffer`, but apparently `D::Resources::Buffer` is going to be implemented in the future, which should make things nicer.

Associated resource type preparations

---

examples/deferred/main.rs
src/device/gl_device/lib.rs
src/device/lib.rs
src/gfx/lib.rs
src/render/lib.rs
src/render/target.rs

I have also constrained `Resources` by additional bounds. This allows for the usage of `#[derive(...)]` when a type is parameterised over `Resources`.

Add resources parameter to types in render::target

---

src/gfx/lib.rs
src/gfx_macros/vertex_format.rs
src/render/batch.rs
src/render/device_ext.rs
src/render/lib.rs
src/render/mesh.rs

Decouple render::mesh from GlDevice

---

src/render/batch.rs
src/render/lib.rs
src/render/shade.rs

More associated resources stuff

---

examples/cube/main.rs
examples/deferred/main.rs
examples/performance/main.rs
examples/terrain/main.rs
src/gfx/lib.rs
src/render/batch.rs
tests/shader_param.rs

Working towards #416.
To truly decouple `render::batch` I need to parametrise `ParamValues`. I am having lifetime difficulties - I will explain elsewhere though.

Parametrise batches over Resources

---

src/device/gl_device/draw.rs
src/device/gl_device/lib.rs
src/device/lib.rs
src/gfx/lib.rs
src/render/device_ext.rs
src/render/lib.rs
tests/vertex_format.rs

Closes #416.
Sorry for flip-flopping on the type parameter of `Renderer` - I previously changed it before `GlResources` was a 'thing'.

Make device::gl_device crate fully self-contained

---

src/gfx_macros/shader_param.rs

Fixes #606, #607 
Allows using generic `gfx::Resources` bounded type for `ShaderParam`, which finalizes our device abstraction. Examples:
```rust
struct MyParam<R: gfx::Resources> {
value: i32,
texture: gfx::TextureParam<R>,
}
struct MyParam2<R2: gfx::Resources> {
value: f32,
_marker: std::marker::PhantomData<R2>,
}
```

Rewrote #[shader_param] expansion using the AST rather than using generic deriving types

---

src/gfx/lib.rs
src/render/batch.rs
src/render/mesh.rs
src/render/shade.rs

Closes #622, #620, #619
This PR doesn't break any API yet, because I was unable to use structures (lifetimes issues #614).
Also, I couldn't make `Context::bind()` to return a reference to the temporal batch. Perhaps, a task for future PRs.

Batch improvements

---

src/device/lib.rs
src/gfx/lib.rs
src/render/batch.rs
src/render/lib.rs
src/render/mesh.rs
src/render/target.rs

(This is a breaking change, please review carefully)
I noticed a couple of things that weren't sound:
1. `RefBatch` carried a publicly accessible `slice`, while not carrying the parameters. The reason for the former was "convenience" (IIRC), the reason for the latter was "just because we can". Hence, this type was neither complete nor minimal.
2. A lot of applications tend to keep a parameter structure together with a `RefBatch`. They are often seen together, and that wasn't convenient to do.
As a solution, I made a `RefCore` batch that only carries minimal (for safety) sealed data, nothing is available to public. The `RefBatch` now is rather open - it carries the core as well as a slice (like it used to) and a parameter structure, all mutable by public.
The idea is - `RefCore` to be used …

Split of referrence batches into Core/non-Core

---

Cargo.toml
src/device/draw.rs
src/device/handle.rs
src/device/mod.rs
src/lib.rs
src/render/batch.rs
src/render/ext/device.rs
src/render/mesh.rs
src/render/mod.rs
src/render/shade.rs

Implements automatic management of the resources. Works just like RAII.
Closes #288, #617 
- there is no such thing as  `factory.delete_something()` any more
- `Renderer` and `Factory` accept all handles by reference to avoid cloning
- `Factory` works with `RawBuffer` type natively now instead of `Buffer<()>`
- need to call `device.after_frame()` after `glfw.swap_buffers()`

Resource tracking and destruction

---

src/device/handle.rs
src/device/mod.rs
src/lib.rs
src/render/mesh.rs
src/render/mod.rs

Fixes #643, requires more PRs in device and examples code.
- Use `create_buffer_index` for index buffer creation

Added index buffer flag

---

src/device/mod.rs
src/lib.rs

Allows user applications to capture `Renderer::as_buffer` if needed.

Added SubmitInfo

---

Cargo.toml

This is consistent with how we use `gfx-rs` from `gfx_device_gl` and other projects.

Switched to use github version of draw_state

---

Cargo.toml
src/lib.rs
src/render/ext/canvas.rs
src/render/ext/mod.rs

Closes #529
Closes #678 
Window Glutin: https://github.com/gfx-rs/gfx_window_glutin/pull/4
Window GLFW: https://github.com/gfx-rs/gfx_window_glfw/pull/2
Examples: https://github.com/gfx-rs/gfx_examples/pull/16
Canvas is a convenient wrapper around a window, device, factory, and a renderer. It allows you to draw stuff with sufficiently less parameters, while still treating `Batch` generically (unlike `Graphics`). It is meant to work with `gfx_window_*` crates for minimal boilerplate initialization. The `present` method will take care of the buffer swapping, renderer reset, and resource cleanups, thus leaving no chance to miss anything.

Canvas - take 2

---

Cargo.toml
src/device/mod.rs
src/render/ext/factory.rs

Also, fixing this error with the previous helper:
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Texture(Invalid data size provided to update the texture, expected size 0)', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:750

Improved texture creation helpers

---

.travis.yml
Cargo.toml
src/device/arc.rs
src/device/draw.rs
src/device/handle.rs
src/device/mod.rs
src/lib.rs
src/render/target.rs

This includes: https://github.com/gfx-rs/gfx-rs/pull/719 (Feel free to cherry-pick this change if you want to include it what that changeset).
This creates a custom Arc type so that we can use `is_unique` in our codebase.
This could be a breaking change as I do not have the full `Arc` for example `Display` is missing.

This adds a custom Arc type for stable reason

---

.travis.yml
Cargo.toml
src/device/draw.rs
src/device/handle.rs
src/device/mod.rs
src/lib.rs
src/render/target.rs

Replaces `rust-1.0` branch.
Closes #716 
Current problems:
- resource cleanup doesn't work
- macros are not ported

[don't merge] Unstable feature

---

Cargo.toml
src/device/attrib.rs
src/device/mod.rs
src/extra/factory.rs
src/lib.rs
src/macros/mod.rs
src/render/mesh.rs
src/render/shade.rs

~~Hold on. I figured the `ShaderParam` implementation needs to handle unused parameters gracefully.~~
Ready to ship!
Closes #676 
Examples: https://github.com/gfx-rs/gfx_examples/pull/23
Macros: https://github.com/gfx-rs/gfx_macros/pull/18
Practically deprecates `gfx_macros`. I've lost a lot of blood writing these syntax extensions, but I'd better have a cleaner (and smaller) code base to deal with, so my vote is to let `gfx_macros` rest in peace.
Current problems (non-critical):
- I had to add `pub` to all the generated structs and members, which prevents these to be declared inside functions
- We have `_r: PhantomData<R>` in each shader parameter structure

Macros return!

---

Cargo.toml
src/device/mod.rs
src/macros/mod.rs
src/render/mod.rs

Also, deriving `Copy` for vertices now. This is actually required to dynamically update them.

Refined buffer updates code

---

Cargo.toml
src/extra/stream.rs

Fixes #749 
Window GLFW: https://github.com/gfx-rs/gfx_window_glfw/pull/7
Window Glutin: https://github.com/gfx-rs/gfx_window_glutin/pull/12
Examples: https://github.com/gfx-rs/gfx_examples/pull/27
This may be a minor breaking change only for people, who stores `OwnedStream` outside of `Stream` abstraction.

Refactored OwnedStream to avoid ICE on present()

---

src/extra/stream.rs
src/render/batch.rs
src/render/mod.rs

Breaking change!
By removing the associated error type the batch trait becomes object-safe. The advantage is, that it allows run-time dispatch of batches, as long as the backing Resources implementation is known at compile-time.
The downside is, of course, that the error type is less generic. This is deemed less useful, as it only conveys information in case of errors and the additional Error::Other enum variant allows for any kind of String to be passed as an error.
As an alternative one could implement an additional trait `DynamicBatch<R>` for all `B: Batch<R>`. This can also be done in user code. However, I think that the possibility to dynamically dispatch batches warrants this change.

Make Batch trait object-safe

---

src/extra/stream.rs
src/render/mod.rs

This allows usage with trait objects, since the modified code only operates on
references to the batches anyway.

Relax sized requirements in API for Batch impls

---

src/render/batch.rs
src/render/shade.rs

Closes #751 
The batch context will be moved into a separate crate (presumably, `gfx_batch`) inside `gfx_scene` project, which needs lightweight batches and can isolate the context unsafety from the user.

[v0.6] Removed batch context

---

Cargo.toml
src/device/draw.rs
src/device/mod.rs
src/device/tex.rs
src/extra/factory.rs
src/extra/stream.rs
src/lib.rs
src/macros/mod.rs
src/render/batch.rs
src/render/mod.rs
src/render/shade.rs
src/render/target.rs

Closes #745 
Has all the changes from 0.6 branch, merged with upstream.
GL device: https://github.com/gfx-rs/gfx_device_gl/pull/42
Glutin window: https://github.com/gfx-rs/gfx_window_glutin/pull/13
GLFW window: https://github.com/gfx-rs/gfx_window_glfw/pull/8
Examples: https://github.com/gfx-rs/gfx_examples/pull/30
Major changes:
- now using crates.io internally for dependencies. Users are encouraged to also use it, we may not guarantee any stability in the Git tree.
- batch context is removed as well as all the relevant batch types. Please use `batch::Core` or `batch::Full`.
- texture kinds enum is totally [changed](https://github.com/kvark/gfx-rs/commit/5f97904cef73432c56c54265f16c57128041ec00)
- `Renderer::update_*` calls now error out instead of panicking
- `gfx_device_gl::Factory` …

[wip] Version 0.6

---

src/backend/gl/src/info.rs

Doesn't actually check if there is such an extension at all, so typos aren't caught.

Fix typo on extension checking

---

src/backend/gl/src/lib.rs
src/core/src/device/dummy.rs
src/core/src/device/handle.rs
src/core/src/device/mod.rs
src/core/src/lib.rs
tests/handle.rs

Solves #688
This exposes the command fences to the developer. Via the `DeviceFence` trait. Fences are managed much like other resources and are added as an associated type. This api adds two abilities, the fence can block the device server by using `fenced_submit`. Or the user may synchronize in the client cpu by using  `fence_wait`.

Add fence suppot

---

src/core/src/device/command.rs
src/core/src/render/mod.rs
src/core/src/render/texture_cache.rs

This creates a texture cache. A texture cache is an LRU that manages the GL_ACTIVE_TEXTURES, it will bind textures until there is no free ACTIVE_TEXTURES, then use the reuse the textures based on their age. older textures are evicted first.

Added Texture cache to gfx

---

src/backend/gl/src/factory.rs
src/core/src/device/mod.rs
src/core/src/device/program.rs
src/core/src/extra/factory.rs

This is a breaking change.
This adds a program-builder for creation of shader programs. This exists to avoid new parameters each time we add support for new features that may require new options when calling create_program.

Add program::Builder

---

src/core/src/device/draw.rs

This is actually unstable but [there's a bug][bug] in the compiler allowing it
to be used. Good news is that these functions are available stable elsewhere!
[bug]: https://github.com/rust-lang/rust/issues/28075

Avoid using the std::intrinsics module

---

src/core/src/macros/mod.rs

Layout of Rust struct without #[repr(*)] is not defined (yet?)

gfx_vertex! potential UB fix

---

src/core/src/device/mapping.rs

Remove some trailing spaces from the end of trait bounds lists on fns

Fix code which caused E0309 warnings, remove trailing commas from trait bounds lists

---

src/backend/gl/Cargo.toml
src/core/Cargo.toml
src/window/glfw/Cargo.toml

First set of cherry-picked changes to backport onto 0.8.
Includes:
- https://github.com/gfx-rs/gfx/pull/812
- https://github.com/gfx-rs/gfx/pull/818

Publish 0.8 w/ the libc fix

---

Cargo.toml
examples/mipmap/main.rs
examples/mipmap/shader/120.glslf
examples/mipmap/shader/120.glslv
src/backend/gl/src/tex.rs

Fixes maximum mipmap level passed to ``set_mipmap_range()`` to be one less than number of mipmaps and adds an example to show that things still work correctly after that.

Fix maximum mipmap level

---

src/backend/gl/Cargo.toml
src/backend/gl/src/factory.rs
src/backend/gl/src/lib.rs
src/window/glutin/Cargo.toml
src/window/glutin/src/lib.rs

This patch replaces all occurrences of ``libc::c_void`` with ``std::os::raw::c_void``. This type is required for parts that interact with gfx_gl (where it comes from gl_generator), and the rest was changed to the same type for consistency.

Remove libc dependency

---

src/backend/gl/src/info.rs

glGetString(GL_EXTENSIONS) is obsolete since OpenGL 3.0, and not
support for it was removed in 3.1.
On Mesa, this can be tested by setting MESA_GL_VERSION_OVERRIDE to
different values. Before this patch, both 3.0FC and 3.1 fail, while 3.0
does not, as expected.
Fixes #778

Use glGetStringi to get extensions on OpenGL 3.0+

---

src/backend/gl/src/shade.rs

OpenGL reports built-in uniforms alongside user defined ones, but they
can not be linked with user data and we can just skip over them.
All built-in uniforms have names that start with reserved prefix OpenGL,
which can be used to distinguish them from user-defined ones.
Fixes #840

Ignore built-in uniforms.

---

src/core/src/format.rs

the doc comment says it should return the number of _bits_, but std::mem::size_of returns the number of _bytes_

fix get_bit_size

---

src/backend/gl/src/info.rs

Just one was still remaining .
This should close https://github.com/gfx-rs/gfx/issues/844

Additional ARM fix

---

examples/blend/main.rs
examples/deferred/main.rs
examples/flowmap/main.rs
examples/instancing/main.rs
examples/mipmap/main.rs
examples/shadow/main.rs
examples/skybox/main.rs
examples/terrain/main.rs
examples/triangle/main.rs
examples/ubo_tilemap/main.rs
src/backend/gl/src/lib.rs
src/core/src/format.rs
src/window/glfw/Cargo.toml
src/window/glfw/src/lib.rs
src/window/glutin/Cargo.toml
src/window/glutin/src/lib.rs

Breaking change.
Fixes #872 , fixes #858 
Removes the default parameters of glutin window `init()` for them being deprecated in the next Rust version.
Switches our examples to use Srgb8.
Switches the windowing backends to depend on gfx_core only.
Changes GL's `create_main_targets` to operate on raw data.

Gamma correctness

---

examples/mipmap/main.rs

R3_G3_B2 is obsolete and is causing problems for DX11 backend.
Fixes #892.

Use R8_G8_B8_A8 format for textures.

---

Cargo.toml
src/render/src/lib.rs
src/render/src/macros/pso.rs
src/render/src/pso/buffer.rs
src/render/src/pso/resource.rs
src/render/src/pso/target.rs
tests/macros.rs

This implements a solid part of #853 
It will allow some stuff to be loaded at run-time without any prior compile-time knowledge, like:
- your vertex layout
- format of the textures, like you don't know if your texture is RGBA or RGB or something else
- output target format, like you may want to configure the precision and sRGB properties
- blending

Raw PSO components

---

Cargo.toml
src/render/Cargo.toml
src/render/src/encoder.rs
src/window/glfw/Cargo.toml

Closes https://github.com/gfx-rs/gfx/issues/911
- Bumped gfx_app to 0.1.1
- Bumped gfx to 0.10.1
- Bumped gfx_window_glfw to 0.9.0

Fixed `Encoder::update_texture`

---

examples/blend/main.rs
examples/cube/main.rs
examples/deferred/main.rs
examples/flowmap/main.rs
examples/skybox/main.rs
src/render/src/lib.rs
src/render/src/macros/pso.rs
src/render/src/pso/bundle.rs
src/render/src/pso/mod.rs

Makes it opt-in without allow(dead_code), also opens way up for multiple
implementations.
Fixes #925.

Move Bundle out of pipeline macro.

---

src/core/src/tex.rs

`get_level_dimensions` keeps unused dims at `0`

---

examples/triangle/main.rs

This dependency is convenient for re-using code between example. However, it makes it also harder for a user to follow and figure out, what they actually have to implement themselves when using gfx.
Raised in #922.

Remove gfx_app dependency from triangle example

---

src/window/glutin/src/lib.rs

Hello,
I've had troubles with GFX and the resolution on my retina display. I found out we needed to multiply the results of a function called hidpi_factor from Glutin Window.
Cheers

Multiplied hidpi_factor on window glutin to get correct resolution on retina displays

---

src/core/Cargo.toml
src/core/src/lib.rs

This makes `amethyst_renderer` much less verbose and shouldn't really hurt here.

Added Any to gfx::Resources

---

Cargo.toml
src/window/dxgi/src/window.rs

Actually, it worked well time ago and became official in Rust stable since 1.8.0.

Support i686-windows-msvc rustc target

---

src/backend/dx11/Cargo.toml
src/backend/dx11/src/command.rs
src/backend/dx11/src/factory.rs
src/backend/dx11/src/mirror.rs
src/backend/gl/src/shade.rs
src/core/src/shade.rs

Basic depth output handling

---

Cargo.toml

Simplify target dependencies

---

.travis.yml
Cargo.toml
appveyor.yml
src/backend/gl/src/info.rs
src/core/src/factory.rs
src/window/glfw/src/lib.rs
src/window/glutin/src/lib.rs
src/window/sdl/src/lib.rs

Changes to appveyor and travis scripts to include testing of submodules.
Changes to appveyor script to only download and install mingw when targetting mingw toolchain.
Code example moved from factory documentation into gfx_window_glutin.
Removed an outdated test, added no_run to some tests to prevent them from failing on CI builds.
fixes #961

Add CI tests for subpackages

---

src/backend/gl/src/shade.rs

This PR fixes an issue when `gfx` was not working properly with `gl` backend if you are using 120-140 versions of shaders.
Also this fixes `index` variable redefinition in `if name.starts_with("gl_FragData") {` branch.

Special index for gl_FragColor for GLSL 120 to 140 shaders

---

Cargo.toml
examples/cube/main.rs
examples/cube/shader/cube.hlsl
examples/cube/shader/cube_100_es.glslf
examples/cube/shader/cube_100_es.glslv
examples/cube/shader/cube_120.glslv
examples/cube/shader/cube_150.glslv
examples/shadow/main.rs
src/backend/gl/src/info.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/state.rs
src/backend/gl/src/tex.rs
src/lib.rs
src/shade.rs
src/window/glutin/Cargo.toml

Closes #160 (basic support, more fixes might be needed later on)
Note: a side effect of this PR is a requirement of GL-3.2 for the example launcher. Glutin needs to be augmented in order to make this more flexible. GFX itself can still work with GL-2.1 though.
Image from @ozkriff:

Basic Android / GLES support

---

src/core/src/factory.rs
src/core/src/format.rs
src/core/src/lib.rs
src/render/src/encoder.rs
src/render/src/factory.rs
src/render/src/lib.rs
src/render/src/macros/structure.rs

This makes structures defined with gfx_vertex_struct! and
gfx_constant_struct! also marked as Pod which is not entirely
correct. These structures should only contain Pod types, but there is no
way to guarantee that.
Fixes #974.

Make cast_slice() work only on Pod types.

---

Cargo.toml
examples/cube/main.rs
examples/cube/shader/cube_frag.metal
examples/cube/shader/cube_vertex.metal
examples/flowmap/main.rs
examples/flowmap/shader/flowmap_frag.metal
examples/flowmap/shader/flowmap_vertex.metal
examples/shadow/main.rs
examples/shadow/shader/forward_frag.metal
examples/shadow/shader/forward_vertex.metal
examples/shadow/shader/shadow_frag.metal
examples/shadow/shader/shadow_vertex.metal
examples/terrain/main.rs
examples/terrain/shader/terrain_frag.metal
examples/terrain/shader/terrain_vertex.metal
src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/factory.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/map.rs
src/backend/metal/src/mirror.rs
src/core/src/pso.rs
src/lib.rs
src/shade.rs
src/window/metal/Cargo.toml
src/window/metal/src/lib.rs

* `gfx_window_metal`
* Metal backend in `gfx_app`
* PSO
* Reflection
* Texture/Samplers
* Command buffer/encoder
* Depth/stencil things
* Bunch of factory methods for updating data etc.
* Instancing
* Fixing memory leaks – the thing i'm looking forward to the least (i'm saving `.retain()`, `.release()` for last)
Probably bunch of other stuff i missed mentioning, but should crop up eventually

[WIP] Metal Backend

---

examples/performance/main.rs

Changed duration_to_f64 to duration_to_ms, which fixes the displayed time for gfx option.

Fix incorrect time in performance example

---

.travis.yml
appveyor.yml
src/backend/vulkan/src/lib.rs
src/lib.rs
src/window/vulkan/Cargo.toml
src/window/vulkan/src/lib.rs

Correctly locate the vulkan dynamic library on windows, use winit for window handling and implement surface creation.
NOT tested on an unix system so far with xcb.
Setting the correct `"VK_KHR_*_surface` extensions for each platform is left as future work for the moment.

Vulkan: Some groundwork for windows vulkan support

---

src/backend/dx11/src/data.rs
src/backend/gl/src/tex.rs
src/backend/metal/src/map.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/data.rs
src/backend/vulkan/src/lib.rs
src/core/src/format.rs
src/lib.rs
src/window/vulkan/src/lib.rs

The backend will now load the required extensions for each platform for the surface creation. Additionally improved the swapchain creation to address serveral validation layer errors (checking for support of formats, capabilities, etc.).
Additionally switched to the (more common?) BGRA8 color format for the swapchain images.
I assume we need to shift some responsibilities for the the swapchain creation to the application to select its prefered formats and settings depending on the capabilities offered by the GPU.
(e.g. my system doesn't support RGBA8 for swapchains nor D24_S8 as depth-stencil format)

Vulkan: Working on swapchain creation

---

src/backend/gl/src/lib.rs

Fixes layered rendering (`GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS`) using @kvark proposition.
Probably results in more redundant state changes ? (#978, #558)

Detach unused color attachments

---

src/backend/gl/src/shade.rs

Where `n` is in the range of `0..core::MAX_COLOR_TARGETS` (4). Done before linking, safe [even if outputs are not present](https://www.opengl.org/wiki/Fragment_Shader#Output_buffers):
> Note that it is perfectly legal to assign names to fragment colors that are not mentioned in the fragment shader. The linking process will only use the names that are actually mentioned in the fragment shader. Because of that, it is also perfectly legal to assign multiple names to the same number; this is only an error if you attempt to link a program that uses both names.

[GL] bind output "Target{n}" to n if  isn't available

---

src/window/sdl/Cargo.toml

`cargo build` and `cargo clippy` still complete without warnings.

Update sdl2 dependency in gfk_window_sdl

---

src/window/glutin/Cargo.toml
src/window/glutin/src/lib.rs

I would like to be able to combine Piston and gfx in a more modular fashion. Currently, there are 2 options to create and initialise a Glutin window with gfx:
1. Use PistonWindow<GlutinWindow>. This creates the window and initialises gfx. The version of gfx is the same one that ships with Piston (potentially outdated).
2. Use gfx_window_glutin. This creates the window and initialises gfx. There is no way to wrap this window in a way Piston understands ([GlutinWindow](https://docs.rs/pistoncore-glutin_window/0.30.0/glutin_window/struct.GlutinWindow.html))
Each library is taking responsibility of creating the window from a builder. I would like to split the responsibility of creating the window, from initialising gfx.
This is a simple overloaded API. Instead of using a passed builder to …

Implement init_existing and init_existing_raw for gfx_window_glutin

---

src/render/src/macros/mod.rs
src/render/src/macros/pso.rs
src/render/src/pso/buffer.rs
src/render/src/pso/resource.rs
src/render/src/pso/target.rs

The more important thing here is the first commit, which fixes the documentation formatting. Before:
After:

A few formatting fixes

---

src/backend/gl/src/lib.rs

This lets the vertex shader write to gl_PointSize, so that point primitives can be rendered as different sizes.
The flag is enabled during initialization of the OpenGL backend.

Enable PROGRAM_POINT_SIZE in OpenGL backend

---

src/render/src/macros/pso.rs

`use $crate;` is not allowed due to recent restrictions and `use super::*;` won't import the gfx crate. (allowed in future but feature gated https://github.com/rust-lang/rfcs/pull/1560)
Closes #1070

Fix pipeline definition macro

---

Cargo.toml
src/window/glutin/Cargo.toml

Glutin 0.7 ported the library to Winit, but otherwise appeared to be a drop-in replacement for 0.6.

Bump glutin version to from 0.6 to 0.7

---

src/core/src/mapping.rs

This isn't caught by the current stable compiler, but to me it looks like it was always wrong (the impl has fewer bounds on T than the struct) and the current nightly compiler errors out without this change.

Add missing lifetime bound in DerefMut impl for RWer

---

src/backend/gl/src/command.rs
src/backend/gl/src/lib.rs

gfx_device_gl uses single VAO, which is binded once during device initialization. This causes problems when gfx is used with other libraries and middlewares, which can use their own VAO.
This PR adds a command which binds VAO owned by gfx, before binding VBO and calling VertexAttribPointer.

[GL] Make sure VAO is binded before calling VertexAttribPointer

---

.travis.yml
Cargo.toml
examples/blend/main.rs
examples/cube/main.rs
examples/deferred/main.rs
examples/flowmap/main.rs
examples/instancing/main.rs
examples/mipmap/main.rs
examples/particle/main.rs
examples/shadow/main.rs
examples/skybox/main.rs
examples/terrain/main.rs
examples/terrain_tessellated/main.rs
examples/ubo_tilemap/main.rs
src/backend/metal/Cargo.toml
src/backend/metal/src/factory.rs
src/backend/metal/src/lib.rs
src/lib.rs
src/render/Cargo.toml
src/render/src/encoder.rs
src/window/dxgi/Cargo.toml
src/window/dxgi/src/lib.rs
src/window/metal/Cargo.toml
src/window/metal/src/lib.rs
src/window/vulkan/src/lib.rs

Fixes #907
This PR simplifies the internals of gfx_app a bit, removing `Wrap*` typedefs as well as `Application*` traits.
It also properly routes the events to the application, making the whole API useful now.
The examples are not only updated, but also the controls are re-implemented for the `deferred`, `ubo_tilemap`, and `blend`.
A follow-up task #1104 has been created to make it even better.
Example of default backend with auto window:
```rust
use gfx_app::Application;
App::launch_simple("MyTitle");
```
Example of default backend with manual window:
```rust
use gfx_app::Application;
let wb = winit::WindowBuilder::new().with_title("MyTitle");
App::launch_default(wb);
```
Example of forced GL3 backend:
```rust
let wb = winit::WindowBuilder::new().with_title("MyTitle"); …
```

App launcher upgrade

---

examples/instancing/main.rs
src/backend/dx11/src/data.rs
src/backend/dx11/src/factory.rs
src/backend/dx11/src/lib.rs
src/core/src/buffer.rs
src/core/src/mapping.rs
src/core/src/texture.rs

Fixes https://github.com/gfx-rs/gfx/issues/1098 . Proper merged version.
Improper version here ; https://github.com/gfx-rs/gfx/pull/1105 .

DX11 buffer mapping (merged)

---

src/render/src/factory.rs
src/render/src/pso/mod.rs

We used to `impl<S: Error> Error for PipelineStateError` while actually using `S = String` and `S = &str`, which don't satisfy the `Error` bound, making the whole thing a bit useless. This PR fixes that.

Fix for the PSO error bounds

---

src/core/src/factory.rs
src/core/src/mapping.rs
src/render/src/pso/mod.rs
src/shade.rs

Exposes more sub-errors through the `Error::cause` method, and imps the `Error` trait on more Error structs.

Error improvements.

---

src/render/src/slice.rs

A simple method to split a slice in two in a similar way as [std::slice::split_at](https://doc.rust-lang.org/std/primitive.slice.html#method.split_at). This is useful when grouping the geometry for several draw calls in the same buffer.

Add a gfx::Slice::split_at method.

---

src/backend/gl/src/shade.rs
src/core/src/shade.rs
src/render/src/shade.rs

Makes the CreateProgramError type a proper struct which impls the `Error` trait. This means that you can now get the cause of a `ProgramError::Link` error.

Make the CreateProgramError a proper struct

---

src/backend/metal/src/lib.rs

Sadly, Metal is not supported on my old Mac Mini 2010.
If someone got a newer one, please try running our examples with "--feature metal" flag. It would be nice to publish that Metal backend at last.

[Metal] Better creation error tracking

---

src/backend/gl/src/shade.rs

This fixes shader reflection on some OpenGL drivers when long
uniform names or nested structs are used in a shader. On conforming
drivers it has no effect.

Work around nonconforming OpenGL drivers returning the length of a uniform name without the trailing null byte.

---

src/backend/dx11/src/factory.rs
src/backend/gl/src/command.rs
src/backend/metal/src/map.rs
src/backend/vulkan/src/data.rs
src/core/src/lib.rs
src/render/src/slice.rs

Fixes #1152 by adding additional variants to `Primitive`.

Add primitives with adjacency information

---

Cargo.toml
examples/trianglell/main.rs
src/backend/dx12ll/Cargo.toml
src/backend/dx12ll/src/data.rs
src/backend/dx12ll/src/lib.rs
src/backend/vulkanll/Cargo.toml
src/backend/vulkanll/src/data.rs
src/backend/vulkanll/src/lib.rs
src/corell/Cargo.toml
src/corell/src/command.rs
src/corell/src/factory.rs
src/corell/src/format.rs
src/corell/src/lib.rs
src/corell/src/memory.rs

The next gen APIs (Vulkan and D3D12) offer an low level interface of the GPU in comparison to older APIs like OpenGL or D3D11. To avoid overhead due to high level abstraction we want to investigate the implementation of a thin wrapper above the mentioned low level APIs to address https://github.com/gfx-rs/gfx/issues/1102.
This PR creates a new low level core API `corell` and two backend implementations for the low level core. corell is heavily based on the vulkan API and shares a lot of concepts like `Instance`, `Surface`, etc., but tries to also take d3d12 into account. In future steps further abstractions could be considered to reduce the amount of setup code.
Planned coverage for this PR:
Note: Also includes some dummy types for other objects.
`format` and `memory` are mainly copied …

 Initial groundwork for a low level api

---

src/render/Cargo.toml

That way gfx will show up here: https://crates.io/categories/rendering::graphics-api.

Add the rendering::graphics-api category

---

examples/trianglell/main.rs

OSX doesn't support our d3d12 or vulkan backend, so in this case the example will just do nothing.

Fix OSX compilation of trianglell example 

---

src/backend/metal/Cargo.toml
src/backend/metal/src/factory.rs
src/backend/metal/src/lib.rs
src/core/src/lib.rs
src/window/metal/Cargo.toml

Added Metal shader library support

---

src/render/src/macros/pso.rs
src/render/src/macros/structure.rs

This pull request fixes issue #1176. Tested it successfully with a dummy crate on my machine.

Allow missing docs for all macro-generated structs

---

src/render/src/pso/buffer.rs
src/render/src/pso/mod.rs

Example:
> thread 'main' panicked at 'Could not create PSO for `DrawShaded`!: DescriptorInit(ConstantBuffer("u_PointLights", Some(Offset { name: "plight[1].center", shader_offset: 48, code_offset: 44 })))'
cc @ebkalderon

Better PSO element errors

---

.travis.yml
Cargo.toml
scripts/travis-install-sdl2.sh
src/window/sdl/src/lib.rs

Installs SDL2 from the formerly used PPA into $HOME/deps, then caches it.
Readds cargo test -p  since cargo test --all still does not test local dependencies.
Trivial fix in gfx_window_sdl doctest.

#1106 CI test SDL window fix

---

Cargo.toml

Existing dependency is on 0.6, which spews a bunch of warnings. This is annoying, so let's bump the dependecy to the latest version. 
Tested: examples.

bump image dependency version

---

src/render/src/factory.rs

A simple addition to the Factory.
While it was easy to create an index buffer separately before (in terms of required boilerplate) using the ToIndexBuffer trait, it was quite hard to find out that is is possible to do at all.

Implement FactoryExt::create_index_buffer.

---

src/backend/dx11/src/execute.rs
src/backend/dx11/src/factory.rs
src/backend/dx11/src/lib.rs
src/backend/metal/src/factory.rs

For #1130 (tiny little potential contribution).
I lack the capacity to test this as I don't have a Windows environment.

Rename `to_resource` to `as_resource`

---

src/render/src/macros/mod.rs

This is a draft. Currently looking for feedback on current information and possible improvements.
Closes #1135

Improved gfx_defines documentation

---

src/lib.rs
src/window/dxgi/src/lib.rs

Closes #1156 
I fixed the minimization crash by ignoring `DXGI_STATUS_OCCLUDED`, so the window will be resized to (0, 0). 
I called `update_views` in gfx_app and I'm not sure if `device.clear_state()` is necessary.

[WIP] [DX11] fix crash when window is minimized

---

src/backend/dx11/src/command.rs
src/backend/dx11/src/execute.rs
src/backend/gl/src/command.rs
src/backend/gl/src/factory.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/tex.rs
src/backend/metal/src/command.rs
src/backend/vulkan/src/command.rs
src/core/src/command.rs
src/core/src/dummy.rs
src/core/src/handle.rs
src/core/src/texture.rs
src/render/src/encoder.rs

Implements texture staging by providing `copy_buffer_to_texture` and `copy_texture_to_buffer` methods.
Would close #1181 
@kvark: @Androcas and me will move on to the D3D11 implementation if you like the OpenGL one, I'm not sure if we want to add another example for staging or modify an existing one?

[WIP] Implement texture staging

---

src/backend/vulkanll/Cargo.toml
src/backend/vulkanll/src/command.rs
src/backend/vulkanll/src/factory.rs

Once a error occurs during pipeline creation we now recover all piplines, which were sucessfully built, instead of returning an error for all of them.

[ll] vulkan: Update to latest ash and fix graphics pipeline creation

---

src/render/src/encoder.rs

Allows to actually use `Device::fenced_submit`.

Add Encoder::fenced_flush_no_reset

---

examples/trianglell/main.rs
src/backend/vulkanll/src/factory.rs
src/corell/src/factory.rs

Add explicit resource destruction as proposed in #1216.
Implemented the new factory methods for the vulkan backend.
I went with a resource consuming interface (takes ownership of the resource) as I liked the concept of the factory giving ownership to the resource on creationg and taking it away on destruction.
```Rust
fn destroy_*(&mut self, R::Resource);
```

[ll] Add explicit resource destruction

---

CHANGELOG.md

Since all changelogs go new to old and it's common to link the issues, I thought why not :)
And @kvark mentioned on reddit he would welcome a PR in this regard.

Change changelog order into new to old and add links for mentioned issues

---

src/backend/gl/src/command.rs

Adds a new public field `display_fb` to the `CommandBuffer` structure in the `gfx_device_gl` backend. If not changed by the user it will have the value 0. This allows to use an existing framebuffer object as the drawing destination instead of the Framebuffer with name 0. Useful on iOS/tvOS where no default frame buffer exists and drawing can only occur on system provided renderbuffers.
I expect this be used with the `create_main_targets_raw` function to create the default color and depth targets. These will automatically use the framebuffer object given in the `display_fb` field.
If you are happy with this I would like to do more pull requests for better iOS support (e.g. only use supported OpenGL ES 3.0 features).

gfx_device_gl: Add a new field allowing to use an externally managed framebuffer object as the display target.

---

src/backend/gl/src/command.rs
src/core/src/pso.rs

Like #1220 except based on the right starting point.  Sorry.

Adding more caching to GL backend.

---

.travis.yml
CHANGELOG.md
Cargo.toml
appveyor.yml
src/backend/dx11/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml
src/core/Cargo.toml
src/core/src/buffer.rs
src/core/src/command.rs
src/core/src/dummy.rs
src/core/src/factory.rs
src/core/src/format.rs
src/core/src/handle.rs
src/core/src/lib.rs
src/core/src/mapping.rs
src/core/src/memory.rs
src/core/src/pso.rs
src/core/src/shade.rs
src/core/src/texture.rs
src/render/Cargo.toml
src/render/src/encoder.rs
src/render/src/lib.rs
src/window/dxgi/Cargo.toml
src/window/glfw/Cargo.toml
src/window/glutin/Cargo.toml
src/window/metal/Cargo.toml
src/window/sdl/Cargo.toml
src/window/vulkan/Cargo.toml

> Note: This is the season finale for our two-part series. Prepare for `gfx` 0.15! :tada:
* Add `serialize` feature to `gfx_app` and `gfx_core`, courtesy of `draw_state` 0.7.0 (fixes #1229)
* Added API docs to `Copy{Buffer,BufferTexture,TextureBuffer}Result` types
* Minor reformatting and alphabetical ordering of `#[derive]` statements
* Switch one manual `Eq` implementation to `#[derive]` instead
* Encoder now uses `#[derive(Debug)]`
* Bumped minor version numbers of affected crates (`gfx` is now up to 0.15.0)
* Updated several third-party dependencies
* Build against Rust 1.16.0 on AppVeyor
* Expose `CopyError` and `Copy{Buffer,BufferTexture,TextureBuffer}Result` types from `gfx`
CC @kvark

Add optional serialization support, version bumps, formatting fixes

---

src/render/src/slice.rs

* Derive `Hash` and `Eq` traits for `Slice` and `IndexBuffer`.

Derive Hash and Eq for Slice and IndexBuffer

---

README.md

- Update build dependency information from "gfx = 0.14" to "gfx = 0.15"
- Fixes "Link to arcsynthesis on OpenGL state machine is dead" (#1213)
- Since the old link is dead and I can't find it in the Wayback Machine Archives my guess is just based on the old URL (gltut[orial]/Basics/Intro What is OpenGL)

Update README.md to v0.15, fix broken link (#1213)

---

examples/trianglell/main.rs
src/backend/vulkanll/src/factory.rs
src/backend/vulkanll/src/lib.rs
src/backend/vulkanll/src/native.rs
src/corell/src/factory.rs
src/corell/src/lib.rs
src/corell/src/queue.rs

First steps regarding synchronization support based on the vulkan API.
It should be possible to emulate Semaphore and Fence in dx12 using ID3D12Fence.
Additionally, extended the queue submit to allow fence and semaphore control, and batch multiple submits.
Following PR will address destruction, reset and further control options for image frame acquisition. Aiming to remove all remaining validation errors left in the trianglell example.

[ll] Add semaphore and fence sync primitives

---

examples/trianglell/main.rs
src/backend/vulkanll/src/factory.rs
src/backend/vulkanll/src/lib.rs
src/corell/src/factory.rs
src/corell/src/lib.rs
src/corell/src/queue.rs

Improve synchronization for submission and frame acquisition.
Fix issue on vulkan backend that queue priority vec only lifes on the stack and can get overwritten.
Current synchronization strategy in the example is pretty bad as it blocks forces a pipeline flush each frame.
Compute shaders next!

[ll] More on sync and minimize errors

---

Cargo.toml
src/render/src/factory.rs
src/render/src/shade.rs

* Add `ProgramError::Geometry` enum variant.
* Add `create_shader_set_geometry` method to `FactoryExt`.
* Clarified `create_shader_set_tessellation` doc comments.
* Corrected usage of "pixel shader" to the correct shader types in `ProgramError` doc comments.
CC @kvark @msiglreith

Add ProgramError::Geometry enum variant

---

src/backend/vulkanll/src/factory.rs
src/backend/vulkanll/src/lib.rs
src/backend/vulkanll/src/native.rs
src/corell/src/factory.rs
src/corell/src/lib.rs

Constant buffer views (Cbv) are a concept introduced by dx12, which uses views for everything now.
Cbvs needs to be explicitly created in contrast to e.g vertex buffer views.
In vulkan these are represented as the underlying buffer and a range.

[ll] Add Constant Buffer Views

---

Cargo.toml
examples/blend/main.rs
examples/deferred/main.rs
examples/gamma/main.rs
examples/performance/main.rs
examples/shadow/main.rs
examples/triangle/main.rs
examples/trianglell/main.rs
examples/ubo_tilemap/main.rs
src/backend/dx12ll/Cargo.toml
src/backend/vulkan/Cargo.toml
src/backend/vulkanll/Cargo.toml
src/lib.rs
src/window/dxgi/Cargo.toml
src/window/dxgi/src/lib.rs
src/window/glutin/Cargo.toml
src/window/glutin/src/lib.rs
src/window/metal/Cargo.toml
src/window/metal/src/lib.rs
src/window/vulkan/Cargo.toml
src/window/vulkan/src/lib.rs

This will require gfx_window_glutin to be published.
I'm on linux and didn't get a chance to test the trianglell example.

Update to glutin 0.8, Winit 0.6

---

src/core/Cargo.toml
src/core/src/command.rs
src/core/src/handle.rs
src/core/src/lib.rs
src/core/src/pso.rs
src/core/src/shade.rs
src/render/Cargo.toml
src/render/src/lib.rs
src/render/src/macros/pso.rs
src/render/src/macros/structure.rs
src/render/src/pso/buffer.rs
src/render/src/pso/mod.rs
src/render/src/pso/resource.rs
src/render/src/pso/target.rs
tests/macros.rs

* Derived `Clone`, `Copy`, `Debug`, `Eq`, `Hash`, and/or `PartialEq` for a bunch of structs, mostly within the `gfx::pso::*` module.
* Updated the `gfx_pipeline!` macro to automatically derive `Clone`, `Debug`, and `PartialEq` for the resulting `Data`, `Meta`, and `Init` structs.
* Updated the `gfx_impl_struct_meta!` macro to automatically derive `Clone`, `Copy`, `Debug`, and `PartialEq` for the resulting struct.
* Minor reformatting.
* Eliminated TODOs for manually implementing `Eq`, `Hash`, and `PartialEq` on several structs which contain `PhantomData<T>` as data members.
CC @kvark @msiglreith

Derive convenience traits for PSO components and a few other types

---

src/backend/gl/src/command.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/native.rs
src/backend/vulkan/src/lib.rs
src/core/src/lib.rs
src/window/glutin/src/lib.rs
src/window/vulkan/src/lib.rs

- Implement device creation part for GL
- Move SwapChain to the window crate because OpenGL requires the glutin window for swapping the buffers on present
Command buffer submission on GL is not optimal atm due to cloning the internal data and cmd buffers.
I'll rebase the `ll` branch after the PR on the latest master to avoid conflicts for the future merge.
Next task would be the d3d11 and d3d12 backend, updating the `gfx_app` and some smaller changes to `render`. Hopefully we can reach an mergable state then.
Unfortunately I don't have access to an OS X machine so I can't take care of the Metal backend.

[ll] Core update (GL) [03/..]

---

src/render/src/pso/buffer.rs
src/render/src/pso/target.rs

The new `ToInstanceRate` trait allows the same PSO declaration and shader to be used with both instanced and non-instanced attribute. There appears to be a real use case for it - sometimes we know the color (for example) on a per-object basis, sometimes it's per-vertex.

Run-time specified instance rate

---

src/backend/metal/src/map.rs
src/core/src/format.rs
src/lib.rs
src/window/metal/src/lib.rs

Two issues were causing distored colors when using the Metal backend:
1. RGBA8 was mapped to BGRA8 when rendering, to accomodate CAMetalLayer's requirement that it only use BGRA ordering for 8-bit backbuffer formats. This however created issues when handling textures, so instead we expose this difference to the user. It should only require them to choose a backbuffer format based on the backend used, which is already needed for Vulkan.
2. CAMetalLayer appears to interpret the buffer as sRGB whether you want it to or not. To accomodate this we use the backbuffer color format (B8_G8_R8_A8, Srgb) in gfx_app when using Metal, so writes to the backbuffer are transformed properly. This may actually be an error on our side, because we do some hacky things with regards to backbuffer management, …

Fix Metal backend's color handling

---

src/render/src/macros/pso.rs
src/render/src/macros/structure.rs

This avoids clash when you define your own `Result` type. e.g.
```rust
gfx_defines! {
vertex Vertex { /* ... */ }
pipeline pipe { /* ... */ }
}
pub type Result<T> = ::std::result::Result<T, MyError>;
```
Will cause a compile failure:
```
error[E0244]: wrong number of type arguments: expected 1, found 2
--> src/file.rs:12:1
|
12 | gfx_defines! {
| ^ expected 1 type argument
|
= note: this error originates in a macro outside of the current crate
error: aborting due to previous error
```

Use full namespaces in macro-generated fns which return ::std types

---

src/render/src/lib.rs
src/render/src/macros/pso.rs
src/render/src/pso/buffer.rs
src/render/src/pso/mod.rs

* Implement `gfx::pso::buffer::RawGlobal`.
* Add global link compatibility error into `gfx::pso::InitError` instead of `()`.
* Perform format compatibility checking for typed `Global`s.
* Initial implementation of `TODO` described in `match_attribute()` function.
CC @kvark @msiglreith

Implement gfx::pso::buffer::RawGlobal

---

src/backend/gl/src/lib.rs

In OpenGL ES, it is enabled by default
and the flag is not supported.

Only enable PROGRAM_POINT_SIZE for desktop

---

Cargo.toml
src/window/sdl/Cargo.toml
src/window/sdl/examples/window.rs

*gfx_window_sdl* requires sdl2 = "0.29" stopping usage of later sdl2 versions or requiring gfx to be updated manually for each sdl2 minor release. 
Since this lib is used as a helper for sdl and isn't particularly likely to break with newer minor versions, it is more helpful to declare a minimum sdl2 version `sdl2 = ">= 0.29, < 1"`. This allows a top-level consumer to declare, for example, sdl2 = "0" and have it work properly (ie currently fetching v0.30.0).
In the case newer versions cause issues, it is still clear which version(s) can be tried by viewing the minimum declared.
I've also added an sdl version of the triangle example, this adds a little compile assurance to gfx_window_sdl when running `cargo test`. I added the gfx dev-depencency sdl version to be `sdl2 = "0"` meaning the …

Add sdl window example, update to 0.30

---

src/backend/dx11/src/factory.rs
src/backend/dx11/src/lib.rs
src/backend/dx12/src/factory.rs
src/backend/dx12/src/lib.rs
src/backend/gl/src/factory.rs
src/backend/gl/src/lib.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/factory.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/pool.rs
src/core/src/command.rs
src/core/src/dummy.rs
src/core/src/factory.rs
src/core/src/lib.rs
src/core/src/pool.rs
src/core/src/queue.rs
src/lib.rs
src/render/src/encoder.rs
src/render/src/lib.rs
src/render/src/pso/bundle.rs
src/window/dxgi/src/lib.rs
src/window/glutin/src/lib.rs
src/window/vulkan/src/lib.rs

A larger PR therefore a bit more explanation!
**Goal**: Merge device setup and 'frontend' (adapters, queues, swapchains, etc.) parts into current core. This doesn't include changes to the factory and command buffers.
- **Deprecate the `Device` trait**, the functionality will be split into the queues and the factory. (not everything ported so far)
- Adding **command pools**, which are necessary for creating command buffers/encoders. Current plan for gfx_app is that the user still will receive an `Encoder` (renamed to `GraphicsEncoder`) when implementing `render`. So keeping the changes to the examples to a minimum for the moment.
- We can rethink the application design in the future if there are some compute examples or multi-queue stuff etc. Also due to the unification of the window …

[ll] Command Pools and application [05/..]

---

examples/trianglell/shader/triangle.metal
src/backend/metalll/Cargo.toml
src/backend/metalll/src/command.rs
src/backend/metalll/src/factory.rs
src/backend/metalll/src/lib.rs
src/backend/metalll/src/native.rs
src/corell/src/factory.rs

Metal's SwapChain implementation now presents the backbuffers directly, without any copying,
by setting the IOSurface backing the Metal texture as the contents of a CALayer. This hands
our renderbuffer straight to the compositor, just as the native swapchain in CAMetalLayer does.
Additionally, the trianglell example now displays almost correctly when using Metal; it now samples
the texture properly instead of displaying the texture coordinates as colors. However blend mode
interpretation is still not implemented, so the background of the rectangle is white, not transparent.

Improved Metal rendering and presentation for corell

---

src/backend/gl/src/tex.rs

Replacing the TODO parts related to `B8_G8_R8_A8`, since using Bgra8 format type with OpenGL backend causes runtime panics, because of these unhandled cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/1279)

Enable Bgra8 on OpenGL backend

---

src/core/src/texture.rs

Previously, specifying 0xFF would produce 1.00196 value.

Border code conversion fix

---

src/backend/dx12/src/command.rs
src/backend/dx12/src/lib.rs
src/backend/gl/src/command.rs
src/backend/gl/src/factory.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/native.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/pool.rs
src/core/src/command.rs
src/core/src/lib.rs
src/core/src/pool.rs
src/core/src/queue.rs
src/window/glutin/src/lib.rs
src/window/vulkan/src/lib.rs

Addresses the mentioned Backend trait from #1291 (first bullet point) for `ll` integration.
Introducing a new `Backend` trait in similar fashion to the current `Resource` trait simplifies the API and helps higher-level layers for operating on the core. For more details regarding the current problems with associated trait approach please checkout the mentioned issue!
Implemented the Backend changes for GL, Vulkan and D3D12 backend so far,
For reviewing: [Backend trait](https://github.com/msiglreith/gfx/blob/pr_asteria_06v2/src/core/src/lib.rs#L229-L242)
Other notable changes:
- Remove `Send` from Buffer, anticipating the upcoming changes towards allocation of command pools instead of sending around Encoder. Also, added dummy implementation for the Buffer trait to allow merging the first …

[ll] Re-introduce Backend trait [06/..]

---

src/core/src/command.rs
src/lib.rs
src/render/src/encoder.rs
src/render/src/lib.rs
src/render/src/pso/bundle.rs

GraphicsEncoder and Application are now generic over `Backend` instead of `Resources`.
(Related to #1291)

[ll] Adopt the new Backend trait for app and render [08/..]

---

Cargo.toml
appveyor.yml
examples/trianglell/main.rs
src/backend/dx12ll/src/command.rs
src/backend/dx12ll/src/data.rs
src/backend/dx12ll/src/factory.rs
src/backend/dx12ll/src/lib.rs
src/backend/dx12ll/src/native.rs
src/backend/vulkanll/src/command.rs

This is a big WIP work, but I think we can merge this at any point in order to minimize friction with other changes.

[LL] Make DX12 ~~great~~ compile again!

---

src/backend/gl/src/lib.rs
src/backend/gl/src/pool.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/pool.rs
src/core/src/lib.rs
src/core/src/pool.rs
src/core/src/queue.rs
src/lib.rs
src/window/glutin/src/lib.rs
src/window/vulkan/src/lib.rs

Currently trying to merge the current `launch_` functions into one backend-agnostic `run` function for app. Only surface and adapter setup should be then backend specific.
Other changes induced by the mentioned goal above (note: focusing on GL and Vulkan atm):
* Implement command pools for GL (maybe pool implementations can be moved towards `core` similar to CommandQueues, which would reduce code size.. )
* Add `SwapchainConfig`, which allows to specify color and depth-stencil formats for the backbuffers. Should be extended in the future for present modes (if possible), swapchain size and possible other options.
* `present` now takes the present queue, which allows to remove the `Mutex` for CommandQueues on Vulkan

[ll] Working on app unification [09/..]

---

.travis.yml
Cargo.toml
appveyor.yml
src/core/Cargo.toml
src/core/src/lib.rs
src/core/src/shade.rs
src/render/Cargo.toml
src/render/src/lib.rs
src/render/src/shade.rs

Closes #1290 
Unfortunately (or maybe not), `Rad` and `Deg` types were removed.

Replace cgmath bindings by `mint`

---

examples/trianglell/main.rs
src/backend/dx12ll/src/command.rs
src/backend/dx12ll/src/lib.rs
src/backend/metalll/src/command.rs
src/backend/metalll/src/lib.rs
src/backend/vulkanll/src/command.rs
src/backend/vulkanll/src/lib.rs
src/corell/src/command.rs

To avoid needing to include traits with lifetime parameters in
the GraphicsCommandBuffer trait, we split the RenderPass\*Encoder trait
into RenderPass\*Buffer (a backend-implemented trait with no lifetime
parameters) and a struct RenderPass*Encoder containing the necessary
lifetime parameters and associated references.
These structs proxy all their calls to the Buffer trait implementations
by passing a reference to the whole struct that includes the buffer as
a member, as well as the lifetime-bound references. As a result the
backend implementations have access to all the data they had previously
without having to resort to lifetime parameters on the trait or
unsafety.

Separate Buffer/Encoder for RenderPass Encoders

---

src/backend/dx11/src/mirror.rs
src/render/src/pso/buffer.rs

Also adds addititonal condition in `match_attribute` function to handle `Vector(1)`.
Fixes #1306

Fix mask_to_vector in dx11 mirroring

---

src/lib.rs
src/render/src/encoder.rs
src/render/src/lib.rs

* Add `GraphicsPoolExt` for easier `GraphicsEncoder` creation
* Ccreate a DSV for each swapchain image in app
* Update `render` trait method for application. Will be changed in the future when we have per-thread pools from #1281, so we don't have to pass a graphics pool.

[ll] Fix depth backbuffers and adopt app API

---

src/backend/gl/src/factory.rs
src/backend/gl/src/lib.rs
src/core/src/lib.rs
src/lib.rs
src/render/src/encoder.rs
src/window/glutin/src/lib.rs

_Note: Generated diff doesn't reflect the changes very well unfortunately!_
* Fix depth stencil view image creation for app
* Create a `GraphicsQueue` on adapter open
* Add command dispatching on queue submission (based on the old device submit code).
The queue submission part will be fixed on a follow-up PR (if interested see https://github.com/msiglreith/gfx/commit/e689f33eb63fdc9cf7298c1e18d9b453426366b2) to match the current device submission code on master better.

[ll] gl: Fix submission, swapchain creation and remove outdated code

---

src/backend/gl/src/command.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/pool.rs
src/core/src/command.rs
src/core/src/lib.rs
src/core/src/pool.rs
src/render/src/encoder.rs

All APIs have only a single command buffer type, except vulkan's secondary command buffers differ a bit. Therefore it seems reasonable to only require gfx backends to only implement one `RawCommandBuffer`  and have backend-agnostic safe wrappers in the core, which will implement the support functionalities depending on the type (`GraphicsCommandBuffer`, `ComputeCommandBuffer`, etc.)
The current change adds a bit more code, but this should have positive effect in the future by reducing the need of macros or additional code for the backend implementations
(SubpassCommandBuffer will stay a separate type atm, as they are a bit special, but could maybe merged as well in the future.)

[ll] Refactor command buffer types [14/..]

---

src/backend/dx11/Cargo.toml
src/backend/dx11/src/command.rs
src/backend/dx11/src/execute.rs
src/backend/dx11/src/factory.rs
src/backend/dx11/src/lib.rs
src/backend/dx11/src/native.rs
src/backend/dx11/src/pool.rs
src/backend/dx11/src/state.rs
src/lib.rs
src/shade.rs
src/window/dxgi/Cargo.toml
src/window/dxgi/src/lib.rs

* dx11: Implement swapchain, command queue and surface creation
* dx11: Implement command pools
* dx11: Use `ComPtr` for d3d11 objects instead of raw pointers
* app: Fix wrong DSV flag
(`comptr` is currently an unpublished crate sitting in my repo, which I've been using for the dx12 backend as well.)

[ll] dx11: Implement necessary pieces for cube demo

---

src/backend/gl/src/tex.rs

The mistake was using `GL_DEPTH`, which is the depth buffer handle, instead of one of the [allowed pixel formats](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glTexSubImage2D.xhtml).

Fix depth pixel format in GL

---

examples/blend/main.rs
examples/cube/main.rs
examples/flowmap/main.rs
examples/skybox/main.rs
src/render/src/lib.rs

* Update blend, flowmap and skybox examples
* Remove `gfx_core` dependency from cube example
cc #1321

[ll] Update examples [17/..]

---

examples/blend/main.rs
examples/cube/main.rs
examples/flowmap/main.rs
examples/skybox/main.rs
src/backend/dx11/src/factory.rs
src/backend/dx11/src/lib.rs
src/backend/gl/src/factory.rs
src/backend/gl/src/lib.rs
src/core/src/factory.rs
src/core/src/handle.rs
src/core/src/lib.rs
src/core/src/mapping.rs
src/core/src/queue.rs
src/lib.rs

Update the corresponding API parts to use the new handles.
Semaphores and fences are hidden behind mutexes to ensure explicit synchronization (important for vulkan),
cc #1321

[ll] Add semaphore handle [18/..]

---

src/core/src/lib.rs
src/core/src/window.rs

Moved the window/surface/swapchain related parts from `lib.rs` into a new module and improved documentation a bit.

[ll] Move WSI parts into new module [19/..]

---

src/backend/dx12ll/src/factory.rs
src/backend/dx12ll/src/lib.rs
src/backend/dx12ll/src/native.rs
src/backend/metalll/src/factory.rs
src/backend/metalll/src/lib.rs
src/backend/metalll/src/native.rs
src/backend/vulkanll/src/factory.rs
src/backend/vulkanll/src/lib.rs
src/backend/vulkanll/src/native.rs
src/corell/src/factory.rs
src/corell/src/lib.rs

I'm not sure if this is something that others want/need but I was playing around with it and thought I'd put it up for comments.
Adds a trait Resource implemented by all Resources associated types that have a destroy_* method in corell::Factory. This makes it much easier to write abstractions/macros for cleanup that work over multiple resource types. DepthStencilView also appeared to be missing a corresponding method in Factory so I added one.
This functionality is basically impossible to implement on top of corell due to coherency issues; any implementations of a trait for both Resources::X and Resources::Y will be marked as conflicting even if they never do in actuality.

Add Resource trait for generic resource destruction

---

src/backend/dx11/src/factory.rs
src/backend/gl/src/factory.rs
src/backend/gl/src/tex.rs
src/backend/metal/src/factory.rs
src/backend/vulkan/src/factory.rs
src/core/src/factory.rs

"Fixes" #1328 (although buffer textures aren't implemented at all for other backends)
Hopefully I managed to update all the function signatures for the different backends. I could only test the GL backend on my computer.

Implement buffer texture format selection for GL backend

---

src/backend/vulkan/src/lib.rs
src/window/glfw/examples/window.rs
src/window/glfw/src/lib.rs
src/window/sdl/examples/window.rs
src/window/sdl/src/lib.rs
src/window/vulkan/src/lib.rs

Adapt glfw and sdl window creation to the new model (Window-> Surface -> SwapChain).
The swapchains of these backends are restricted as mentioned in #1304 (set surface format at the beginning and swapchain config has to match those).
Backbuffer image creation could be abstracted in a followup PR as it's similar on all three (glutin, glfw, sdl) window backends.
Edit: I need to fix sdl build on my linux system later - done

[ll] Update glfw and sdl window [21/..]

---

src/window/glfw/Cargo.toml

glfw-rs 0.15 was purely a dependency upgrade itself.

Update glfw dependency to 0.15

---

examples/triangle/main.rs
src/core/src/queue.rs
src/core/src/window.rs
src/lib.rs
src/render/src/lib.rs
src/render/src/swapchain.rs
src/window/dxgi/src/lib.rs
src/window/glfw/src/lib.rs
src/window/glutin/src/lib.rs
src/window/sdl/src/lib.rs
src/window/vulkan/src/lib.rs

- Port the triangle example to the new core. Due to the ll changes this requires a lot more boilerplate for the setup. Interesting direction would be providing some shortcuts for the user for specific scenarios (e.g single queue setup)
- Add API support for waiting on semaphores on present to allow patterns like acquire frame -> wait -> draw -> signal -> present. Not implemented for the backends so far (vk and dx12 are non-functional atm anyway..)
cc #1321

[ll] Update triangle example [27/..]

---

src/core/src/command.rs
src/core/src/lib.rs
src/lib.rs

Follow to #1359 
- Remove `Encoder` trait bounds
- Add `open_with` to `Adapter` which takes an closure returning the number of queues for each family

[ll] Remove trait bounds and simplify device opening [29/..]

---

Cargo.toml
examples/blend/main.rs
examples/deferred/main.rs
examples/gamma/main.rs
examples/performance/main.rs
examples/triangle/main.rs
examples/trianglell/main.rs
examples/ubo_tilemap/main.rs
src/backend/dx12ll/Cargo.toml
src/backend/metalll/Cargo.toml
src/backend/vulkan/Cargo.toml
src/backend/vulkanll/Cargo.toml
src/lib.rs
src/window/dxgi/Cargo.toml
src/window/glutin/Cargo.toml
src/window/glutin/src/lib.rs
src/window/metal/Cargo.toml
src/window/vulkan/Cargo.toml

This PR brings gfx up to date with the latest glutin & winit releases. Having a `ContextBuilder` in addition to the `WindowBuilder` and a rework of the event structures are the main changes for gfx users. The events are particularly groansome for refactoring. I'm particularly interested in getting gfx up to date so I can finally have XWayland window support in Linux. See [glutin ContextBuilder addition PR](https://github.com/tomaka/glutin/pull/901) & [winit event rework PR](https://github.com/tomaka/winit/pull/164)
Fixes #1348

Update dependencies & examples to glutin 0.9 / winit 0.7

---

src/window/glutin/src/headless.rs

I missed this compile issue for `gfx_window_glutin` in headless mode in PR #1362.
This was obscured by the current mac build issue, as travis only builds this feature on mac.

Fix glutin headless GlContext compile issue

---

examples/gamma/main.rs
examples/triangle/main.rs
src/lib.rs

Additional call is required on mac/wayland, see [glutin docs](https://docs.rs/glutin/0.9.0/glutin/trait.GlContext.html#tymethod.resize) & [this comment](https://github.com/gfx-rs/gfx/pull/1362#issuecomment-314512747)

Call GlWindow#resize on resize events in examples

---

appveyor.yml
examples/blend/main.rs
examples/cube/main.rs
examples/deferred/main.rs
examples/flowmap/main.rs
examples/instancing/main.rs
examples/mipmap/main.rs
examples/particle/main.rs
examples/shadow/main.rs
examples/skybox/main.rs
examples/terrain/main.rs
examples/terrain_tessellated/main.rs
examples/ubo_tilemap/main.rs
src/backend/dx12/src/pool.rs
src/backend/gl/src/command.rs
src/backend/gl/src/pool.rs
src/core/src/command.rs
src/core/src/lib.rs
src/core/src/pool.rs
src/lib.rs
src/render/src/encoder.rs
src/render/src/lib.rs
src/window/dxgi/src/lib.rs
src/window/sdl/src/lib.rs

* core Add necessary trait bounds for pools and backend
* render: Allow to split finish and submit for GraphicsEncoder, allowing to send submission across threads
* shadow: Instead of having an encoder per thread, we now have a pool per thread, record a command buffer on each thread, finish and send back the submit info to the main thread, where we submit the commands atm.
cc #1321

[ll] Update shadow example and adjust core for multi-threading

---

examples/blend/main.rs
examples/cube/main.rs
examples/deferred/main.rs
examples/flowmap/main.rs
examples/gamma/main.rs
examples/instancing/main.rs
examples/mipmap/main.rs
examples/particle/main.rs
examples/performance/main.rs
examples/shadow/main.rs
examples/skybox/main.rs
examples/terrain/main.rs
examples/terrain_tessellated/main.rs
examples/triangle/main.rs
examples/ubo_tilemap/main.rs
src/backend/dx11/src/lib.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/pool.rs
src/backend/gl/src/lib.rs
src/backend/vulkan/src/lib.rs
src/core/src/lib.rs
src/core/src/queue.rs
src/lib.rs
src/render/src/encoder.rs
src/render/src/lib.rs
src/window/glfw/examples/window.rs
src/window/sdl/examples/window.rs

Allow to specify the queue type on initialization (e.g create a graphics queue from a general queue family).
Due to this queue 'casting' the queue reference wrappers become more or less obsolete as the user can now specify the wished queue type upfront and doesn't need to cast after they have been created.

[ll] Support queue family casting and remove queue ref wrappers

---

src/core/src/lib.rs
src/render/src/lib.rs
src/window/glutin/src/headless.rs
src/window/glutin/src/lib.rs

Adding support for headless init as alternative to acquiring a surface and adapters from `WindowsExt`.

[ll] Headless initialization [33/..]

---

Cargo.toml
appveyor.yml
examples/blend/main.rs
examples/deferred/main.rs
examples/gamma/main.rs
examples/performance/main.rs
examples/triangle/main.rs
examples/trianglell/main.rs
examples/ubo_tilemap/main.rs
src/backend/dx12ll/Cargo.toml
src/backend/vulkan/Cargo.toml
src/backend/vulkanll/Cargo.toml
src/lib.rs
src/window/dxgi/Cargo.toml
src/window/glutin/Cargo.toml
src/window/glutin/src/lib.rs
src/window/metal/Cargo.toml
src/window/vulkan/Cargo.toml

I cherry picked the glutin/winit upgrade commits on master and updated the appveyor config as some dependencies now require a more recent rustc than 1.16

Update v0.16 dependencies & examples to glutin 0.9 / winit 0.7

---

src/core/src/memory.rs

When I have a bit of time I'll go through things that I find lacking or confusing in the doc and try to improve a bit with what I know. I'll add more doc to this PR as I go but don't hesitate to give feedback and corrections along the way.
First thing to note is that rustdoc doesn't do justice to some of the attempts at documenting the code. For example it's hard to see from the docs what the different bit patterns for a particular bitflags are. Landing on the page for `Bind` for instance isn't very informative: https://docs.rs/gfx/0.16.1/gfx/struct.Bind.html
It could probably be improved by the bit_flags macro but in the mean time, listing the different bit patterns in the doc of the bitflag itself helps a great deal I think (from the point of view of someone who tries to make something …

Some doc improvements

---

src/backend/metalll/Cargo.toml
src/backend/metalll/src/conversions.rs
src/backend/metalll/src/factory.rs
src/backend/metalll/src/lib.rs
src/backend/metalll/src/native.rs

Adds MTLHeap support to the Metal backend, and uses it whenever possible for memory allocations.
This isn't quite ready to merge, https://github.com/gfx-rs/metal-rs/pull/7 needs to make it into crates.io first.

Use MTLHeap when possible for resource allocation

---

src/backend/gl/src/factory.rs
src/core/src/handle.rs

Fixes #1395
Fixes #1054 
Note: this PR only fixes GL backend. Other backends still have the problem, but given that only a handful of people use them, we can just focus on LL transition instead.
cc @icefoxen

[pre][gl] Removal of frame_handles from the Factory

---

src/core/src/dummy.rs

`dummy` backend is useful for writing examples in the documentation. Implementing the new traits, especially `Backend` from the ll integration.

Update dummy backend for documentation

---

src/core/src/factory.rs
src/core/src/memory.rs
src/render/src/lib.rs
src/render/src/slice.rs

This is a work in progress. This PR adds the gfx::doc::terminology module which only contains rustdoc documentation. The idea is to have a centralized place with information about what various gfx concepts map to in other APIs. I am not quite certain what the best way to present this information is. For example we could also have sections "OpenGL to gfx", "D3D11 to gfx", etc which would only link to the documentation of each term in gfx concisely (like: " - GL thing: [gfx thing](link to thing in the doc)".
What I am trying to address here is that for someone who does not know the internals of gfx, using this crate currently is a small exercise in reverse-engineering, especially when you know what you want to do (but not how it is called in gfx).
The other thing that I want to move …

More documentation

---

.travis.yml
scripts/travis-before_install.sh
scripts/travis-script.sh

The [internal compiler errors][ICE] are annoying.
[ICE]: https://travis-ci.org/gfx-rs/gfx/jobs/257898756#L500

Exclude the nightly compiler from bors builds

---

src/backend/dx11/Cargo.toml
src/backend/dx11/src/execute.rs
src/backend/dx11/src/factory.rs
src/backend/dx11/src/lib.rs
src/backend/dx11/src/state.rs
src/backend/dx12/Cargo.toml
src/backend/dx12/src/command.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/pool.rs
src/window/dxgi/Cargo.toml
src/window/dxgi/src/lib.rs

Temporary refering to my `wio` fork as we are blocked on winapi 0.3 (or a new 0.2 release) anyway and this might require an `wio` version bump again.
Closes #1402

dx11/dx12: Replace comptr with wio

---

src/backend/dx12ll/Cargo.toml
src/core/src/adapter.rs
src/core/src/dummy.rs
src/core/src/lib.rs
src/core/src/queue.rs
src/core/src/window.rs

* Moving adapter parts into separate module, allowing better documentation and move stuff out of `lib.rs`
* Extend documentation for window, adapter and queues (still early, API isn't totally fixed atm)
cc #1321

core: Split adapter into module and extend documentation

---

src/backend/dx11/src/command.rs
src/backend/dx11/src/lib.rs
src/backend/dx12/src/command.rs
src/backend/dx12/src/lib.rs
src/backend/gl/src/command.rs
src/backend/gl/src/lib.rs
src/backend/metal/src/command.rs
src/backend/metal/src/lib.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/lib.rs
src/core/Cargo.toml
src/core/src/command.rs
src/core/src/dummy.rs
src/core/src/lib.rs
src/core/src/queue/capability.rs
src/core/src/queue/mod.rs
src/core/src/queue/submission.rs
src/render/src/encoder.rs

Current queue submission allowed to submit all kind of buffers to a queue which could cause issues on some backends. We provide now untyped and a strong-typed interface for command buffer submission employing a builder pattern internally.
Queue capabilities and hierarchies are fully encoded into the type systems. Submissions will be upcasted to the match the required capabilities needed for executing the passed command buffers. Only queue with matching capabilities can execute this submissions.
A missing point which will be addressed in a followup would to allow submission of different Submission objects, currently required to have the same capability, possibly with an additional builder for a collection of submissions.
Example for submission building:
```rust
let submission_a = …
```

core: Rework queue submission

---

src/core/src/queue/submission.rs

Allow the user to manually promote a submission object in order to be submitted with submissions of the same capability with a single submit.
e.g we have a submission with graphics capability and one with compute capability. Trying to batch them into one `submit` call would fail due to type difference. We could try to add a submission list builder but that's tricky without possible overhead I believe.
The implemented approach here is quite straightforward imo and the error messages are ok-ish if we try to promote the submission into an illegal state.
```
error[E0277]: the trait bound `core::queue::Transfer: core::queue::Supports<core::queue::Graphics>` is not satisfied
--> src\render\src\encoder.rs:204:48
|
204 | …
```

core: Add queue submission promotion

---

.travis.yml

Add missing glfw dependencies for the newer trusty images.

Fix travis linux build

---

src/backend/vulkan/src/command.rs
src/backend/vulkan/src/data.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/native.rs
src/core/src/command/compute.rs
src/core/src/command/general.rs
src/core/src/command/graphics.rs
src/core/src/command/mod.rs
src/core/src/command/raw.rs
src/core/src/command/transfer.rs
src/core/src/device.rs
src/core/src/memory.rs
src/core/src/texture.rs

* Adjust the core command buffer API for clear/copy/resolve commands to matching the vulkan API
* Implement `clear_depth_stencil`, `copy_*` and `resolve_image` for vulkan
* Smaller cleanup (formating, merge barriers into an enum, ...)
cc #1416

[ll] Implement clear, copy and resolve commands for vulkan [38/..]

---

src/backend/gl/src/command.rs
src/backend/gl/src/device.rs
src/backend/gl/src/info.rs
src/backend/gl/src/lib.rs
src/core/src/device.rs
src/core/src/lib.rs

* gl: Implement index buffer binding command
* gl: Create a `GeneralQueue` if we have compute support, else fall back to `GraphicsQueue`
* core: Split `Capabilities` into `Features` (specify which aspects of the our API are supported) and `Limits` (numerical limits like max_texture_size, max_viewports, ..)

[ll] Further work on the gl backend [41/..]

---

src/backend/gl/Cargo.toml
src/backend/gl/src/command.rs
src/backend/gl/src/info.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/pool.rs
src/backend/gl/src/state.rs
src/core/src/command/raw.rs
src/core/src/lib.rs

Implement `set_viewports` and `set_scissors`:
* Our old implementation only allowed one viewport and scissor. To minimize heap allocations we store everything into the `DataBuffer` in the hope to reuse the memory in upcoming frames (we could actually share the internal buffers across all command buffers of a pool!).
* Add validation checks on the command buffer side
* Enabling and Disabling of scissors test will done on when binding the pipeline. Scissor disabling seems to only make sense when rasterization is disabled as vulkan requires at least one viewport/scissor.
* Disabling (zeroing) all non-active viewports and scissors requires a bit more logic. This is required to be consitent with D3D12.

[ll] gl: Implement setting viewports and scissors [42/..]

---

src/backend/gl/src/command.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/native.rs
src/backend/gl/src/state.rs
src/core/src/command/general.rs
src/core/src/command/graphics.rs
src/core/src/command/raw.rs
src/core/src/pso/graphics.rs
src/core/src/pso/input_assembler.rs
src/window/glutin/src/lib.rs

* core: Add further configuration possibilities for graphics pipelines (still not finished so far: multisampling, depth-stencil state and dynamic states)
* core: Split the setting of reference values (blend constants and stencil ref) into two commands
* glutin: Fix window backend after the merge of `Resources` and `Backend`
* gl: Implement color clearing based on the old implementation

[ll] Extend pso functionality and work on gl backend [43/..]

---

appveyor.yml
examples/Cargo.toml
examples/corell/trianglell/main.rs

Exclude all the necessary crates for building with appveyor.
`gfx_window_dxgi` is also excluded as it depends on dx12, which we need to feature-gate in the a followup PR but this would block #1437

Fix appveyor for dx12 builds

---

src/core/src/adapter.rs
src/core/src/handle.rs
src/core/src/lib.rs
src/window/glutin/src/lib.rs

Added some documentation to help new users figure out how the various structures are typically obtained, as well as an example (& doc-test) for `gfx_window_glutin`.
It's a very minor improvement, but every little bit helps! :D

Minor documentation improvements.

---

src/backend/empty/src/lib.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/pool.rs
src/core/src/command/mod.rs
src/core/src/command/raw.rs
src/core/src/command/renderpass.rs
src/core/src/lib.rs
src/core/src/pool.rs
src/core/src/queue/submission.rs

Refactor the current command pool implementation and remove `SubmitInfo`.
Motivated by providing a lower level design which is more vulkan flavored.
We basically follow the (internal) paradigm of providing `Raw` objects (close to the metal, zero overhead, C-ish) and having safe wrappers on top of them which enforce some constraints at compile time and come with minimal overhead.
* The `RawCommandBuffer` isn't supposed to store the command buffers internally and moves that task onto the library user.
* `SubmitInfo` was a safe object to pass over thread boundaries to prevent users from recording multiple command buffers at the same time. We now move towards sending (+ cloning) `RawCommandBuffers` which requires the users to take care of not recording multiple buffers from one pool at the …

[ll] core: Refactor command pools

---

src/backend/gl/src/command.rs
src/backend/gl/src/conv.rs
src/backend/gl/src/device.rs
src/backend/gl/src/info.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/native.rs
src/backend/gl/src/pool.rs
src/core/src/lib.rs

* Fix GL backend build after command pool changes #1457 (pool reset still WIP)
* Implement fence and semaphore handling (ported from the old implementation)
* Implement sampler creation, adding few more features to properly reflect capabilities of the backend

[ll] Working on gl backend (build, fences and samplers)

---

examples/core/quad/main.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/pool.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/pool.rs
src/core/src/command/raw.rs
src/core/src/pool.rs
src/core/src/queue/mod.rs

* core: Add possiblity to select reset behavior on pool creation (as exposed in vulkan)
* gl/vk: Implement new reset mechaniccs
The OpenGL implementation is a bit more tricky as we need to internally keep book of the buffer memory at the command pool side to be able to `CommandPool::reset`. We differ between two cases: pool reset only (linear) and allow individual pool resets (individual).
* `Linear` stores all buffer memory inside one (actually two..) large Vec, which is possible as we only allow (not enforced) one buffer to be recorded at the same time for each pool.
* `Individual` requires a bit more bookkeeping (`HashMap`) by splitting the memory storage up into one Vec for each command buffer.
Internally using `Arc<RefCell<_>>` for storing buffers. It's a consensus on the safety …

[ll] gl: Command pool resetting

---

src/backend/gl/src/command.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/pool.rs

* Rework command pool memory storage to work now with a combination of `UnsafeCell` + shared atomic to denote if safe access to the underlying pool and memory is possible. It works similar to a `Mutex` but doesn't block and should be faster. We can revisit the implementation approach on a later stage when we have implemented the rest of the backend imo.
* Fix behavior of `RawCommandBuffer::begin` which should implicitly reset when individual reset flag is set on pool creation
* Emit an error when `reset` is called without the mentioned flag

[ll] gl: Add more safety for the command pool memory storage

---

src/core/src/image.rs
src/render/Cargo.toml
src/render/src/buffer.rs
src/render/src/device.rs
src/render/src/handle.rs
src/render/src/image.rs
src/render/src/lib.rs

Working on #1466, starting with a fresh `cleanup()` implementation.
I commented out a lot of code to be able to compile it.

[ll][WIP] Gpu, Device and handles for render

---

src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/window.rs

* Fix build for surface creation
* Filter request layers to only initialize with available layers, else instance creation can fail (e.g debug layers may not be registered when installing LunarG SDK on windows afaik)

[ll] vk: Fix win32 initialization

---

scripts/travis-script.sh
src/backend/gl/src/window/glutin.rs

This should allow us to use bors for the `ll` branch.
Changed the headless test to a doc example because it fails on appveyor (and maybe travis also) with `NonAvailablePixelFormat`. Glutin doesn't allow to configure the pixel format settings at the moment afaik.

[ll] Fix build for CI, rewriting headless test as doc example

---

src/backend/gl/src/state.rs

Fixes #1487 
It looks like there aren't any more occurrences of GL_MULTISAMPLE.

Don't touch GL_MULTISAMPLE in GLES

---

examples/corell/trianglell/main.rs
src/backend/dx12ll/src/command.rs
src/backend/dx12ll/src/factory.rs

This change was done for a GPUWeb test (positive!), but I don't think why we'd want this wasted ;)

Indexed triangle strip cut for TriangleLL

---

examples/render/quad_render/main.rs
src/backend/empty/src/lib.rs
src/core/src/buffer.rs
src/core/src/device.rs
src/core/src/image.rs
src/render/src/allocators/boxed.rs
src/render/src/allocators/mod.rs
src/render/src/allocators/stack.rs
src/render/src/buffer.rs
src/render/src/device.rs
src/render/src/encoder.rs
src/render/src/handle.rs
src/render/src/image.rs
src/render/src/lib.rs
src/render/src/memory.rs

Working on #1484.
With the simplest `BoxedAllocator` (allocates an heap for each resource) the example looks fine.
With the `StackAllocator` the logo is not displayed, do I need to use the heap offsets when doing mapping, copies, .. ?
@kvark I hope that's simple enough ;)

[ll] Fix garbage leak and implement allocation for render

---

examples/core/quad/main.rs
examples/render/quad_render/main.rs
src/backend/gl/src/device.rs
src/backend/vulkan/src/conv.rs
src/backend/vulkan/src/device.rs
src/core/src/lib.rs
src/core/src/pso/graphics.rs
src/core/src/pso/input_assembler.rs
src/core/src/pso/mod.rs

I believe `fragment` is a better term (it's not always pixels being processed) and more consistent with Vulkan. Sorry for bikeshedding!
Also removed explicit rasterizer discard, we'll instead just check for the fragment shader presence.

[ll] Pixel to Fragment rename

---

examples/core/quad/main.rs
examples/render/quad_render/Cargo.toml
examples/render/quad_render/main.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/gl/src/lib.rs
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/native.rs
src/core/src/device.rs
src/core/src/lib.rs
src/core/src/mapping.rs
src/render/src/allocators/stack.rs
src/render/src/buffer.rs
src/render/src/device.rs
src/render/src/encoder.rs
src/render/src/handle.rs
src/render/src/lib.rs
src/render/src/mapping.rs

Modifies the mapping API for `core` as we discussed.
~~Tracking is not yet implemented for `render`.~~
~~Currently using an unpublished version of `ash` for the Vulkan backend.~~
A nice side effect is that the render example now works with `StackAllocator` :)

[ll] More mapping

---

examples/core/quad/main.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs

* Fix build issue in `quad` for dx12 backend
* Improve documentation for root signature layout. Better reflect internal layout.
* Implement compute pipeline creation
* Increase default descriptor heap size for CBV/SRV/UAV heaps to match Tier 1 limit
* Implement a few more destroy functions
* Only enable debug layer for debug builds following Vulkan

[ll] dx12: Compute pipelines and cleanup

---

src/backend/dx12/src/window.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/window/glutin.rs
src/backend/metal/src/window.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/window.rs
src/core/src/lib.rs
src/core/src/window.rs

Support querying surface properties to obtain reasonable values for swapchain creation.
Next step are extending swapchain create infos to make use of the queried results.
Metal currently unimplemented

[ll] Surface capability querying

---

src/backend/dx12/src/command.rs
src/backend/dx12/src/conv.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/conv.rs
src/core/src/buffer.rs
src/core/src/image.rs
src/core/src/memory.rs

Implement pipeline barriers for dx12 based on vulkan's access model.
Requires a few workarounds and restrictions to make this work:
* We differ between read and read/write states as it's a limitation by dx12. Allowing to only have one write bit set but multiple read bits if no write bit is set.
* `TRANSFER_WRITE` for images is used for all copy commands (including resolve). We add transitions barriers for resolve operations before and afterwards (can be optimized maybe) to have a consistent state accross command list boundaries.
* `SHADER_READ` is limited to SRV reads, which we need to enforce on the shader side for HLSL to get it working. `SHADER_WRITE` is used for write access to UAV and can be combined with `SHADER_READ` to obtain read access to UAV (but not SRV).
* Buffers can only be …

[ll] dx12: Implement pipeline barriers

---

examples/core/quad/main.rs
examples/render/quad_render/main.rs
src/backend/dx12/src/command.rs
src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/native.rs
src/backend/vulkan/src/device.rs
src/core/src/format.rs
src/core/src/pass.rs

I'm not yet confident that this is going to be enough, but the implementation is somewhat sound, and it will get us going for the nearest future. Basic logic is the following:
We ignore the access masks and pipeline stages of dependencies, but use the source/dest subpass indexes in order to build an order of subpasses, which fulfills the dependencies (i.e. traversing the graph in this order means that the dependencies of each next subpass are resolved by the time we get to it).
Within the produced order, for each attachment we figure if there is a particular state it needs to be, or preserved, or we don't care. Once we see a required state, we determine where the transition needs to start (at some previous pass, or right here in place), record new barriers, and update the current values …

[ll][dx12] Subpass Dependencies

---

src/render/src/macros/pso.rs

Can produce 
```
warning: unused import: `super::gfx`
```

[0.16] Add allow unused super::gfx import for pso macro

---

examples/core/quad/main.rs
examples/render/quad_render/Cargo.toml
examples/render/quad_render/main.rs
src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/native.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/gl/src/device.rs
src/backend/gl/src/info.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/native.rs
src/backend/metal/src/conversions.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/native.rs
src/core/src/device.rs
src/core/src/image.rs
src/core/src/lib.rs
src/core/src/memory.rs
src/render/Cargo.toml
src/render/src/allocators/boxed.rs
src/render/src/allocators/stack.rs
src/render/src/device.rs
src/render/src/lib.rs

This PR renames heaps to memory, which is allocated/freed instead of creation/destruction.
Seeing how we are getting further from DX12 heaps and leaning towards thinner Vk portability layer, naming memory allocations for what they are should make sense.
Also, the DX12 backend update will include splitting the memory types for Resource Heap Tier1 hardware (like NV Vulkan driver does), which is what allows us to get rid of an unsound `ResourceHeapType`.
Todo:

[ll] heap creation -> memory allocation

---

src/backend/metal/Cargo.toml
src/backend/metal/src/lib.rs
src/backend/metal/src/window.rs

Metal backend in `ll` branch needed winit object to create surface. However, it was inconvenient for users with sdl2, glew3 windowing library instead of winit library. Thus I made a trait NativeWindow to bridge window objects and the metal Instance in gfx-rs.

[ll] Metal Backend: Support multiple windowing libs

---

src/backend/dx12/Cargo.toml
src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs

Start integration SPIRV-Cross into gfx-rs for generating HLSL shaders from SPIR-V.
TODO:
Big Thanks @grovesNL for the `spirv_cross` wrapper 👏

[ll] dx12: Start spirv_cross integration

---

appveyor.yml
src/render/src/macros/mod.rs
src/render/src/macros/structure.rs

Adds support for attributes on struct fields, such as doc comments. This doesn't work on stable because of a macro parser bug. Wait until rust-lang/rust#42913 is in a stable release (1.20 probably) before merging this.

Support field attributes on vertex and constant structures

---

examples/core/quad/main.rs
src/backend/metal/src/command.rs
src/backend/metal/src/conversions.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs

This change has a few //TODO items, with an assumption that we need to have a follow-up pass that clarifies Send/Sync usage on resource anyway.
There are still issues with Metal backend: WebGPU prototype crashes while recording an MTL blit encoder, (improper reset/cb re-use most likely), but at least it shows the first frame correctly with a texture now.
The backend also needs to properly implement binding inheritance (e.g. don't require PSO to be set outside of the encoder), but that's for future PRs.

Metal: primitive types, image to buffer copies

---

Cargo.toml
appveyor.yml
src/backend/dx12ll/Cargo.toml
src/backend/metalll/Cargo.toml
src/backend/vulkanll/Cargo.toml
src/render/src/macros/pso.rs
src/window/dxgi/Cargo.toml
src/window/glutin/Cargo.toml
src/window/metal/Cargo.toml
src/window/vulkan/Cargo.toml

v0.16 improvements for the pre-ll branch.
* Fix: Updating appveyor 1.n -> 1.n+1 isn't fun
* Add: Latest glutin/winit is nice to have
* Fix: Unused warnings in out-of-crate macros is a bore

[pre-ll] Cherry picks from v0.16

---

CHANGELOG.md
README.md
src/backend/dx12/src/device.rs
src/backend/metal/src/native.rs

The old README/CHANGELOG contents make little sense for `ll`. We'll keep them in `pre-ll`, where we'll be forwarding people who needs compatibility stuff.

[ll] updated Readme, Changelog, fixed dx12 nightly build

---

src/backend/metal/src/command.rs
src/backend/metal/src/lib.rs

In short:
Pools with individual reset have `managed == None`, their command buffers have `queue == Some`, and they use it to reset themselves.

Metal: individual command buffer reset

---

src/backend/dx11/src/command.rs
src/backend/dx11/src/execute.rs
src/backend/dx11/src/lib.rs
src/backend/gl/src/command.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/tex.rs
src/backend/metal/src/command.rs
src/backend/vulkan/src/command.rs
src/core/src/command.rs
src/core/src/dummy.rs
src/core/src/factory.rs
src/core/src/texture.rs
src/render/src/encoder.rs

Fixes #1540
Why is there never a case where I can just go in, fix something, and go out. Had to refactor a bunch of API calls and their implementations for the best. Hopefully, it's not going to be thrown away too fast.
Edit:
Note that I've actually verified this to work in a simple test case on GL + D3D11, the modified blend example code can be found at https://github.com/kvark/gfx/commit/c2234e62ca163d2c95dc33805a31fbb9bcfca014
(one needs to hack in TRANSFER_SRC/DST flags into core temporarily to test it on that example).

[pre-ll] Copy texture to texture

---

examples/core/quad/main.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/window/glutin.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/core/src/command/graphics.rs
src/core/src/command/raw.rs
src/core/src/command/renderpass.rs
src/core/src/device.rs
src/core/src/lib.rs
src/core/src/window.rs
src/render/src/device.rs
src/render/src/handle.rs
src/render/src/lib.rs
src/render/src/macros.rs

This is to be consistent with Vulkan.
Note: `RenderPass` is like this in Vulkan, so no need to fix it.

[ll] consistent framebuffer naming

---

src/backend/dx12/src/command.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/metal/src/command.rs
src/backend/vulkan/src/command.rs
src/core/src/command/compute.rs
src/core/src/command/raw.rs

Add `bind_compute_descriptor_sets` command, which is essential for compute support!
Only vulkan and dx12 implementation.

[ll] Add compute descriptor set binding

---

src/hal/src/command/renderpass.rs

There are some commands allowed in RenderPass mode are missing.
- ~set_line_width~ (move to another PR)
- ~set_depth_bounds~  (move to another PR)
- ~set_depth_bias~  (move to another PR)
- ~set_stencil_compare_mask~  (move to another PR)
- ~set_stencil_write_mask~  (move to another PR)

[ll] Fix missing methods in RenderPass Encoder

---

examples/hal/quad/main.rs
src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/native.rs
src/backend/gl/src/info.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/native.rs
src/backend/metal/src/conversions.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/lib.rs
src/hal/src/lib.rs
src/hal/src/memory.rs
src/render/src/device.rs

* Remove the `WRITE_COMBINE` memory property and adjust it towards the vulkan model
* Implement uniform and storage buffers for dx12 where we dynamically create view objects
* Fix exposed memory heaps and types (query available memory of the system)

Make the dx12 backend ocean ready 🌊 

---

src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/hal/src/image.rs

Image extents need to be at least 1 in each dimensions in contrast to 0 for unused dimensions in the older implementation.

Redefine image extents semantic

---

src/window/dxgi/src/lib.rs

@kvark These are the small changes we made and mentioned before.
- An `init_existing_raw` function for dxgi window, to use an already initialized window.
- We added reference counting for the inner (winit window) member of the dxgi window, because we need to use the winit window after `init_existing_raw` is done.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/1569)

Dxgi window patches

---

src/backend/dx12/src/device.rs

Follow up of #1590 
See discussions there for details

mask out content types of memory type ID when indexing into `heap_properties`

---

examples/hal/quad/main.rs
examples/render/quad_render/main.rs
src/backend/dx11/src/lib.rs
src/backend/dx12/src/lib.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/lib.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/lib.rs
src/hal/src/adapter.rs
src/warden/src/bin/reftest.rs
src/warden/src/gpu.rs

Not sure if you care about this stuff.

Rename Adapter methods to match conventions

---

Makefile

This cleans up our feature build ordering:
1. no features are enabled, everything is built except `warden`
2. examples are built with various backends
3. `warden` is built with all the backends, which triggers a rebuild of `hal` due to required `serialize` feature
4. test everything
5. re-test `render` with `mint` feature

Reoder CI commands

---

src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/pool.rs

Creating command signatures on device creation and share them with all command buffers.
Currently enforcing a fixed stride for draw commands.

dx12: Implement indirect command

---

src/backend/dx12/src/lib.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/lib.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/lib.rs
src/hal/src/adapter.rs
src/hal/src/lib.rs

Small feature to allow setting queue priorities on device creation. Only used for vulkan and mainly for portability.
cc #1610

hal: Custom queue priorities

---

examples/hal/compute/main.rs
examples/hal/quad/main.rs
src/backend/dx12/src/device.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/device.rs
src/hal/src/device.rs
src/hal/src/pso/compute.rs
src/hal/src/pso/graphics.rs
src/hal/src/pso/mod.rs
src/render/src/device.rs
src/render/src/macros/pipeline.rs
src/render/src/pso.rs

- Add support for deriving pipelines from other pipelines as supported in Vulkan.
- Additional pipeline flag (ie disable optimizations)
- Refactor pipeline descriptors a bit for compute and graphics
Only HAL and Vulkan implemented so far, others require a few adjustment due to the new API.
cc https://github.com/gfx-rs/gfx/issues/1610

Pipeline deriving

---

src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/native.rs

Implement the `fill_buffer` command on d3d12.
We use `ClearUnorderedAccessViewUint` for the internal clearing, requiring us to create a UAV for the buffer. Atm we have the same restrictions as for other clear commands to only allow clearing of whole resources. Otherwise we need to dynamically create views on each command (cheap?).
Additional barriers required as D3D12 needs resources to be in unordered access state whereas vulkan needs transfer write. Probably due to implementation internal things (DMA unit vs compute).
(For future reference: `vkCmdFillBuffer` is also supported on transfer queues with the maintenance extension. D3D12 doesn't support it on Copy queues so far.)
Tested and seems to work. 🏁

dx12: Implement buffer filling command

---

src/backend/dx12/src/device.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/device.rs
src/hal/src/device.rs

In order to query the status of a fence, `Device` trait needs `get_fence_status` method.
For GL and DX12 backend, I decided to implement them later since they are not high priorities for our working project.

[hal][Vulkan][Metal][Empty] Add get_fence_status method to Device trait

---

src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/native.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/gl/src/device.rs
src/backend/gl/src/info.rs
src/backend/gl/src/lib.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/conv.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/native.rs
src/hal/src/command/graphics.rs
src/hal/src/command/mod.rs
src/hal/src/command/raw.rs
src/hal/src/device.rs
src/hal/src/lib.rs
src/hal/src/query.rs
src/hal/src/queue/capability.rs

First steps regarding full query support. This PR only contains query pool creation and recording. Resolve is still up to discussion #1638 .
Implementation details:
* D3D12 uses binary occlusion queries if `PRECISE` is not specified
* D3D12 internally caches the currently used query to have access on the query type on end
* Query operations are supported on compute and graphics command buffers. Therefore a new helper capability is introduced which is implemented for Compute, Graphics and General command buffers to circumvent this.
~~**WIP** as there are outstanding ash changes (and might include resolve operations)~~

Query operations

---

examples/hal/quad/main.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/window.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/gl/src/window/glutin.rs
src/backend/metal/src/device.rs
src/backend/metal/src/window.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/window.rs
src/hal/src/device.rs
src/hal/src/window.rs
src/render/src/lib.rs

Remove the requirement for specifying a present queue on swapchain creation. D3D12 requires to hide the present queue inside the device and have a single queue family supporting presentation. This changes aligns swapchain creation more with Vulkan for the sake of the portability layer.
I didn't touch the actual swapchain creation implementations only shift code a bit around.
Old API:
```rust
fn Surface::build_swapchain(&mut self, config: SwapchainConfig, present_queue: &CommandQueue<B, C>);
```
New API:
```rust
fn Device::create_swapchain(&mut self, surface: &mut Surface, config: SwapchainConfig);
```

Vulkanify swapchain creation

---

examples/hal/compute/main.rs
examples/hal/quad/main.rs
src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/gl/src/device.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/device.rs
src/hal/src/command/compute.rs
src/hal/src/command/graphics.rs
src/hal/src/command/raw.rs
src/hal/src/device.rs
src/render/src/device.rs
src/render/src/macros/pipeline.rs
src/warden/src/gpu.rs
src/warden/src/raw.rs

This PR adds support for the use of push constants in shaders. 
It consists of three public api additions/changes: an extra parameter to `Device::create_pipeline_layout`, and the addition of `push_graphics_constants` and `push_compute_constants` to appropriate command buffers.
These can be easily implemented on Vulkan and ~~DX12~~ (nevermind, we need shader reflection it seems), I will see about other backends before this is merged, hopefully.

Push constants!

---

src/window/dxgi/src/lib.rs

Added the `memory::TRANSFER_SRC` bind flag for the main_color. This is required, if we want to copy the main_color's content into a staging texture with `copy_texture_to_texture_raw`, and read the data from the staging buffer with `map_texture_read` introduced in #1630.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/1649)

[pre-ll] [dx11] Add memory::TRANSFER_SRC to main target

---

examples/hal/quad/main.rs
src/backend/dx12/Cargo.toml
src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/native.rs
src/backend/dx12/src/root_constants.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/device.rs
src/hal/src/device.rs
src/hal/src/pso/mod.rs

Implement root constants for the d3d12 backend following https://github.com/gfx-rs/gfx/issues/1631
Push constants will be split into disjunct ranges, which can be mapped to root constants in the root signature. On pipeline creation, the generated HLSL shaders from spirv-cross will be patched to match the root signature.
~~This PR is still in an early state. Especially, doing the spirv-cross changes will take a bit of time.~~
Closes https://github.com/gfx-rs/gfx/issues/1625 https://github.com/gfx-rs/gfx/issues/1631

dx12: Implement root constants

---

examples/hal/quad/main.rs
src/backend/metal/Cargo.toml
src/backend/metal/src/device.rs

- Removed push constants from quad example so Metal can run again
- Increased minimum Metal version to 1.2 (necessary for function constants), at least for now
- Added support for specialization constants
WIP because it requires https://github.com/gfx-rs/metal-rs/pull/21 to be published first.

[metal] Add specialization constants

---

Cargo.toml
src/backend/dx12ll/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/vulkanll/Cargo.toml
src/lib.rs
src/render/Cargo.toml
src/window/dxgi/Cargo.toml
src/window/glutin/Cargo.toml
src/window/metal/Cargo.toml
src/window/vulkan/Cargo.toml

Cherry pick of #1660 _without deleting trianglell_.
**winit/glutin updates**
gfx_app `0.7` -> `0.8`
~gfx_device_dx12ll `0.1.1` -> `0.2`~
~gfx_device_vulkanll `0.1` -> `0.2`~
gfx_window_dxgi `0.10` -> `0.11`
gfx_window_glutin `0.18` -> `0.19`
gfx_window_metal `0.2` -> `0.3`
gfx_window_vulkan `0.3` -> `0.4`
**nonbreaking dependency updates**
gfx_device_gl `0.14.5` -> `0.14.6` _(gfx_gl)_
~gfx_core `0.7.2` -> `0.7.3`~
gfx `0.16.1` -> `0.16.2` _(release 427ab42134de4852bb5958b5326792133699c698)_

[v0.16] Update winit + glutin, bump versions

---

Cargo.toml
src/backend/gl/Cargo.toml
src/core/Cargo.toml
src/render/Cargo.toml
src/window/dxgi/Cargo.toml
src/window/glutin/Cargo.toml
src/window/vulkan/Cargo.toml

I thought it would be helpful to merge the bumped versions from _v0.16_ into _pre-ll_ to keep track of future releases more easily. If this isn't necessary feel free to simply close this PR.

Merge v0.16 version bumps into pre-ll

---

examples/hal/quad/main.rs

The hal/quad demo had two vertex shader push constant ranges that the vulkan validation layers were complaining about. I combined them into one range.
ERROR:gfx_backend_vulkan: [DS] vkCreatePipelineLayout() Duplicate stage flags found in ranges 0 and 1. The spec valid usage text states 'Any two elements of pPushConstantRanges must not include the same stage in stageFlags'

quick fix for invalid vulkan api usage (via validation layers)

---

examples/hal/quad/main.rs

slightly altered the image staging buffer code to do the same (needed to defer the buffer bind so i could get the requirements).
At least for the Image Buffer, this suppresses another Vulkan validation layer error, as i guess these buffers technically needed a little more memory than their input data size?
Also changed the second image barrier to transition to the fragment stage instead of END_OF_PIPE

allocating only as much memory as required for Buffers

---

src/backend/dx12/Cargo.toml
src/backend/dx12/src/command.rs
src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/native.rs
src/backend/dx12/src/pool.rs
src/backend/dx12/src/shade.rs
src/backend/dx12/src/window.rs

Worked around the lacking `Debug` derives using `derivative` crates and ignore the relevant winapi structs.
Most work was finding the relevant new type locations, shouldn't include any semantic changes.

Port to winapi 0.3

---

src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/pool.rs

Currently, `gfx/portability` uses `kvark/gfx` with the `portable` branch for obtaining the gfx repository. Moving this over to the main repository would make rebasing easier and centralizes information.
🔔 **NOTE** Don't merge this right now, as it would be merged into the master branch. Once we have a consensus on this change I will setup a new branch and redirect the PR.

Move the portable branch into main repository

---

examples/hal/compute/main.rs
examples/hal/quad/main.rs
src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/native.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/device.rs
src/hal/src/device.rs
src/render/src/device.rs
src/warden/src/gpu.rs

Stride was only needed for dx12 to use it for vertex buffer binding. The PSO stride and the stride on buffer creation needed to be equal, causing issues on the user side. Caching the vertex buffers and use the strides from the active PSO fixes this. Also, helps for better vulkan portability.

Remove stride parameter on buffer creation

---

examples/hal/compute/main.rs
examples/hal/quad/main.rs
examples/render/quad_render/main.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/gl/src/lib.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/hal/src/adapter.rs
src/hal/src/buffer.rs
src/hal/src/device.rs
src/hal/src/lib.rs
src/render/src/allocators/stack.rs
src/render/src/lib.rs
src/warden/src/gpu.rs

Fixes https://github.com/gfx-rs/gfx/issues/1671 https://github.com/gfx-rs/gfx/issues/1657 (set to 11.0)
Implements 2nd approach (open device -> query information -> close device) for dx12. For other backends only code has been shifted around.
Main motivation for this is vulkan portability, it doesn't provide new features.

Allow device information acquisition on physical devices

---

examples/hal/Cargo.toml
examples/hal/quad/main.rs
examples/render/quad_render/Cargo.toml
examples/render/quad_render/main.rs
src/backend/dx12/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml
src/window/dxgi/src/lib.rs

Update winit to the latest version, which introduced the Clone implementation for EventsLoopProxy. This winit feature is required to run Webrender tests/examples and servo in the future with gfx-hal.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/1686)

[hal] Update winit and glutin, bump version

---

examples/hal/compute/main.rs
examples/hal/quad/main.rs
src/backend/dx12/src/command.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/metal/src/command.rs
src/backend/vulkan/src/command.rs
src/hal/src/command/compute.rs
src/hal/src/command/graphics.rs
src/hal/src/command/raw.rs
src/hal/src/command/renderpass.rs
src/hal/src/command/transfer.rs
src/render/src/encoder.rs
src/render/src/macros/pipeline.rs

An attempt at #1604, I haven't yet implemented the changes for metal, dx11 & dx12 as I'm on Linux and don't trust myself without a compiler. The formatting is also currently all over the place. This is my first time using rust so I don't know if this is even what you were intending, but I'm happy to have a go at fixing anything.
Are there any more areas where slices should be replaced with iterators? I think I have hit all traits but there are some plain impls that could also be subjected to this (e.g. most of render/src/encoder.rs).
(I may have introduced some bugs, I can't run the examples as I'm also having trouble with vulkan :confounded:)

Replace Slices for Iterators in Command Buffer API

---

.travis.yml
examples/hal/quad/main.rs
src/backend/gl/Cargo.toml
src/backend/gl/src/command.rs
src/backend/gl/src/device.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/native.rs

Adds SPIRV-Cross GLSL compilation and fixed some trivial warnings. Most of the implementation is taken from DX12 backend for now.

[gl] Generate GLSL with SPIRV-Cross

---

src/backend/gl/src/window/glutin.rs

Added a simple implementation of `capabilities_and_formats` for the GL backend. I think it should be sufficient for now.
I left out `max_image_layers` for now because it would require access to the GL context.

[gl] Initial implementation of `capabilities_and_formats`

---

src/backend/gl/src/command.rs
src/backend/gl/src/queue.rs

It seems like `transmute` does not perform the expected slice conversion here. Switching to `from_raw_parts` seems to work correctly, but I'm not sure what the performance trade-off will be (in the long-term).

[gl] Switch `transmute` to `from_raw_parts`

---

src/backend/gl/src/command.rs
src/backend/gl/src/conv.rs
src/backend/gl/src/device.rs
src/backend/gl/src/native.rs
src/backend/gl/src/queue.rs

Use the primitive from the graphics pipeline for `Draw` and `DrawIndexed` commands.

[gl] Use primitive from graphics pipeline

---

src/backend/gl/src/command.rs
src/backend/gl/src/queue.rs

Cherry pick the first two commits from #1701 to reduce noise in the diff there. I think these commits are probably fine to merge in their current state.
- Clear during `begin_renderpass`
- Always `soft_reset` during `RawCommandBuffer::begin` to reset the command buffer state

[gl] Clear render pass start/always soft reset command buffers

---

examples/render/quad_render/Cargo.toml
examples/render/quad_render/main.rs
src/backend/metal/src/device.rs
src/backend/metal/src/window.rs

A shader with only optional function constants will be handled improperly by the current Metal backend, resulting in a crash. `MTLLibrary` distinguishes between creating a function without passing any specialization constants and creating a function with an empty list of specialization constants. If the function has only optional constants the former method produces a reflection-only function, while the latter produces a function suitable for inclusion in a PSO. This PR detects this edge case and handles it appropriately.
It also implements a few missing functions to get the `gfx_render` quad example working on Metal (the high level quad example also exercises the above edge case).

Fix handling of optional function constants in Metal backend

---

src/backend/gl/src/lib.rs
src/backend/metal/src/lib.rs
src/backend/vulkan/src/lib.rs
src/window/dxgi/src/lib.rs
src/window/metal/src/lib.rs
src/window/sdl/src/lib.rs

This addresses #506 for the pre-ll version, by filling the gaps on missing `Error` and `Display` implementations.
In the event that this procedure is also required in the latest versions, that can be arranged as well in a separate PR.

[pre-ll] Impl Display + Error for remaining error types

---

src/backend/dx12/src/command.rs

(Required for fixing `gfx_ocean`)

dx12: Fix compute descriptor tables

---

src/backend/gl/src/command.rs
src/backend/gl/src/conv.rs
src/backend/gl/src/device.rs
src/backend/gl/src/native.rs
src/backend/gl/src/queue.rs

This adds basic functionality to run the hal/quad example on the GL backend. Windows seems to work fine. OS X fails because the varying name doesn't match across vertex/fragment shaders, although I think this is supposed to work on 4.10.
~~WIP because there are a few format-related attribute arguments hardcoded (element type/size/stride) at the moment, but I'll probably wait for #1700 to fix them.~~

[gl] Make hal/quad example work on GL backend

---

src/backend/dx12/src/lib.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/gl/src/lib.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/lib.rs
src/hal/src/adapter.rs

Following Vulkan specification and required to get portability running with dx12.
Currently, implementation clones the adapter, but that's a hack and creating multiple devices would result in a mess as all would be the same device under the hood on dx12.

hal: Allow creating multiple logical devices from a physical device

---

.travis.yml
Makefile
reftests/scenes/basic.ron
src/backend/gl/src/device.rs
src/backend/gl/src/info.rs
src/warden/Cargo.toml
src/warden/src/bin/reftest.rs
src/warden/src/gpu.rs

This PR makes a few steps towards #583 goal of getting Warden running on CI:
- it splits the `gl` feature on Warden in to pure "gl" and software CI-compatible "gl-soft"
- makes Warden parse all the inputs before any backends are initialized, allowing us to at least stop breaking the test formatting (enabled on CI here)
- updates reftest RON files
- makes GL backend `create_framebuffer` to be compatible with OsMesa GL 2.1 context

Warden and GL improvements

---

.travis.yml
Makefile
src/backend/gl/src/command.rs
src/backend/gl/src/device.rs
src/backend/gl/src/native.rs
src/backend/gl/src/queue.rs
src/hal/src/command/transfer.rs
src/warden/Cargo.toml
src/warden/src/bin/reftest.rs

It's super annoying that GL doesn't have `GetTexSubImage`, which would make total sense in terms of API symmetry...
~~Next steps would be implementing the memory mapping.~~
Note:
We should probably use headless GL on CI. However, Travis Ubuntu 14.04 image only has an old "libosmesa6-dev" package that is not compatible with our `osmesa-sys`. Working around that doesn't appear to be trivial (but it is time consuming), and neither glutin or glium work on Linux CI either :/.
Fortunately, our headed GL context seems to be fine, so we are using that now.

[gl] Warden on CI, basic texture to buffer copies and memory mapping

---

examples/hal/compute/main.rs
examples/hal/quad/main.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/gl/src/lib.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/hal/src/adapter.rs
src/hal/src/backend.rs
src/hal/src/device.rs
src/hal/src/lib.rs
src/hal/src/queue/family.rs
src/hal/src/queue/mod.rs
src/hal/src/window.rs
src/render/src/lib.rs
src/warden/src/gpu.rs

Identify queue families by handle and use actual queue families only for device creation.
It hides the `RawQueueGroup` as implementation detail and gives the user a bit more contol over selecting the queue groups after creation.
Removes also the `open_with` function for now, as it's a bit awkward to use imo as we give up information about the order of queue families. I'm looking into replacing it with an alternative for single queue family selection using a filter, which is probably more common and sound.
Use-case scenario:
```rust
let adapter = instance.enumerate_adapters();
let (family_ids, families) = adapters.find_families(..);
let Gpu { device, queues } = adapter.open(families);
let main_queue = queues.take::<Graphics>(family_id[0]);
let compute_queue = …
```

[RFC] Refactor queue creation

---

src/hal/src/pso/descriptor.rs

This will allow structures with `B::DescriptorPool` field to be `Sync`.

Require `DescriptorPool` to be `Sync`

---

src/backend/dx12/src/command.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/gl/src/device.rs
src/backend/gl/src/native.rs
src/backend/gl/src/queue.rs
src/backend/metal/src/command.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/conv.rs
src/hal/src/command/graphics.rs
src/hal/src/command/mod.rs
src/hal/src/command/raw.rs
src/hal/src/format.rs

The Vulkan API uses unions for [clear value structs](https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkClearValue.html), so we don't know which enum variant to choose when implementing the portability layer.
Therefore, I added new `raw` variants for a few clear based commands using union structs for the clear values, which should be memory layout compatible with the vulkan union structs. The raw functions are only exposed by the raw command buffer interface as they don't have much use for normal gfx-rs API users.
`clear_attachments` is excluded as I quite confident that we can infer the enum variants from the associated information when calling the function in the portability layer.
**Suggestions/feedback are welcome!**
~~Only defining the API layer for now, implementation will …

[RFC] Expose raw, union-based clearing API for portability

---

src/backend/dx12/src/conv.rs

These may or may not work with spirv-cross so far but doesn't hurt implementing them all for now.

dx12: Convert remaining execution models

---

src/backend/vulkan/src/command.rs

Replace the original image extent with the region's extent.
Currently the image extent is ignored when mapping the region. This can cause unwanted memory overwrite.
cc @kvark 
(Also the image parameter is unused for now, i can remove it if you want)

Add correct image extent (vulkan)

---

src/backend/dx12/src/lib.rs
src/backend/dx12/src/window.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/queue.rs
src/backend/gl/src/window/glutin.rs
src/backend/metal/src/command.rs
src/backend/metal/src/window.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/window.rs
src/hal/src/command/raw.rs
src/hal/src/queue/mod.rs
src/hal/src/window.rs
src/render/src/lib.rs

Add a new `present` function to queues for multiswapchain presentation (at least in theory for non-vulkan backends for now).
Fixes https://github.com/gfx-rs/gfx/issues/1738

hal: Add multi swapchain presentation

---

examples/hal/quad/main.rs
src/backend/dx12/src/device.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/gl/src/native.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs
src/backend/vulkan/src/conv.rs
src/backend/vulkan/src/device.rs
src/hal/src/device.rs
src/hal/src/lib.rs
src/hal/src/pso/descriptor.rs
src/hal/src/range.rs
src/render/src/device.rs
src/render/src/pso.rs

Adds the Range abstraction discussed in #1749 
Supporting `..`, `a..`, `..b`, `a..b` and `(Option<_>, Option<_>)` (covering all prior mentioned cases).
**WIP**: Update gl, d3d12, metal and higher level crates
Fixes #1749

hal: Support various range types as function parameters

---

src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/native.rs

Tier1 devices expose 3 memory type groups (buffer only, image only and target only). We can only create a buffer for mapping in the first group. This PR fixes the exposed memory types and only creates buffers if possible (tier2 or tier1 buffer only and cpu visible).
The remaining issue are exposed image memory types, which should be only device local for tier1 (will be addressed in a followup). Vulkan requires us to expose at least one host-visible memory type for images supporting linear tiling. But we can circumvent this by not exposing any format supporting linear tiling at all for heap tier1 hardware..
Fixes #1756 
cc @Rhuagh @AlphaModder 
NOTE: This PR is written against the generic range type PR.

dx12: Fix tier1 resource creation

---

.travis.yml
reftests/data/fill.comp
reftests/data/passthrough.vert
reftests/scenes/basic.ron
reftests/scenes/compute.ron
reftests/suite.ron
src/warden/Cargo.toml
src/warden/src/bin/reftest.rs
src/warden/src/gpu.rs
src/warden/src/raw.rs

There was quite a few things missing to get compute tested:
- buffer support (oh...)
- ability to read a buffer
- compute pipeline resources and binding
- compute jobs
- descriptor updates
- actual ref-test for compute
Unfortunately, this isn't enough still. TODO:

Warden compute support

---

src/hal/src/adapter.rs
src/hal/src/queue/family.rs

These are edits to a couple parts of the documentation that annoyed me as I was reading through
PR checklist:

Tweak documentation in a couple places

---

examples/hal/compute/main.rs
examples/hal/quad/main.rs
src/hal/src/adapter.rs
src/render/src/lib.rs
src/warden/src/gpu.rs

PR checklist:
\* Unrelated, but the command is actually `make reftests` (plural). The PR template should probably be updated...

Simplify interface for Adapter::open_with

---

.travis.yml
Makefile
reftests/suite.ron
src/backend/dx12/src/lib.rs
src/backend/gl/Cargo.toml
src/backend/gl/src/command.rs
src/backend/gl/src/device.rs
src/backend/gl/src/info.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/pool.rs
src/backend/gl/src/queue.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/lib.rs
src/hal/src/lib.rs
src/warden/Cargo.toml
src/warden/examples/basic.rs
src/warden/src/bin/reftest.rs
src/warden/src/gpu.rs

The main reasoning behind using bitflags is not as much an economy of space but the ability to check for intersections and do mathematical set-related operations for Warden. As such, I want to specify which features are affected by a test, so that the framework can skip backends that we know (at run-time) are not capable of running this test. This is way better than current crashing on, say, GL compute.
Requesting early feedback since converting all the backends is considerable amount of work.

Convert HAL features to bitflags, move legacy out

---

examples/hal/quad/main.rs

Implements the requested changes from https://github.com/gfx-rs/gfx/pull/1636
(Had to scope the pipelines description again due to lexical lifetimes...)

quad: Move shader creation and destruction into pipeline creation

---

src/backend/metal/src/command.rs

PR checklist:
Wasn't working before also.
- Metal. They wasn't using this method anyway.

Metal update buffer

---

src/backend/dx12/Cargo.toml
src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/native.rs
src/backend/dx12/src/pool.rs
src/backend/dx12/src/shade.rs

~~~Currently fails due to new nullptr assert.~~~
Should only be merged once a new crates.io version has been published.
Fixes https://github.com/gfx-rs/gfx/issues/1754

dx12: Update to latest wio version

---

src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/window.rs

vk: Update to winapi 0.3

---

examples/hal/compute/main.rs

Fix buffer usage flags in compute example and destroy command pool

---

src/backend/dx12/src/conv.rs

PR checklist:
(untested but should work..)

dx12: Expose D32Float format

---

examples/hal/compute/main.rs
examples/hal/quad/main.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/native.rs
src/backend/dx12/src/root_constants.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/gl/src/device.rs
src/backend/gl/src/native.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/native.rs
src/hal/src/command/compute.rs
src/hal/src/command/graphics.rs
src/hal/src/command/raw.rs
src/hal/src/command/renderpass.rs
src/hal/src/device.rs
src/hal/src/pso/descriptor.rs
src/hal/src/queue/submission.rs
src/render/src/device.rs
src/render/src/lib.rs
src/render/src/pso.rs
src/warden/src/gpu.rs
src/window/glfw/src/lib.rs

A more debatable half of #1604, which APIs use slices and which should use iterators is more up for consideration. My implementation for the Device iterators frequently just collects them anyway which to me suggests there isn't much point (apart from some idea of API uniformity).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/1665)

Replace iterators with slices (Non command buffer)

---

src/hal/src/device.rs

PR checklist:
metal, gl
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/1792)

Fix flushing and invalidating by helpers

---

src/backend/dx12/src/format.rs
src/backend/dx12/src/lib.rs
src/hal/src/format.rs

Implementing format properties in dx12, mostly all formats are unsupported for now. Need to gradually implement more over the time..
Another point is to try merging format conversion and format properties in a follow up.
PR checklist:

dx12 : format properties

---

src/backend/vulkan/src/pool.rs

Use ash reset_command_pool

---

src/backend/dx12/src/command.rs
src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/native.rs
src/backend/metal/src/native.rs
src/backend/vulkan/src/conv.rs
src/backend/vulkan/src/device.rs
src/hal/src/pso/descriptor.rs

Add support for combined image samplers (vulkan and dx12 only). Missing register space adjustment for sampler part, not able in spirv-cross atm.
Fix a bunch of other bugs on the go:
* dx12: vertex attributes check to conservative
* dx12: clear values where stencil and color/depth are cleared at the same time
* dx12: buffer copy allows to specify 0 for row length and height if they shall match image extents
* dx12: typo in descriptor size for SrvCbvUav
PR checklist:

Combined image samplers

---

Makefile
src/backend/gl/README.md
src/backend/metal/README.md
src/backend/vulkan/Cargo.toml
src/backend/vulkan/README.md
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/window.rs

Allows https://github.com/gfx-rs/portability/pull/30 to proceed
PR checklist:

Mandatory XCB dependency

---

src/backend/dx12/src/lib.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/lib.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/vulkan/src/lib.rs
src/hal/src/adapter.rs

Make it possible to query whether queue supports presentation on surface after queues creation
PR checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/1811)

Tweak surface presentation support

---

examples/hal/compute/main.rs
examples/hal/quad/main.rs
src/backend/dx12/src/device.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/device.rs
src/hal/src/device.rs
src/hal/src/pso/descriptor.rs
src/render/src/pso.rs
src/warden/src/gpu.rs

PR checklist:
This PR avoids the need to allocate vectors just for descriptor updates. It also introduces a separate `Device` entry point for descriptor copies, implemented on Vulkan only at the moment.

Descriptor set updates and copies

---

src/lib.rs

This commit uses `.poll_events()` to allow processing multiple events per rendered frame. (Before, only one event was processed per frame.) This is necessary because it's easy for the user to generate events much faster than frames can be rendered (e.g. by moving the mouse).
Additionally, with `.run_forever()`, rendering blocked on receiving events. (An event had to occur before a frame was rendered.) In order to see an animation such as the `particle` example, the user had to generate events fast enough to cause frames to be rendered (e.g. by moving the mouse over the window).
See also https://github.com/tomaka/winit/issues/276 and https://github.com/tomaka/winit/issues/231
PR checklist:
I don't see a Makefile. `make` says `make: *** No targets specified and no makefile found.  Stop.`
I …

Switch from .run_forever() to .poll_events() in gfx_app

---

examples/hal/quad/main.rs
src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/window.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/gl/src/device.rs
src/backend/gl/src/window/glutin.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/window.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/native.rs
src/backend/vulkan/src/window.rs
src/hal/src/command/graphics.rs
src/hal/src/command/mod.rs
src/hal/src/command/raw.rs
src/hal/src/command/render_pass.rs
src/hal/src/device.rs
src/hal/src/window.rs
src/render/src/handle.rs
src/render/src/macros/pipeline.rs
src/warden/src/gpu.rs

Fixes #1827
PR checklist:
- Metal
On running `make refests` I get the following:
```
Parsing test suite 'local'...
Warding Metal:
Scene 'transfer':
Test 'copy' ... ran: FAIL [0, 0, 0, 0]
Command buffer re-use is not ready, exiting
Warding GL:
Scene 'transfer':
Test 'copy' ... ran: PASS
Scene 'compute':
skipped 1 tests (GLSL shaders)
Scene 'basic':
skipped 2 tests (GLSL shaders)
TestResults { pass: 1, skip: 3, fail: 0 }
make: *** [reftests] Error 1
```
I'm not sure what this means, but I don't think it was this that broke it. I'm assuming the message means that command buffer re-use isn't implemented yet for Metal?

Fix #1827: Naming / casing issues

---

examples/hal/quad/main.rs
examples/render/quad_render/main.rs
examples/support/deferred/main.rs
src/backend/dx11/src/device.rs
src/backend/dx11/src/execute.rs
src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/window.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/window/glutin.rs
src/backend/metal/src/device.rs
src/backend/metal/src/window.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/window.rs
src/hal/src/adapter.rs
src/hal/src/error.rs
src/hal/src/image.rs
src/hal/src/window.rs
src/render/src/encoder.rs
src/render/src/lib.rs
src/render/src/pso.rs
src/support/src/shade.rs
src/warden/src/bin/reftest.rs
src/warden/src/gpu.rs

Fixes #1833
PR checklist:
- Metal

Fix #1833: Change getter names to follow Rust conventions

---

src/hal/src/command/mod.rs
src/hal/src/command/render_pass.rs
src/hal/src/device.rs
src/hal/src/queue/mod.rs
src/hal/src/queue/submission.rs

Proper naming of conversion functions.

---

src/backend/dx12/src/command.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/native.rs
src/backend/dx12/src/pool.rs
src/backend/dx12/src/window.rs
src/backend/gl/src/device.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/native.rs
src/backend/gl/src/queue.rs
src/backend/gl/src/window/glutin.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs
src/backend/metal/src/window.rs
src/hal/src/adapter.rs
src/hal/src/command/raw.rs
src/hal/src/device.rs
src/hal/src/lib.rs
src/hal/src/pool.rs
src/hal/src/queue/family.rs
src/hal/src/queue/mod.rs
src/hal/src/window.rs

Place `Send + Sync` bound on everything in `Backend`.
Add `single-threaded` feature that removes `Send + Sync` bounds from some objects of `Backend`.
OpenGL backend requires `single-threaded` feature.
Some types from metal backend weren't `Send` or `Sync`.
Either their public methods takes `&mut self` and they don't share internal state.
Or metal docs says that they are internally synchronised.
The only exception is `RawCommandBuffer`. But it already was `Send` making use of it unsafe. Adding `Sync` can't make things to worse.
Let IC checks vulkan and dx12 as I can't compile them.
PR checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/1820)

Make exposed objects send+sync.

---

src/backend/vulkan/src/conv.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs

Fixes Vulkan validation warning:
> vkCreateSampler(): The samplerAnisotropy feature was not enabled at device-creation time, so the maxAnisotropy member of the VkSamplerCreateInfo structure must be 1.0 but is 0.000000.
PR checklist:

[vk] better anisotropy sampling checks

---

src/backend/vulkan/src/device.rs
src/hal/src/pso/graphics.rs

Follow-up to #1846
Fixes Vulkan validation warning:
> vkCreateGraphicsPipelines(): the depthClamp device feature is disabled: the depthClampEnable member of the VkPipelineRasterizationStateCreateInfo structure must be set to VK_FALSE. The spec valid usage text states 'If the depth clamping feature is not enabled, depthClampEnable must be VK_FALSE' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkPipelineRasterizationStateCreateInfo-depthClampEnable-00782)
Also enables framebuffer images to be used as clear/transfer/blit destinations.
PR checklist:

 [vk] careful depth clamping check 

---

src/backend/dx12/src/lib.rs

Fixes #1851 
PR checklist:
- dx12
Even if we couldn't initialize debug_controller, we would always try to call Release,
sometimes on a null ptr. Now only Release the debug_controller if we could get it
successfully.

Fix #1851: Crash on dx12

---

src/backend/dx12/src/command.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/gl/src/device.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs
src/backend/metal/src/soft.rs
src/backend/metal/src/window.rs
src/backend/vulkan/src/command.rs
src/hal/src/command/compute.rs
src/hal/src/command/raw.rs
src/hal/src/command/render_pass.rs
src/hal/src/command/transfer.rs
src/hal/src/device.rs
src/hal/src/pso/input_assembler.rs
src/warden/src/bin/reftest.rs

[metal] Re-usable command buffers

---

Cargo.toml
src/backend/gl/Cargo.toml
src/lib.rs
src/window/dxgi/Cargo.toml
src/window/glfw/Cargo.toml
src/window/glutin/Cargo.toml
src/window/metal/Cargo.toml
src/window/sdl/Cargo.toml
src/window/vulkan/Cargo.toml

Dependency update for glutin/winit + gfx_gl
* gfx_device_gl -> `0.16`
- gfx_gl -> `0.5`
* gfx_window_dxgi -> `0.12`
- winit -> `0.11`
* gfx_window_glfw -> `0.17`
- gfx_device_gl -> `0.16`
* gfx_window_glutin -> `0.21`
- glutin -> `0.13`
- gfx_device_gl -> `0.16`
* gfx_window_metal -> `0.5`
- winit -> `0.11`
* gfx_window_sdl -> `0.9`
- gfx_device_gl -> `0.16`
* gfx_window_vulkan -> `0.5`
- winit -> `0.11`
Also update gfx_app's dev-dependencies
PR checklist:
- ~`make` succeeds (on *nix)~ _pre-ll_
- ~`make reftests` succeeds~ _pre-ll_

[pre-ll] Update glutin, winit, gfx_gl

---

src/backend/vulkan/src/device.rs

Fixes #1872 
PR checklist:
- hal/quad (vulkan)

Add TRANSFER_SRC usage flag for swapchain images

---

appveyor.yml
src/backend/gl/Cargo.toml
src/backend/gl/src/tex.rs

Related to #1881
Forces the texture-to-buffer copies to go through FBO path if only a sub-texture is needed instead of panicing.

[0.17/gl] improved texture copies

---

src/backend/vulkan/src/lib.rs

vulkan: Fix unsound conversion of `&str` to `CStr`

---

Makefile
src/backend/dx12/src/command.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/conv.rs
src/hal/src/command/transfer.rs
src/hal/src/image.rs
src/render/src/encoder.rs
src/render/src/pso.rs

As discussed on Gitter, this changes the `Subresource` and `ImageCopy` structs to match the Vulkan API.
`Subresource` is `Copy` because it's just three ints, and because the previous `Subresource` type (a tuple of two ints), was also copy and some existing code assumes this.
I had to change the DirectX and Vulkan code blind as I can't compile them, so as well as the CI, perhaps @kvark and/or @msiglreith can take a look at that especially.
PR checklist:

Change Subresource and ImageCopy to match Vulkan API

---

src/backend/vulkan/src/device.rs

Fixes the following error:
```
ERROR:: [DS] Object: 0x7f2b421a6e00 | vkCmdSetBlendConstants(): pipeline was created without VK_DYNAMIC_STATE_BLEND_CONSTANTS flag. The spec valid usage text states 'The currently bound graphics pipeline must have been created with the VK_DYNAMIC_STATE_BLEND_CONSTANTS dynamic state enabled' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkCmdSetBlendConstants-None-00612).
```
This is just a workaround. The ultimate solution should be passing these dynamic states at creation.
PR checklist:

[vk] Add BlendConstants to DynamicState

---

src/hal/src/device.rs

Implement std::error::Error on FrameBufferError

---

src/backend/dx12/src/command.rs

Replaces  #1877
Fixes #1843
PR checklist:

[dx12] aligned buffer-image copies

---

src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/conv.rs
src/backend/vulkan/src/device.rs

Fixes `unimplemented!()` entry in VK backend, updates the clear color semantics.
PR checklist:

[vk] ash update, destroy buffer view

---

src/backend/dx11/src/command.rs
src/hal/src/adapter.rs
src/hal/src/device.rs
src/hal/src/queue/capability.rs
src/hal/src/queue/mod.rs
src/hal/src/window.rs

Remove unnamed parameters in traits

---

src/backend/dx12/src/window.rs

Fixes #1826 
PR checklist:
- DX12

DX12 surface only supports present queue

---

src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs

Because of the way Swapchains are implemented, Xcode's frame capture
gets confused on where the frame starts and ends (which is the default
capture scope).
This commit creates a capture scope that tries to mimic the usual
behaviour. Enabled only when debug_assertations is on.
Fixes #issue
PR checklist:
I was just noodling around and this annoyed me a bit. The commit may not quite be ready for merge, perhaps those classes/methods should be exposed in metal-rs first?

metal: Add debug capture scopes

---

examples/hal/quad/main.rs
src/backend/dx12/src/device.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/device.rs
src/hal/src/device.rs

This fixes the Vulkan object tracker error in the _hal/quad_ example:
```
ERROR 2018-04-06T18:20:46Z: gfx_backend_vulkan: [ObjectTracker] OBJ ERROR : For device 0x2a20eda1c50, SwapchainKHR object 0x3 has not been destroyed. The spec valid usage text states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-vkDestroyDevice-device-00378)
```
PR checklist:
- DX12
- GL
- Vulkan

Add destroy_swapchain method and update example

---

src/backend/vulkan/src/lib.rs

Might help with https://github.com/msiglreith/gfx_ocean/issues/8
Considering the warnings/issues with the vulkan loader, we might want to consider using a specific value..
PR checklist:

Set vulkan version

---

src/backend/gl/src/device.rs

The _hal/quad_ example would crash when running in GL mode, because a lot of the destroy methods where not implemented.
PR checklist:
- GL

Make hal/quad runnable with GL

---

Cargo.toml
src/window/dxgi/Cargo.toml
src/window/glutin/Cargo.toml
src/window/glutin/src/lib.rs
src/window/metal/Cargo.toml
src/window/vulkan/Cargo.toml

Fixes [multiple issues with X11 and macOS](https://github.com/tomaka/winit/blob/master/CHANGELOG.md#version-0120-2018-04-06). Most importantly for me is the HiDPI fix for macOS, which affects dependents such as: https://github.com/Gekkio/imgui-rs/issues/98
PR checklist:
`make` is N/A because this is for `pre-ll`

[pre-ll] Update glutin and winit

---

src/backend/vulkan/src/info.rs
src/backend/vulkan/src/lib.rs

[vk] disable dual-source blending on Intel/Windows

---

examples/hal/quad/main.rs
src/backend/dx12/src/command.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/gl/src/queue.rs
src/backend/metal/src/command.rs
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/command.rs
src/hal/src/command/graphics.rs
src/hal/src/command/raw.rs
src/hal/src/command/render_pass.rs
src/render/src/macros/pipeline.rs
src/warden/src/gpu.rs

Fixes #1824
PR checklist:
The state cache impl for dx12 inside the command buffer is not the cleanest, and we don't have the most recent Metal interfaces for multiple viewports, so metal support remains as-is.
Todo: ~~warden support~~, ~~waiting on upstream ash support for cmd_set_scissors~~.

[WIP] Support setting scissors/viewports from starting index

---

src/backend/dx12/src/command.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/metal/src/command.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/conv.rs
src/hal/src/command/mod.rs
src/hal/src/command/raw.rs
src/hal/src/pool.rs
src/hal/src/query.rs

Add `CommandBufferInheritanceInfo` which is nonnull for secondary command buffers. It is necessary for portability to continue the CTS.
PR checklist:

Add inheritance info to begin command buffer

---

info/getting_started.md

compilation fails without libxcb1-dev and xorg-dev packages in ubuntu. so added them to list of packages to install

added additional x11 and vulkan dev dependencies

---

Cargo.toml
src/window/dxgi/Cargo.toml
src/window/glutin/Cargo.toml
src/window/glutin/src/lib.rs
src/window/metal/Cargo.toml
src/window/vulkan/Cargo.toml

PR checklist:
No make on 0.17.

[v0.17] Update glutin and winit

---

src/backend/dx12/src/command.rs

Fixes part of https://github.com/szeged/webrender/issues/73#issuecomment-381637301
PR checklist:
r? @dati91 @msiglreith

[dx12] row pitch calculation fix for the worst case image-buffer copies

---

examples/hal/Cargo.toml
examples/hal/quad/main.rs
examples/render/quad_render/Cargo.toml
src/backend/dx12/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/metal/src/conversions.rs
src/backend/metal/src/device.rs
src/backend/metal/src/window.rs
src/backend/vulkan/Cargo.toml

Improves the CTS support.
PR checklist:
~~A follow-up is planned to use https://github.com/gfx-rs/metal-rs/pull/37 , but it doesn't have to go here.~~

[mtl] dependencies, dpi, more formats

---

src/backend/dx12/src/command.rs

[dx12] fix layer offset for the buffer footprint

---

src/backend/dx12/src/device.rs

Don't change the descriptor table space values for cbv/srv/uav and samplers. HLSL has additional signature parameter by indicating the descriptor type allowing to live two sets in harmony together.
Fixes combined image samplers for dx12!
PR checklist:

Adjust dx12 root descriptor set spaces

---

src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs

Set anisotropic filter when defined

---

src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/format.rs
src/hal/src/format.rs

* fix SRV format for depth stencil view
* expose more format information for BC formats
* fix buffer offset for buffer to image copies (bytes vs texels)
* fix number of bytes for rgba16 formats
Fixes #1957

Smaller dx12 bug fixes

---

src/backend/dx12/Cargo.toml
src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs

* bump spirv_cross for specialization constant fixes (fixes a few Vulkan samples)
* fix depth clipping (inverse of vulkan's depth clamping)
* silence debug layer warning: `pInputElementDesc` might be non-zero for empty vec's triggering a warning
* expose wireframe polygon fill mode (fixes pipeline example)

Further dx12 fixes

---

src/backend/dx12/src/command.rs

Fixes https://github.com/gfx-rs/gfx/issues/1963
Tested the example locally with dx12

dx12: Fix buffer offset for copy splitting

---

src/backend/metal/src/command.rs

Fixes #issue
PR checklist:
`metal`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/1967)

Fix memory options for upload_buffer method

---

src/backend/dx12/src/lib.rs

The code simply checks if the flag for software rendering is set for the adapter to determine if WARP was enabled.
Fixes #issue
PR checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/1969)

[dx12] Check for WARP driver

---

examples/hal/quad/main.rs
examples/render/quad_render/main.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs

Use autorelease pools internally in Metal backend

---

src/backend/dx12/src/lib.rs

See https://github.com/gfx-rs/gfx/issues/1945#issuecomment-384558682
PR checklist:
As a side note I noticed `make reftests` is failing on dx12 for me (on master).

dx12: Increase descriptor heap limits temporarily

---

src/backend/metal/src/device.rs

Fixes #1948 (several CTS errors)
PR checklist:
Some notes:
- Resource size still labeled as `TODO`: maximum texture size is unknown, so I've increased it for now. I think this is probably okay because it's still possible for image creation to fail (see [the note about this in the Vulkan specification](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkImageFormatProperties.html)). I've filed a bug report with Apple to ask whether the feature set tables could be expanded to include this information. The only maximum resource size listed at the moment is for buffers, which doesn't apply to textures that aren't backed by a `MTLBuffer`, see for example [this forum post discussing this limit](https://moltengl.com/forums/topic/uploading-large-texture-data/).
- It appears we …

mtl: Image format properties

---

examples/hal/compute/main.rs
examples/hal/quad/main.rs
src/hal/src/command/mod.rs
src/hal/src/device.rs
src/hal/src/pool.rs
src/hal/src/queue/family.rs
src/hal/src/queue/mod.rs
src/warden/src/gpu.rs

This allows middle-level crates to use raw command pools and queues while providing typed for higher-level code.
PR checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/1970)

Provide unsafe methods to convert raw command pool and queue into typed

---

examples/hal/quad/main.rs
reftests/scenes/basic.ron
src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/native.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/hal/src/lib.rs
src/hal/src/pass.rs
src/hal/src/pso/graphics.rs
src/render/src/macros/pipeline.rs
src/warden/src/gpu.rs
src/warden/src/raw.rs

* hal: Add resolve attachments, limits and multisampling desc to pso
* dx12: Handle sampling settings for images and pipeline states
* dx12: Add resolve operations for renderpasses
* dx12: Update resource barriers between subpasses
TODO:
Fixes https://github.com/gfx-rs/gfx/issues/1542
PR checklist:

Initial multisampling support

---

src/backend/dx12/src/command.rs

Tested against a few of the vulkan samples, hit every path at least once iirc.

dx12: Block compressed format support for buffer-image copies

---

src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/native.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/device.rs
src/hal/src/pso/descriptor.rs

Untested so far, probably requires small changes to portability due to API breakage.

dx12: Implement buffer views

---

examples/hal/quad/main.rs
src/backend/dx11/src/command.rs
src/backend/dx12/src/command.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/metal/src/command.rs
src/backend/vulkan/src/command.rs
src/hal/src/command/graphics.rs
src/hal/src/command/raw.rs
src/hal/src/command/render_pass.rs
src/render/src/macros/pipeline.rs
src/warden/src/gpu.rs

Implements #1684
I want to start contributing to this project and this issue seemed like a good introduction. I apologize if I'm not doing something according to procedures.
Tested on Windows 10 with `dx12` and `vulkan` backends, Ubuntu 18.04 with `vulkan`, and macOS 10.13 with `metal`.
One thing I noticed while adding this that seemed a little bit awkward is that `GraphicsPipelineDesc::vertex_buffers` doesn't provide any way to skip around binding indices. The roughly equivalent part of Vulkan, `VkVertexInputBindingDescription`, allows you to specify the binding `index` explicitly along with the `stride` and `rate` instead of just making it implicit. Food for thought.
PR checklist:

[ll] First slot for vertex buffer binding

---

src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/metal/src/command.rs
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/device.rs
src/hal/src/command/graphics.rs
src/hal/src/command/raw.rs
src/hal/src/command/render_pass.rs
src/hal/src/pso/graphics.rs

Stubs and DirectX 12 amd Vulkan implementations of #1737
PR checklist:

[ll] Depth bounds test

---

Makefile
src/backend/metal/shaders/commands.metal
src/backend/metal/src/command.rs
src/backend/metal/src/conversions.rs
src/backend/metal/src/device.rs
src/backend/metal/src/internal.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs
src/backend/metal/src/window.rs
src/hal/src/image.rs

Fixes #2006
(note: also disables d32s8 for now)
Brings the following goodies:
- actually working blits. I was missing the Y-flip in rendering, which I encoded into the viewport now.
- proper fast-path for copy_image. I screwed the src/dst arguments...
- basic integer support for blit shaders (to be extended)
- retained textures
- non-equal formats support for copy_image (not verified by CTS yet)
Overall with this change, I was able to get through "api.copy_and_blit.core.blit_image.all_formats.color" section with the following stats:
- 3538 successes
- 29 failures (!)
- 15 crashes
The failures/crashes don't appear systematic, may be caused by #1984
PR checklist:

[mtl] Improved blitting

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs

~~Only the last commit matters. Eventually to be rebased on #2004.~~
Greatly reduces the amount of unsafety we have in the backend, at the cost of a bit of extra verbosity.
The idea previously was that since the API isn't valid for accessing the same command buffer concurrently, we don't need to check for that at run-time. I believe it's a wishful thinking, and a footgun for possible unexpected issues.
Unless proven otherwise (by benchmarks), we should stick to safe Rust and be kept in warm and safety by the combination of type (where possible) and run-time checks.
PR checklist:

Remove UnsafeCell from Metal

---

examples/hal/quad/main.rs
src/backend/dx12/src/device.rs
src/backend/gl/src/command.rs
src/backend/gl/src/device.rs
src/backend/gl/src/native.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/device.rs
src/hal/src/pso/input_assembler.rs
src/render/src/pso.rs

Implements #1994
PR checklist:

[ll] Explicit binding parameter for vertex bindings

---

src/backend/dx12/src/lib.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/lib.rs
src/hal/src/lib.rs
src/warden/src/gpu.rs

[mtl] Only invalidate/flush on memory map/unmap for coherent types, fix size alignment

---

reftests/local.ron
reftests/scenes/transfer.ron
src/backend/dx12/src/command.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/metal/Cargo.toml
src/backend/metal/shaders/commands.metal
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/internal.rs
src/backend/metal/src/native.rs
src/backend/metal/src/window.rs
src/backend/vulkan/src/command.rs
src/hal/src/command/graphics.rs
src/hal/src/command/raw.rs
src/hal/src/command/render_pass.rs
src/render/src/encoder.rs
src/warden/src/gpu.rs
src/warden/src/raw.rs

Fixes #2007
Depends on https://github.com/gfx-rs/metal-rs/pull/49
With this PR as well as the upcoming portability changes, we can go through the whole `api.image_clearing` section (on Metal) without crashes. 143 passes and 216 failures at the moment, out of 1027 tests in total.
PR checklist:

Out-of-pass image clears

---

src/backend/metal/src/conversions.rs
src/backend/metal/src/device.rs

Fixes #2019
(finally had a good reason to learn "git bisect", at last)
The image views should be robust now. Unfortunately, related CTS tests fail because one of the buffers used in their compute somehow ends up with offset of 5 being bound, which is not supported by Metal. Need to investigate more (later).
PR checklist:

Metal image views

---

src/backend/dx12/shaders/blit.hlsl
src/backend/dx12/src/command.rs
src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/format.rs
src/backend/dx12/src/internal.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/pool.rs

Revives work of #2001
PR checklist:

Blitting for dx12

---

src/backend/dx12/src/lib.rs

This is a small but important piece we need for dx12 blitting (after #2028). CTS results for "dEQP-VK.api.copy_and_blit.core.blit_image" are:
- Passed: 110
- Failed: 0 (!)
- Not supported: 44964
Formally speaking, we pass this test :) :tada: 
PR checklist:

[dx12] filter out unknown formats

---

src/backend/dx12/src/command.rs
src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/native.rs

Brings our image-image copies to the level where only depth/stencil is failing (on CTS) :tada: 
PR checklist:

[dx12] temporary image aliases for copies of different formats

---

src/backend/metal/src/device.rs

Temporary workaround so we can prevent some crashes in portability.
PR checklist:

mtl: Add temporary workaround for validation issue

---

src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs
src/hal/src/format.rs

Fixes all of the image related copy/blit CTS tests (>11K passes!). There are 0 failures in this category now and ~5 crashes due to #1945.
PR checklist:

Format packing semantics, dx12 handling

---

src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/native.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/metal/src/command.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/conv.rs
src/hal/src/command/raw.rs
src/hal/src/command/render_pass.rs
src/hal/src/pso/graphics.rs

Replaces the `Rect` in `clear_attachments` with `ClearRect` to allow for clearing layers in an attachment. Only implemented for vulkan & dx12 for now.
PR checklist:

[ll] layer range for clear_attachments

---

src/backend/gl/src/device.rs

Downgrades error to warning

---

src/backend/dx11/src/device.rs
src/backend/dx11/src/lib.rs
src/backend/dx11/src/state.rs
src/backend/dx12/src/command.rs
src/backend/dx12/src/conv.rs
src/backend/dx12/src/lib.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/command.rs
src/hal/src/command/graphics.rs
src/hal/src/command/raw.rs
src/hal/src/command/render_pass.rs

Just implementing stubs for `set_line_width` to help with portability crashes. No-ops on DX12 and Metal because it doesn't seem we have any way to expose it there (at least at first glance), so we simply don't expose `wideLines` as a feature and force `1.0` as the line width.
(I haven't actually tried to build the Vulkan and DX12 backends yet, so CI may fail here – I'll fix later if it does)
PR checklist:

Implement `set_line_width`

---

src/hal/src/command/graphics.rs

Restrict render pass begin usage

---

Cargo.toml
src/window/dxgi/Cargo.toml
src/window/glutin/Cargo.toml
src/window/metal/Cargo.toml
src/window/vulkan/Cargo.toml

Bump affected `gfx_window_glutin`, `gfx_window_dxgi`  versions for release
PR checklist:

[pre-ll] Update winit -> 0.15, glutin -> 0.16

---

Cargo.toml
src/window/dxgi/Cargo.toml
src/window/glutin/Cargo.toml
src/window/metal/Cargo.toml
src/window/vulkan/Cargo.toml

Bump affected `gfx_window_glutin`, `gfx_window_dxgi`  versions for release
PR checklist:

[v0.17] Update winit -> 0.15, glutin -> 0.16

---

src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/conversions.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs
src/backend/metal/src/window.rs

Fixes #2069
~~Includes #2070 (please only review the last 2 commits)~~
The PR effectively removes all the complicated memory allocation tracking from the Metal backend, instead relying on mapping the available storage types (with CPU caching policy) more accurately to what can be represented in Vulkan API.
With this in, we slice through the whole `memory` section without crashes. The only issue I failed to fix/workaround is filed as #2077
PR checklist:

Metal revised memory types

---

src/backend/dx11/src/lib.rs
src/backend/dx12/src/command.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs
src/backend/metal/src/soft.rs
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/device.rs
src/hal/src/command/graphics.rs
src/hal/src/command/raw.rs
src/hal/src/command/render_pass.rs
src/hal/src/pso/graphics.rs

Fixes some CTS Metal issues with dynamic depth bias, or possibly areas where static depth bias is applied (through rasterizer info)
~~Depends on MaikKlein/ash#65~~
PR checklist:

Implement `set_depth_bias`

---

src/backend/dx12/src/lib.rs

dx12: expose access to native device pointer for ffi

---

examples/hal/compute/main.rs
examples/hal/quad/main.rs
reftests/scenes/compute.ron
src/backend/dx11/src/lib.rs
src/backend/dx12/src/device.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs
src/backend/vulkan/src/device.rs
src/hal/src/device.rs
src/hal/src/pso/descriptor.rs
src/render/src/device.rs
src/render/src/macros/descriptors.rs
src/warden/src/gpu.rs
src/warden/src/raw.rs

Immutable samplers

---

src/backend/gl/src/lib.rs

Only call `glDrawArraysInstancedBaseInstance` when base is non-zero & `instance_base_supported`. Fixes OpenGL 3.2 instance rendering (https://github.com/alexheretic/gfx-glyph/issues/26).
PR checklist:

[pre-ll] Call glDrawArraysInstanced when base=0

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs

This is a follow-up to #2078, which fixes an issue where a vertex buffer wouldn't be bound upon switching the PSO after binding vertices.
PR checklist:

[mtl] Lazier vertex buffer binding

---

src/backend/metal/src/device.rs

Fixes #2080
Related to #2069
All 1568 tests of the "dEQP-VK.texture.filtering" are passing now :tada: :tada: :tada: 
PR checklist:

Metal shared memory and sampling states

---

src/backend/metal/shaders/blit.metal
src/backend/metal/shaders/clear.metal
src/backend/metal/shaders/commands.metal
src/backend/metal/shaders/fill.metal
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs

Fixes:
- all of the "generate_mipmaps" section of CTS, adding about 1K passes to our collection ;) No failures/crashes there
- all of the "texture.shadow" tests of the CTS, adding 300 passes ;)
Note: I'm slightly confused about the interaction of `set_resource_options` versus `set_storage_mode` and `set_cpu_cache_mode`. So far it looks like those affect the same bits, so I'm not issuing redundant commands any more.
PR checklist:

Metal mipmapping, private depth/stencil storage, and other goodies

---

reftests/local.ron
src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/native.rs

Map input attribute id to input binding to work around issues where attribute offsets are larger than the vertex stride. Current mapping strategy is naive, mapping one attribute to one binding. Better packing would be useful but only provides performance improvements.
Tested against several samples and the CTS texture reftests look reasonable but fail due to lack of freeDescriptorSets implementation.
PR checklist:

dx12: remap vertex bindings

---

src/backend/metal/shaders/blit.metal
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/internal.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs
src/backend/metal/src/soft.rs

Fixes #2069
Fixes #2094
Fixes #2092 
This PR accumulated quite a few seemingly unrelated changes, but all rather tasty ones:
- one mega-queue instead of a queue pool
- condvars for fences
- enabled coherent memory
- inverted depth range workaround
- depth blits
PR checklist:

Metal mega-queue, coherent memory, and other goodies

---

src/backend/dx11/src/conv.rs
src/backend/dx11/src/lib.rs
src/backend/dx11/src/shader.rs

Adds basic pipeline creation and some plumbing for creating/converting from hal to dx11 state. The shader stuff is mostly from the dx12 backend without the root signature stuff, need to investigate how much patching needs to be done on the output (SM 5.0 vs 5.1)
PR checklist:

[dx11] add graphics pipeline creation & shader module creation

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/internal.rs
src/backend/metal/src/native.rs

Fixes #2050 (yay! `image_format_properties()` saves the day)
Fixes 3D and 2D multi-layer clears in CTS.
Known issues:
- for some reason, RGBA32* formats fail for multi-layered clears. Need to investigate further and/or make a repro case for Apple
- depth multi-layered clears work for the most part, but the initial clear that touches all the layers is (for some reason) ignoring layer=0... Similarly, this needs to be investigated, reproduced, and tracked separately.
- I implemented a fast path that clears all the layers at once. We clear by making a dummy render pass, and I'm creating an extra texture view (to have the layers start at 0) and make it a layered attachment. This doesn't appear to work, even though layered attachments work fine in general (when CTS explicitly wants them).
PR …

Metal clear image improvements

---

src/backend/auxil/range_alloc.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/native.rs
src/backend/metal/src/native.rs

dx12: Allow destroying descriptor pools before freeing all sets
Removing all the special case handling and also returning an error. In case we hit an actual error case in the former implementation it would indicate that the user tried to free the same descriptor set multiple times or we did something wrong internally. The first case shouldn't be possible due to move semantics and in the second case an assert should be fine enough also. This version catches the same issues as the previous one.
PR checklist:
cc @Xaeroxe

auxil: Simplify allocator range freeing

---

src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs

Basic changes required for supporting input attachments. As vulkan requires to specify input attachments in descriptor sets and additionally via an index, mapping to dx12 is quite easy.
Currently no explicit handling in the renderpass.
PR checklist:

dx12: basic input attachment support

---

reftests/scenes/vertex-offset.ron
src/backend/metal/shaders/blit.metal
src/backend/metal/shaders/clear.metal
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/internal.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs
src/hal/src/image.rs

It's great to have that shader-based clear code finally coming handy :)
Known issues: all multi-layered clears fail. Seems to be very similar to #2103. Supposedly, layered rendering in Metal gets totally off the rails when used on an image view, e.g. a texture that has a parent texture with non-zero layer offset. I'll start making a repro case for Apple to address, which will hopefully let us pass all the tests and do it efficiently.
PR checklist:

Metal attachment clears

---

src/backend/dx12/src/command.rs
src/backend/dx12/src/descriptors_cpu.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/native.rs

Dynamic allocator for CPU descriptor heaps. We currently have 2 ways of allocating CPU descriptors: from a device global heap and command local linear allocators. This PR cleans up the two paths a bit and fixes the current size limitation for the first kind by dynamically creating new small fixed size CPU heaps.
Freeing currently not support but that's not an regression as we didn't support it before either.
Small 'regression' concerning `fill_buffer` which was implemented incorrectly as far as I can see. Probably would work only on AMD. This breaks the fill reftests.
Fixes #1945 
PR checklist:

dx12: Add dynamically sized CPU descriptor heaps

---

examples/hal/compute/main.rs
examples/hal/quad/main.rs
src/backend/dx11/src/lib.rs
src/backend/dx12/src/command.rs
src/backend/dx12/src/conv.rs
src/backend/dx12/src/native.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs
src/backend/vulkan/src/command.rs
src/hal/src/command/compute.rs
src/hal/src/command/graphics.rs
src/hal/src/command/mod.rs
src/hal/src/command/raw.rs
src/hal/src/command/render_pass.rs
src/hal/src/pso/descriptor.rs
src/render/src/macros/pipeline.rs
src/warden/src/gpu.rs

Start defining the basic API for dynamic buffer descriptors. Atm based upon vulkan, not optimal but provides the best performance. Other possbiel API design could use `(set, Option<Offset>)` for descriptor set binding, but involves more work on the portability layer and might be more typing for users.
Feedback appreciated.
More backends to follow ..
Addresses https://github.com/gfx-rs/gfx/issues/1949
PR checklist:

Dynamic buffers

---

src/backend/dx11/src/conv.rs
src/backend/dx11/src/device.rs
src/backend/dx11/src/lib.rs
src/backend/dx12/src/command.rs
src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/gl/src/state.rs
src/backend/metal/src/command.rs
src/backend/metal/src/conversions.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs
src/backend/metal/src/soft.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/conv.rs
src/backend/vulkan/src/device.rs
src/hal/src/command/graphics.rs
src/hal/src/command/raw.rs
src/hal/src/command/render_pass.rs
src/hal/src/pso/graphics.rs
src/hal/src/pso/mod.rs
src/hal/src/pso/output_merger.rs
src/warden/src/raw.rs

Fixes #2067.
- Map static stencil values for Metal
- Implement dynamic stencil reference values for Metal
- Modify signature of `set_stencil_reference` to match Vulkan (debatable, although otherwise we don't have a way to set single faces..)
- Add a new `State` type (open to better name ideas) to try out the idea of static/dynamic fields instead of moving them all into `baked_states`
I haven't had a chance to run any test cases for this yet, so I'm hoping the state setup/binds at least make sense logically.
I also haven't added dynamic read/write masks yet, though maybe I can do that in a followup PR instead.
PR checklist:

Improve static/dynamic stencil support

---

src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/metal/src/command.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/conv.rs
src/hal/src/command/graphics.rs

Fixes https://github.com/szeged/webrender/pull/183#issuecomment-395087515
PR checklist:

Attachment clears API refinement, DX12 depth/stencil support

---

src/backend/dx11/src/device.rs
src/backend/dx11/src/lib.rs

Based on the dx12 counterpart. Fixes all of the crashes in `dEQP-VK.info.format_properties`
Fixes #issue
PR checklist:

[dx11] add format_properties and image_format_properties

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/internal.rs
src/backend/metal/src/native.rs
src/hal/src/pass.rs

Fixes #2121
PR checklist:
Interestingly, the scissors still need more work (in follow-ups) to handle rectangle size of 0 somehow.

[mtl] work around incompatible render passes

---

src/backend/dx11/src/device.rs
src/backend/dx11/src/dxgi.rs

In particular the `CreateDXGIFactory2` was used to create the factory,
but it is not present on older dxgi versions. Other function calls
shouldn't be affected since the factory creation infers the dxgi version
and tip-toes around the newer functions.
Fixes #issue
PR checklist:

[dx11] fix some dxgi calls not being present on windows 7

---

src/backend/dx11/src/lib.rs
src/backend/dx12/src/command.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs
src/backend/vulkan/src/command.rs
src/hal/src/command/graphics.rs
src/hal/src/command/raw.rs
src/hal/src/command/render_pass.rs
src/hal/src/pso/graphics.rs
src/hal/src/pso/mod.rs
src/hal/src/pso/output_merger.rs

Implemented only on Vulkan and Metal for now.
As mentioned I think the Metal implementation could be improved a lot by reworking depth stencil descriptors/states to make it more obvious how these states are being passed around and bound.
Fails in Dota 2 apparently due to the same reason as #2121: `self.state.depth_stencil_desc` does not exist at the time we try to update the stencil masks, so the assertion fails – not sure if I can attempt a local fix here..
PR checklist:

Dynamic stencil masks

---

src/hal/src/pso/graphics.rs
src/hal/src/pso/output_merger.rs

- Reorder `StencilOp`, `LogicOp`, and `Comparison` to match Vulkan ordering and values ([`VkStencilOp`](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkStencilOp.html), [`VkLogicOp`](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkLogicOp.html), [`VkCompareOp`](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkCompareOp.html)).
- Add explicit values to (blend) `Factor` to align with Vulkan ([`VkBlendFactor`](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkBlendFactor.html)).
This is really trivial but could be a tiny opportunity to skip mapping for portability, so I don't see a reason to avoid aligning these.

hal: Reorder stencil op values to match Vulkan

---

src/backend/metal/src/command.rs

Fixes #2134
PR checklist:
Probably easier to read these commits one at a time because they all fix separate issues:
- Always set load/store actions for attachments which aren't being cleared. We need this to preserve values in shared textures, i.e. between two separate depth and stencil attachments with the same backing texture.
- During the changes in #2129, we stopped mapping load/store actions during framebuffer creation. As a result we always used "don't care" which led to unexpected images at the beginning of render passes. For example, if image clears occurred prior to beginning the render pass, we had no guarantee that the image was still cleared at the beginning of the render pass.
- The stencil write mask updates passed the wrong argument, so they were misinterpreted as read mask …

mtl: Fix depth stencil issues

---

examples/hal/quad/main.rs
examples/render/quad_render/main.rs
src/backend/dx11/src/lib.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/window.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/queue.rs
src/backend/gl/src/window/glutin.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs
src/backend/metal/src/soft.rs
src/backend/metal/src/window.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/window.rs
src/hal/src/backend.rs
src/hal/src/lib.rs
src/hal/src/pso/output_merger.rs
src/hal/src/queue/mod.rs
src/hal/src/window.rs
src/render/src/lib.rs

Fixes/rewrites the presentation mechanics in Metal, improves the API side elsewhere.
Old swapchain was represented by `CALayer` with custom created `IOSurface` frames that we attempted to present. This is nowhere near the recommended presentation path, which is implemented here. Honestly, I don't think the old path ever worked properly:
- our example (`quad`) doesn't do any animation, and waits after each frame
- LunarG samples weren't really tested on MacOS
- gfx_ocean (as well as Dota) showed presentation lags/artifacts IIRC
The new logic creates a `CAMetalLayer`, set's up its format and parameters, and acquires drawables with `nextDrawable`. There is one but important complication with this method: frame images are temporary. Thus, while we can get `MTLTexture` from a drawable, it's …

CAMetalLayer presentation

---

src/backend/dx12/src/device.rs

Tier 1 GPUs require placing images with TRANSFER_DST usage on the RT_DS heap as we internally use render targets for transfer operations.
Fixes #2097 
cc @grovesNL could you test it on your machine?
Fixes #issue
PR checklist:

dx12: Fix wrong memory heap selection for transfer dst usage.

---

src/backend/dx11/src/device.rs
src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/internal.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/pool.rs
src/window/dxgi/src/lib.rs

Since the crate now uses `winapi` 0.3, we can use the `Interface` trait's `uuidof` method instead of accessing the `IID_*` constants.
Fixes #1142 
PR checklist:
(I don't use Windows but since they compile and no ID has been changed it should work).

Use `uuidof` instead of the raw IID

---

.travis.yml
examples/Cargo.toml
src/backend/dx11/Cargo.toml
src/backend/dx12/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml

There is a problem in winit 13, which is fixed in 15. Related issue: https://github.com/tomaka/glutin/issues/1023
PR checklist:
- Vulkan, GL

Update winit to 15 and glutin to 16

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/internal.rs
src/backend/metal/src/native.rs
src/backend/metal/src/soft.rs

PR checklist:
r? @gfx-rs/metallists 
This PR attempts to have lightweight software commands that don't take any heap space or own ObjC objects. In most cases, where a command list is live-recorded and executed once, this should reduce the amount of work we do per command, which is especially important if those commands are thrown away (e.g. because we are not inside a render pass).
My expectation would be to see an improvement in #2161 due to us doing less work. The actual results are somewhat shocking: with v-sync enabled I'm getting the same 59-60 fps as usual. With v-sync OFF, I'm getting between 25 and 50 fps now (which is lower than the previous 50-70). Not sure what's going on, the instrumental profile doesn't give a clue. Please check out the code.

[mtl] Borrowed commands

---

src/backend/gl/Cargo.toml
src/backend/gl/src/command.rs
src/backend/gl/src/device.rs
src/backend/gl/src/info.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/native.rs
src/backend/gl/src/queue.rs

I'll rebase off master when I'm done.
Uniforms in gl only have a bindings field, not a set one. This means that for shaders that use multiple sets to work, we must change where we are binding them.
See page 14 for what I mean: https://www.khronos.org/assets/uploads/developers/library/2016-vulkan-devday-uk/4-Using-spir-v-with-spirv-cross.pdf
PR checklist:

Remaping descriptor sets in the gl backend

---

src/backend/dx11/src/device.rs
src/backend/dx12/src/device.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/device.rs
src/hal/src/buffer.rs
src/hal/src/device.rs

hal: Improve buffer documentation and cleanup error handling

---

examples/quad/main.rs
src/backend/dx11/src/lib.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/window.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/queue.rs
src/backend/gl/src/window/glutin.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs
src/backend/metal/src/soft.rs
src/backend/metal/src/window.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/window.rs
src/hal/src/lib.rs
src/hal/src/queue/mod.rs
src/hal/src/window.rs
src/window/dxgi/src/lib.rs
src/window/glfw/src/lib.rs
src/window/sdl/src/lib.rs

~~Includes #2164~~
Fixes #2168
Fixes #2143
Removes deferred image resolution (yay!), and also renames some of the outdated concepts.
We have no flickering, and proper frame sync now.
PR checklist:

Persistent Metal swapchain

---

src/backend/dx11/src/lib.rs
src/backend/dx12/src/lib.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/lib.rs
src/hal/src/lib.rs

Unblocks a couple of CTS cases (`dEQP-VK.pipeline.image` and `dEQP-VK.pipeline.sampler`)

[hal] add support for maxColorAttachment device limit

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs
src/backend/metal/src/soft.rs
src/backend/metal/src/window.rs

Partially fix to #2161
PR checklist:
This replaces buffer/texture/sampler object usage with pointers instead. This allows us to bypass Objective-C's reference counting (i.e. retain/release). The idea is to create the same objects as before, but purposely leak them and acquire a pointer to them instead. When we're finished with the objects, we take back ownership and release as usual. We should be able to do this either through `drop` on the owning struct, or through relevant `destroy_*` functions.
Still heavily WIP (but works with quad/Dota 2) because there are a few places that will cause leaks or use-after-free in its current state (need to fix cases where the same image is returned for an image view, verify `drop` exists on all the correct owners, etc.)

mtl: Use pointers for temporary state

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs

PR checklist:
The logic is changed in the following way:
- a framebuffer still keeps a hold of a render pass descriptor, but now behind a mutex
- starting a render pass mutates that locked descriptor in place
- if a command buffer is deferred, only then we copy the whole descriptor out
- careful treatment of image blits/clears is done to re-use the RP descriptor more often
Note: doesn't seem to affect Dota framerate considerably

[mtl] minimize creation of render passes

---

src/backend/metal/src/lib.rs
src/backend/metal/src/window.rs

The freeing up of the drawable now checks if there is anything to free
from the has_swapchain boolean.
The boolean is totally a hack, and might have some edge-cases where it
is wrong, but this happens to fix warnings and red-frame flashes
(present of not drawn frame) from the quad example, with the resizing
still working.
Fixes #issue
PR checklist:

metal: Hack to fix the first frame of a swapchain

---

src/backend/auxil/range_alloc.rs
src/backend/dx11/src/lib.rs
src/backend/dx12/src/native.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/native.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs
src/backend/vulkan/src/native.rs
src/hal/src/device.rs
src/hal/src/pso/descriptor.rs

Fixes the heap allocations in descriptor sets, to help #2161.
Edit: the improvement is there, but it's not the one we were looking for.
Adds real value semantics for the `DescriptorPool`, which now owns the allocation and has the actual descriptor sets pointing to it.
PR checklist:
~~Note: it doesn't work correctly yet, but I'd be happy to get the review comments and notes. Perhaps, you can spot the mistake? ;)
Sadly, my CTS is non-operational atm, so it's not easy to figure out a test case.
Note2: the individual commits are not build-able. Will squash once finished.~~

Heap-less descriptor sets in Metal

---

Makefile
examples/quad/main.rs
src/backend/dx11/src/lib.rs
src/backend/dx12/src/command.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs
src/backend/vulkan/src/command.rs
src/hal/src/command/graphics.rs
src/hal/src/command/raw.rs
src/hal/src/command/render_pass.rs
src/hal/src/pso/input_assembler.rs
src/warden/src/gpu.rs

Helps #2161 . I'm now getting 80-85 fps on the test run.
Aside from Metal, also changes HAL to avoid heap allocation for vertex buffer binding.
PR checklist:

Various Metal performance optimizations

---

Cargo.toml
examples/gamma/main.rs
examples/performance/main.rs
examples/triangle/main.rs
src/lib.rs
src/window/dxgi/Cargo.toml
src/window/dxgi/src/lib.rs
src/window/glutin/Cargo.toml
src/window/glutin/src/lib.rs
src/window/metal/Cargo.toml
src/window/metal/src/lib.rs
src/window/vulkan/Cargo.toml
src/window/vulkan/src/lib.rs

* gfx_window_glutin -> `0.25`
* gfx_window_dxgi -> `0.16`
* Use physical dimensions in window projects.
* Use `poll_events` in examples instead of `run_forever` which can only handle one event per frame.
* Use WINIT_HIDPI_FACTOR override in performance example to avoid non-1 dpi x11 issues as this example can't handle resizing.
PR checklist:

[pre-ll] Update winit -> 0.16

---

Cargo.toml
examples/gamma/main.rs
examples/performance/main.rs
examples/triangle/main.rs
src/core/src/texture.rs
src/lib.rs
src/window/dxgi/Cargo.toml
src/window/dxgi/src/lib.rs
src/window/glutin/Cargo.toml
src/window/glutin/src/lib.rs
src/window/metal/Cargo.toml
src/window/metal/src/lib.rs
src/window/vulkan/Cargo.toml
src/window/vulkan/src/lib.rs

* gfx_window_glutin -> `0.25`
* gfx_window_dxgi -> `0.16`
* Use physical dimensions in window projects.
* Use `poll_events` in examples instead of `run_forever` which can only handle one event per frame. _Included in this branch as otherwise testing is a pain_.
* Use WINIT_HIDPI_FACTOR override in performance example to avoid non-1 dpi x11 issues as this example can't handle resizing.
PR checklist:

[v0.17] Update winit -> 0.16

---

src/backend/dx11/src/conv.rs
src/backend/dx11/src/device.rs
src/backend/dx11/src/lib.rs

Adds a few baked states to pipeline binding and fixes blend factor mapping to map to vulkan semantics (except for issue described in #2171), see: https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkBlendFactor.html#_description
This behavior also applies to dx12, which I have a separate branch for including moving blit shaders to auxil

[dx11] add stencil reference and fix blend factor mapping

---

src/backend/gl/Cargo.toml
src/backend/gl/src/device.rs

Depends on https://github.com/grovesNL/spirv_cross/pull/77
Should fix the gl backend failure on macs reported by bayanijulian on gitter. No clue about metal.
PR checklist:

Fixes the legacy, no explicit uniform bindings in shader mode.

---

src/backend/metal/src/command.rs

Appears to fix #2199 
PR checklist:
With this change, `dEQP-VK.dynamic_state.ds_state` seems to pass consistently again. The reason I looked into this `Deferred` branch is because the autorelease pool wouldn't have covered it previously. So moving it up the callstack caused the copied render pass descriptor to be allocated correctly but freed before its used.
I haven't tested this at all (outside of the CTS), so this may leak in other places, but the reasoning seems to make sense at least.

[mtl] Retain copied render pass descriptor

---

src/backend/auxil/range_alloc.rs
src/backend/dx12/src/native.rs
src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs
src/backend/metal/src/window.rs
src/hal/src/device.rs

Fixes a large number of CTS's out-of-pass image clearing tests.
PR checklist:

A bunch of Metal goodies (better image clears and debugging)

---

src/backend/metal/src/command.rs

Fixes #2204
PR checklist:
Apparently, capture is stopping automatically at present(), and we abort if if call `stop_capture` explicitly...

[mtl] don't stop the capture at present

---

src/backend/metal/src/command.rs
src/backend/metal/src/lib.rs

Allows us to quickly test if the reference retaining saves the day.
PR checklist:

[mtl] debug option to retain references

---

src/backend/dx11/src/device.rs
src/backend/dx11/src/internal.rs
src/backend/dx11/src/lib.rs

Descriptor pools now holds a fixed size `Vec` containing d3d11 interface pointers, managed by `RangeAlloc`. Slices of the `Vec` are given out to descriptor sets .
A descriptor set layout contains information on what binding number maps to what index in the descriptor set's slice of handles. This is copied to descriptor sets on set allocation.
PipelineLayout has optimized ranges (less api calls) of descriptors for each relevant shader stage.
Images now create & store subresource views (only UAV & RTV for now) on image binding.
Also fixes some minor stuff like invalidating memory ranges bigger than `1 << 15` vertex buffer strides & offsets.
r? @kvark

[dx11] rework descriptors, add UAV/RTV for subresources

---

src/backend/metal/src/command.rs
src/backend/metal/src/conversions.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs
src/hal/src/pso/graphics.rs

PR checklist:
r? anyone
Note: the viewport change is needed because that's what CTS wants to use (with MAINTENANCE1 extension) for the cull tests... although they still fail. It looks like Metal changes the winding order based on the viewport, while Vulkan does not (or the other way around...).

[mtl] cull face support

---

src/hal/src/command/mod.rs

Previous code relies on command buffers internally having the same state after `clone()`ing, which is only true for vulkan since the backend type is just a opaque handle anyway.
Tested with Vulkan and dx12, but this shouldn't break any previous code, as it only changes the order that `finish()` is called (previously when `self` was dropped and now before.

[hal] change the order of cmd buffer finish call

---

src/backend/metal/src/command.rs

PR checklist:
The `>> level` is already set in [this call](https://github.com/dati91/gfx/blob/b1e0b438354631aa25150f1c3b4b88fe1a8b81f5/src/backend/metal/src/command.rs#L2164).

[mtl] Remove >> level from blit

---

src/backend/dx11/shaders/blit.hlsl
src/backend/dx11/shaders/copy.hlsl
src/backend/dx11/src/conv.rs
src/backend/dx11/src/device.rs
src/backend/dx11/src/internal.rs
src/backend/dx11/src/lib.rs

Adds support for creating views of 2d arrays, 3d textures, cube maps and cube map arrays.
Changes the views that image binding creates for copying/blitting etc. from `D2` to `D2Array`
Adds a memory type enum which replaces the previous hardcoded conditionals.

[dx11] add more view support and memory type enum

---

src/backend/dx11/src/conv.rs
src/backend/dx12/src/conv.rs
src/backend/gl/src/state.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs
src/backend/metal/src/soft.rs
src/backend/metal/src/window.rs
src/backend/vulkan/src/device.rs
src/hal/src/pso/graphics.rs

Fixes #2170
Expands our Metal stats to report the number of active and temporary command buffers. Coalesces the completion handlers, and finally fixes the depth bias issue we've been seeing (HAL breaking change).
PR checklist:

[mtl] dynamic depth bias, callback coalescence, and more stats

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs

Addresses part of  #2229 by ~~removing the descriptor pool lock entirely - it's meant to be externally synchronized by Vulkan anyway~~ moving the ranges out of the descriptor lock.
Fixes the correctness of a pool reset that's not created with the individual reset flag.
PR checklist:

Metal pools improved

---

Makefile
src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/internal.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs
src/backend/metal/src/window.rs

Addresses a part of #2229
~~Based on #2240~~
PR checklist:
~~Unfortunately, I see no performance advantage from switching to `parking_lot` so far. cc @Amanieu~~
After a series of unsuccessful attempts to hook up a third party library (what could possibly be easier, eh?), I got the performance numbers - we are up from 80 to almost 90, which is more than a 10% bump. Given that `parking_lot` is not a drop-in replacement for `std::sync`, I suggest we ship it by default and provide `antidote` as an optional dependency.

Metal parking lot

---

src/backend/auxil/range_alloc.rs
src/backend/metal/src/command.rs
src/backend/metal/src/native.rs
src/backend/metal/src/soft.rs

This PR has a few changes that lighten up our most heavy operations at the moment: render pass start and PSO binding. In particular, it re-uses the heap allocation properly now at the latter, ~~and the former tries to avoid waiting on a mutex (for the RP descriptor) if there is another spare available~~.
PR checklist:

Faster passes and PSO bindings in Metal

---

src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/internal.rs
src/backend/metal/src/lib.rs

Fixes #2227
Adds dependency to `storage-map` crate for locking on Metal. If it proves to be useful, we'll likely want it to be used for other backends as well.
Dota performance changes:
- immediate: 90 -> 92 fps
- deferred: 92 -> 99 fps
PR checklist:

[mtl] Experimental concurrent map storage integration

---

src/backend/metal/src/device.rs

Match the `create_image` [logic](https://github.com/gfx-rs/gfx/blob/e5df0879425595619d95db5db77e9b5213ad34e0/src/backend/metal/src/device.rs#L1700-L1703).
PR checklist:

[mtl] Fix image view kind

---

src/backend/gl/src/info.rs

Make the Explicit shader support comment more inline with the others.

---

src/backend/dx12/src/device.rs

Fix zero allocated range DX12

---

src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/window.rs

Fixes the time wasted on setting up temporary autorelease pools, mostly. Although the resulting FPS doesn't appear to be affected. At least we no longer depend on core-foundation :)
cc @jrmuizel (and thanks!) for the way it looks now
PR checklist:

[mtl] new autorelease

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs
src/backend/metal/src/soft.rs

Fixes #2270
PR stages:
Status: ~~currently the perf is unaffected, but we save 30 LOC :)~~
Deferred recording feels a bit snappier. Total time spent in our code appears to be 12% now (opposed to the old 15%), which is a big win.  Plus, 60 lines of codes saved.
PR checklist:

Optimized descriptor binding

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs

Fix dynamic buffer offsets on Metal

---

src/backend/dx11/src/device.rs
src/backend/dx12/src/device.rs
src/backend/gl/src/device.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/device.rs
src/hal/src/device.rs

Fixes #2243
This is needed by the DX12 backend. I tried to round up when converting, because it would be strange to convert 1 nanoseconds to 0 milliseconds and not wait anything. Is this correct behavior?
`u64` with nanoseconds can express much longer time period than `u32` milliseconds. I use `<u32>::max_value()` in case of overflow, but that means to wait INFINITY in win32.
There is a loop in the HAL's `wait_for_fences` implementation, mostly it is the same as the metal backend's wait loop. Should I create a function for it? But I don't know where to place it.
PR checklist:

Change timeout_ms parameter in wait_for_fence(s) to nanoseconds and u64

---

src/backend/dx11/Cargo.toml
src/backend/dx11/src/device.rs
src/backend/dx11/src/internal.rs
src/backend/dx11/src/lib.rs

Adds a "software" Fence implementation, taken from the Metal backend. Initially I tried to implement fences using `D3D11_QUERY_EVENT`, but it turns out it would end up looking the same anyway (Queue and Device share the same ID3D11DeviceContext which has to be synchronized between threads).
The only difference from the Metal backend is that this isn't using a completed handler to signal the fence when the queue is done, but rather when they are scheduled (after `ExecuteCommandLists`). This should be fine since we only care about protecting our emulated objects (eg. DescriptorSet), while the driver should handle access of objects in use.
Also adds object leak checking through the `ID3D11Debug` interface.
Fixes #issue
PR checklist:

[dx11] add fences and some debugging

---

src/core/src/shade.rs

Implement BaseTyped for f64

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/soft.rs

Saves a ton of code and potentially allows for less copies issued by an imperfect compiler (since owned commands are executed directly without conversion to reference commands first).
PR checklist:

Simplify soft commands on Metal

---

src/backend/dx11/shaders/copy.hlsl
src/backend/dx11/src/conv.rs
src/backend/dx11/src/debug.rs
src/backend/dx11/src/device.rs
src/backend/dx11/src/internal.rs
src/backend/dx11/src/lib.rs
src/hal/src/command/raw.rs

Re-do format conversion to be more comprehensive and less hacky
Add Bgra8 -> Buffer transfer
Add basic render passes (missing partial clear/resolves)
Add debugging using `ID3DUserDefinedAnnotation`. This functionality is behind a `#[cfg(debug_assertions)]` and is further restricted from being used on deferred contexts when RenderDoc is not used.
Separate `MemorySync` into Flush/Invalidate variants
r? @kvark 
Fixes #issue
PR checklist:

[dx11] add render passes and debugging

---

examples/colour-uniform/main.rs
examples/compute/main.rs
examples/quad/main.rs

Currently the colour uniform example produces 
```
ERROR gfx_backend_vulkan > [Validation]  [ VUID-VkMappedMemoryRange-size-01390 ] Object: 0x6 (Type = 8) | vkFlushMappedMemoryRanges: Size in pMemRanges[0] is 0x84, which is not a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize (0x40). The spec valid usage text states 'If size is not equal to VK_WHOLE_SIZE, size must either be a multiple of VkPhysicalDeviceLimits::nonCoherentAtomSize, or offset plus size must equal the size of memory.' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkMappedMemoryRange-size-01390)
```
when creating and updating buffers because it is using calculated sizing instead of received buffer size from memory requirements for creating memory mapped ranges.
In addition, added a note …

Small fix/doc improvement for colour uniform example

---

src/hal/src/pso/descriptor.rs
src/hal/src/pso/mod.rs

I believe I've been accurate in describing these, let me know if not. I also changed DescriptorSetWrite in a way that makes more sense for people looking through docs to figure out how it's supposed to be used, and I don't think it should have broken anything.
PR checklist:

Improve Descriptor-related docs and make it more obvious what should be in the DescriptorSetWrite descriptors field

---

src/backend/vulkan/src/device.rs

Implements for the vulkan backend #issue 1949
PR checklist:

Added support for writing to UniformBufferDynamic descriptors. (#issue 1949)

---

src/backend/metal/src/command.rs

Prevents rebinding of all the state and resources in case of consecutive compute dispatches.
~~Also, tries to make a list of commands for graphics pipeline setup and pass it as one big thing (instead of calling `pre.issue` for each individual one). This is piggy-backing on the `issue_many` function of the base commit here.~~ Edit: removed this commit for causing a performance regression.
Changes the sink API to be more clear about how the passes are started/ended, it's now the same across compute/render and distinct from blits.
PR checklist:

[mtl] Refined passes

---

src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs

Based on #2288
Implements first bits of #2236
Allows the client to control the recording option without re-building gfx-rs.
Also hides the remote sink behind a feature. We can't CI-test it until https://github.com/SSheldon/rust-dispatch/pull/10 is accepted and published.
PR checklist:

Metal command recording option

---

Cargo.toml
src/window/dxgi/Cargo.toml
src/window/glutin/Cargo.toml
src/window/metal/Cargo.toml
src/window/vulkan/Cargo.toml

Up gfx_window_glutin version -> 0.26 for release
[winit changelog](https://github.com/tomaka/winit/blob/master/CHANGELOG.md#version-0170-2018-08-02)
[glutin changelog](https://github.com/tomaka/glutin/blob/master/CHANGELOG.md#version-0180-2018-08-03)
PR checklist:

[v0.17] Update winit -> 0.17, glutin -> 0.18

---

Cargo.toml
src/window/dxgi/Cargo.toml
src/window/glutin/Cargo.toml
src/window/metal/Cargo.toml
src/window/vulkan/Cargo.toml

Up gfx_window_glutin version -> 0.26 (for release in v0.17 branch)
[winit changelog](https://github.com/tomaka/winit/blob/master/CHANGELOG.md#version-0170-2018-08-02)
[glutin changelog](https://github.com/tomaka/glutin/blob/master/CHANGELOG.md#version-0180-2018-08-03)
PR checklist:

[pre-ll] Update winit -> 0.17, glutin -> 0.18

---

src/backend/dx11/src/device.rs
src/backend/dx12/src/device.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs
src/backend/vulkan/src/device.rs
src/hal/src/device.rs

Follow-up to #2294
PR checklist:

Make merge_pipeline_caches to be non-consuming

---

src/backend/metal/src/command.rs
src/backend/metal/src/conversions.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs
src/backend/metal/src/soft.rs

~~Fixes~~ preparation for #2295
This PR is best to review by commits:
- first one just makes things tidier. I was hoping to get denser command format (by using `u8`) but this regressed the performance, so leaving `ResourceIndex` as `u32` for now
- second one makes it cheaper to store options of resource pointers
PR checklist:

Optimize Metal resource binding

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs

Fixes #2295
Based on #2298
This gives us another 2.5% performance on the benchmark. ~~However, it is really going to shine when we start binding the descriptors in bulk (hence WIP here).~~ Edit: actually, not. I'll get that shining PR separately.
PR checklist:

Flattened descriptor sets on Metal

---

src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/soft.rs

Based on #2300 
Fixes #2308
Interestingly, I don't see this being an improvement on a dual core machine, despite the fact we are issuing less Metal commands. Not sure why this is, any ideas are welcome.
PR checklist:

Metal resource bundles

---

src/backend/metal/src/internal.rs

Include shaders directly into the library instead of loading from file. This should fix our binary, i.e. https://github.com/gfx-rs/portability/pull/128#issuecomment-412973805
PR checklist:

[mtl] Embed shaders

---

examples/colour-uniform/main.rs
examples/quad/main.rs
src/backend/dx11/src/device.rs
src/backend/dx12/src/device.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/window.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/window.rs
src/hal/src/device.rs
src/hal/src/window.rs

Fixes #2322
Addresses the Metal part of #2291
The PR changes our swapchain configuration to reflect the capabilities better and be constructed from it.
It also removes the earlier hack in Metal backend  w.r.t. applying the hiDPI factor, rewriting the logic of how `CAMetalLayer` is created and configured. Now, it's logical and physical spaces strongly correspond to the underlying view. It respects the given extents not by changing the layer, but by configuring the images (drawables) produced from it.
Most importantly, the render space matches *logical* space of the layer. This means that if we have a window of size 1440x900 with hiDPI scale of 2.0, then it will behave as if it's a 1440x900 window and report size and create drawables accordingly. The scaling/stretching is left for the …

Updated SwapchainConfig logic

---

src/backend/metal/src/device.rs

These are required for https://github.com/RPCS3/rpcs3/pull/4996
PR checklist:

[mtl] expose anisotropy and DXT format features

---

src/backend/dx11/src/lib.rs
src/backend/dx12/src/window.rs
src/backend/gl/src/window/glutin.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs
src/backend/metal/src/window.rs
src/backend/vulkan/src/conv.rs
src/backend/vulkan/src/window.rs
src/hal/src/window.rs

Fixes  #1908
Also refactors Metal's logic for assigning the push constant IDs. I believe the new method is less hacky.
PR checklist:

Surface usage flags

---

src/backend/dx11/src/device.rs
src/backend/dx11/src/lib.rs
src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/gl/src/device.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs
src/backend/metal/src/soft.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/conv.rs
src/backend/vulkan/src/device.rs
src/hal/src/command/graphics.rs
src/hal/src/command/raw.rs
src/hal/src/command/render_pass.rs
src/hal/src/device.rs
src/hal/src/query.rs

Fixes #1638 (for the most part)
PR checklist:

Query API and basic support on Metal

---

src/backend/metal/src/command.rs
src/backend/metal/src/conversions.rs
src/backend/metal/src/device.rs
src/backend/metal/src/window.rs
src/hal/src/image.rs

Fixes Dota2 after #2116 
PR checklist:

[mtl] Fix A2BGR10 format mapping

---

src/backend/metal/src/conversions.rs
src/backend/metal/src/device.rs

Improves our reporting of image capabilities and buffer view creation
PR checklist:

[mtl] no buffer features on depth and compressed formats

---

src/backend/dx11/src/lib.rs
src/backend/dx12/src/lib.rs
src/backend/gl/src/info.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/vulkan/src/lib.rs
src/hal/src/lib.rs

Makes our buffer views bigger, relying on https://github.com/KhronosGroup/SPIRV-Cross/issues/664
PR checklist:

[mtl 2D texel buffer view

---

src/backend/metal/build.rs
src/backend/metal/shaders/blit.metal
src/backend/metal/shaders/clear.metal
src/backend/metal/shaders/macros.metal
src/backend/metal/src/lib.rs
src/backend/metal/src/window.rs

Here's the start of a PR to introduce support for iOS in gfx-backend-metal. With this PR gfx-backend-metal does build on iOS, but I have yet to get into testing. I'm far from a metal expert, so I would appreciate any feedback.
1. `Instance` has two impls, one for iOS and one for macOS. Is there a preferred way to organize these differences? For example, having a platform submodule, with ios.rs, and macos.rs submodules.
2. iOS does not support `[[render_target_array_index]]`, but as far as I can tell, it does fully support array textures depending on the specific iOS version. blit.metal and clear.metal use `[[render_target_array_index]]` so I added a macros.metal file which will conditionally use the attribute. This allows the shaders to build, but I have no idea what the runtime behavior …

[WIP] [mtl] [iOS] hacking on iOS metal support

---

src/backend/metal/src/device.rs

follow-up to #2340
PR checklist:

[mtl] hotfix for the buffer alignment

---

src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs

Partial fix for #2342 (probably need some more version checks, but I have no simple way to check)
Also fixes the MSL version check for macOS versions beyond (technically `(11, 0)` would've failed)
PR checklist:

[mtl] Expose version check

---

examples/colour-uniform/main.rs
examples/quad/main.rs
src/backend/dx11/src/lib.rs
src/backend/dx12/src/window.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/window/glutin.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/window.rs
src/backend/vulkan/src/window.rs
src/hal/src/lib.rs
src/hal/src/window.rs

Fixes #2333
PR checklist:
I can't exactly figure out how to control the drawables returned by `CAMetalLayer`, so I'm at least going to report anything unusual as an error downstream, instead of crashing.
cc @Mistodon @JohnColanduoni

Acquire error codes

---

src/backend/metal/src/device.rs

Fixes the following use cases affecting RPCS3:
1. buffer view created from a buffer that doesn't begin at the origin of the allocated memory
2. descriptor write with a buffer that doesn't begin at the origin of the allocated memory
3. having multiple descriptor binding entries in a layout for the same binding but different shader stages
- currently we require them to have the same contents
PR checklist:

Various important Metal fixes for RPCS3

---

src/backend/metal/src/device.rs
src/backend/metal/src/window.rs

Continue fixes for #2342 
Alternatively, we could just not expose `PresentMode::Immediate` for older macOS versions. @kvark what do you prefer?
Also [iOS doesn't list support for `displaySyncEnabled` at all](https://developer.apple.com/documentation/quartzcore/cametallayer/2887087-displaysyncenabled?language=objc). I've disabled it for now, let me know if this is incorrect.
PR checklist:

[mtl] Add version check to `displaySyncEnabled`

---

src/backend/vulkan/src/window.rs

PR checklist:
This PR fixes build issues on android. winit uses `LogicalSize` instead of `(u64, u64)`, and the android code didn't get updated to deal with that.

[vk] [android] fix winit feature on android

---

src/backend/metal/src/lib.rs

Fixes use of `libportability.dylib` with `vulkaninfo`.
PR checklist:

[mtl] don't panic on missing window

---

src/backend/dx12/src/device.rs
src/backend/dx12/src/window.rs

Fix surface extents on DX11

---

src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs

[mtl] expose dual-source blending

---

.travis.yml
Makefile
examples/Cargo.toml
src/warden/Cargo.toml

PR checklist:
This PR adds aarch64-apple-ios with rust nightly to travis - the only iOS target supporting metal. Only `make check` is run on this target. The examples, and warden now also pass `make check` on iOS
TODOs:
- there are [ways](https://github.com/rust-lang/libc/blob/master/ci/ios/deploy_and_run_on_ios_simulator.rs) to [run](https://github.com/snipsco/dinghy) tests on simulator; however, metal doesn't work on simulator.
- Figure out the correct value for, and a way to set `-miphoneos-version-min`

[iOS] add aarch64-apple-ios travis job

---

src/backend/dx11/shaders/clear.hlsl
src/backend/dx11/shaders/copy.hlsl
src/backend/dx11/src/conv.rs
src/backend/dx11/src/device.rs
src/backend/dx11/src/internal.rs
src/backend/dx11/src/lib.rs

Implemented partial attachment clears with some internal shaders & depth stencil state.
Also some other small(er) fixes:
* Add Geometry & Tessellation shaders to pipeline
* Add D1/D1Array creation
* Image & buffer binding resources are now initialized to the memory contents
* Copy shaders now work in 8x8 thread groups and have bounds checking
* The memory type order has been switched (coherent comes before non-coherent)
r? @kvark 
Fixes #issue
PR checklist:

[dx11] add partial attachment clears & misc fixes

---

src/backend/dx11/src/lib.rs
src/backend/dx12/src/lib.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/lib.rs
src/hal/src/lib.rs

Expose `max_sampler_anisotropy`

---

reftests/scenes/transfer.ron

Fixes #2358 
.5001 is too small, still hits 127, .501 hits 128
make reftests passes now with this change.
PR checklist:

adjust clear-image test to hit 128

---

src/backend/metal/src/command.rs
src/backend/metal/src/native.rs

Fixes #2363
Fixes #2364
... supposedly, since I haven't tested it manually, and CTS doesn't bother setting the cube compatible bit. I filed an internal issue about that to Khronos.
PR checklist:

[mtl] cubemap blit support

---

src/backend/metal/src/device.rs

format_depth24_stencil8 is macOS only feature.
checks on iPhone 8, 7p
Fixes #issue
PR checklist:
- [] `make` succeeds (on *nix)

[mtl] fix format_depth24_stencil8 crashes on iOS

---

examples/quad/main.rs

Fixes #2326
First pass at simplifying logic, would like review here before tightening it up more.
Some logic is repeated, should it be pulled out into a function or left as is so that the logic is linear down the page?
Anything I am missing?
Have not run rustfmt yet, will make that a separate commit.
PR checklist:

simplify quad resize logic

---

src/backend/dx11/src/device.rs

swap chains are automatically destroyed since they're all com pointers. this is the same as what we do in the dx12 backend.

dx11: swapchain is automatically released.

---

Makefile
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs
src/backend/metal/src/window.rs
src/hal/src/command/transfer.rs

Fixes  #2095
Gets us to a point where the "cube" example from LunarG works out of the box (by just providing `VK_ICD_FILENAMES`).
Also re-enables "metal" backend by default on Darwin systems.
Edit: also fixes the copy_* operations on buffers to take the in-heap offset into account. This was a major issue that we somehow evaded.
PR checklist:

[mtl] support buffer-backed host-visible textures

---

examples/colour-uniform/main.rs
examples/compute/main.rs
examples/quad/main.rs
src/backend/dx11/src/shader.rs
src/backend/dx12/src/device.rs
src/backend/gl/src/device.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/conv.rs
src/backend/vulkan/src/device.rs
src/hal/src/pso/mod.rs
src/warden/src/gpu.rs

Fixes a large portion of CTS "dEQP-VK.pipeline.spec_constant" group. The compute sub-part has 83 successes and 38 failures. The graphics part seems to suffer from a descriptor allocation issue, which is unrelated.
Related to https://github.com/gfx-rs/gfx/issues/2059#issuecomment-416439423

Raw specialization data

---

src/backend/metal/src/lib.rs
src/backend/metal/src/window.rs

Fixes an exception happening when `VkGetPhysicalDeviceSurfaceSupportKHR` is called on a different thread.
PR checklist:

[mtl] only access the view on main thread

---

src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/internal.rs
src/backend/metal/src/lib.rs

This fixes gfx-backend-metal after [metal-rs/#73](https://github.com/gfx-rs/metal-rs/pull/73).
With this, I was able to rig up a tweaked version of quad that runs on iphone.
PR checklist:

[mtl] fixes for metal-rs #73

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs

Fixes a validation error happening in vkQuake because we always bind the whole push constant array. This PR makes us only bind the relevant slice (which should also reduce the data passed to GPU), and avoid doing so if we know in advance that more data has to come in.
Tested on vkQuake and the relevant CTS section.
PR checklist:

[mtl] obey push constant ranges

---

src/backend/metal/shaders/fill.metal
src/backend/metal/src/command.rs

Fixes copy_buffer calls when either of buffer offsets is not aligned to 4 bytes (affects vkQuake)
PR checklist:

[mtl] support non-aligned copy_buffer offsets

---

examples/colour-uniform/main.rs
examples/quad/main.rs
src/backend/dx11/src/device.rs
src/backend/dx11/src/lib.rs
src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/native.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/gl/src/lib.rs
src/backend/metal/src/command.rs
src/backend/metal/src/conversions.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/conv.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/hal/src/adapter.rs
src/hal/src/device.rs
src/hal/src/image.rs
src/warden/src/gpu.rs

WIP steps towards #2396, exploiting CI to get it error-less.
PR checklist:

Richer image view capabilities

---

src/backend/metal/src/command.rs

Intended to fix https://github.com/szeged/webrender/issues/216
Note: this is a little scary of an issue. Doesn't appear that we have any more of them, but we need to keep an eye on those cases.
PR checklist:

[mtl] keep borrowed clear value longer

---

src/backend/metal/src/command.rs

A proper follow-up to #2402
PR checklist:

[mtl] retain raw_value for longer

---

src/backend/metal/src/command.rs

[mtl] return an error on Swapchain::present if drawable not found

---

appveyor.yml
src/backend/metal/build.rs

Fixes xcode10 and an iOS version < 12.0 are now compatible with each other. Previously gfx-backend-metal would panic when it detected a MTLLanguageVersion - 2.1 - not supported by device.
PR checklist:

[mtl] the backend metal shaders by default get built with minimum requirements in mind

---

Makefile
src/backend/empty/src/lib.rs
src/hal/src/adapter.rs
src/hal/src/lib.rs

Add some docs to `gfx_hal::Instance`, and provide a make target for `cargo doc`.

---

src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/pool.rs

dx12::RawCommandPool now holds a collection of ID3D12CommandAllocator,
introducing a new one each time a new command buffer is allocated.
dx12::RawCommandPool::reset() now performs a reset() on each allocator in
the collection, mimicking the prior single-allocator behaviour.
dx12::CommandBuffer::reset() now handles the `release_resources` flag by
reseting its allocator.
Fixes #2140 
PR checklist:
*make reftests fails here:
```
Warding DX12:
Scene 'basic':
thread 'main' panicked at 'assertion failed: `(left != right)`
left: `0`,
right: `0`', src\warden\src\gpu.rs:1152:9
```
I haven't looked too closely into this, but it also fails with the patch reverted. Other than this, there are 15 passing reftests.
---
*rustfmt --check requests many changes (not limited to things inserted in this …

dx12: support individual command buffer reset

---

src/core/src/texture.rs

I'm not sure if there should be a default filter (currently there is not) or if the default wrap mode should be removed. All the other defaults are equal to what's been used by `SamplerInfo::new`.

Add serde defaults for `SamplerInfo` fields

---

examples/quad/main.rs
src/backend/metal/src/device.rs
src/backend/metal/src/internal.rs
src/backend/metal/src/window.rs

Fixes #2414 
Also hang on resizing in general in some applications... like Dota2. Apparently, it's now resizing by re-creating the surface completely (previously, it only re-created the swapchain). In this case, we fail to track if the old swapchain is still presented, and the hack becomes inactive.
This new version of the hack is smarter: it's always active, and if the user provided the old swapchain, we'll even do a nice blit from the old frame to the new one, to address the flicker.
cc @mtak- 
PR checklist:

[mtl] simple blit with scaling between the swapchains

---

examples/quad/main.rs
src/backend/dx12/src/device.rs

Fixes https://github.com/gfx-rs/gfx/issues/2431
PR checklist:
Currently crashes on shutdown, not totally sure. Might be that the window handle is already invalid but the swapchain is still alive? Need to investigate further..

dx12: Destroy old swapchain on recreation

---

src/backend/metal/src/lib.rs

Anonymous functions parameters are deprecated (RFC 1685)
Fixes #issue
PR checklist:

Fix deprecated anonymous functions parameters

---

src/backend/gl/src/command.rs
src/backend/gl/src/device.rs
src/backend/gl/src/info.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/pool.rs
src/backend/gl/src/queue.rs
src/backend/gl/src/state.rs
src/backend/gl/src/window/glutin.rs

An assortment of changes done while working on this: https://github.com/gfx-rs/gfx/pull/2347
Backporting things like `GlContainer`, even if they do nothing, will decrease the # of accidental merge conflicts between master and #2347 , which will make my life easier.
Fixes #issue
PR checklist:

Backports from Merge Window Creation 2

---

src/backend/metal/src/window.rs

Fixes #2441
cc @overdrivenpotato
PR checklist:

[mtl] pre-release the drawables of the old swapchain

---

src/backend/vulkan/src/device.rs

Swapchain was not being destroyed when being passed back into device.create_swapchain which resulted in memory leaks and validation messages.
Fixes #2467 
PR checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/2464)

[Vulkan] Add swapchain cleanup on recreation.

---

Cargo.toml
examples/deferred/main.rs
examples/gamma/main.rs
examples/terrain/main.rs
examples/triangle/main.rs
src/lib.rs
src/window/dxgi/Cargo.toml
src/window/glutin/Cargo.toml
src/window/glutin/src/headless.rs
src/window/metal/Cargo.toml
src/window/vulkan/Cargo.toml

Upgrading the `glutin` and `winit` dependencies.
**Q:** Will this automatically publish a new version or should I bump the version too?
---
Also, something to note in [`glutin v0.19`](https://github.com/tomaka/glutin/blob/master/CHANGELOG.md#version-0190-2018-11-09):
> **Breaking:** The entire API for headless contexts has been removed. Please instead use Context::new() when trying to make a context without a visible window. Also removed headless feature.
I've updated the headless tests to just use `Context::new()`.

Update glutin to 0.19 and winit to 0.18

---

info/getting_started.md

Improve Getting Started: macOS instructions

---

examples/compute/main.rs

no need for back::
Fixes #issue
PR checklist:

fn main is attributed already

---

Makefile
examples/Cargo.toml
src/backend/dx11/Cargo.toml
src/backend/dx12/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/gl/src/window/glutin.rs
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml
src/warden/src/bin/reftest.rs

Transitively brings numerous fixes from newer winit version. https://github.com/tomaka/winit/blob/v0.18.0/CHANGELOG.md#version-0180-2018-11-07
PR checklist:

Bumped glutin version to 0.19
