examples/cube/main.rs
examples/deferred/main.rs
examples/performance/main.rs
examples/terrain/main.rs
examples/triangle/main.rs
src/device/shade.rs
src/device/state.rs
src/device/target.rs
src/device/tex.rs
src/gfx_macros/lib.rs
src/gfx_macros/shader_param.rs
src/gfx_macros/vertex_format.rs
src/gl_device/lib.rs
src/gl_device/shade.rs
src/gl_device/state.rs
src/render/batch.rs
src/render/lib.rs
tests/shaders_macro.rs

needs https://github.com/gfx-rs/gfx_gl/pull/7 to be merged first.

Updated to latest rustc

---

src/render/batch.rs

This blocks Hematite from working.

Derive Copy for RefBatch

---

examples/cube/main.rs
examples/deferred/main.rs
examples/performance/main.rs
examples/terrain/main.rs
examples/triangle/main.rs
src/gfx_macros/lib.rs
src/gfx_macros/shader_param.rs

Fix the gfx_macros for latest ast changes.
Fix the fact that unwrap() has been removed.

Fix build with latest rustc

---

examples/cube/main.rs
examples/deferred/main.rs
examples/performance/main.rs
examples/terrain/main.rs
src/gfx_macros/lib.rs
src/gfx_macros/shader_param.rs
tests/shader_param.rs

Removed batch typedef from #[shader_param]

---

src/device/gl_device/info.rs
src/device/lib.rs

This will get us ready to the point when gl-rs gets fixed.

Fix for gl_device errors with latest Rust

---

src/gfx_macros/shader_param.rs
tests/shader_param.rs

Implemented Copy and Debug for ShaderParam::Link

---

src/device/draw.rs
src/device/gl_device/draw.rs
src/device/gl_device/lib.rs
src/device/lib.rs
src/device/target.rs
src/render/lib.rs

Implemented blit mirror flags

---

Cargo.toml
src/device/Cargo.toml
src/gfx_macros/Cargo.toml

... so that we can re-publish after ~~todays~~ yesterdays changes. Hematite would enjoy that ;)

Version bump to 0.1.2

---

Cargo.toml
examples/cube/main.rs
examples/deferred/main.rs
examples/performance/main.rs
examples/terrain/main.rs
examples/triangle/main.rs
src/device/lib.rs
src/gfx/lib.rs
src/render/lib.rs
src/render/state.rs
src/render/target.rs

Closes #525 
Note: we also check for missing colors

Added draw call errors for missing targets

---

src/render/target.rs

Added a hack into Frame::get_mask to work with the default frame

---

src/gfx_macros/shader_param.rs
src/gfx_macros/vertex_format.rs

generic::ty::Self -> generic::ty::Self_

---

src/gfx/lib.rs

Closes https://github.com/gfx-rs/gfx-rs/issues/572

Reexport `Resources` in `gfx`

---

examples/performance/main.rs
examples/triangle/main.rs
src/device/gl_device/info.rs
src/device/gl_device/lib.rs
src/device/gl_device/shade.rs
src/device/lib.rs
src/device/shade.rs
src/device/state.rs
src/device/target.rs
src/gfx_macros/lib.rs
src/gfx_macros/shader_param.rs
src/gfx_macros/vertex_format.rs
src/render/batch.rs
src/render/shade.rs
tests/shader_param.rs
tests/vertex_format.rs

-Add `PhantomTypes`
-Remove most uses of `[]` (a few are left in `ShaderParam` macro)

Fix gfx with latest rustc

---

src/lib.rs
src/render/batch.rs
src/render/mod.rs
src/render/shade.rs

This fixes the build break in #634

Remove ParamValue for &mut ParamStorage

---

src/device/handle.rs

Closes #637 
Requires https://github.com/gfx-rs/gfx_device_gl/pull/11

Removed Bare trait

---

src/render/batch.rs
src/render/mod.rs

Fixed shader values allocation hazard

---

src/render/mod.rs
src/render/shade.rs

Fixes #649 
Fixes #642 
Linked with  https://github.com/gfx-rs/gfx_macros/pull/8

Safe shader parameters

---

src/device/handle.rs
src/device/mapping.rs
src/render/mod.rs

Add necessary lifetime bound and remove unnecessary cast.

Update to latest rust

---

src/render/mesh.rs

This was needed before we had the `<T as Trait>::method` syntax.

Remove unused arg from VertexFormat::generate

---

src/device/draw.rs
src/device/mod.rs
src/device/shade.rs
src/device/tex.rs
src/render/batch.rs
src/render/mesh.rs

`cargo test` succeeds for me with these changes, tested with `rustc 1.0.0-nightly (d17d6e7f1 2015-04-02) (built 2015-04-03)`

Compilation fixes

---

src/device/mapping.rs
src/lib.rs
src/render/batch.rs

Remove Clone bounds and some unused unstable features

---

src/device/mod.rs

With updates, sorry about the deleted branch!

adding optional texture kind parameter to texture update

---

src/lib.rs
src/render/ext/device.rs
src/render/ext/factory.rs

This is a cut from #668 without the `Window` trait as it seems controversial at the moment.
The GL part: https://github.com/gfx-rs/gfx_device_gl/pull/23
Examples: https://github.com/gfx-rs/gfx_examples/pull/12
Everything is ready to be reviewed/merged

Factory - no Windowing stuff

---

src/device/draw.rs
src/device/mod.rs
src/device/tex.rs
src/render/ext/factory.rs
src/render/mesh.rs
src/render/mod.rs
src/render/target.rs

sRGB support

---

Cargo.toml
src/device/mod.rs
src/device/tex.rs
src/lib.rs
src/render/ext/device.rs
src/render/ext/factory.rs
src/render/mod.rs
src/render/target.rs

Closes #681 
GL device: https://github.com/gfx-rs/gfx-rs/pull/682
Examples: https://github.com/gfx-rs/gfx_examples/pull/15
Window: https://github.com/gfx-rs/gfx_window_glutin/pull/1

Frame abstraction and safety

---

src/render/ext/canvas.rs
src/render/ext/factory.rs
src/render/mod.rs

Closes https://github.com/gfx-rs/gfx-rs/issues/686

Missing pieces from the Canvas PR

---

.travis.yml
Cargo.toml
src/device/draw.rs
src/device/handle.rs
src/device/mod.rs
src/lib.rs
src/render/batch.rs
src/render/mesh.rs

Makes it actually compile on rust-beta, fixing some of #676 
Note: we could use some of these fixes on master as well.

Rust beta/1.0 compatibility

---

.travis.yml
src/device/handle.rs
src/device/mod.rs
src/device/shade.rs
src/render/ext/factory.rs
src/render/ext/shade.rs

Closes #656 
GL part: https://github.com/gfx-rs/gfx_device_gl/pull/30

Shader compile/link logging

---

Cargo.toml
src/device/handle.rs
src/device/mod.rs
src/device/shade.rs
src/render/ext/factory.rs

Reverts part of #695 
Closes #569 
GL part: https://github.com/gfx-rs/gfx_device_gl/pull/31

Returning shader error log

---

Cargo.toml
src/device/mod.rs
src/extra/factory.rs
src/render/mod.rs

Fixes #728 
Fixes blitting from a main FBO.
Improves `FactoryExt`.

Fbo-less support

---

Cargo.toml

Resolves #723 for gfx-rs, Continuation of #746

Use draw_state from crates.io

---

src/device/tex.rs
src/extra/stream.rs
src/lib.rs
src/render/mod.rs

[v0.6] Texture/Buffer update errors

---

src/device/draw.rs
src/device/mod.rs
src/device/tex.rs
src/extra/factory.rs
src/lib.rs
src/render/mod.rs
src/render/target.rs

[v0.6] Refactored texture kinds

---

examples/flowmap/main.rs

Everyone doesn't have slow computers!

Add delta time integration to flowmap example

---

src/backend/gl/Cargo.toml
src/core/Cargo.toml
src/window/glfw/Cargo.toml
src/window/glutin/Cargo.toml

Update all link urls

---

Cargo.toml
src/backend/gl/Cargo.toml
src/core/Cargo.toml
src/window/glfw/Cargo.toml
src/window/glutin/Cargo.toml

Depends on https://github.com/gfx-rs/draw_state/pull/33 (merged).
* Bumped to 0.7.0

Updated dependencies

---

src/core/src/device/mod.rs

This reverts commit be32dc4f349fd378a745b0bf1d05ac0308752592.

Revert "Added 'static lifetime to Resources"

---

.travis.yml

Reduce cargo doc job level to 1

Possible fix to what looks like a race in cargo doc

---

src/core/Cargo.toml
src/core/src/device/mapping.rs
src/core/src/device/mod.rs
src/core/src/macros/mod.rs
src/core/src/render/mesh.rs

This adds  @burtonageo and @red75prime changes to the 0.7 branch.

Publish 0.7.2

---

Cargo.toml
src/backend/gl/Cargo.toml
src/window/glfw/Cargo.toml
src/window/glutin/Cargo.toml
src/window/glutin/src/lib.rs

Requires https://github.com/gfx-rs/gfx_gl/pull/25

Bump everything up to libc 0.2

---

Cargo.toml
src/backend/gl/Cargo.toml
src/window/glfw/Cargo.toml
src/window/glutin/Cargo.toml
src/window/glutin/src/lib.rs

Same thing as the change applied to the v0.8 branch, but applied to Master.

Merge changed to v0.8 into master

---

.travis.yml

Update .travis.yml to use new build infrastructure

---

src/backend/gl/src/info.rs
src/backend/gl/src/shade.rs

TEMPORARY! to ease the merging of #828

Revert of the ARM compatibility change (#845)

---

src/render/src/lib.rs

More convenient access to core factory errors

---

src/core/src/handle.rs

Expose public interface to get dimensions of RTV and DSV

---

Cargo.toml
src/window/glfw/Cargo.toml

Update gfx_window_glfw dependencies

---

Cargo.toml
examples/cube/main.rs
examples/deferred/main.rs
examples/performance/main.rs
examples/shadow/main.rs
examples/skybox/main.rs
examples/terrain/main.rs
examples/ubo_tilemap/main.rs

Upgrade cgmath in dev-deps and update examples.

---

src/window/glutin/src/lib.rs

Window resize support

---

src/backend/gl/src/shade.rs

Will assign the blocks to their indices if there are no bindings found that are *not* zero (default). Tested with `ubo_tilemap` and local `tiled_forward` example.

Assign block bindings automatically when no explicit layout bindings are given

---

examples/blend/main.rs
src/core/src/format.rs

Srgb + alpha format shortcut

---

Cargo.toml
src/window/sdl/Cargo.toml
src/window/sdl/src/lib.rs

Applied the patch from #914 with minor formatting fixes.

SDL2 window by @eugene2k

---

src/lib.rs

A very small change to gfx_app that makes parts of the code a bit more readable. Didn't want to just throw it away.

gfx_app refactored a little to improve readability

---

examples/blend/main.rs
examples/flowmap/main.rs
examples/instancing/main.rs
examples/mipmap/main.rs
examples/shadow/main.rs
examples/skybox/main.rs
examples/terrain/main.rs
examples/triangle/main.rs
examples/ubo_tilemap/main.rs
src/lib.rs

Srgba8 does not seem to work with my drivers causing none of the examples to work. Switching to Rgba8 seems to fix this issue.

Use ColorFormat instead of Srgba8

---

src/render/src/macros/pso.rs

Disable warnings about unused bundle.

---

examples/blend/shader/blend_150.glslf
examples/cube/shader/cube_150.glslf
examples/deferred/main.rs
examples/flowmap/shader/flowmap_150.glslf
examples/instancing/shader/instancing_150.glslf
examples/mipmap/main.rs
examples/mipmap/shader/150.glslf
examples/mipmap/shader/150.glslv
examples/shadow/shader/forward_150.glslf
examples/skybox/shader/cubemap_150.glslf
examples/ubo_tilemap/shader/tilemap_150.glslf
src/backend/gl/src/shade.rs
src/render/src/pso/target.rs

OSX will still be broken because it does not support the ARB. It should `work` as it uses the same fallback behaviour as before.

Use GL_ARB_program_interface_query to query the shader outputs

---

appveyor.yml

Add GCC to path.

---

src/backend/gl/src/shade.rs
src/backend/gl/src/tex.rs

Fixed format_to_glpixel to support integer formats

---

src/backend/dx11/src/state.rs
src/backend/gl/src/command.rs
src/backend/gl/src/state.rs
src/core/Cargo.toml
src/render/Cargo.toml

Move CullFace out of RasterMethod #936

---

src/render/Cargo.toml
src/render/src/macros/pso.rs

Probably fixes https://github.com/PistonDevelopers/conrod/pull/710
TODO: port to master branch

Fixed the PSO macro to use scissor properly

---

src/core/src/factory.rs
src/core/src/pso.rs
src/render/src/encoder.rs
src/render/src/factory.rs
src/render/src/lib.rs
src/render/src/mesh.rs
src/render/src/pso/buffer.rs
src/render/src/pso/mod.rs
src/render/src/pso/resource.rs
src/render/src/pso/target.rs

This PR aims to improve the documentation of the GFX crate. This is tightly bound to #942.

[WIP] Documentation improvements (see #942)

---

src/backend/gl/src/state.rs

Fixes #952 
Will need to be ported to `master` if it's accepted.

[GL] made the blend state to use ARB functions instead of the core

---

.travis.yml
CHANGELOG.md
Cargo.toml
appveyor.yml
examples/blend/main.rs
examples/cube/main.rs
examples/deferred/main.rs
examples/flowmap/main.rs
examples/instancing/main.rs
examples/mipmap/main.rs
examples/performance/main.rs
examples/shadow/main.rs
examples/skybox/main.rs
examples/terrain/main.rs
examples/triangle/main.rs
examples/ubo_tilemap/main.rs
src/backend/dx11/Cargo.toml
src/backend/gl/Cargo.toml
src/core/Cargo.toml
src/core/src/factory.rs
src/core/src/shade.rs
src/core/src/tex.rs
src/render/Cargo.toml
src/render/src/factory.rs
src/window/dxgi/Cargo.toml
src/window/glfw/Cargo.toml
src/window/glutin/Cargo.toml
src/window/sdl/Cargo.toml
tests/macros.rs

Updated `draw_state` dependency and bumped all the versions.
Also closes #838

Version v0.11

---

src/core/src/lib.rs

Not a lot, but it's something.

Added Device docs.

---

src/render/Cargo.toml
src/render/src/lib.rs

Typed re-export

---

src/core/src/factory.rs
src/core/src/pso.rs
src/core/src/shade.rs
src/core/src/tex.rs
src/render/src/encoder.rs
src/render/src/factory.rs
src/render/src/pso/mod.rs
src/render/src/shade.rs

Also edits some comments to have better English, and use more try! handling in render/factory.rs. I mostly got the error messages from doc comments, but would be happy to bikeshed them.

Implement Error trait for all errors

---

src/backend/gl/src/factory.rs
src/backend/gl/src/info.rs
src/backend/gl/src/shade.rs

Refactored program interface queries to support deprecated GL

---

README.md

https://www.bountysource.com/issues/25341329

Some updates to README.md inspired from discussion in

---

README.md
examples/deferred/main.rs
examples/skybox/main.rs
examples/terrain/main.rs
src/backend/gl/src/factory.rs
src/backend/gl/src/info.rs

A bit worried that init_buffer() is not much used.
Would like to have more tests than only --example instancing.
Also, semantics of usage-flags differ significantly between glBufferStorage and glBufferData.
Kind regards,
Erik.

Proposal to #283

---

src/backend/gl/Cargo.toml
src/backend/gl/src/info.rs
src/backend/gl/src/lib.rs

(v0.12) Old glClear code bath as a fallback

---

src/backend/gl/Cargo.toml
src/backend/gl/src/factory.rs
src/backend/gl/src/lib.rs
src/core/src/factory.rs

Fixes most of #1008 
We might need to add some more stuff in here before publishing new GL crate.

[GL] Proper handling for FBO and UBO support

---

.travis.yml

This fixes the glfw issue. xcb is unsolved for now.

Update .travis.yml to use a newer version of cmake

---

src/render/src/macros/mod.rs

Make trailing comma optional in gfx_defines! declarations

---

src/backend/metal/src/command.rs
src/backend/metal/src/factory.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/map.rs
src/backend/metal/src/mirror.rs
src/lib.rs
src/window/metal/src/lib.rs

Metal backend fixes

---

src/backend/dx11/src/command.rs
src/backend/gl/src/command.rs
src/backend/metal/src/command.rs
src/backend/vulkan/src/command.rs
src/core/src/pso.rs

Make sure the viewport is never of size 0

---

src/render/Cargo.toml
src/render/src/lib.rs
src/render/src/pso/buffer.rs
tests/macros.rs

[v0.12] Implemented RawConstantBuffer

---

src/render/src/lib.rs
src/render/src/pso/buffer.rs
tests/macros.rs

Added raw constant buffer PSO component

---

README.md
src/backend/dx11/README.md
src/backend/gl/README.md
src/backend/metal/README.md
src/backend/vulkan/README.md

Document GLSL mirroring

---

.travis.yml
Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/factory.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/map.rs
src/backend/metal/src/mirror.rs
src/lib.rs
src/shade.rs

I was able to get the Metal target to both run, and added a Travis CI target to try to keep it steady.
This should fix issue #1048 and issue #1014.
Sorry about my formatting - I realized my editor runs `rustfmt` on save, but it doesn't look like this entire code base is formatted this way, so these commits appear larger than they are. Do you have any kind of editor settings I could use to reformat this if this is a problem?
I know its kind of not a good idea to fix two things in a single pull request, but since it seemed like the Metal target rotted due to not having CI, I thought it might be best to add them in together. That way if I have to change the Metal code its still ran under CI, but also so that my pull request doesn't immediately cause the build to fail, if that stat is …

Getting the Metal target to run, adding OSX as a Travis CI target.

---

src/backend/gl/src/command.rs
src/backend/gl/src/lib.rs

[GL] Disabling unused vertex attributes

---

.travis.yml
Cargo.toml
src/window/vulkan/Cargo.toml
src/window/vulkan/src/lib.rs

Fixes #998
Excludes SDL backend from CI testing (careful!)

Travis container mode with caching

---

examples/instancing/main.rs
examples/shadow/main.rs
src/backend/dx11/src/factory.rs
src/backend/dx11/src/lib.rs
src/backend/gl/src/factory.rs
src/backend/gl/src/lib.rs
src/backend/metal/src/factory.rs
src/backend/metal/src/lib.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/factory.rs
src/backend/vulkan/src/lib.rs
src/core/src/dummy.rs
src/core/src/factory.rs
src/core/src/handle.rs
src/core/src/lib.rs
src/core/src/mapping.rs
src/render/src/factory.rs

Here's what I made for core and gl, let me know if you don't like something.
@kvark

[WIP] Send and Sync for Fence and Mapping

---

src/backend/gl/src/lib.rs

For debugging gl calls in Factory or wherever

Move check() from Device to Share

---

examples/instancing/main.rs
src/backend/dx11/src/data.rs
src/backend/dx11/src/execute.rs
src/backend/gl/src/factory.rs
src/backend/gl/src/lib.rs
src/backend/metal/src/map.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/data.rs
src/backend/vulkan/src/factory.rs
src/core/src/factory.rs
src/core/src/lib.rs
src/core/src/mapping.rs
src/core/src/memory.rs
src/render/src/factory.rs

Following #1098.
@snuk182 @kvark

Prepare mapping API for D3D11

---

src/core/src/buffer.rs
src/render/src/encoder.rs
src/render/src/factory.rs

I ran @kryptan simple demo app with the changes and here's the new error:
Fixes #1107

Check memory usage before memory update

---

src/core/Cargo.toml
src/core/src/texture.rs

[v0.13] Capping the level by MAX_LEVEL

---

src/core/Cargo.toml
src/core/src/texture.rs

Sibling of #1116 for the master branch

Capping the level by MAX_LEVEL

---

src/backend/gl/src/factory.rs
src/backend/gl/src/lib.rs

Should help investigating #1101 and #1114

[GL] covered factory methods with GL error checks

---

Cargo.toml
examples/blend/main.rs
examples/cube/main.rs
examples/deferred/main.rs
examples/flowmap/main.rs
examples/gamma/main.rs
examples/instancing/main.rs
examples/mipmap/main.rs
examples/particle/main.rs
examples/shadow/main.rs
examples/skybox/main.rs
examples/terrain/main.rs
examples/terrain_tessellated/main.rs
examples/triangle/main.rs
examples/ubo_tilemap/main.rs
src/backend/dx11/src/factory.rs
src/backend/dx11/src/lib.rs
src/lib.rs
src/window/dxgi/Cargo.toml
src/window/dxgi/src/lib.rs
src/window/glutin/src/lib.rs

[APP] Resize support

---

src/backend/gl/src/info.rs

[GL] proper tessellation support check

---

examples/instancing/main.rs
examples/particle/main.rs
examples/shadow/main.rs
src/backend/dx11/src/data.rs
src/backend/dx11/src/execute.rs
src/backend/dx11/src/factory.rs
src/backend/dx11/src/lib.rs
src/backend/gl/src/factory.rs
src/backend/gl/src/lib.rs
src/backend/metal/src/command.rs
src/backend/metal/src/factory.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/map.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/data.rs
src/backend/vulkan/src/factory.rs
src/core/src/buffer.rs
src/core/src/factory.rs
src/core/src/handle.rs
src/core/src/mapping.rs
src/core/src/memory.rs
src/core/src/pso.rs
src/render/src/encoder.rs
src/render/src/factory.rs
src/render/src/lib.rs
src/window/dxgi/src/lib.rs
tests/handle.rs

Planned:
Fixes #970
#423 will become necessary for staging.

Change usage semantics

---

examples/instancing/main.rs
src/backend/dx11/src/command.rs
src/backend/dx11/src/execute.rs
src/backend/dx11/src/lib.rs
src/backend/gl/src/command.rs
src/backend/gl/src/lib.rs
src/backend/metal/src/command.rs
src/backend/vulkan/src/command.rs
src/core/src/command.rs
src/core/src/dummy.rs
src/core/src/handle.rs
src/core/src/pso.rs
src/render/src/encoder.rs
src/render/src/factory.rs

Implement buffer copying

---

CHANGELOG.md
Cargo.toml
src/window/dxgi/Cargo.toml

Fixed the gfx_window_dxgi version

---

src/render/src/encoder.rs

Tracking the index buffer mapping

---

src/backend/dx11/src/lib.rs
src/backend/gl/src/lib.rs
src/backend/metal/src/lib.rs
src/backend/vulkan/src/command.rs
src/core/src/command.rs
src/core/src/dummy.rs
src/core/src/lib.rs
src/core/src/pso.rs
src/render/src/encoder.rs
src/render/src/pso/mod.rs
src/window/vulkan/src/lib.rs

Also moves the structure from `core::pso` to `core::command` to highlight its relation with the command submission process.
Closes #1133

Use HashSet for AccessInfo

---

src/core/src/memory.rs

Closes https://github.com/gfx-rs/gfx/issues/1157

Implement `Pod` for tuples

---

README.md
info/contrib.md

Document the directory structure

---

src/backend/dx11/src/factory.rs
src/core/src/factory.rs
src/window/dxgi/src/lib.rs

https://github.com/gfx-rs/gfx/issues/1122

DX11 resize fix

---

src/core/src/lib.rs

Add Surface, Instance, Swapchain, CommandQueue, QueueFamily and Adapter traits to core from corell.
The backends would need updates later-on. The dx12ll and vulkanll backends can be used for reference.
After the backend changes, the window crates shouldn't be needed anymore and replaced by the `Surface` and `SwapChain` parts.
Open question would be the support for other windows like SDL and glfw, because the current surface trait uses an associated window type.

Migrate low level core API changes to core.

---

src/backend/dx11/src/lib.rs
src/backend/gl/src/lib.rs
src/backend/metal/src/lib.rs
src/backend/vulkan/src/command.rs
src/core/src/buffer.rs
src/core/src/command.rs
src/core/src/dummy.rs
src/core/src/factory.rs
src/core/src/lib.rs
src/core/src/mapping.rs
src/render/src/encoder.rs
src/window/vulkan/src/lib.rs

Closes #1164.
Triggered error on the supplied code:

Stricter mapping access behavior

---

Cargo.toml
src/window/sdl/Cargo.toml
src/window/sdl/src/lib.rs

Based on #1171
Fixes #1169 
cc @jplatte @Icefoxen

SDL window update

---

appveyor.yml

AppVeyor Rust version bump to 1.15

---

src/backend/gl/src/factory.rs

[GL] Work around 0-sized storage buffers

---

src/render/src/macros/structure.rs

Fix base offset in `query()`

---

src/backend/dx11/src/lib.rs
src/backend/gl/src/info.rs
src/backend/gl/src/lib.rs
src/backend/metal/src/lib.rs
src/backend/vulkan/src/command.rs
src/core/src/dummy.rs
src/core/src/lib.rs

re https://github.com/gfx-rs/gfx/issues/1131

expose copy buffer support in capabilities

---

src/backend/metal/Cargo.toml
src/window/metal/Cargo.toml

Update objc crate version for Metal backends.

Update objc crate version

---

src/backend/metal/Cargo.toml
src/window/metal/Cargo.toml

Should hopefully fix build errors in #1205

Bump metal-rs version

---

src/backend/gl/src/command.rs
src/core/src/pso.rs

Adding more caching to GL backend. (#1221)

---

src/render/src/lib.rs

- Reexport `SubmissionError` and `SubmissionResult` types.
CC @kvark @msiglreith

Reexport SubmissionError and SubmissionResult

---

src/backend/vulkanll/Cargo.toml
src/backend/vulkanll/src/factory.rs
src/corell/src/factory.rs

Add compute pipeline creation
cc #1052 
(corell now should have support for most of the core features from vulkan/dx12.)

[ll] Compute pipeline

---

src/backend/dx11/src/lib.rs
src/backend/gl/src/lib.rs
src/backend/metal/src/lib.rs
src/core/src/command.rs
src/core/src/dummy.rs
src/core/src/lib.rs
src/core/src/memory.rs
src/core/src/pso.rs

_[01/..] Part of a longer project for merging corell into core_
Merge device setup and surface creation part from corell.
Adapater, Surface, Swapchain, etc. will be gradually updated to match corell.
Device trait will be replaced by a struct containing queues, heaps and a resource factory.

[ll] Core update [01/..]

---

src/window/sdl/src/lib.rs

Added some functions similar to those in gfx_window_glutin so you can resize the viewport according to the window size.

Add resizing support for gfx_window_sdl

---

Cargo.toml
src/backend/dx12/Cargo.toml
src/backend/dx12/README.md
src/backend/dx12/src/command.rs
src/backend/dx12/src/factory.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/native.rs
src/backend/dx12ll/Cargo.toml
src/backend/gl/Cargo.toml
src/lib.rs

Create backend for dx12 to keep track with the current changes.
Most parts still unimplemented and focusing on the device setup parts.

[ll] Add new dx12 backend [04/..]

---

src/backend/gl/src/info.rs
src/backend/gl/src/shade.rs

Only enable gl.BindFragDataLocation for desktop (v2)

---

src/backend/gl/Cargo.toml
src/backend/gl/src/info.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/shade.rs

Includes #1277 and #1266
cc @ozkriff

[v0.16] GL fixes for Android

---

.travis.yml
Cargo.toml
src/window/glutin/Cargo.toml
src/window/glutin/src/headless.rs
src/window/glutin/src/lib.rs

:tada: We are now able to test `gfx` to make it more robust :tada:

Add init_headless to gfx_window_glutin

---

src/render/src/slice.rs

Fix typo and remove trailing whitespace in slice.rs

---

src/backend/gl/src/factory.rs
src/backend/gl/src/info.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/tex.rs

I think these values are correct.
I compared the header at https://www.khronos.org/registry/OpenGL/api/GLES3/gl32.h to the functions listed in the extension specifications at https://www.khronos.org/registry/OpenGL/extensions/ARB/

Improved GLES capability list

---

Cargo.toml
src/lib.rs
src/shade.rs

* Hide GL behind a feature for better consistency and control
* Add dx11 feature to allow dx12 backend in the future

[ll] app: Cleanup backend features [07/..]

---

README.md

Includes #1302 
Closes #1111 
We should carefully look at instructions in README to avoid new user's problems.

Fix version in readme

---

src/backend/dx11/src/command.rs
src/core/src/command.rs

Fixes #1149 
I'm not sure that I understood task correctly...

Force command buffer to be 'static

---

src/backend/gl/src/factory.rs
src/backend/gl/src/lib.rs
src/lib.rs
src/shade.rs
src/window/glutin/src/lib.rs

Current focus lays on refactoring the app to minimize the backend specific code to window setup.

[ll] app: Adopt GL to the application refactor [10/..]

---

README.md

Provide badges for every crate

---

README.md

Add rust-oids into readme

---

examples/cube/main.rs
src/backend/gl/src/lib.rs
src/core/src/lib.rs
src/core/src/queue.rs
src/lib.rs
src/render/src/encoder.rs

* `Cube` demo now runs on GL (excluding resizing..)
* Fix queue submission on GL as mentioned on the prior PR, based on the old `Device` interface
(Removed unneeded attribute from the last PR)

[ll] Port cube example and fix gl queue submission [13/..]

---

src/backend/gl/src/lib.rs

As discussed :)
edit (msiglreith): Fixes #1319

Fixed support for OpenGL drivers without VAO

---

src/backend/vulkan/src/command.rs
src/backend/vulkan/src/factory.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/native.rs
src/backend/vulkan/src/pool.rs
src/core/src/command.rs
src/core/src/window.rs
src/window/vulkan/src/lib.rs

* Fix build due to latest API changes
* Remove global static `Instance` 
cc #1321

[ll] Update vulkan backend [20/..]

---

src/backend/dx11/Cargo.toml
src/backend/dx12/src/command.rs
src/backend/dx12/src/data.rs
src/backend/dx12/src/factory.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/native.rs
src/backend/dx12/src/pool.rs
src/lib.rs
src/shade.rs
src/window/dxgi/Cargo.toml
src/window/dxgi/src/lib.rs

Update the backend, implement dxgi window backend and integrate it into app.
Add a few changes from https://github.com/gfx-rs/gfx/pull/1330 regarding the swapchain setup.
cc #1321 
Note: The backend doesn't work at the current state (panics sooner or later).

[ll] Update dx12 backend [22/..]

---

examples/cube/shader/cube_150.glslv
examples/particle/shader/particle_150.glslg
examples/shadow/shader/forward_150.glslf
examples/shadow/shader/shadow_150.glslv
examples/skybox/shader/cubemap_150.glslv
examples/terrain/shader/terrain_150.glslv
examples/terrain_tessellated/shader/terrain.glsle
examples/ubo_tilemap/shader/tilemap_150.glslf
examples/ubo_tilemap/shader/tilemap_150.glslv

Needs verification from someone who knows what they're doing, though.

Add layout specifiers to some examples that didn't have them.

---

examples/mipmap/main.rs
examples/terrain_tessellated/main.rs
examples/ubo_tilemap/main.rs
src/render/src/encoder.rs

[ll] Update tilemap, tessellation and mipmap example [24/..]

---

Cargo.toml
src/window/metal/Cargo.toml

Metal window version bump

---

src/render/Cargo.toml
src/render/src/encoder.rs

This is very basic and just exposes the existing API of `CommandBuffer`.

Added generate_mipmap

---

examples/deferred/main.rs
src/backend/gl/src/factory.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/pool.rs

- Update deferred example
- Restore GL functionality which got lost during the integration changes (setting permanent states and fbo for each command buffer)

[ll] Update deferred and fix GL backend [25/..]

---

src/backend/dx11/src/factory.rs
src/backend/dx11/src/lib.rs
src/backend/gl/src/factory.rs
src/backend/gl/src/info.rs
src/backend/metal/src/lib.rs
src/core/src/lib.rs
src/core/src/pool.rs
src/core/src/queue.rs
src/core/src/window.rs

* Improve formatting of core
* Improve capabilities documentation
* Remove unused dx11 code

[ll] Improve documentation and formatting [26/..]

---

examples/gamma/main.rs
examples/performance/main.rs
examples/triangle/main.rs
src/backend/dx12/src/command.rs
src/backend/dx12/src/factory.rs
src/backend/gl/src/command.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/pool.rs
src/backend/vulkan/src/factory.rs
src/core/src/pool.rs
src/lib.rs
src/render/src/encoder.rs
src/window/dxgi/src/lib.rs
src/window/glfw/examples/window.rs
src/window/glutin/src/lib.rs
src/window/sdl/examples/window.rs
src/window/sdl/src/lib.rs
src/window/vulkan/src/lib.rs

- Update the performance example
- Optimize GL submission and fix command buffer reset
- Windows now take ownership of the raw windows
- Fix rebasing issues
cc #1321

[ll] Update performance and change windows [30/..]

---

Cargo.toml
src/backend/metal/Cargo.toml
src/backend/metalll/Cargo.toml
src/window/metal/Cargo.toml

OSX dependencies bumps

---

.travis.yml
Cargo.toml
examples/trianglell/main.rs
examples/trianglell/shader/triangle_indirect.metal
src/backend/dx12ll/src/factory.rs
src/backend/metal/src/lib.rs
src/backend/metalll/Cargo.toml
src/backend/metalll/src/command.rs
src/backend/metalll/src/factory.rs
src/backend/metalll/src/lib.rs
src/backend/metalll/src/native.rs
src/backend/vulkanll/src/factory.rs
src/corell/src/factory.rs

Implements my idea from https://github.com/gpuweb/gpuweb/issues/19#issuecomment-306901896
Depends on https://github.com/gfx-rs/metal-rs/pull/6
~~Note: changes the coreLL API a bit (added to #1241)~~
Fixes  #1372

[ll][metal] Basic indirect argument buffer support

---

src/core/src/factory.rs
src/core/src/memory.rs
src/render/src/lib.rs
src/render/src/slice.rs

#1388 but rebased on top of the pre-ll branch.

Add more documentation (pre-ll).

---

.travis.yml
Cargo.toml
bors.toml

Bors-ng integration

---

src/backend/gl/src/lib.rs

I tested it in a VM that only supported OpenGL 3.0 and it seems to work fine. However, I don't know if the assert is necessary, should it be removed?

Check for CopyBufferSubData, fixes #1356 and adds an alternative path

---

src/corell/src/factory.rs
src/corell/src/shade.rs

Implement Error trait for more error types in the ll crate

[ll] Implement error trait for more errors

---

src/backend/gl/src/info.rs
src/backend/gl/src/lib.rs
src/core/src/lib.rs
src/core/src/pso/graphics.rs

Address the aspects mentioned in #1436

[ll] Followup to #1436 

---

examples/render/triangle/main.rs
examples/render/triangle/shader/triangle_120.glslf
examples/render/triangle/shader/triangle_150.glslf
examples/render/triangle/shader/triangle_150.glslv

The shader versions were changed in #1417.

Fix shader versions to work on macOS

---

src/render/src/lib.rs

I think this is supposed to be public, so the user can send it around.

Make `GraphicsSubmission` public.

---

src/backend/empty/src/lib.rs
src/core/Cargo.toml
src/core/src/adapter.rs
src/core/src/device.rs
src/core/src/lib.rs
src/core/src/pass.rs
src/core/src/window.rs

* core: Remove duplicate `Subpass` struct

[ll] Fix empty backend and core tests

---

examples/core/quad/main.rs
src/backend/vulkan/src/device.rs

[ll] sub-pass post-fixes in quad example & vulkan

---

src/backend/gl/Cargo.toml
src/backend/gl/src/factory.rs
src/core/Cargo.toml
src/core/src/handle.rs

Port of #1397 to 0.16
required us to bump gfx_core as well, unfortunately

[pre][GL] removal of Factory::frame_handles

---

examples/cube/main.rs
examples/mipmap/main.rs
examples/ubo_tilemap/main.rs
src/backend/dx12ll/src/command.rs
src/backend/dx12ll/src/factory.rs

d3d12ll build fix

---

examples/core/quad/main.rs
examples/core/quad/shader/quad_450.glslf
examples/core/quad/shader/quad_450.glslv
src/backend/dx12/src/device.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/gl/src/native.rs
src/backend/vulkan/src/device.rs
src/core/src/device.rs
src/core/src/lib.rs
src/core/src/pass.rs
src/core/src/pso/mod.rs

* gl: Implement shader and program creation for graphics pipeline
* core: Rename `SubPass` to `Subpass` everywhere (wasn't consistent across the source)
* core: Improve memory heaps doc a bit (following the recent confusion about merging heaps and types)

[ll] gl: Working on pipeline creation

---

src/backend/gl/src/command.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/pool.rs

Switch from `UnsafeCell`+`AtomicBool` over to `Mutex` as discussed on gitter.
Motivated by low performance penality for the (usual) uncontained case for the memory access.
Now shares the complete `BufferMemory` instead of only `OwnedBuffer` because there seems no library support to `map` a mutex or share it for multiple data structures.

[ll] gl: Mutexes for command pool storage

---

src/backend/gl/src/command.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/pool.rs
src/backend/vulkan/src/device.rs

Followup to #1479 
* Only `try_lock` the command pool memory, else panic as it would be an invalid access pattern
* Fix vulkan backend build

[ll] gl: Only try to lock command pools

---

.travis.yml
src/backend/metal/src/factory.rs

Add missing glfw dependencies for the newer trusty images.
Same as #1422

[pre-ll] Fix travis linux build

---

examples/core/quad/main.rs
examples/render/quad_render/main.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/native.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/native.rs
src/core/src/device.rs
src/core/src/lib.rs
src/core/src/pass.rs
src/core/src/pso/graphics.rs
src/core/src/pso/mod.rs

I made it pretty Vulkan-ic :)
In the future, we may add specialization to `EntryPoint` struct.

[ll] shader module API rework

---

src/backend/gl/Cargo.toml
src/backend/gl/src/lib.rs

[gl] FBO fix and version bump

---

src/backend/gl/src/lib.rs
src/backend/gl/src/state.rs

Includes #1488 (from 0.16 branch)

[gl] Android and FBO fixes

---

src/backend/vulkan/src/conv.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/window.rs

Validation says that anisotropy needs to be 1.0 exactly if disabled...
Also fixes the window detection on Vk

[ll][vk] anisotropy fix

---

examples/core/quad/main.rs
scripts/travis-script.sh
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs

[ll] Metal indirect argument buffer path

---

src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/native.rs
src/backend/dx12/src/pool.rs
src/backend/dx12/src/window.rs
src/core/src/pass.rs

(can't test it on AMD atm, Intel worked either way)

[ll][dx12] Basic subpass dependencies

---

src/backend/dx12/src/command.rs
src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/native.rs
src/backend/vulkan/src/conv.rs
src/core/src/image.rs

This PR gets DX12 backend to a state capable of running 05-image sample of webgpu-servo

[ll][dx12] Proper resource flags, image to buffer copies

---

src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/native.rs
src/backend/dx12/src/window.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/metal/src/command.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/conv.rs
src/core/src/command/graphics.rs
src/core/src/command/raw.rs
src/core/src/command/renderpass.rs
src/core/src/image.rs

* Add `clear_attachments` command for clears inside renderpasses
* dx12: Implement `Reset` command
* dx12: Fix subresource ranges for image transitions

[ll] Clear attachments and small fixes

---

Cargo.toml
src/backend/dx12ll/Cargo.toml
src/backend/vulkanll/Cargo.toml
src/window/dxgi/Cargo.toml
src/window/glutin/Cargo.toml
src/window/metal/Cargo.toml
src/window/vulkan/Cargo.toml

Increment gfx_window_glutin -> 0.18 for release.
No example code changes were needed.

[v0.16] Update to glutin 0.10, winit 0.8

---

src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/window.rs

Similar to PR #1518
Closes #1524

[ll] vulkan: Add native X11 and Wayland integration support

---

src/backend/gl/src/tex.rs

[gl] detect main FBO in bind_read_fbo

---

src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs

Follow-up to #1560
cc @AlphaModder

[vk] Ash update to 0.19.1

---

src/backend/dx12/Cargo.toml
src/backend/dx12/src/native.rs
src/hal/Cargo.toml
src/hal/src/buffer.rs
src/hal/src/image.rs
src/hal/src/memory.rs
src/hal/src/pool.rs
src/hal/src/pso/mod.rs
src/render/Cargo.toml
src/render/src/memory.rs

[ll] Update bitflags to 1.0

---

src/hal/src/lib.rs
src/hal/src/pso/input_assembler.rs

Add PartialOrd and Ord to several types

---

bors.toml
examples/hal/quad/main.rs
examples/render/quad_render/main.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/window.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/metal/src/device.rs
src/backend/metal/src/window.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/window.rs
src/hal/src/buffer.rs
src/hal/src/device.rs
src/hal/src/window.rs
src/render/src/allocators/boxed.rs
src/render/src/allocators/stack.rs
src/render/src/device.rs
src/render/src/handle.rs
src/render/src/lib.rs
src/render/src/memory.rs
src/render/src/pso.rs
src/warden/src/gpu.rs

Fixes #1608 (some non-device parts can go as follow-ups)
Also:
- removes `Clone` bound
- updates some device documentation
- re-orders device methods (in HAL only so far)
- adds image count to swapchain config

Internally synchronized Device

---

src/backend/dx11/src/factory.rs

This is a little hacky, but it's fine for backend-specific stuff (especially in pre-ll).
@zakorgy would be great to get some feedback from you on it. And no rush!

[dx11] texture mapping for reads

---

src/backend/dx11/src/execute.rs

[pre-ll][dx11] texture slice copy support

---

.travis.yml
appveyor.yml
src/backend/gl/src/command.rs
src/backend/gl/src/factory.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/state.rs

[pre-ll][gl] Main FBO masking workaround

---

.travis.yml
appveyor.yml
src/backend/gl/Cargo.toml
src/backend/gl/src/command.rs
src/backend/gl/src/factory.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/state.rs

Copy of #1645 for v0.16 (non-breaking)

[v0.16][gl] Main FBO masking

---

src/backend/vulkan/src/window.rs

vk: win32: Custom hinstance on surface creation

---

src/backend/dx11/src/factory.rs

The D3D11_MAPPED_SUBRESOURCE's RowPitch value can differ from the expected value (width * texel_size). Most probably it is a driver related thing.
This is just a half solution, because we get the whole pixel data from the texture, including empty pixels. And adding the correct rowpitch as a return value.
At the end it should be better to give back the filtered data, but I didn't had the time to do that.

Workaround for dx11 readpixels rowpitch issue

---

src/backend/dx12/src/command.rs
src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs
src/hal/src/command/renderpass.rs

* dx12: Fix VBV and IBV offsets
* dx12: Fix buffer usage flags
* dx12: Fix UBO SPIR-V resource binding
* hal: Add missing `push_graphics_constants` for subpass encoder

Bunch of minor dx12 and hal fixes

---

src/backend/metal/src/command.rs
src/backend/metal/src/conversions.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs

Depth metal

---

src/backend/gl/src/info.rs
src/backend/gl/src/tex.rs

[gl] Texture border capability

---

src/backend/gl/src/command.rs
src/backend/gl/src/queue.rs

Bind the GL program during `bind_graphics_pipeline`

[gl] Bind program

---

src/backend/gl/src/command.rs
src/backend/gl/src/device.rs
src/backend/gl/src/native.rs
src/backend/gl/src/queue.rs

Sets blend per attachments. I haven't added caching yet because I wanted to verify whether this is the correct approach.

[gl] Set blend per attachment

---

examples/hal/compute/main.rs
examples/hal/quad/main.rs
examples/render/quad_render/main.rs
src/backend/dx12/src/lib.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/lib.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/result.rs
src/hal/Cargo.toml
src/hal/src/adapter.rs
src/hal/src/lib.rs
src/render/Cargo.toml
src/render/src/lib.rs
src/warden/Cargo.toml
src/warden/src/bin/reftest.rs
src/warden/src/gpu.rs
src/warden/src/lib.rs

Add error handling for `PhysicalDevice::open` using the Vulkan return codes.
Early feedback appreciated!
~~**[WIP]** Implement remaining backends~~

Add error handling for logical device creation

---

.travis.yml
src/render/Cargo.toml
src/render/src/macros/pso.rs
src/render/src/pso/resource.rs

Allows hashing and comparing pipeline states.

[v0.16] Hash for pipe::Meta

---

src/render/Cargo.toml
src/render/src/macros/pso.rs
src/render/src/pso/resource.rs

[v0.17] Hash for pipe::Meta

---

src/render/src/macros/pso.rs
src/render/src/pso/resource.rs

[pre-ll] Hash for pipe::Meta

---

.travis.yml
Makefile
reftests/data/passthrough.frag
reftests/data/passthrough.vert
reftests/scenes/basic.ron
reftests/suite.ron
src/backend/gl/src/device.rs
src/backend/gl/src/info.rs
src/hal/src/pso/compute.rs
src/hal/src/pso/graphics.rs
src/hal/src/pso/mod.rs
src/warden/Cargo.toml
src/warden/src/bin/reftest.rs
src/warden/src/gpu.rs
src/warden/src/lib.rs
src/warden/src/raw.rs

Has a test, but I had to comment out the old one for now, until #1712 is merged.

[warden] Pipeline creation

---

reftests/scenes/basic.ron
src/warden/src/gpu.rs
src/warden/src/raw.rs

Fixes passtrough test on the vulkan backend

warden: Add commands for setting viewports and scissor rects

---

src/core/src/pso.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/1750)

feat: Increase maximum number of vertex buffers in a descriptor

---

examples/hal/Cargo.toml
examples/render/quad_render/Cargo.toml
src/backend/dx12/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml

Builds on all backends, not tested on any backends due to blocked by bugs and/or lack of supported devices.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/1759)

feat: Update winit to 0.10

---

examples/hal/compute/main.rs
src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs
src/backend/metal/src/window.rs

Fixes #1743
Depends on https://github.com/gfx-rs/metal-rs/pull/27
Includes part of #1751
r? @grovesNL

Metal compute support

---

src/backend/dx12/Cargo.toml
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/queue.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/result.rs
src/hal/src/adapter.rs
src/hal/src/device.rs
src/hal/src/error.rs
src/hal/src/lib.rs
src/hal/src/queue/mod.rs

Add `wait_idle` for queues and devices, currently implemented on vulkan only.
Once finished this should supersede https://github.com/gfx-rs/gfx/pull/1637

Add wait_idle

---

src/hal/src/command/raw.rs

Minor annotation as I've just seen this flag.

Add TODO regarding const fn for bitflags

---

Makefile
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/window.rs

[vk] XCB window support

---

src/backend/vulkan/src/device.rs

Fix image view creation in `gfx_ocean`.

vk: Fix image view aspect flags

---

src/backend/metal/src/command.rs

PR checklist:
metal backend is broken as well as in master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/1793)

[metal] draw_indexed doesn't consume index buffer

---

src/backend/dx12/Cargo.toml
src/backend/dx12/src/device.rs

dx12: Update spirv-cross

---

src/backend/metal/src/command.rs

PR checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/1801)

[metal] fix segfault

---

src/hal/src/command/mod.rs
src/hal/src/queue/submission.rs

PR checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/1810)

Cow instead of Box<Borrow>

---

.github/PULL_REQUEST_TEMPLATE.md
src/backend/dx12/src/command.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/conv.rs
src/hal/src/command/graphics.rs
src/hal/src/command/mod.rs
src/hal/src/command/raw.rs
src/hal/src/command/transfer.rs

Basic blits

---

src/warden/src/bin/reftest.rs

PR checklist:
This is better than trying to bail out on `macos` feature. Hopefully, the disability struct will not grow ;)

Warden temporary disabilities

---

src/backend/gl/src/device.rs

PR checklist:
`destroy_shader_module` is needed for the hal/quad example.
We generally assume that gfx controls the compiled shader object's lifetime. Because we don't cache these anywhere at the moment, we can also assume that it's fine to detach and delete the shader objects immediately after `LinkProgram` is called.
The downside is that this isn't valid for user-created shader modules where they may want to reuse shader objects later, but we're not sure whether that will be supported in the future anyway.

gl: Destroy shader modules

---

src/backend/vulkan/src/conv.rs
src/hal/src/image.rs

Add INPUT_ATTACHMENT & TRANSIENT_ATTACHMENT image usage flags

Add missing image usage flags

---

info/getting_started.md

Add Ubuntu prereqs to getting started

---

src/backend/vulkan/src/lib.rs

The debug adapter must be destroyed before the instance does or else
we'll get a warning.
PR checklist:
Vulkan

Fix Vulkan debug adapter warning.

---

src/backend/gl/Cargo.toml

[0.17] gfx_device_gl bump with the new gfx_gl

---

src/hal/src/adapter.rs
src/hal/src/backend.rs
src/hal/src/buffer.rs
src/hal/src/command/compute.rs
src/hal/src/command/graphics.rs
src/hal/src/command/mod.rs
src/hal/src/command/raw.rs
src/hal/src/command/render_pass.rs
src/hal/src/command/transfer.rs
src/hal/src/device.rs
src/hal/src/format.rs
src/hal/src/image.rs
src/hal/src/lib.rs
src/hal/src/mapping.rs
src/hal/src/memory.rs
src/hal/src/pass.rs
src/hal/src/pso/compute.rs
src/hal/src/pso/descriptor.rs
src/hal/src/pso/graphics.rs
src/hal/src/pso/input_assembler.rs
src/hal/src/pso/mod.rs
src/hal/src/pso/output_merger.rs
src/hal/src/query.rs
src/hal/src/queue/capability.rs
src/hal/src/queue/family.rs
src/hal/src/queue/mod.rs
src/hal/src/queue/submission.rs
src/hal/src/range.rs
src/hal/src/window.rs

New PR to replace #1800 with something that's a little less messy, commit-wise.
There's still some things that need fixing, they are marked with `DOC TODO` comments.  But there's only a few of them, and they're all things I either don't understand or need more holistic knowledge to explain well.  I hope to revisit them and clean them up at some point but there's other things I want to do first.
I seem to have accidentally messed up the names of a couple functions, those will get fixed ASAP.

Gfx docs rework

---

Cargo.toml
src/lib.rs
src/window/dxgi/Cargo.toml
src/window/glutin/Cargo.toml
src/window/metal/Cargo.toml
src/window/vulkan/Cargo.toml

Cherry pick 734a4fdcb710c89aca52a1a774de18403ef8011f to release support for glutin 0.13 / winit 0.11
PR checklist:

[v0.17] Update glutin, winit

---

src/backend/vulkan/src/device.rs
src/backend/vulkan/src/native.rs

[vk] image view type

---

src/backend/dx12/src/device.rs

Fixes #1842
PR checklist:
Wasn't able to test it on that machine, but nothing suspiciously wrong.

[dx12] Full image kind support for view creation

---

examples/hal/quad/main.rs
examples/render/quad_render/main.rs
src/backend/dx12/src/command.rs
src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/gl/src/conv.rs
src/backend/gl/src/device.rs
src/backend/metal/src/command.rs
src/backend/metal/src/conversions.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/conv.rs
src/backend/vulkan/src/device.rs
src/hal/src/command/graphics.rs
src/hal/src/command/raw.rs
src/hal/src/image.rs

Fixes https://github.com/gfx-rs/gfx/issues/1404
PR checklist:

WIP: Vulkanize the sampler

---

appveyor.yml
src/backend/gl/src/tex.rs

[pre-ll/gl] improved texture copies

---

src/backend/dx12/src/device.rs

Follow-up to #1876
PR checklist:
cc @zakorgy

[dx12] image kind support for RTV creation

---

examples/hal/quad/main.rs
examples/render/quad_render/main.rs
reftests/scenes/basic.ron
src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/native.rs
src/backend/dx12/src/window.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/conv.rs
src/backend/gl/src/device.rs
src/backend/gl/src/window/glutin.rs
src/backend/metal/src/device.rs
src/backend/metal/src/window.rs
src/backend/vulkan/src/conv.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/native.rs
src/backend/vulkan/src/window.rs
src/hal/src/command/graphics.rs
src/hal/src/command/mod.rs
src/hal/src/command/transfer.rs
src/hal/src/device.rs
src/hal/src/image.rs
src/hal/src/window.rs
src/render/src/device.rs
src/render/src/handle.rs
src/render/src/image.rs
src/render/src/lib.rs
src/warden/src/gpu.rs
src/warden/src/raw.rs

Fixes #1879 
~~Early WIP opened for feedback on the new HAL image API bits.~~ Ready for review now.
PR checklist:

Image kinds re-design

---

examples/hal/quad/main.rs
examples/render/quad_render/main.rs
src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/native.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/gl/src/state.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs
src/backend/metal/src/soft.rs
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/conv.rs
src/backend/vulkan/src/device.rs
src/hal/src/command/graphics.rs
src/hal/src/command/raw.rs
src/hal/src/command/render_pass.rs
src/hal/src/command/transfer.rs
src/hal/src/pso/graphics.rs
src/hal/src/pso/output_merger.rs
src/render/src/macros/pipeline.rs
src/render/src/pso.rs
src/warden/src/gpu.rs
src/warden/src/raw.rs

Baked pipeline states

---

examples/hal/Cargo.toml
examples/render/quad_render/Cargo.toml
src/backend/dx12/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml

Update library versions.

---

src/backend/vulkan/src/conv.rs
src/hal/src/buffer.rs
src/hal/src/command/raw.rs
src/hal/src/format.rs
src/hal/src/image.rs
src/hal/src/pso/mod.rs
src/hal/src/query.rs

Fixes #1724 
Before continuing with some more, I wanted to make sure this is the way to continue?
PR checklist:

Align HAL falgs with Vulkan flags

---

examples/hal/quad/main.rs
src/backend/dx12/src/device.rs
src/backend/vulkan/src/device.rs
src/hal/src/window.rs

Fixes #1875
PR checklist:
- vulkan
- dx12

Add image usage to swapchain config

---

src/backend/dx12/src/command.rs

Fixes #1905
PR checklist:
we should really get those reftests in place...

[dx12] worst case image-buffer copy fixes

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs

Fixes #1911
PR checklist:
~~It doesn't work yet (for some reason)~~

[osx] virtualized memory mapping

---

src/backend/dx12/Cargo.toml

Fixes https://github.com/gfx-rs/gfx/issues/1916
@callym: Could you check if it works for your project?
PR checklist:

dx12: Bump spirv-cross version

---

src/backend/vulkan/src/device.rs

Gets us further down the CTS line.
PR checklist:

[vk] destroy device on drop()

---

examples/hal/compute/main.rs
examples/hal/quad/main.rs
src/backend/dx12/src/native.rs
src/backend/gl/src/native.rs
src/backend/metal/src/native.rs
src/backend/vulkan/src/native.rs
src/hal/src/pso/descriptor.rs
src/render/src/device.rs
src/warden/src/gpu.rs

Make allocate_set(s) failable

---

src/backend/metal/src/command.rs

Fixes #1779
PR checklist:
r? @JohnColanduoni @grovesNL 
As mentioned on gitter, this doesn't allow us to get rid of the autorelease pools unfortunately. We can see it as a different issue.

[mtl] manually retain command buffer data

---

src/backend/dx12/src/lib.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/lib.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/lib.rs
src/hal/src/adapter.rs
src/hal/src/command/mod.rs

Refactor Adapter::open

---

src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs

Some initial cleanup for #1972
Depends on gfx-rs/metal-rs#38 to be merged/published first
PR checklist:

mtl: Remove some `msg_send`

---

Cargo.toml
examples/gamma/main.rs
examples/performance/main.rs
examples/triangle/main.rs
src/lib.rs
src/window/dxgi/Cargo.toml
src/window/glutin/Cargo.toml
src/window/metal/Cargo.toml
src/window/vulkan/Cargo.toml

* Update winit & glutin
* Update image dev-dependency
* Up versions to v0.17 nexts
PR checklist:

[pre-ll] Update glutin 0.15, winit 0.13

---

Cargo.toml
examples/gamma/main.rs
examples/performance/main.rs
examples/triangle/main.rs
src/lib.rs
src/window/dxgi/Cargo.toml
src/window/glutin/Cargo.toml
src/window/metal/Cargo.toml
src/window/vulkan/Cargo.toml

As #1986 for release
PR checklist:

[v0.17] Update glutin 0.15, winit 0.13

---

examples/hal/Cargo.toml
examples/hal/quad/main.rs
examples/render/quad_render/Cargo.toml
examples/render/quad_render/main.rs
src/backend/dx12/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml

Update winit to 0.13 and glutin to 0.15

---

reftests/local.ron
reftests/scenes/transfer.ron
src/backend/metal/Cargo.toml
src/backend/metal/shaders/commands.metal
src/backend/metal/src/command.rs
src/backend/metal/src/internal.rs

Fixes the case where size is not a multiple of 4
~~Based on (incomplete) #1995~~
PR checklist:

[mtl] Copy buffer compute shader

---

src/backend/metal/src/window.rs

metal: Fix Surface dimensions with retina

---

src/backend/dx12/src/command.rs

[ll] Fixed dx12 infinite loop when vertex buffers pending bind skip slot 0

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs

Apparently the store mode is DontCare *by default* on depth/stencil. This change doesn't let us pass more tests though - something is broken up in multiple spots (no sure who to blame yet):
- clearing multiple ranges doesn't work with UINT/INT (go figure what it has to do with multiple ranges...)
- clearing 1D texture doesn't work with any formats above 16 bits (e.g. RGBA8, RG16, etc), except for sRGB ones (we do have a hack in place to treat 1D textures as 2D if mipmaps are requested, but still unclear how is this related with the observed limitations)
Note: CTS has a lot of magic in it, and maybe it's simply broken (that already happened a few times), or there is something wonky going on around transfers/mapping that are required to check the results (even if clears are fine).
PR …

[mtl] force Store mode on depth/stencil clears

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/internal.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs
src/backend/metal/src/window.rs

Addresses a major part of #1984 but doesn't resolve it completely.
PR checklist:

[mtl] lock Device with Mutex. Force Private memory for tiled textures.

---

src/backend/dx11/src/lib.rs
src/backend/dx12/src/device.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs
src/backend/metal/src/window.rs
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/conv.rs
src/backend/vulkan/src/device.rs
src/hal/src/device.rs
src/hal/src/image.rs

Subresource footprint

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs

[mtl] vertex buffer remapping

---

src/backend/dx12/src/native.rs

dx12: fix descriptor freeing range

---

src/core/src/texture.rs

I could change the wording here if requested.

Fix inaccuracy in docs for FilterMethod

---

src/backend/metal/src/command.rs

Fixes a Metal validation error on us setting up the depth/stencil state upon entering a render pass that has no depth/stencil.
PR checklist:

[mtl] Filter the render pass states

---

info/getting_started.md

Updated path to examples in getting_started.md.

---

src/backend/dx11/src/conv.rs
src/backend/dx11/src/device.rs
src/backend/dx11/src/dxgi.rs
src/backend/dx11/src/internal.rs
src/backend/dx11/src/lib.rs
src/backend/dx11/src/shader.rs

[dx11] get rid of warnings

---

examples/Cargo.toml
examples/quad/main.rs
src/backend/dx11/Cargo.toml
src/backend/dx12/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/gl/src/command.rs
src/backend/gl/src/window/glutin.rs
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/window.rs
src/window/dxgi/src/lib.rs

Some minor fixes I did while working on #2136
PR checklist:

Latest winit, dpi bugfix and remap descriptors fix.

---

examples/quad/main.rs

See: https://github.com/amethyst/amethyst/issues/649 for similar issue
Might fix #2184
PR checklist:

Fixes resizing in Wayland and possibly in macOS.

---

src/backend/dx11/shaders/copy.hlsl
src/backend/dx11/src/device.rs
src/backend/dx11/src/lib.rs

[dx11] change buffer UAV/SRVs to raw views and add compute pipelines

---

src/backend/metal/src/command.rs

[mtl] defer the depth-stencil checks to the sync point

---

src/hal/src/buffer.rs

Fix typo in hal/src/buffer.rs

---

src/backend/auxil/range_alloc.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs

[mtl] debug output for descriptor allocation and frame wait times

---

.github/PULL_REQUEST_TEMPLATE.md
rustfmt.toml

This is not designed to be merged as-is but is here for discussion over whether this is a good idea/what options should be used. This covers most of @msiglreith's concerns on #1427 apart from the fact that the whitespace in the `Backend` trait gets removed. I've made comments on the few config options that it might make sense to tweak.

Add Rustfmt to workflow

---

src/backend/dx11/Cargo.toml
src/backend/dx12/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml

Cut logging in release

---

src/hal/src/device.rs

Add comments to hal/src/device.rs

---

src/backend/metal/src/command.rs

Fixes Dota on high settings.
PR checklist:

[mtl] fix compute resource override

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs

Fixes dynamic offsets (once again).
I accidentally noticed that piece of Vulkan spec:
> Values are taken from pDynamicOffsets in an order such that all entries for set N come before set N+1; **within a set, entries are ordered by the binding numbers in the descriptor set layouts**; and within a binding array, elements are in order. dynamicOffsetCount must equal the total number of dynamic descriptors in the sets being bound.
My previous code was written within an assumption that the user-given order of things define how both immutable samplers and dynamic buffers are handled. Apparently, the latter are always handled in the sorted order, which we already do (yay!), so with this (and a bit of extra reordering of immutable samplers) we are able to get rid of the associated data index (of …

[mtl] rewrite handling of dynamic offsets and immutable samplers

---

src/backend/metal/src/command.rs

These are useful to experiment with.
PR checklist:

[mtl] expose stitching and dummy encoder options

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/internal.rs
src/backend/metal/src/native.rs

Fixes #2324
Fixes #2307
Fixes #2058 (unrelated to the PR, but harmless)
PR checklist:

[mtl] New vertex binding logic

---

examples/Cargo.toml
src/backend/dx11/Cargo.toml
src/backend/dx11/src/device.rs
src/backend/dx12/Cargo.toml
src/backend/dx12/src/device.rs
src/backend/empty/src/lib.rs
src/backend/gl/Cargo.toml
src/backend/gl/src/device.rs
src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/device.rs
src/hal/src/device.rs

Metal-rs and winit updates

---

src/backend/metal/src/device.rs

Detect OS version to set `MTLLanguageVersion` based on the minimum version specified in [the Apple documentation](https://developer.apple.com/documentation/metal/mtllanguageversion?language=objc) (on each enum value's page)
Note `NSProcessInfo` already exists in foundation, but `operatingSystemVersion`/`NSOperatingSystemVersion` appear to be missing for now (eventually we can upstream it).
PR checklist:

[mtl] Detect OS version

---

src/backend/metal/src/conversions.rs

Fixes the early RPC3/Uncharted failures
PR checklist:

[mtl] fix Bc1Rrgba support and the alpha swizzle

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs

Fixes Dolphin emulator ;)
PR checklist:

[mtl] fix MSL version chooser

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs

Partially reverts #2300
Fixes #2383
PR checklist:
Tested on Dota2 and some CTS categories.

[mtl] unflatten descriptor pools

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs

Fixes vkQuake:
PR checklist:
~~TODO: need to fix Dolphin~~

Metal multi-pass support

---

src/backend/metal/src/command.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/window.rs

There are still occasional asserts on frame acquisition, so leaving #2400 open for now.
PR checklist:

[mtl] Filament compatibility fixes

---

src/backend/metal/src/command.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/window.rs

Allows us to work with the `CAMetalLayer` directly, bypassing the NSView/UIView. This matches the discussion of VkPI group and recent changes in MVK.
I'll have it tested on Dolphin, although there shouldn't be any harm merging as is.
PR checklist:

[mtl] refactor surface creation, support CAMetalView initialization

---

src/hal/src/device.rs
src/hal/src/pso/mod.rs

To make error handling easier :)
PR checklist:

Just some simple error impls.

---

src/backend/gl/src/lib.rs
src/core/Cargo.toml
src/core/src/handle.rs
src/render/Cargo.toml

I needed this for submitting frames to my VR compositor. I'm very unsure of the quality of this PR however :stuck_out_tongue:

[pre-ll] Add accessors to allow getting a raw GLuint from a texture

---

examples/quad/main.rs

I really struggled to know what was going on here for a long time, so I wrote some notes to help those that follow.

Add some notes about finding the right memory

---

src/backend/dx11/src/factory.rs

Fix for panic when creating an empty vertex buffer dx11

---

src/hal/src/adapter.rs

Fixes an issue
PR checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/2442)

Make Adapter more frendly

---

src/backend/metal/src/internal.rs

lifetime elision

---

.gitignore
examples/colour-uniform/main.rs
examples/compute/main.rs
examples/quad/main.rs
src/backend/dx11/src/device.rs
src/backend/dx12/src/device.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/window.rs
src/hal/src/buffer.rs
src/hal/src/device.rs
src/hal/src/image.rs
src/hal/src/mapping.rs
src/hal/src/pso/mod.rs
src/hal/src/query.rs
src/hal/src/window.rs
src/warden/src/gpu.rs

Can't actually check building for backends except metal.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/2424)

Remove most 'expect' calls from 'gfx-backend-vulkan'.

---

src/backend/dx12/Cargo.toml
src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/internal.rs
src/backend/dx12/src/lib.rs

Bump d3d12 version

---

Cargo.toml
examples/deferred/main.rs
examples/gamma/main.rs
examples/terrain/main.rs
examples/triangle/main.rs
src/lib.rs
src/window/dxgi/Cargo.toml
src/window/glutin/Cargo.toml
src/window/glutin/src/headless.rs
src/window/metal/Cargo.toml
src/window/vulkan/Cargo.toml

This PR was requested in #2468.
Any changes requested in this PR should be requested in #2468 first, and then I'll update this PR accordingly.

update glutin to 0.19 and winit to 0.18

---

src/backend/gl/src/command.rs
src/backend/gl/src/device.rs
src/backend/gl/src/info.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/native.rs
src/backend/gl/src/queue.rs

Fixes to get gl backend to work with opengl 3.0

---

Cargo.toml
examples/gamma/main.rs
examples/performance/main.rs
examples/triangle/main.rs
src/lib.rs
src/window/glutin/Cargo.toml
src/window/glutin/README.md
src/window/glutin/src/lib.rs

Backport #2491 to v0.17

---

Cargo.toml
examples/gamma/main.rs
examples/performance/main.rs
examples/triangle/main.rs
src/lib.rs
src/window/glutin/Cargo.toml
src/window/glutin/README.md
src/window/glutin/src/lib.rs

Motivation: https://github.com/amethyst/amethyst/issues/135#issuecomment-441402015

Return result from gfx_window_glutin::init

---

examples/compute/main.rs
src/backend/dx12/src/command.rs
src/backend/vulkan/src/command.rs
src/hal/src/memory.rs
src/warden/src/gpu.rs

Fixes #issue
PR checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/2505)

subbuffer-barrier

---

src/backend/gl/src/lib.rs
src/backend/vulkan/src/factory.rs

[pre-ll/gl] don't use temporary manager for resource creation

---

src/backend/metal/src/lib.rs

When creating a surface from an NSView, macOS has fallbacks in case the main layer is not a CAMetalLayer. This PR implements similar fallbacks on iOS for UIView by creating a CAMetalLayer sublayer. This might not be a behavior one would want in gfx, so feel free to close the PR is this is not the proper fix for this issue.
I tested this with omni-viral's rendy on an iOS device with a default winit window **against hal-0.1.0**, as rendy is not compatible with latest master.
PR checklist:
I can try to test the repo's other examples on iOS but I am not sure if I will be able to sort out platform-specific issues.

Add fallback on iOS for missing CAMetalLayer

---

src/backend/gl/src/factory.rs
src/backend/gl/src/info.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/tex.rs

[pre-ll/gl] Native texture SRV views

---

src/hal/src/pool.rs

The documentation for command pools became out of date with #2514. As far as I can tell, the command pool no longer automatically manages command buffers for you, and you must handle allocating and freeing them yourself.
PR checklist:

Fix command pool documentation

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/internal.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/window.rs

Before this, if using a default `SwapchaingConfig`, gfx would think the swapchain drawables were changed every 3rd frame under certain conditions on iphone5s release builds (very specifically...). This is because the Drawable pool size is fixed at 3 in release builds for that device, and `SwapchainConfig` defaults to a pool size of 2.
The [API](https://developer.apple.com/documentation/quartzcore/cametallayer/2938720-maximumdrawablecount?language=objc) for setting the drawable pool size is fairly new, but appears to work on _some_ devices, and possibly on older macos versions? So there's only version checking on iOS.
Also, I moved `PrivateCapabilities` into `Shared` as discussed in #2548.
PR checklist:

fix for iphone5s drawable pool size being locked at 3

---

src/hal/src/queue/mod.rs

Fix misleading documentation of `submit` functions

---

src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/window.rs

PR checklist:
- Vulkan (Windows, Linux)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/2565)

[vk] ash update to 0.27.0

---

src/backend/gl/src/command.rs
src/backend/gl/src/info.rs
src/backend/gl/src/queue.rs

This allows instancing on the GL backend.

Add support for attribute binding rate on the GL backend

---

.travis.yml
src/backend/dx12/src/device.rs

[dx12] get_fence_status

---

src/hal/src/image.rs

As noticed by https://github.com/Lokathor/learn-gfx-hal/blob/master/book/src/04_triangle_intro.md#depth-testing

Remove legacy image api

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs

[mtl] remove unnecessary unsafe blocks

---

src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs

Make Format Properties Lazy for dx12 backend

---

src/backend/metal/src/window.rs

Fixes iOS after https://github.com/gfx-rs/gfx/pull/2607
iOS does not have convertRectToBacking. `nativeScale` on UIScreen serves the same purpose.

[mtl][iOS] fix for dimensions. no convertRectToBacking on iOS

---

src/backend/dx12/src/command.rs

[dx12] fix push constants offset

---

src/backend/dx11/src/lib.rs
src/backend/dx12/src/lib.rs
src/backend/gl/src/device.rs
src/backend/gl/src/info.rs
src/backend/metal/src/device.rs
src/backend/metal/src/window.rs
src/backend/vulkan/src/lib.rs
src/hal/src/lib.rs

Needed for https://github.com/gfx-rs/portability/pull/174
PR checklist:

Metal surface fix, extended features and limits for portability

---

src/backend/metal/src/window.rs

Fixes Dota in portability
Also can help with #2563, but some testing  is needed to confirm
PR checklist:

[mtl] fixed surface size, better presentation debug messages

---

CHANGELOG.md
Cargo.toml
README.md
src/backend/dx11/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/gl/src/shade.rs
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml
src/core/Cargo.toml
src/core/src/command.rs
src/core/src/pso.rs
src/core/src/shade.rs
src/core/src/texture.rs
src/render/Cargo.toml
src/render/src/shade.rs
src/render/src/slice.rs
src/window/dxgi/Cargo.toml
src/window/glfw/Cargo.toml
src/window/glutin/Cargo.toml
src/window/metal/Cargo.toml
src/window/sdl/Cargo.toml
src/window/sdl/src/lib.rs
src/window/vulkan/Cargo.toml

last v0.18 pre-release fixes

---

src/backend/vulkan/src/device.rs

support for tessellation patch count in vulkan-backend

---

src/backend/metal/src/command.rs
src/backend/metal/src/conversions.rs
src/backend/metal/src/device.rs
src/backend/metal/src/internal.rs
src/backend/metal/src/native.rs
src/backend/metal/src/soft.rs
src/backend/metal/src/window.rs

[mtl] clean code such as remove .clone()

---

src/hal/src/image.rs

[hal] improve literal readability

---

src/hal/src/image.rs

[hal] replace range loop with iterator

---

examples/quad/main.rs

quad: Remove some old TODOs

---

src/backend/dx12/Cargo.toml
src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/resource.rs

sibling of #2664 for hal-0.1 branch

[0.1/dx12] typeless image format

---

src/backend/vulkan/src/lib.rs

Replace unimplemented! debug implementation with placeholder

---

CHANGELOG.md
examples/Cargo.toml
examples/colour-uniform/main.rs
examples/compute/main.rs
examples/quad/main.rs
src/backend/dx11/Cargo.toml
src/backend/dx11/src/device.rs
src/backend/dx11/src/internal.rs
src/backend/dx11/src/lib.rs

Dx11 fixes and the changelog

---

src/hal/src/command/raw.rs
src/hal/src/pso/input_assembler.rs

Improve vertex buffer binding documentation

---

src/backend/metal/src/device.rs

[mtl] expose custom sampler configuration

---

README.md

https://www.reddit.com/r/rust_gamedev/comments/b01zy9/please_help_me_understand_the_gfxrs_architecture/
Several others have been confused about this too in the past
PR checklist:

Clarify the differences between `gfx`, `gfx-hal`, and `wgpu` in the README

---

src/hal/src/window.rs

Fixes [#2703](https://github.com/gfx-rs/gfx/issues/2703)

Make `AcquireError` auto-implement `Clone`

---

src/backend/dx11/src/lib.rs

[pre-ll] initialize device

---

.travis.yml
Cargo.toml
examples/gamma/main.rs
examples/performance/main.rs
examples/triangle/main.rs
src/lib.rs
src/window/glutin/Cargo.toml
src/window/glutin/src/headless.rs
src/window/glutin/src/lib.rs

Update to the latest quite breaking glutin api changes.
PR checklist:

[pre-ll] Update glutin -> 0.21

---

examples/Cargo.toml
examples/colour-uniform/main.rs
examples/quad/main.rs
src/backend/dx11/Cargo.toml
src/backend/dx12/Cargo.toml
src/backend/empty/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/gl/src/window/glutin.rs
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml
src/warden/src/bin/reftest.rs

Fixes #2743 
PR checklist:
- [~] `make reftests` succeeds
Regarding reftests... I hope that this means it succeeded:

Update winit dependency to 0.19 and glutin to 0.20

---

src/hal/src/command/render_pass.rs

Fixes few compiler warnings.
PR checklist:

Prevent render pass encoders from ending render pass multiple times.

---

examples/colour-uniform/main.rs
examples/quad/main.rs
src/backend/dx11/src/lib.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/window.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/queue.rs
src/backend/gl/src/window/glutin.rs
src/backend/metal/src/command.rs
src/backend/metal/src/window.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/window.rs
src/hal/src/queue/mod.rs
src/hal/src/window.rs

Add missing acquire image/present errors

---

src/hal/src/image.rs

Fixes https://github.com/amethyst/rendy/issues/117
PR checklist:

Expand docs and add some Default impl's for image

---

src/backend/gl/src/command.rs
src/backend/gl/src/device.rs
src/backend/gl/src/info.rs
src/backend/gl/src/native.rs
src/backend/gl/src/queue.rs
src/backend/gl/src/window/glutin.rs

Changes to support wgpu gl backend

---

examples/colour-uniform/main.rs
examples/compute/main.rs
examples/quad/main.rs
src/hal/src/queue/mod.rs
src/hal/src/window.rs
src/warden/src/gpu.rs

[hal] rename present_nosemaphores

---

src/backend/metal/src/lib.rs

[mtl] impl create_surface() the way vulkan backend did

---

src/backend/metal/src/lib.rs

https://github.com/gfx-rs/gfx/pull/2802#issuecomment-499417344
PR checklist:

[mtl] restore removed surface functions

---

src/backend/vulkan/src/device.rs

As reported in gitter, resolve attachments are not workin at the moment

vk: Add missing renderpass resolve attachments

---

examples/colour-uniform/main.rs

Fix command buffer leak in the color-uniform example

---

CHANGELOG.md
Makefile
src/backend/metal/Cargo.toml
src/backend/metal/src/device.rs
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/window.rs

Port #2828 and #2831 from `hal-0.2` to `master`

---

src/backend/vulkan/src/window.rs

Fixes `VK_ERROR_INITIALIZATION_FAILED: vkCreate_PLATFORM_SurfaceMVK(): On-screen rendering requires a layer of type CAMetalLayer` with MoltenVK.
PR checklist:

[vk] create `CAMetalLayer` for `NSView` if it doesn't exist

---

src/hal/Cargo.toml

It's already 0.2.1 on crates.io

Version bump

---

src/backend/vulkan/src/lib.rs

I also replaced the panic on short input with a `return false` in the spirit of robustness of public APIs.
PR checklist:

Fix unaligned reads, endianness confusion in Vulkan is_valid_cache

---

examples/colour-uniform/main.rs
src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs
src/backend/metal/src/soft.rs

[mtl] argument buffer support

---

README.md

Does what it says on the tin :)

Add note about contributor-friendly issues to README

---

src/backend/metal/src/device.rs

Makes argument buffers compatible with push constants again. Also reduce the binding of argument buffers to only the affected stages.
PR checklist:
I think this brings us to the end of the second push for argument buffers. They seem pretty solid and operational as of today, vkQuake is a good test case. There are serious limitations though that ask for big changes:
1. Storage images and dynamic-offset buffers can't be a part of the argument buffer - #2866 . This requires shader translation changes.
2. We need to know the dimensionality and msaa-ness of textures at the descriptor set layout creation time. This would mean another derivation from Vulkan proper.
Once we have these implemented, we'll be able to benchmark Dota and Dolphin again. But until then, argument buffer support will be …

[mtl] override argument buffer sets

---

src/backend/dx12/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml

bump version numbers to match what was published

---

src/backend/empty/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/gl/src/device.rs
src/backend/gl/src/info.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/window/glutin.rs
src/backend/gl/src/window/web.rs

Fixes number of small issues I encountered

Various GL fixes

---

src/backend/metal/Cargo.toml
src/backend/metal/build.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs

backport iOS metal sim support to hal0.2 branch

---

src/backend/gl/src/command.rs
src/backend/gl/src/device.rs
src/backend/gl/src/info.rs
src/backend/gl/src/native.rs

Something something something COMPUTE!

---

examples/colour-uniform/main.rs
examples/quad/main.rs
src/backend/dx11/src/lib.rs
src/backend/dx12/src/window.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/command.rs
src/backend/gl/src/device.rs
src/backend/gl/src/window/glutin.rs
src/backend/gl/src/window/web.rs
src/backend/gl/src/window/wgl.rs
src/backend/metal/src/window.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/window.rs
src/hal/src/window.rs
src/warden/src/bin/reftest.rs

Also remove `Surface::kind` and fix few rough points.

Decouple window from gl context

---

examples/Cargo.toml
src/backend/dx11/Cargo.toml
src/backend/dx12/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/gl/src/device.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/queue.rs
src/backend/gl/src/window/dummy.rs
src/backend/gl/src/window/mod.rs
src/backend/gl/src/window/wgl.rs
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml
src/warden/Cargo.toml

Unblocks https://github.com/gfx-rs/wgpu/issues/64
cc @seivan @cosmicchipsocket
PR checklist:

No Winit by default

---

src/backend/dx12/Cargo.toml
src/backend/dx12/src/device.rs

[dx12] allow view creation to fail

---

src/backend/dx12/Cargo.toml
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs

[dx12] query supported multisample counts

---

src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/conversions.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs

Addresses Metal side of #2875 
PR checklist:

[hal-0.2/mtl] attachment resolves

---

src/backend/dx12/src/command.rs
src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/conversions.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs

Sibling of #2924 for `master`
PR checklist:

[mtl] attachment resolves

---

src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs

Sibling of #2934 for `master`
Fixes #2643

[dx12] refactored root signature creation, improved shader visibility

---

src/backend/dx11/src/mirror.rs

If one puts a struct as a member of a constant buffer, `gfx` crashes trying to divide by zero.
When a shader variable type is a `D3D_SVC_STRUCT`, it is an array when the `Elements` field is > 0 and a struct when the `Members` field is > 0.
This changeset makes it so we calculate the struct of an array variable only when it is an array.

[pre-ll] dx11: handle structs in cbuffers

---

CHANGELOG.md
examples/Cargo.toml
src/backend/dx11/Cargo.toml
src/backend/dx12/Cargo.toml
src/backend/empty/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml
src/hal/Cargo.toml
src/warden/Cargo.toml

Release 0.3 version bumps and changelog

---

src/backend/gl/Cargo.toml

[gl] Use glow 0.2.2

---

README.md

Discovered by trying to follow Getting started on crates.io listing

Updated Getting started to reflect ll rewrite

---

examples/Cargo.toml
src/backend/dx11/Cargo.toml
src/backend/dx12/Cargo.toml
src/backend/empty/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml

Bump glutin dependency versions

---

src/backend/gl/Cargo.toml

[v0.18] Release gfx_device_gl 0.16.2

---

src/backend/metal/src/device.rs

Fixes https://github.com/szeged/webrender/pull/306#issuecomment-525760288
PR checklist:

[mtl] fix immutable samplers in combined descriptor

---

src/backend/metal/src/command.rs

[mtl] don't panic inside a panic

---

src/backend/vulkan/src/lib.rs

[vk] fix `wait_semaphore` not being used in `present_surface`

---

examples/README.md

[doc] added shader compilation section to readme

---

src/backend/vulkan/src/window.rs

[vk] fix overflow in swapchain timeout

---

src/backend/metal/src/conversions.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs

[mtl] add missing limits

---

src/backend/metal/src/device.rs

[mtl] fix spec consts not passed on to SPIRV-Cross

---

CHANGELOG.md
src/backend/dx12/Cargo.toml
src/backend/dx12/src/command.rs
src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/resource.rs
src/hal/src/pass.rs

Sibling of #3010 
~~Also includes a tiny fix for `num_levels` being used. @msiglreith - could you peek at that please?~~

[dx12] use explicit external pass barrier access

---

src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/resource.rs

- Improve documentations on the descriptor set internals
- Prepare dynamic uniform/storage buffers
- Cache pipeline layout related calculations

dx12: Refactor descriptor sets and pipeline layouts

---

examples/quad/main.rs

Fixes #3045
PR checklist:
This just pads both (possibly non-coherent) buffer allocations by the necessary byte alignment for non-coherent atom sizes.

quad: Pad buffers by non-coherent atom size

---

src/backend/metal/src/lib.rs

Addresses https://github.com/gfx-rs/wgpu-rs/issues/97
PR checklist:

[osx] make a view to want a new layer

---

CHANGELOG.md
examples/Cargo.toml
src/auxil/auxil/Cargo.toml
src/backend/dx11/Cargo.toml
src/backend/dx12/Cargo.toml
src/backend/empty/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml
src/hal/Cargo.toml
src/warden/Cargo.toml

Version bumps for 0.4

---

src/backend/dx12/Cargo.toml
src/backend/dx12/src/device.rs

Fixes https://ci.appveyor.com/project/loki04/webrender/builds/28520384#L580
PR checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/3072)

[0.3/dx12] Fix for building with rust 1.35.0

---

src/backend/dx12/src/device.rs

The sibling of https://github.com/gfx-rs/gfx/pull/3072
PR checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/3075)

[dx12] Fix for building with rust 1.35.0

---

src/backend/dx12/Cargo.toml
src/backend/dx12/src/device.rs

The sibling of https://github.com/gfx-rs/gfx/pull/3072
PR checklist:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/gfx-rs/gfx/3074)

[0.4/dx12] Fix for building with rust 1.35.0

---

src/backend/gl/Cargo.toml

Fixes #3090
Glutin issues - https://github.com/rust-windowing/glutin/issues/1236
PR checklist:

[GL] Update glutin version

---

src/backend/dx11/Cargo.toml
src/backend/dx12/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/window.rs
src/hal/Cargo.toml

Upgrade to smallvec 1.0

---

src/backend/metal/src/device.rs

Fixes #3099 , presumably. Need to do some testing to confirm...

[mtl] Use a separate internal queue for mapping invalidation

---

CHANGELOG.md
src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs

[0.4/mtl] restore the viewport after clear_attachments

---

examples/Cargo.toml
examples/colour-uniform/main.rs
examples/quad/main.rs
src/backend/dx11/Cargo.toml
src/backend/dx11/src/device.rs
src/backend/dx11/src/lib.rs

 [dx11] disable coherent memory, remove MemoryHeapFlags

---

CHANGELOG.md
src/backend/dx12/Cargo.toml
src/backend/dx12/src/lib.rs

[0.4/dx12] hold DXGI library alive

---

CHANGELOG.md
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/window.rs

[0.4/vk] work around Intel swapchain bug

---

CHANGELOG.md
src/backend/metal/Cargo.toml
src/backend/metal/src/lib.rs

[0.4/mtl] support shading language v2.2

---

CHANGELOG.md
src/backend/metal/Cargo.toml
src/backend/metal/src/lib.rs

Sibling of #3149 for master
Fixes #3148 
PR checklist:

[mtl] support shading language v2.2

---

.travis.yml
README.md

* remove gitter link in README
* remove gitter webhook from travis.yml

Remove gitter references

---

src/backend/dx11/src/lib.rs
src/backend/dx12/src/resource.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs
src/backend/vulkan/src/conv.rs
src/hal/src/lib.rs
src/hal/src/pso/descriptor.rs
src/warden/src/bin/bench.rs
src/warden/src/bin/reftest.rs
src/warden/src/gpu.rs
src/warden/src/lib.rs
work/benches/blit.ron
work/reftests/ci.ron
work/reftests/local.ron
work/scenes/large.ron

Fixes #3164
Fixes #3126
PR checklist:

Read-only image descriptors

---

src/backend/dx11/src/conv.rs
src/backend/dx11/src/lib.rs
src/backend/dx12/src/conv.rs
src/backend/dx12/src/lib.rs
src/backend/gl/src/conv.rs
src/backend/gl/src/info.rs
src/backend/metal/src/conversions.rs
src/backend/metal/src/device.rs
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/conv.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/window.rs
src/hal/src/image.rs
src/hal/src/lib.rs

MirrorClamp feature

---

CHANGELOG.md
examples/Cargo.toml
src/auxil/auxil/Cargo.toml
src/backend/dx11/Cargo.toml
src/backend/dx12/Cargo.toml
src/backend/empty/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/internal.rs
src/backend/vulkan/Cargo.toml
src/hal/Cargo.toml
src/warden/Cargo.toml

Candidate for the last PR before we release 0.5
PR checklist:

All around version bumps for hal-0.5 and metal fixes

---

CHANGELOG.md
src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/lib.rs

Includes #3185, #3187, #3188, #3189
PR checklist:

[0.5/vk+mtl] release hotfixes

---

CHANGELOG.md
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/conv.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/native.rs
src/backend/vulkan/src/pool.rs
src/backend/vulkan/src/window.rs

[vk] fix handling of AMD viewport negation

---

src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs

And support for 8 color targets!

Metal compute limits

---

CHANGELOG.md
src/backend/metal/Cargo.toml
src/backend/metal/src/device.rs
src/backend/metal/src/internal.rs
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/lib.rs

Required for a smooth update in gecko...

[0.4] Update core-foundation and cocoa deps

---

info/getting_started.md

Add links to some tutorials @grovesNL recommended on how to use gfx-hal.
Works towards solving #1919

Add links to tutorials on how to use gfx

---

src/backend/vulkan/src/device.rs

Fixes #3213.
I have not been able to test this change unfortunately since I have been unable to find a combination of wgpu, wgpu-rs and gfx that work without errors.
PR checklist:

Fix index out of bounds access when using object labels longer than 64 characters

---

CHANGELOG.md
src/backend/vulkan/src/lib.rs

[vk] gracefully handle the case where the drive supports it but hardware does not

---

.monocodus
CHANGELOG.md
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/lib.rs

Required for https://bugzilla.mozilla.org/show_bug.cgi?id=1633472
PR checklist:

[0.5/vk] gracefully handle the case where the drive supports it but hardware does not

---

CHANGELOG.md
src/backend/dx12/Cargo.toml
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/window.rs

[0.5/dx12] waitable swapchain

---

CHANGELOG.md
src/backend/dx12/Cargo.toml
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/window.rs

Fixes #3193
Fixes #3088
Tested on wgpu-rs examples.

DX12 waitable swap chain

---

.travis.yml

Works around Travis OSX nightly failures: https://travis-ci.org/github/gfx-rs/gfx/jobs/682710129#L3676

Disable all feature testing on Metal nightly

---

src/auxil/auxil/Cargo.toml
src/backend/dx11/Cargo.toml
src/backend/dx12/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml

Update spirv_cross to version 0.20

---

src/backend/metal/src/command.rs

[0.5/mtl] fix issue with fill_buffer when using offset and size

---

CHANGELOG.md
src/backend/dx12/Cargo.toml
src/backend/dx12/src/lib.rs

[0.5/dx12] Backport Integrated GPU Detection

---

CHANGELOG.md
src/backend/dx12/src/device.rs

[0.5/dx12] fix shader stage string UB

---

CHANGELOG.md
src/auxil/range-alloc/Cargo.toml
src/auxil/range-alloc/src/lib.rs
src/backend/dx12/Cargo.toml
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/resource.rs

[dx12] implement descriptor pool destruction, bump version

---

examples/Cargo.toml
examples/colour-uniform/main.rs
examples/compute/main.rs
examples/mesh-shading/main.rs
examples/quad/main.rs
src/auxil/auxil/src/lib.rs
src/backend/dx11/src/conv.rs
src/backend/dx11/src/device.rs
src/backend/dx11/src/internal.rs
src/backend/dx11/src/lib.rs
src/backend/dx11/src/shader.rs
src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs
src/backend/gl/src/device.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/soft.rs
src/hal/src/device.rs
src/hal/src/pso/mod.rs
src/warden/Cargo.toml
src/warden/src/gpu.rs

Move pso::Stage to auxil::ShaderStage

---

src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/conv.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/window.rs
src/hal/src/lib.rs

Ports #3271 to master.
This is not a completely trivial port, as I needed to integrate the mesh shader work into the existing extension infrastructure. No major unsafe code was changed however.

[master] Port #3271 to Master

---

src/backend/vulkan/src/lib.rs

Just a small refactor, no functional changes

[vk] Use higher-level swapchain wrapper

---

info/getting_started.md

Fixes nothing :)
PR checklist:

Add Vulkan installation guide for Archlinux

---

src/backend/dx11/Cargo.toml

[master/dx11] Bump libloading to 0.6

---

CHANGELOG.md
examples/quad/main.rs
src/backend/empty/Cargo.toml
src/backend/empty/src/buffer.rs
src/backend/empty/src/image.rs
src/backend/empty/src/lib.rs
src/backend/empty/src/memory.rs

Backports the changes of #3280 from `master`

[0.5] Mock the empty backend

---

.travis.yml

Fixes the CI issues of #3290, hopefully

Switch CI to msvc

---

src/backend/empty/src/buffer.rs
src/backend/empty/src/descriptor.rs
src/backend/empty/src/lib.rs

Mirror of #3290 but for `master` branch.

[master] Mock empty backend descriptor set functions

---

CHANGELOG.md
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs

Should address https://github.com/gfx-rs/wgpu/issues/718
~~It's a bit risky, but that's the recommendation from Vulkan so far.~~

[0.5/vk] skip unknown memory properties

---

src/backend/gl/src/command.rs
src/backend/gl/src/device.rs
src/backend/gl/src/native.rs

baked states for gl backend

---

examples/colour-uniform/main.rs
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/device.rs
src/hal/src/device.rs

replaced heap allocated vecs with stack allocated arrays for vulkan backend

---

src/backend/metal/Cargo.toml
src/backend/metal/src/lib.rs
src/backend/metal/src/window.rs

Same as https://github.com/gfx-rs/metal-rs/pull/157
PR checklist:

Remove core-graphics deps

---

src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs

This ends up dropping the dependency on 'core-graphics'

Replace 'cocoa' dependency with 'cocoa-foundation'

---

src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs

This ends up dropping the dependency on 'core-graphics'
Edit: sibling of #3314

[0.5] Replace 'cocoa' dependency with 'cocoa-foundation'

---

src/backend/metal/src/command.rs
src/backend/vulkan/src/command.rs
src/hal/src/command/mod.rs

use stack allocated arrays in CommandBuffer in vulkan backend

---

src/backend/dx12/src/command.rs
src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/window.rs

[dx12] Essential fixes to depth views and command allocation

---

src/backend/metal/src/conversions.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs

Helps https://github.com/gfx-rs/wgpu/pull/877
PR checklist:

[mtl] add texture cube feature, refactor private caps

---

src/backend/dx11/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/gl/src/lib.rs
src/backend/gl/src/window/dummy.rs
src/backend/metal/Cargo.toml

Just preparing for the release.
Note that GL's windowing features are totally disabled. That is to allow us to introduce them later without breaking.
Currently GL backend is considered broken.

Dependency updates, mainly parking_lot

---

CHANGELOG.md
examples/colour-uniform/main.rs
examples/mesh-shading/main.rs
examples/quad/main.rs
src/backend/dx11/src/device.rs
src/backend/dx12/src/device.rs
src/backend/gl/src/device.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/device.rs
src/hal/src/pso/graphics.rs
src/warden/src/gpu.rs

This is for consistency with other PSO descriptors.

Rename primitive assember to PrimitiveAssemberDesc

---

.travis.yml
CHANGELOG.md
README.md
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/device.rs

[vk] fix Android target and add it to CI

---

CHANGELOG.md
src/backend/dx12/Cargo.toml
src/backend/dx12/src/command.rs
src/backend/dx12/src/conv.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/resource.rs

based on #3342, which is already published, but stuck on CI
related to https://github.com/gfx-rs/wgpu-rs/issues/47
tested on wgpu-rs examples

[Dx12] object labels and multisampling

---

Makefile
examples/Cargo.toml
examples/mesh-shading/main.rs
examples/quad/main.rs
src/backend/gl/Cargo.toml
src/backend/gl/src/lib.rs
src/backend/gl/src/queue.rs
src/backend/gl/src/window/surfman.rs

WIP getting GL finally working again with `surfman`.
PR checklist:
- vulkan
- gl

GL Final Showdown

---

CHANGELOG.md
src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/resource.rs

Sibling of #3360 for hal-0.6 branch
To be released together with #3358 (cc @grovesNL )

[0.6/dx12] fix root signature indexing

---

src/backend/dx11/src/device.rs
src/backend/dx11/src/internal.rs
src/backend/dx11/src/lib.rs

[dx11] fix cpu-visible memory

---

CHANGELOG.md
src/backend/dx11/Cargo.toml
src/backend/dx11/src/device.rs
src/backend/dx11/src/lib.rs

The flush ranges were computed incorrectly.
Tested on vange-rs

[0.6/dx11] fix memory flushes and presentation

---

src/backend/dx11/src/device.rs
src/backend/dx11/src/lib.rs

[dx11] flushing and presentation fixes

---

src/hal/src/command/mod.rs

I just took each of the explanations directly from https://vulkan-tutorial.com/Drawing_a_triangle/Drawing/Command_buffers#page_Command-buffer-allocation

Document command::Level variants

---

CHANGELOG.md
src/backend/dx12/Cargo.toml
src/backend/dx12/src/lib.rs
src/backend/metal/Cargo.toml
src/backend/metal/src/device.rs
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/lib.rs

Fixes https://github.com/gfx-rs/wgpu-rs/issues/579 and https://github.com/gfx-rs/wgpu-rs/issues/580.

[0.6] Fix Descriptor Indexing Features on DX12/VK/Metal

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs
src/hal/src/image.rs
src/hal/src/pso/mod.rs

Fixes a bunch of things, except performance on Dota :(
Fixes #3381

Metal optimizations and fixes

---

src/backend/vulkan/src/lib.rs

[vk] Properly enable VK_KHR_maintenance3

---

CHANGELOG.md
examples/colour-uniform/main.rs
src/backend/dx12/Cargo.toml
src/backend/dx12/src/command.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/resource.rs
src/backend/vulkan/src/lib.rs

Sibling of #3396 for hal-0.6 branch

[0.6/dx12] debug markers and more object names

---

src/backend/dx12/src/conv.rs

[dx12] map color blend factors to alpha

---

CHANGELOG.md
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/device.rs

Follow-up to #3411
Fixes https://github.com/gfx-rs/wgpu/issues/991

[0.6/vk] fix support for writing descriptor arrays

---

src/backend/dx12/src/lib.rs

[master/dx12] Improve D3D12 limits

---

src/backend/dx12/Cargo.toml
src/backend/dx12/src/command.rs
src/backend/dx12/src/descriptors_cpu.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/resource.rs
src/backend/dx12/src/window.rs
src/hal/src/lib.rs

[dx12] implement descriptor freeing and recycling

---

CHANGELOG.md
src/backend/dx12/Cargo.toml
src/backend/dx12/src/command.rs
src/backend/dx12/src/descriptors_cpu.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/resource.rs
src/backend/dx12/src/window.rs

Should fix https://github.com/gfx-rs/wgpu/issues/993
PR checklist:

[0.6/dx12] descriptor freeing and recycling

---

CHANGELOG.md
src/backend/dx11/Cargo.toml
src/backend/dx11/src/debug.rs
src/backend/dx11/src/device.rs
src/backend/dx11/src/lib.rs

Fixes compilation issues in release, errant warnings, and creation of DeferredContext1.
Waiting for @m4b to confirm if the context fix works.

[0.6/dx11] Bugfixes

---

src/backend/dx12/src/descriptors_cpu.rs
src/backend/dx12/src/device.rs
src/backend/dx12/src/lib.rs
src/backend/dx12/src/resource.rs

An improved port of #3434 for master

[dx12] fix and improve descriptor handling

---

src/auxil/auxil/Cargo.toml
src/backend/dx11/Cargo.toml
src/backend/dx11/src/shader.rs
src/backend/dx12/Cargo.toml
src/backend/dx12/src/device.rs
src/backend/gl/Cargo.toml
src/backend/gl/src/device.rs
src/backend/metal/Cargo.toml
src/backend/metal/src/device.rs

[auxil/gl/dx11/dx12/metal] Select entry point when multiple exist

---

CHANGELOG.md
examples/Cargo.toml
src/auxil/auxil/Cargo.toml
src/backend/dx11/Cargo.toml
src/backend/dx11/src/shader.rs
src/backend/dx12/Cargo.toml
src/backend/dx12/src/device.rs
src/backend/gl/Cargo.toml
src/backend/gl/src/device.rs
src/backend/metal/Cargo.toml
src/backend/metal/src/device.rs
src/warden/Cargo.toml

[0.6/auxil/gl/dx11/dx12/metal] Select entry point when multiple exist

---

CHANGELOG.md
src/backend/dx11/Cargo.toml
src/backend/dx11/src/device.rs
src/backend/dx11/src/lib.rs
src/backend/dx11/src/shader.rs

Fixes https://github.com/gfx-rs/wgpu/issues/1009.
Fixes assorted smaller issues. Implements push constants and draw indirect.
This PR should be reviewed commit by commit and each commit is freestanding.
After this PR lands, I think the DX11 backend _should_ have everything wgpu needs implemented in some form, so we can start telling people to try DX11 on their project as it might actually work (and I can start collecting bugs) 🎉

[0.6/dx11] Implement and Fix Assorted Issues

---

src/backend/dx11/Cargo.toml
src/backend/dx11/src/conv.rs
src/backend/dx11/src/debug.rs
src/backend/dx11/src/device.rs
src/backend/dx11/src/internal.rs
src/backend/dx11/src/lib.rs
src/backend/dx11/src/shader.rs

Ports #3427 #3430 #3431 #3433 and #3442 to master.

[master/dx11] Rollup of DX11 Fixes 

---

CHANGELOG.md
src/backend/dx12/src/device.rs

Sibling of https://github.com/gfx-rs/gfx/pull/3447

dx12: fix entry point selection

---

CHANGELOG.md
src/backend/dx11/Cargo.toml
src/backend/metal/Cargo.toml

Just a bunch of steps to ease Gecko update of wgpu...

[dx11+metal] update parking_lot to 0.11

---

src/backend/gl/src/queue.rs

glWaitSync isn't always available (e.g. on the web), so we could probably skip it when it's not supported for now.

[0.6/gl] avoid wait sync if it's not available

---

src/backend/dx12/src/device.rs

[dx12] fix the respect of readonly storage flags

---

.github/workflows/CI.yml
src/backend/gl/src/command.rs
src/backend/gl/src/device.rs
src/backend/gl/src/info.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/native.rs

[GL] descriptor fixes

---

.github/workflows/CI.yml
bors.toml

Fixes a fallout of #3460, and also unconfuses bors...

Fix cargo-deny checks

---

.github/workflows/CI.yml

Fixes https://github.com/gfx-rs/gfx/issues/3429
github containers ship with preinstalled ndk

[ci] remove android ndk installation

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs

Addresses https://github.com/gfx-rs/wgpu/issues/1044 on master
PR checklist:

[mtl] fix render pass compatibility check wrt sample count

---

.github/workflows/CI.yml
CHANGELOG.md
src/backend/dx11/src/conv.rs
src/backend/dx11/src/debug.rs
src/backend/dx11/src/device.rs
src/backend/dx11/src/internal.rs
src/backend/dx11/src/lib.rs
src/backend/dx11/src/shader.rs
src/backend/dx12/src/device.rs
src/backend/gl/src/device.rs
src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs
src/hal/src/lib.rs

Sibling of #3486 for 0.6
Also does some cargo formatting

[0.6/mtl] fix render pass compatibility wrt multisampling

---

examples/Cargo.toml
examples/quad/main.rs
src/backend/gl/src/device.rs
src/backend/gl/src/info.rs
src/backend/gl/src/window/egl.rs

Fixes #3495
Still doesn't show anything on my other Linux laptop, investigating...
I'm seeing that `NATIVE_RENDERABLE = TRUE`  results in no FB configurations found. I believe this is required for our stuff to work :/

Minor OpenGL improvements

---

src/backend/vulkan/src/lib.rs

Fixes #3482 (at least for the Vulkan backend)
PR checklist:

Enable vulkan debug markers in release builds

---

src/backend/dx11/src/dxgi.rs
src/backend/dx11/src/lib.rs

Determine GPU type on DX11 when possible

---

src/backend/gl/src/info.rs

Webgl min storage buffer offset alignment

---

Makefile
src/backend/metal/Cargo.toml
src/backend/metal/src/device.rs
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/hal/Cargo.toml
src/hal/src/device.rs

Depends on https://github.com/gfx-rs/naga/pull/299 . Will need to change the tag once that lands.
Paves more way towards the pervasive Naga usage across the stack.

Fix Metal entry points reflected from Naga, extend to Vulkan backend

---

examples/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/gl/src/window/egl.rs
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml
src/hal/Cargo.toml

Fixes the problem of Naga not providing the workgroup size in compute shaders.

Update Naga to gfx-4

---

src/backend/gl/src/info.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/native.rs

Fixes our ability to run simple wgpu-rs examples on GL backend.

OpenGL memory mapping fixes

---

src/backend/gl/src/device.rs

Fix size computation in create_image for gl backend

Correct computation of image size

---

src/backend/dx11/src/device.rs
src/backend/dx12/src/device.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/device.rs
src/backend/webgpu/src/device.rs
src/hal/src/device.rs
src/hal/src/pso/compute.rs
src/hal/src/pso/graphics.rs
src/warden/src/gpu.rs

Adjusts for the way Metal does things, see https://github.com/gfx-rs/metal-rs/pull/193.
I believe it's not critical here to try aligning the pipeline labels with Vulkan.

Move pipeline labels into the descriptors

---

.github/workflows/CI.yml
src/backend/dx11/README.md
src/backend/dx12/README.md
src/backend/gl/Cargo.toml
src/backend/gl/README.md
src/backend/gl/src/window/egl.rs
src/backend/metal/README.md
src/backend/vulkan/README.md
src/backend/webgpu/README.md

Should remove our dependency on libEGL at build time, see https://github.com/timothee-haudebourg/khronos-egl/issues/8

Switch to EGL dynamic loading

---

src/backend/vulkan/src/lib.rs

The `ash` generated methods `*::name()` return a `&'static CStr`, which means we probably don't need to use `lazy_static` to keep track of extension names.

[vk] Remove lazy_static and (most) hard-coded strings for layer and extension names

---

src/backend/dx11/src/lib.rs
src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/metal/src/native.rs
src/backend/metal/src/window.rs

Adds an ability to make surfaces transparent on Metal.
Related to https://github.com/gfx-rs/wgpu/issues/687#issuecomment-720599249

[metal] use metal-rs github, implement transparency

---

src/backend/gl/src/conv.rs

Changed icorrect format parameters from glow::DEPTH to glow::DEPTH_FORMAT

Fixed incorrect depth format conversions in GL backend

---

src/backend/gl/Cargo.toml
src/backend/gl/src/window/egl.rs

[GL] Fix Android support

---

examples/colour-uniform/main.rs
examples/mesh-shading/main.rs
examples/quad/main.rs
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/window.rs

Remove lazy_static dependency from Vulkan

---

src/backend/metal/Cargo.toml
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs

[Metal] Remove lazy_static

---

src/backend/metal/src/lib.rs

Fixes https://github.com/gfx-rs/gfx/pull/3579#issuecomment-759497638
PR checklist:

[mtl] use existing GfxManagedMetalLayerDelegate if available

---

src/backend/gl/src/native.rs

Fixes #3587
Untested due to #3588

[gl] fix framebuffer aspects

---

examples/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml
src/hal/Cargo.toml

Update naga to gfx-6

---

src/backend/gl/src/device.rs
src/backend/gl/src/info.rs

Add support for compute on GLES

---

src/backend/gl/Cargo.toml
src/backend/gl/src/command.rs
src/backend/gl/src/info.rs
src/backend/gl/src/queue.rs
src/backend/gl/src/window/egl.rs

Fixes the issue discussed on Matrix - the compute example on GL doesn't always show the correct result.
PR checklist:

[gl] storage memory barriers

---

CHANGELOG.md
examples/colour-uniform/main.rs
src/backend/dx11/src/device.rs
src/backend/dx12/src/device.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/command.rs
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/native.rs
src/backend/webgpu/src/device.rs
src/hal/src/command/mod.rs
src/hal/src/device.rs
src/hal/src/pso/descriptor.rs
src/hal/src/queue/mod.rs

Fixes #3609
This PR is a product of wonderful collaboration with @zakarumych and @NotIntMan. Thank you guys!
PR checklist:
Tested on wgpu-rs examples.

Remove ExactSizeIterator bounds, update inplace_it usage

---

src/backend/metal/src/lib.rs

Fixes the following errors in wgpu-rs test log:
> objc[21181]: Class GfxManagedMetalLayerDelegate is implemented in both ?? (0x7f99dbe04520) and ?? (0x7f99dbd04520). One of the two will be used. Which one is undefined.
I think the reason is that class registration is not instantaneous, and not blocking. So with the current code (as of #3585) we could still try to register the same class twice.
PR checklist:

[mtl] Use Once for delegate initialization

---

src/backend/vulkan/src/device.rs

Doesn't fix anything, just simplifies the code a bit.

[vk] Remove Pin usage from pipeline creation

---

src/backend/dx11/src/lib.rs

[DX11] Fix debug device creation

---

examples/Cargo.toml
src/auxil/auxil/Cargo.toml
src/auxil/range-alloc/Cargo.toml
src/backend/dx11/Cargo.toml
src/backend/dx12/Cargo.toml
src/backend/empty/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml
src/backend/webgpu/Cargo.toml
src/hal/Cargo.toml
src/warden/Cargo.toml

Release hal-0.7

---

src/backend/dx12/src/lib.rs

Helps with https://github.com/gfx-rs/portability/issues/242#issuecomment-771881593
PR checklist:

[dx12] Fill out max_framebuffer_layers and max_per_stage_resources

---

src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml
src/hal/Cargo.toml

Gets a ton of fixes from Naga
PR checklist:

Bump naga to gfx-10

---

src/backend/gl/Cargo.toml
src/backend/gl/src/device.rs
src/backend/gl/src/native.rs
src/backend/metal/Cargo.toml
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/device.rs
src/backend/vulkan/src/lib.rs
src/hal/Cargo.toml
src/hal/src/device.rs

Picks up a whole bunch of fixes from Naga, including the Analysis.

Update naga to gfx-11

---

CHANGELOG.md

Add CHANGELOG.md entries for #3626

Update changelog for #3626

---

src/backend/dx12/src/lib.rs
src/backend/gl/src/info.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs
src/backend/vulkan/src/lib.rs

Helps with https://github.com/gfx-rs/wgpu/issues/1225
PR checklist:

[mtl] better shader error reporting

---

src/backend/gl/Cargo.toml
src/backend/gl/src/device.rs
src/backend/metal/Cargo.toml
src/backend/metal/src/device.rs
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/device.rs
src/hal/Cargo.toml

Picks up another set of fixes from Naga, such as https://github.com/gfx-rs/naga/pull/491, https://github.com/gfx-rs/naga/pull/505, https://github.com/gfx-rs/naga/pull/506, and others

Update naga to gfx-12

---

src/backend/dx11/src/lib.rs
src/backend/dx11/src/shader.rs

This fixes the issues on wgpu's shadow example. Now DX11 runs all examples flawlessly.
Works On My Machine™

[dx11] Implement Fill Buffer and Fix Panic

---

src/backend/gl/src/info.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/queue.rs

[GL] Improve WebGL version and feature checking

---

src/backend/gl/src/window/egl.rs

[GL] Added comment why we need egl pbuffer

---

src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/physical_device.rs

Helps with https://github.com/gfx-rs/wgpu/issues/1261, not sure if it fixes it though

[vk] handle device creation error more gracefully

---

src/backend/gl/src/window/egl.rs

My system has `GL_OES_surfaceless_context`, but unable to create pbuffer surfaces (It's mesa, so I doubt I'm the only one)
As I see it correct way would be to:
1) See if we have the extension
2) Try to choose config with `PBUFFER_BIT` if not
3) Notify user if both fails
But to check for extension we need to already have context and consequently a chosen config, so it's a bit recursive.
I simply try to bind newly created context and proceed to make pbuffer only if it fails.

[gl] make dummy pbuffer optional

---

src/backend/gl/src/device.rs

Blocked by https://github.com/gfx-rs/naga/pull/555
PR checklist:

[GL] Rebinding buffers using reflection info from naga

---

src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/metal/src/device.rs
src/backend/vulkan/Cargo.toml
src/hal/Cargo.toml

Gets us another bunch of fixes, including better control flow analysis

Update naga to gfx-15

---

src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/lib.rs
src/backend/vulkan/src/native.rs

Fixes the duplicate libloading dependency

[vk] update Ash to 0.32

---

src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/command.rs
src/hal/Cargo.toml

Includes https://github.com/gfx-rs/naga/pull/585 and https://github.com/gfx-rs/naga/pull/587

Update naga to gfx-16

---

src/backend/gl/Cargo.toml
src/backend/gl/src/window/egl.rs

[GL] Fix EGL context creation and set setBuffersGeometry for Android

---

src/backend/dx11/src/conv.rs
src/backend/dx11/src/device.rs
src/backend/dx11/src/internal.rs
src/backend/dx11/src/lib.rs
src/backend/dx11/src/shader.rs
src/backend/dx12/src/lib.rs
src/backend/gl/src/info.rs
src/backend/metal/src/device.rs
src/backend/vulkan/src/physical_device.rs
src/hal/src/lib.rs

Makes progress towards https://github.com/gfx-rs/wgpu/issues/1244.
I'm not terribly happy with the downlevel feature flags as they are, but I hope to improve them/make them more concrete in a future PR, so I'm not worried about that too much.
Diff isn't very pretty as I didn't split things up.

[dx11] Support FL10 and expose a beginning set of support flags

---

src/backend/dx12/src/device.rs

[dx12] don't panic on DSV creation

---

src/backend/dx11/src/device.rs
src/backend/dx11/src/internal.rs
src/backend/dx11/src/lib.rs
src/backend/dx11/src/shader.rs
src/backend/dx12/src/device.rs
src/backend/gl/src/info.rs
src/backend/gl/src/lib.rs
src/backend/gl/src/queue.rs
src/backend/gl/src/window/egl.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs
src/backend/vulkan/src/physical_device.rs

Fixes our ability to load shaders with many different layouts.
Depends on https://github.com/gfx-rs/naga/pull/630

[msl] fix querying entry point names

---

src/backend/dx11/src/device.rs
src/backend/dx12/src/device.rs
src/backend/empty/src/lib.rs
src/backend/gl/src/device.rs
src/backend/metal/Cargo.toml
src/backend/metal/src/device.rs
src/backend/vulkan/src/device.rs
src/backend/webgpu/src/device.rs
src/hal/src/device.rs
src/warden/Cargo.toml

added capture

---

src/backend/dx11/src/device.rs
src/backend/dx12/src/device.rs
src/backend/gl/src/device.rs
src/backend/vulkan/src/device.rs
src/backend/webgpu/src/device.rs

Don't panic on start_capture unnecessarily

---

src/backend/dx11/src/device.rs

Fixes #3711 
Tries to mimic the fix for the Dx12 backend. This works for me, but I'm not sure how ideal this is because it pretty much ignores any error from `view_image_as_depth_stencil` when creating the image view, maybe the ignored errors should be logged?
PR checklist:

avoid panic & error propagation on DSV creation

---

src/backend/gl/Cargo.toml
src/backend/gl/src/device.rs
src/backend/metal/Cargo.toml
src/backend/metal/src/device.rs
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/physical_device.rs
src/hal/Cargo.toml

See https://github.com/gfx-rs/naga/pull/652#issuecomment-812325479

Update naga to gfx-20

---

src/backend/vulkan/src/native.rs
src/backend/vulkan/src/pool.rs

Fixes the validation error in https://github.com/gfx-rs/wgpu-rs/issues/837#issuecomment-813790158

[vk] only free non-zero number of commmand buffers or descriptors

---

src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/conversions.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs
src/backend/metal/src/window.rs
src/backend/vulkan/Cargo.toml
src/hal/Cargo.toml

See https://github.com/gfx-rs/naga/pull/668
Will be unblocked with the next Naga train.

[metal] immutable sampler support on Naga path

---

src/backend/dx12/src/device.rs
src/backend/vulkan/src/device.rs
src/hal/src/window.rs

[vk] handle unknown swapchain creation errors

---

src/backend/metal/Cargo.toml
src/backend/metal/src/command.rs
src/backend/metal/src/device.rs

This should help us look at the performance as a whole, and also compare spirv-cross to Naga shader paths.

[metal] integrate profiling

---

src/backend/gl/Cargo.toml
src/backend/gl/src/device.rs
src/backend/metal/Cargo.toml
src/backend/metal/src/device.rs
src/backend/metal/src/lib.rs
src/backend/vulkan/Cargo.toml
src/backend/vulkan/src/physical_device.rs
src/hal/Cargo.toml

SPV capabilities are a bit relaxed now, and there's been a whole ton of fixes in Naga, revealed through testing of Dota2 and Vange-rs.

Update naga to gfx-23

---

src/backend/metal/Cargo.toml
src/backend/metal/src/device.rs

It didn't even compile. We'll need a way to check them on CI.

[mtl] profiling fixes

---

src/backend/dx11/src/lib.rs

Make Dx11 fill_buffer use an extra buffer for non 16-byte aligned fills

---

CHANGELOG.md
examples/Cargo.toml
src/auxil/auxil/Cargo.toml
src/backend/dx11/Cargo.toml
src/backend/dx12/Cargo.toml
src/backend/empty/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml
src/backend/webgpu/Cargo.toml
src/hal/Cargo.toml
src/warden/Cargo.toml

Fixes #3678
Let's merge this when we release, together with the version bumps

Release hal-0.8

---

README.md

Fix link to `wgpu-rs` in README.md

---

src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml
src/hal/Cargo.toml

Update naga to gfx-25

---

src/backend/metal/src/command.rs
src/backend/metal/src/device.rs
src/backend/metal/src/native.rs
src/backend/metal/src/window.rs
src/backend/vulkan/src/window.rs

Fixes #3757
Closes #3751
~~The only thing left here is re-binding on descriptor changes. Also need to test to see if it actually works...~~

[metal] provide size information to the shaders

---

src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/metal/src/lib.rs
src/backend/metal/src/window.rs
src/backend/vulkan/Cargo.toml
src/hal/Cargo.toml

Bump naga to gfx-26

---

CHANGELOG.md
README.md
examples/Cargo.toml
src/auxil/auxil/Cargo.toml
src/backend/dx11/Cargo.toml
src/backend/dx12/Cargo.toml
src/backend/empty/Cargo.toml
src/backend/gl/Cargo.toml
src/backend/metal/Cargo.toml
src/backend/vulkan/Cargo.toml
src/backend/webgpu/Cargo.toml
src/hal/Cargo.toml
src/warden/Cargo.toml

Prepare to Release 0.9
